### ISSUE TITLE
WinRM script: script.ps1 not executing on Windows 2003 because file path has a space

### ISSUE THREAD

**Issue by sonjz** [ansible/ansible-modules-core#1007]
On Windows 2003, the `TMP` folder is in `C:\Documents and Settings\...` and not `C:\Users\...`, because the ps1 is copied to the temp, you have to execute like this:

```
# this
&"C:\Documents and Settings\..\script.ps1"
# instead of
C:\Documents and Settings\..\script.ps1

# In which case we receive this error
stderr:
'C:\Documents' is not recognized as an internal or external command,
operable program or batch file.
```

**NOTE: I believe this is a larger issue.** 
For example, if a  the ps1 has a space in it, it would also trigger this issue..  Or if an argument is a filepath with spaces in it.  In the end I had to create my own hacks to handle these differently, and added this hack to the top of my ps1 files:

```
# HACK: To fix issues with ansible slash transporting
#       Look for "^/MS/" then replace any / with \
#       e.g. "/MS/E:/Data/" => "E:\Data\"
$msPrefix = "/MS/";
foreach ($item in $PSBoundParameters.GetEnumerator()) {
  if ($item.Value.StartsWith($msPrefix)) {
    Set-Variable $item.Key (($item.Value -replace $msPrefix, "") -replace '/', '\') ;
  }
}
```

Addtionally, I've had problems trying to pass in complex powershell objects, and had to nerf my approach, eg: try passing in.

```
script.ps1 @( @{ Name = "xxx"; Value = "yyy" }, @{ Name = "yyy"; Value = "yyy" } )
```

**Comment by cchurch** [comment]
Should be fixed by merge of https://github.com/ansible/ansible/issues/11719
