### ISSUE TITLE
s3 module usage yields error => aws_access_key and aws_secret_key undefined.

### ISSUE THREAD

**Issue by semifocused** [ansible/ansible-modules-core#1022]
Missed some s3 usage conditions in the shift to aws_connect_kwargs to support STS tokens, this is currently causing s3 usage to fail in some conditions:

https://github.com/ansible/ansible-modules-core/commit/64a2077787904f144f77839660071f35f25d181f#commitcomment-10455189

**Comment by bennojoy** [comment]
fixed via #1029
