### ISSUE TITLE
ansible 1.9.0.1 module: user traceback on osx

### ISSUE THREAD

**Issue by thudry** [ansible/ansible-modules-core#1063]
Issue Type:

Bug Report 

Ansible Version:
ansible 1.9.0.1
  configured module search path = /usr/share/ansible

Environment:

Ansible is installed on debian wheezy with pip, ansible manage osx 10.10

Summary:

With a user that is already created my task fail

Steps To Reproduce:

My task:

```
 - name: User bocal
   user: name=bocal state=present shell=/bin/zsh
```

Expected Results:

Actual Results:

```
TASK: [staging | User bocal] **************************************************
failed: [dump-bocal.42.fr] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "<stdin>", line 3704, in <module>
  File "<stdin>", line 2050, in main
  File "<stdin>", line 1667, in modify_user 
  File "<stdin>", line 1515, in _update_system_user
TypeError: int() argument must be a string or a number, not 'NoneType

FATAL: all hosts have already failed -- aborting
```

The user isn't modified.

**Comment by bcoca** [comment]
i tried that exact line and i get:

```
ok: [testserver] => {    "changed": true,    "comment": "",    "createhome": true,    "group": 1001,"home": "/home/bocal",    "name": "bocal",    "shell": "/bin/zsh",    "state": "present",    "system": false,    "uid": 1001}
```

**Comment by thudry** [comment]
Is testserver on yosemite 10.10?
Because i've test it on many iMac and i always get the same result.

**Comment by bcoca** [comment]
No, I used Debian (I reversed the scenario in your initial report) and other linux distros. Looking for someone with Mac as I don't have one available for testing, so the problem, if confirmed, will be only for those.

**Comment by thudry** [comment]
I've look into the module code and the variable in question (line 1515) isn't use in the method

```
uid = int(self.uid)
```

But after commenting this line i've an other error:

```
Traceback (most recent call last):
  File "<stdin>", line 3704, in <module>
  File "<stdin>", line 2068, in main
  File "<stdin>", line 538, in user_info
  File "<stdin>", line 552, in user_password
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by bcoca** [comment]
i don't know if how this ever worked, pushed a new fix for that line, try now with my PR

**Comment by juliedavila** [comment]
I'm on OSX 10.10.2 and could not replicate on CentOS, for completeness I'll test on Debian wheezy next

edit: read the issue wrong, retesting in reverse

**Comment by thudry** [comment]
Still get the same error

**Comment by bcoca** [comment]
looking at this code I'm skeptical that it ever worked, this is going to need someone to fix it with direct access to a Mac, I'll have to pass it along as updating my PR and having you test is very inefficient way of programming.

**Comment by thudry** [comment]
Ok thank you for your time.

**Comment by bcoca** [comment]
closing this by merge of PR #1084
