### ISSUE TITLE
stat module documentation

### ISSUE THREAD

**Issue by twekberg** [ansible/ansible-modules-core#107]
##### Issue Type:

What kind of ticket is this? “Documentation Report”
##### Ansible Version:

1.7.2 development
##### Environment:

What OS are you running Ansible from and what OS are you managing? Ubuntu 12.04
##### Summary:

The stat module exposes many attributes available via the stat function in the Python os module, and some additional attributes. These attributes should be mentioned in the documentation of the stat module. The attributes pw_name and isdir were used in the examples. I had to go to the source for the stat module to find the other attributes.

Here is what I would like to see added to the end of ansible/library/files/stat's DOCUMENTATION string. The only ones that I'm unsure about are pw_name, isgid and isuid.

returns: a stat object with the following attributes:
atime - last access time
ctime - last creation time
dev - path's device
exists - true if the file exists
gid - path's group id
inode - path's inode
isblk - true if path is a block device
ischr - true if path is a character device
isdir - true if path is a directory
isfifo - true if path is a fifo (a.k.a. named pipe)
isgid - invoking group's id matches path's group id
islnk - true if path is a symbolic link
isreg - true if path is a regular file
issock - true if path is a socket (a.k.a. UNIX Domain Socket)
isuid - invoking user's id matches path's user id
lnk_source - where path links to
md5 - md5 checksum for path
mode - the mode of path in 4 octal digits
mtime - last modification time
nlink - number of hard links to this path
pw_name - owner of path
rgrp - path mode: group read
roth - path mode: other read
rusr - path mode: user read
size - size of path
uid - path's user id
wgrp - path mode: group write
woth - path mode: other write
wusr - path mode: user write
xgrp - path mode: group execute
xoth - path mode: other execute
xusr - path mode: user execute
##### Steps To Reproduce:

Look at the stat module's documentation.
##### Expected Results:

More detail in the documentation without having to look at the stat module's source code.
##### Actual Results:

N/A

**Comment by dellis23** [comment]
+1, this seems very basic and makes it hard to use the `stat` module without knowing what options are available.

**Comment by spanneberg** [comment]
+1
Also the initial discussion at https://github.com/ansible/ansible/issues/7457 shows that a lot of people would like to see that in the Ansible documentation.

**Comment by willharris** [comment]
+1, what dellis23 said...

Also, missing from the list above:
checksum - the file's checksum (currently sha1) (added in Ansible 1.8)

**Comment by ardentperf** [comment]
+1 agree, glad i found this link via google (wouldn't have had time to search python stat module)

**Comment by chicks-net** [comment]
:+1: thanks for doing this!  Hopefully it will make it into the real docs someday. :sheep:

**Comment by dellis23** [comment]
For other folks that wind up here: _none_ of these will be avalable if `exists` is `False`.  So you can't just necessarily just test `isdir` for instance -- you have to test both `result.stat.exists and result.stat.isdir`.

**Comment by twekberg** [comment]
That is one of the few things that is present in the current stat documentation. You have to skip down to the examples section to find it.

  "#...Note that we need to test
  # both that p.stat.isdir actually exists, and also that it's set to true."

**Comment by dellis23** [comment]
Ah I see:

`p.stat.isdir is defined and p.stat.isdir`

Unfortunately **THAT DOESN'T MAKE IT OKAY**!

:-)

**Comment by twekberg** [comment]
It sounds like you are suggesting is that these should be False when 'exists' is False:

```
isdir, ischr, isblk, isreg, isfifo, islnk, issock
```

The other stat values don't have meaning if exists is False. A change like that would be simple to make and backward compatible.

**Comment by dellis23** [comment]
Yeah, that sounds reasonable to me.  Still, my overall point is that the documentation here is the biggest problem.

**Comment by bcoca** [comment]
so this is one documentation solution that is being proposed for all modules:
https://groups.google.com/forum/#!topic/ansible-devel/5OuTJXZWgvY

**Comment by chicks-net** [comment]
I have been looking at doing some documentation patches for ansible and this is one I'd really like to see fixed, but the challenge of explaining how some of the variables show up some of the time and other times do not did not sound like a good time to me. :scream: If this were cleaned up as [twekberg](https://github.com/twekberg) suggests it would make ansible much more useful and cause fewer nightmares for whoever actually gets it documented properly.

[dellis23](https://github.com/dellis23) said:
| Still, my overall point is that the documentation here is the biggest problem.

:+1:  You are totally correct.  The weak docs are a sad impediment for a project that seems to be so excellent otherwise.

@bcoca that sounds like a good direction to go.

**Comment by dellis23** [comment]
@bcoca I like that.  (https://github.com/bcoca/ansible-modules-core/commit/9575cbc99f8ed43d37a54b47430a2b72e3e8c7ba is the commit, for anyone else).

**Comment by bcoca** [comment]
created 2 PRs #823 (now also documents stat module) and https://github.com/ansible/ansible/pull/10295 implements the viewer in ansible-doc

**Comment by twekberg** [comment]
Forget about my 'backward compatible' comment on Feb 17. It isn't

**Comment by twekberg** [comment]
Bcoca: I reviewed the PR #823 and made some comments. Hopefully you got them.

**Comment by bcoca** [comment]
@twekberg already updated PR, check again

**Comment by bcoca** [comment]
closing via merged #823
