### ISSUE TITLE
Create gce instance with permissions / service account scopes

### ISSUE THREAD

**Issue by jplehmann** [ansible/ansible-modules-core#109]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.4.3
##### Environment:

N/A
##### Summary:

Want to use gce module to create an instance with any permissions to access any other Google cloud resources like storage.  Apparently I need to pass in the [service_account_scopes flag](https://developers.google.com/compute/docs/instances)  [as is seen done in the unit test](https://github.com/ansible/ansible/blob/devel/test/gce_tests.py#L208) when calling `gcutil` directly.  How can I pass this flag using the module?
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

cc @erjohnso

Many thanks!

NOTE: this issue was ported over from the old ansible repo where it was https://github.com/ansible/ansible/issues/6003

**Comment by erjohnso** [comment]
@jplehmann - sorry I missed this before it was moved over to the new modules repo.  I'll see if I can get a PR out for this soon.

**Comment by ofir-petrushka** [comment]
@erjohnso Did you get any progress with this?

**Comment by ottob** [comment]
I agree, this would be very nice to have. :+1: 

I needed write access to cloud storage, so I made this quick patch for https://github.com/ansible/ansible-modules-core/blob/devel/cloud/google/gce.py#L349:

```
--- gce.py.orig 2015-02-09 22:08:23.356574248 +0000
+++ gce.py  2015-02-09 22:22:51.736554665 +0000
@@ -317,9 +317,10 @@
                 pd = gce.ex_get_volume("%s" % name, lc_zone)
         inst = None
         try:
+            ex_sa = [{'scopes': ['storage-rw']}]
             inst = gce.create_node(name, lc_machine_type, lc_image,
                     location=lc_zone, ex_network=network, ex_tags=tags,
-                    ex_metadata=metadata, ex_boot_disk=pd)
+                    ex_metadata=metadata, ex_boot_disk=pd, ex_service_accounts=ex_sa)
             changed = True
         except ResourceExistsError:
             inst = gce.ex_get_node(name, lc_zone)
```

**Comment by kernelt** [comment]
Hi all. When will this feature be implemented? We need it.

**Comment by coderlol** [comment]
+1

**Comment by kernelt** [comment]
I implemented and tested patch above. It's works for the ansible 1.9.1. However, if we can manually change type of access to backets (ro,rw etc...) via playbooks it would be great.

**Comment by gregdek** [comment]
The best way to get this implemented is for someone to turn it into a pull request. @ottob or @kernelt maybe?

**Comment by goozbach** [comment]
pull request should be #1335
