### ISSUE TITLE
AIX setup module fails

### ISSUE THREAD

**Issue by bigl0af** [ansible/ansible-modules-core#1108]
**Ansible Version: 1.9 from Github**

ansible 1.9 (detached HEAD e82ba723e2) last updated 2015/04/06 13:25:47 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 04c34cfa02) last updated 2015/04/06 13:25:47 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 21fce8ac73) last updated 2015/04/06 13:25:47 (GMT -400)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/02/10 07:41:54 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 21fce8ac73) last updated 2015/04/06 13:25:47 (GMT -400)
  configured module search path = /usr/share/ansible

**Environment:**

OS RHEL 6.4, managed node AIX 6.1

**Summary:**
During collecting facts (executing setup module on AIX) as a non root user that has sudo privs, module fails with error:

**Expected Results:**

module setup should be able to collect facts.

**Actual Results:**
$ ansible host1 -m setup -i hosts

host | FAILED >> {
    "cmd": "/usr/sbin/bootinfo -p",
    "failed": true,
    "msg": "[Errno 13] Permission denied",
    "rc": 13
}

**Comment by bigl0af** [comment]
Looks like this same issue was reported here https://github.com/ansible/ansible/issues/6458 but closed during code re-org...

**Comment by bcoca** [comment]
I'm guessing you need root in both cases to succeed?

**Comment by bcoca** [comment]
^ check if this PR fixes issues, the other issue with routes seems to have also been solved in previous commits.
