### ISSUE TITLE
Missing module yum_repository

### ISSUE THREAD

**Issue by BlessJah** [ansible/ansible-modules-core#1110]
There should be core module allowing to manage repositories for yum (like apt_repository for apt).

**Comment by binrush** [comment]
I've created a pull request to add such module to ansible https://github.com/ansible/ansible-modules-extras/pull/411

**Comment by DavidWittman** [comment]
This was added in https://github.com/ansible/ansible-modules-extras/pull/1016

**Comment by bcoca** [comment]
closing as per merged module above
