### ISSUE TITLE
ec2_vpc module will not update subnet tags

### ISSUE THREAD

**Issue by nfelger** [ansible/ansible-modules-core#1113]
#### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.0.1
##### Environment:

n/a
##### Summary:

When declaring a VPC with existing subnets that match the declared CIDR blocks, but have _different tags_, the module ignores the tags.

(Looking at the code, the same thing seems to be the case for AZs, but I haven't run into that issue myself.)
##### Steps To Reproduce:

Assuming we've got a VPC with the `10.0.0.0/16` block, tagged `Name="myvpc"`. The VPC has 1 subnet for the `10.0.1.0/24` block, tagged `Name="wrongname"`.

Running this task:

```
- ec2_vpc:
  cidr_block: 10.0.0.0/16
  region: "{{ ec2_region }}"
  resource_tags:
    Name: myvpc
  subnets:
    - cidr: 10.0.1.0/24
      az: "{{ ec2_availability_zone }}"
      resource_tags:
        Name: great_subnet_name
```

will not change the tag value for the subnet.  
##### Expected Results:

After running the task, the `10.0.1.0/24` subnet should have the tag `Name="great_subnet_name"`.
##### Actual Results:

It has the tag `Name="wrongname"`.

**Comment by analytically** [comment]
+1

**Comment by webmonarch** [comment]
+1

**Comment by autotune** [comment]
One thing to note after poking around the code for this module and additional testing so far is that it does update the tags upon creation of a new subnet, but once that subnet has been created it does not make additional updates when resource tags are modified. I am continuing to look into this bug, and will likely just be a matter of adding a condition to make sure they get updated outside of new subnet creation if the tags are different. This is present in the latest version of Ansible as well (2.1.0 (devel 15135f3c16) last updated 2015/12/16) on CentOS 7.1.
