### ISSUE TITLE
uri module doesn't honour environment proxy

### ISSUE THREAD

**Issue by smasset** [ansible/ansible-modules-core#1125]
When behind a proxy, the following uri task fails because the remote host cannot be resolved :

```
- name: Download from remote host behind a proxy with uri module
  sudo: yes
  uri:
    url=http://remote.host.com/remote.file
    dest=/var/tmp/remote.file
    HEADER_Cookie="name=value"
  environment: proxy_env
```

The following get_url task works (i.e. it resolves the host but fails to download contents as I can't set custom request header) :

```
- name: Download from remote host behind a proxy with get_url module
  sudo: yes
  get_url:
    url=http://remote.host.com/remote.file
    dest=/var/tmp/remote.file
  environment: proxy_env
```

Haven't looked at the code yet but could the uri module use the fetch_url utility method like get_url does ?

**Comment by smasset** [comment]
Two more bits of info :
- I'm using ansible 1.9.0.1
- I've used a command task with wget as a workaround

**Comment by darjeeling** [comment]
how did you setup  environment: proxy_env ?
like this document you should setup http://docs.ansible.com/playbooks_environment.html or var file

```
      environment:
        http_proxy: http://proxy.example.com:8080
```

I looked at the code, IMHO the uri module well support proxy environment.
because it's using httplib2 and 
it's automatically get proxy variable like `http_proxy` or `https_proxy`

https://github.com/ansible/ansible-modules-core/blob/devel/network/basics/uri.py#L262

https://github.com/jcgregorio/httplib2/blob/master/python2/httplib2/__init__.py#L804

https://github.com/jcgregorio/httplib2/blob/master/python2/httplib2/__init__.py#L1157

**Comment by smasset** [comment]
proxy_env is defined in a all.yml file in group_vars. Here are its values:

```
proxy_env:
  http_proxy: http://genproxy.domain.local:8080
  https_proxy: http://genproxy.domain.local:8080
```

So both modules use the same proxy configuration. I'll run the playbook again just to be sure.

**Comment by smasset** [comment]
Ran it again. Same result, sorry.

**Comment by kei-yamazaki** [comment]
I encountered same problem.
I'm using ansible 1.9.0.1 too.

**Comment by mstrzele** [comment]
:+1:

**Comment by DerekV** [comment]
Yes this is a thing.  1.9.2.  wget workaround.

**Comment by muffl0n** [comment]
Same issue here with Ansible 1.9.2. When I define the proxy in the playbook it does not work for `get_url`. `apt` for example works fine!

Workaround for me is to set the proxy in /etc/environment (on Ubuntu 12/14):

```
    - name: add http-proxy for internal hosts
      lineinfile: dest=/etc/environment regexp="^http_proxy" line="http_proxy=\"http://usr:pwd@myproxy.company:8080\""

    - name: add https-proxy for internal hosts
      lineinfile: dest=/etc/environment regexp="^https_proxy" line="https_proxy=\"http://usr:pwd@myproxy.company:8080\""
```

**Comment by dieu** [comment]
+1

**Comment by mstrzele** [comment]
This issue is caused by the old version of `httplib2` being installed as the dependency for Ansible. Can [this code](https://github.com/jcgregorio/httplib2/blob/master/python2/httplib2/__init__.py#L804-L861) be ported to the Ansible repository?

**Comment by dieu** [comment]
hm, I think it's problem with timeout, I don't know foreign environment, but our proxy sometimes a long react on large files. 

for me large timeout (Timeout for URL request) fixed all the problems.

**Comment by sivel** [comment]
This should no longer be an issue.  As of 2.1 the `uri` module no longer has a dependency on `httplib2` and will utilize the same shared code as the `get_url` module.

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
