### ISSUE TITLE
hostname module errors on systemd hosts when hostname > 64 characters

### ISSUE THREAD

**Issue by detiber** [ansible/ansible-modules-core#1142]
hostnamectl throws an error when a hostname is passed that is > 64 characters (`Failed to issue method call: Invalid argument`).

Suggestion for fix:
- if hostname is > 64 characters, try to split short hostname from domain and set to just short hostname
- if short hostname > 64 characters, error with a helpful message

**Comment by Jmainguy** [comment]
@detiber give #1359 a shot, I went for erroring out if longer than 64 chars, I would rather the module fail than succeed with a shorter name and possible confuse the admin later.

```
[root@phy01 ansible]# ansible -i hosts all -m hostname -a "name=nametosolvetheissuewherehostnamescannotbelongerthan64chars.soh.re"
centos7.soh.re | FAILED >> {
    "failed": true,
    "msg": "name cannot be longer than 64 characters on systemd servers, try a shorter name"
}

centos6.soh.re | FAILED >> {
    "failed": true,
    "msg": "Command failed rc=1, out=, err=hostname: name too long\n"
}
```

**Comment by detiber** [comment]
@Jmainguy lgtm, thanks!
