### ISSUE TITLE
DigitalOcean API 2 ssh_key_ids  problem

### ISSUE THREAD

**Issue by romain-dartigues** [ansible/ansible-modules-core#1161]
##### Issue Type:
- Bug Report
- Documentation Report
##### Ansible Version:
- ansible/ansible@f4172fb9daf27baaedd63d1f67ad072b2263d9e7
- ansible/ansible-modules-core@be89a2f5fcf9ca45c6ab45391f4d4f3b22bd1d4d

```
ansible 2.0.0 (devel f4172fb9da) last updated 2015/04/18 19:42:59 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a19fa6ba48) last updated 2015/04/18 19:43:07 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/18 19:43:15 (GMT +200)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/04/18 19:43:24 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/18 19:43:35 (GMT +200)
  configured module search path = None
```
##### Environment:

Irrevelant (Slackware GNU/Linux).
##### Summary:
1. The `ssh_key_ids` documentation is really unclear (is it a list of slugs, numerical ID, numerical ID as string, does it require spaces?).
2. The value is incorrectly parsed and sent, resulting in a `msg: ["103926","103927","747489"] are invalid key identifiers for Droplet creation.` error
##### Steps To Reproduce:

Following [Yamil Asusta tutorial](https://sendgrid.com/blog/ansible-and-digital-ocean/) and the [Digital Ocean module documentation](http://docs.ansible.com/digital_ocean_module.html):

``` yaml

---
- hosts: localhost
  tasks:
  - name: Create new DigitalOcean Droplet
    digital_ocean: >
      state=present
      command=droplet
      id=1
      name=ansible-tutorial
      size_id=512mb
      region_id=nyc3
      image_id=ubuntu-14-04-x64
      ssh_key_ids=["103926","103927","747489"]
```
##### Expected Results:

No errors :^)

A clear documentation.
##### Actual Results:

Gives the following error:

```
failed: [localhost] => {"failed": true}
msg: ["103926","103927","747489"] are invalid key identifiers for Droplet creation.
```
##### Possible solution

I found on digitalocean/api-v2#92 the numerical ID should be sent as string‽ (for the documentation).

I noticed the value of [`module.params['ssh_key_ids']`](https://github.com/ansible/ansible-modules-core/blob/360409cee8a54122c3e6debab3a5b17dc2ce9c72/cloud/digital_ocean/digital_ocean.py#L340) is interpreted (and i suppose sent) as a string.

Result of `repr(module.params)`:

``` python
{'api_token': None,
 'backups_enabled': False,
 'command': 'droplet',
 'id': 1,
 'image_id': 'ubuntu-14-04-x64',
 'name': 'ansible-tutorial',
 'private_networking': False,
 'region_id': 'nyc3',
 'size_id': '512mb',
 'ssh_key_ids': '["103926","103927","747489"]',
 'ssh_pub_key': None,
 'state': 'present',
 'unique_name': False,
 'user_data': None,
 'virtio': True,
 'wait': True,
 'wait_timeout': 300}
```

To check my hypothesis, i added after [`if not droplet:`](https://github.com/ansible/ansible-modules-core/blob/360409cee8a54122c3e6debab3a5b17dc2ce9c72/cloud/digital_ocean/digital_ocean.py#L334)

``` python
                module.params['ssh_key_ids'] = ["103926","103927","747489"]
```

Now the droplet is created and the `repr(module.params)` is:

``` python
{'api_token': None,
 'backups_enabled': False,
 'command': 'droplet',
 'id': 1,
 'image_id': 'ubuntu-14-04-x64',
 'name': 'ansible-tutorial',
 'private_networking': False,
 'region_id': 'nyc3',
 'size_id': '512mb',
 'ssh_key_ids': ['103926', '103927', '747489'],
 'ssh_pub_key': None,
 'state': 'present',
 'unique_name': False,
 'user_data': None,
 'virtio': True,
 'wait': True,
 'wait_timeout': 300}
```

(Notice that `ssh_key_ids` is now a list of string instead of a plain string.)

**Comment by bcoca** [comment]
closing as fixed by merged #1167
