### ISSUE TITLE
s3 checksum

### ISSUE THREAD

**Issue by RaasAhsan** [ansible/ansible-modules-core#1164]
I'm trying to upload some files with s3, but is it possible to not upload the file at all if the checksums of the files are the same?

I see the module checks for the checksum, but uploads anyways if its the same?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
