### ISSUE TITLE
Error when accessing an S3 bucket with dots in the bucket name

### ISSUE THREAD

**Issue by bbasata** [ansible/ansible-modules-core#1183]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel d996a2c216) last updated 2015/04/21 12:07:29 (GMT -400)
  lib/ansible/modules/core: (detached HEAD a19fa6ba48) last updated 2015/04/20 11:17:52 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/20 11:17:30 (GMT -400)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/02/25 16:33:46 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/20 11:17:30 (GMT -400)
  configured module search path = None
```
##### Environment:

OS X 10.9.5
##### Summary:

When I use the `s3` module to `create` or `get_url` for an S3 bucket with dots (`.`) in the name, the module fails with `boto.https_connection.InvalidCertificateException`.

This was working for me with Ansible 1.8. I cannot reproduce it in 1.9 because I instead see the error from #964, which has been fixed on `devel`.
##### Steps To Reproduce:

```
$ ansible -i 'localhost,' all -c local -m s3 -a "bucket=friendly.mouse mode=create"
```
##### Expected Results:

```
localhost | success >> {
    "changed": true,
    "msg": "Bucket created successfully."
}
```

or

```
localhost | success >> {
    "changed": false,
    "msg": "Bucket already exists."
}
```
##### Actual Results:

`boto.https_connection.InvalidCertificateException: Host friendly.mouse.s3.amazonaws.com returned an invalid certificate (remote hostname \"friendly.mouse.s3.amazonaws.com\" does not match certificate)`

Full output:

```
localhost | FAILED >> {
    "failed": true,
    "msg": "Traceback (most recent call last):\n  File \"/Users/me/.ansible/tmp/ansible-tmp-1429633039.8-158505780475999/s3\", line 2289, in <module>\n    main()\n  File \"/Users/me/.ansible/tmp/ansible-tmp-1429633039.8-158505780475999/s3\", line 449, in main\n    module.exit_json(msg=\"Bucket created successfully\", changed=create_bucket(module, s3, bucket, location))\n  File \"/Users/me/.ansible/tmp/ansible-tmp-1429633039.8-158505780475999/s3\", line 158, in create_bucket\n    bucket = s3.create_bucket(bucket, location=location)\n  File \"/usr/local/lib/python2.7/site-packages/boto/s3/connection.py\", line 612, in create_bucket\n    data=data)\n  File \"/usr/local/lib/python2.7/site-packages/boto/s3/connection.py\", line 664, in make_request\n    retry_handler=retry_handler\n  File \"/usr/local/lib/python2.7/site-packages/boto/connection.py\", line 1070, in make_request\n    retry_handler=retry_handler)\n  File \"/usr/local/lib/python2.7/site-packages/boto/connection.py\", line 942, in _mexe\n    request.body, request.headers)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 973, in request\n    self._send_request(method, url, body, headers)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1007, in _send_request\n    self.endheaders(body)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 969, in endheaders\n    self._send_output(message_body)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 829, in _send_output\n    self.send(msg)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 791, in send\n    self.connect()\n  File \"/usr/local/lib/python2.7/site-packages/boto/https_connection.py\", line 138, in connect\n    'certificate' % hostname)\nboto.https_connection.InvalidCertificateException: Host friendly.mouse.s3.amazonaws.com returned an invalid certificate (remote hostname \"friendly.mouse.s3.amazonaws.com\" does not match certificate): {'notAfter': 'Jun  5 23:59:59 2015 GMT', 'subjectAltName': (('DNS', '*.s3.amazonaws.com'), ('DNS', 's3.amazonaws.com')), 'subject': ((('countryName', u'US'),), (('stateOrProvinceName', u'Washington'),), (('localityName', u'Seattle'),), (('organizationName', u'Amazon.com Inc.'),), (('organizationalUnitName', u'S3-A'),), (('commonName', u'*.s3.amazonaws.com'),))}\n",
    "parsed": false
}
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

This is an ssl issue, amazon uses a wildcard cert which is valid only for _.basedomain, since you are adding a 2nd subdomain *._.basedomain is not covered.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above. You might want to set validate_certs=no to avoid this.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by bbasata** [comment]
Thanks, @bcoca, I'll post to the mailing list. The wildcard cert validity is understood, but I opened the issue because: [1] it worked in Ansible 1.8 and [2] it appears that boto's `OrdinaryCallingFormat` for s3, which the Ansible `s3` module uses, supports interacting with `s3.amazonaws.com` without using a subdomain.

**Comment by bbasata** [comment]
Mailing list post: https://groups.google.com/d/topic/ansible-project/saHvvn35OJk/discussion

I will try to further isolate the difference in behavior in hope of helping to address this.

**Comment by hryamzik** [comment]
For those who finds this on google: just put a [correct](https://github.com/boto/boto/issues/2836) profile file:

``` yml
- template: src=boto dest=/etc/boto
```

```
[s3]
calling_format = boto.s3.connection.OrdinaryCallingFormat
```

**Comment by AnthonyWC** [comment]
How does one fix this issue on the (newer style) aws config?

Tried

```
default]
output = json
region = us-east-1

[s3]
calling_format = boto.s3.connection.OrdinaryCallingFormat
host = s3-us-west-1.amazonaws.com
```

Gives the same error.  Also tried to put in .boto but got some other errors /w my dynamic inventory (ec2.py), is there a way to specify s3 config in .aws/config (like you could in s3 cli)?

**Comment by lig** [comment]
BTW s3_logging uses OrdinaryCallingFormat. Why don't implement the same in s3_bucket?

**Comment by CafeLungo** [comment]
This is still an issue as of ansible 2.3.1.0, why is this closed? It appears there is something that the ansible code base could change to allow it to work, using the OrdinaryCallingFormat. Setting `validate_certs: no` does not correct this problem, as far as I can tell.

**Comment by corydodt** [comment]
Nor should turning off cert validation be required.

The s3 module is simply using the wrong s3 calling format. This is still a bug, please reopen.

**Comment by dagwieers** [comment]
@corydodt This repository is not longer being maintained, as everything has been moved over to https://github.com/ansible/ansible. So I don't think reopening this issue is going to help move things forward.

I suggest that if this is still an issue, you open a new ticket at https://github.com/ansible/ansible/issues or you could try out [this tool](https://github-issue-mover.appspot.com/) that can migrate an existing issue (preserving context).

If you know the solution and can fix it, opening a PR would be even better :-)

Thanks for taking the time. *Persistence is utile.*

**Comment by KwankiAhn** [comment]
Thanks~!

I got error with : gsutil ls -al s3://aa.bb.cc
-> Failure host xxx returned an invalid certificate

editing .boto like below works !
[s3]
calling_format = boto.s3.connection.OrdinaryCallingFormat

gsutil ls -al s3://aa.bb.cc | more
         0  2017-03-27T01:06:44Z  s3://...  metageneration=None
         8  2017-03-27T02:07:21Z  s3://... metageneration=None
        20  2017-03-27T02:07:14Z  s3://...  metageneration=None
        ...
