### ISSUE TITLE
Support directory_mode for file module

### ISSUE THREAD

**Issue by Glandos** [ansible/ansible-modules-core#1186]
Hi,

Currently, when setting permissions recursively with the `file` module, there is only one mode (e.g. 0750). It should be good to have, as the `copy` module, a `directory_mode` to set a special mode on directories.

**Comment by Glandos** [comment]
My bad. I didn't see that symbolic modes in ansible/ansible#5220 support the x/X that should set permission on directory only.

**Comment by jeffwidman** [comment]
It would still be convenient to have a `directory_mode` on the `file` module, both for convenience and because--like you--I first messed with file permissions via the `copy` module, and expected to find a similar option in the `file` module.
