### ISSUE TITLE
mysql_user module fails without config_file set

### ISSUE THREAD

**Issue by jeffbryner** [ansible/ansible-modules-core#1215]
Attempting to create a user without specifying a config_file results in the following stack trace (forced by removing generic exception catching and using the ansible-examples wordpress deploy) : 

TASK: [wordpress | Create WordPress database user] ****************************
failed: [<ipaddress here>] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1430237848.07-140306729185464/mysql_user", line 2183, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1430237848.07-140306729185464/mysql_user", line 420, in main
    cursor = connect(module, login_user, login_password, config_file)
  File "/root/.ansible/tmp/ansible-tmp-1430237848.07-140306729185464/mysql_user", line 196, in connect
    if os.path.exists(config_file):
  File "/usr/lib64/python2.6/genericpath.py", line 18, in exists
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

Setting a config_file (even to one that doesn't contain user info) allows this to proceed, but seems like a bug.

The original error message provided by the module is incorrect and misleading: 
TASK: [wordpress | Create WordPress database user] ****************************
failed: [<ipaddress here>] => {"failed": true}
msg: unable to connect to database, check login_user and login_password are correct

**Comment by juliakreger** [comment]
Also seeing this bug, along with additional issues I'm sorting out now.  Seems like a very quick fix because None is always passed in overriding the default set in the method for the default location of the file.

**Comment by bcoca** [comment]
ansible version? os? mysql version? or if you could just use the https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md

**Comment by juliakreger** [comment]
I'm seeing it on devel branch, Ubuntu 14.04LTS, Most recent mysql patches applied.  If I fix the default and set it so it is not defaulted to None, I get further along, but my user creation still fails.  Not exactly sure why, just started my first cup of coffee.

https://github.com/juliakreger/bifrost/blob/master/playbooks/roles/ironic-install/tasks/main.yml#L87 is the task that was working a few days ago for me.  Now,  it just returns "msg: unable to connect to database, check login_user and login_password are correct", Adding the exception string to the output, I end up getting "TypeError: coercing to Unicode: need string or buffer, NoneType found".

**Comment by jeffbryner** [comment]
Oh, sorry..didn't know about the template. But @juliakreger that's exactly the same issue I had until I added the conf file to the call. 
Here's the info: 

Issue Type: Bug Report
Version: ansible --version
ansible 2.0.0
  configured module search path = None

Environment: OSX ansible-playbook managing ubuntu 14.04 installing the ansible wordpress example.

Summary: Request to create user always fails with errant message about not being able to log in when in fact the error is related to an os call to find a none-existant .cnf file.

Steps to Reproduce: 
Attempt to create a worpress user using the ansible-examples wordpress deployment template.

Expected Results: 
wordpress user is created
Actual Results: 
TASK: [wordpress | Create WordPress database user] ****************************
failed: [] => {"failed": true}
msg: unable to connect to database, check login_user and login_password are correct

**Comment by juliakreger** [comment]
Looks like my additional issues were due to package updates trashing my local mysql install....  I wiped it out, started over and a quick fix to the module I was up and running again.

**Comment by juliakreger** [comment]
I have proposed https://github.com/ansible/ansible-modules-core/pull/1235 to correct this issue.  Tested locally, works as expected.

**Comment by abadger** [comment]
#1235 has been merged.  This should be fixed in the devel branch.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
