### ISSUE TITLE
synchronize adds extra to the --rsh argument and causes failure

### ISSUE THREAD

**Issue by ryanobjc** [ansible/ansible-modules-core#1219]
failed: [MY_HOST -> 127.0.0.1] => {"cmd": "rsync --delay-updates -F --compress --delete-after --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no None' --exclude=logs --out-format='<<CHANGED>>%i %n%L' \"/src/file\" \"root@MY_HOST:/root/\"", "failed": true, "rc": 255}

The 'None' after the StrickhostKeyChecking=no causes this command to fail with host not found 'none'

**Comment by lcanal** [comment]
I wanted to chime in that adding:
ssh_args : no 
to the module arguments results in having it insert "False":

TASK: [appserver | Copy Files To Server] **************************************
build   28-Apr-2015 14:09:56    failed: [MY_HOST -> 127.0.0.1] => {"cmd": "rsync --delay-updates -F --compress --delete-after --checksum --recursive --rsh 'ssh -i /home/bamboo/.ssh/id_rsa -S none -o StrictHostKeyChecking=no False' --no-motd --exclude=.git --out-format='<<CHANGED>>%i %n%L' \"/home/bamboo/xml-data/build-dir/131073/24641538-24739847/files/\" \"deployer@MY_HOST:/opt/WebRoot-DEV/"", "failed": true, "rc": 255}
msg: ssh: Could not resolve hostname False: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]

**Comment by rhartkopf** [comment]
I was about to open an issue for the same. Here's my task:

```
- name: Apache sites-enabled
  synchronize: src=sites-enabled-prodweb dest=/etc/apache2/sites-enabled delete=yes
  sudo: yes
  notify: restart apache2
```

And the output:

```
failed: [example.com -> 127.0.0.1] => {"cmd": "rsync --delay-updates -F --compress --delete-after --archive --rsh 'ssh -i /var/lib/jenkins/.ssh/ansible/id_dsa_example.com -S none -o StrictHostKeyChecking=no None' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/var/lib/jenkins/workspace/ansible-run/apache-config/files/sites-enabled-prodweb\" \"ansible@172.20.30.165:/etc/apache2/sites-enabled\"", "failed": true, "rc": 255}
msg: ssh: Could not resolve hostname None: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]
```

Removing `None` after `StrictHostKeyChecking=no` fixes the issue. PR to follow.

**Comment by rhartkopf** [comment]
The faulty line is here:

https://github.com/ansible/ansible-modules-core/blob/c323ef9233e63cf6538648be68262eb55b35bd06/files/synchronize.py#L319

Testing conditional to get around this, will submit a request in a few minutes.
