### ISSUE TITLE
win_msi: Can't handle text required to be quoted in extra_args parameter

### ISSUE THREAD

**Issue by itshanney** [ansible/ansible-modules-core#1229]
First of all, I didn't see that extra_args was supported in the documents so this may, or may not, be officially supported. After looking at the source code, it appears that extra_args can be passed with the win_msi module so I attempted to use this.

After attempting with one variable, all is well. As soon as multiple variables separated by a space are added, the msiexec process just hangs that's kicked off by the win_msi.ps1 script. I have to kill the msiexec process on the Win machine to let the playbook continue.

Here is both the win_msi.ps1 and arguments files that are sent over the wire and remains on the Win machine after I told the control machine to not delete the files.

win_msi.ps1 - https://gist.github.com/itshanney/9a98c6c2f3975b43f8a8
arguments: https://gist.github.com/itshanney/0afb89dc2cb427d973b1

Finally, here is the -vvvv output from the ansible-playbook run:

https://gist.github.com/itshanney/e14878e8446552ed8da0

I would be happy to give you other debugging information if you can direct me how to retrieve what you need. This is all running on Ansible version 1.9.0.1 with a CentOS 6.5 host machine talking to a Windows Server 2008 machine.

**Comment by itshanney** [comment]
Posted this to the Google Group and supplied some more research on the issue. While I'm no PowerShell or Windows expert, it appears that the msiexec command being called is extremely persnickety in the params that are passed to it. Quoted values are just not valid.

https://groups.google.com/forum/#!topic/ansible-project/iZ8j9LvLDXI

**Comment by blade2005** [comment]
I'm not sure this is solely a quoting issue.

I'm using extra args:

> INSTALL_ONLY=1 PROV_NOW=0

And it hangs, If I give it only one of them it works fine. I believe this points to an issue with powershell or the ps1.

> $complex_args = @'
> {"_ansible_no_log": false, "_ansible_diff": false, "_ansible_verbosity": 3, "extra_args": "INSTALL_ONLY=1 PROV_NOW=0", "_ansible_check_mode": false, "_ansible_debug": false, "path": "C:\\TEMP\\al_agent-LATEST.msi", "wait": true}
> '@
> 

The extra_args are obviously present, it's double quoted like it should be but it's not performing correctly.

**Comment by jhawkesworth** [comment]
Based on latest feedback from @blade2005 this has been fixed via another commit, so i an closing this.
