### ISSUE TITLE
apt: state=present for virtual packages always shown as changed

### ISSUE THREAD

**Issue by drzraf** [ansible/ansible-modules-core#1230]
If you already have a package installed which _Provides_ a virtual package, then a
`apt: state=present name=virtual-package`
always appears as changed, apparently because the `apt-get install` output is slightly different (this is not very robust).

Eg:
_exim4-daemon-light_ is installed
Then try:
`- apt: name=default-mta state=present`
There apt output includes these 2 lines which seem to disturb the apt module:

> Note, selecting 'exim4-daemon-light' instead of 'default-mta'
> exim4-daemon-light is already the newest version.

**Comment by bcoca** [comment]
I've tried to fix this a couple of times, but end up hitting infinite loops (specifically with mta dma).

**Comment by devjatkin** [comment]
I have proposed #1348 as fix. Main idea is return status of provided package, for example: return postfix package status as status of default-mta
