### ISSUE TITLE
sysctl module fails on OpenBSD

### ISSUE THREAD

**Issue by nusenu** [ansible/ansible-modules-core#1233]
OpenBSD's sysctl has no '-p' option:

msg: Failed to reload sysctl: sysctl: unknown option -- p
usage: sysctl [-Aan]
       sysctl [-n] name ...
       sysctl [-nq] name=value ...

Shortly looking at the code shows that there is a case that handles FreeBSD but none for OpenBSD.
https://github.com/ansible/ansible-modules-core/blob/devel/system/sysctl.py#L230

**Comment by cmacrae** [comment]
A quick note on this (figured it may be handy): OpenBSD's `sysctl` utility doesn't have a 'reload' option, nor an associated daemon that could be restarted. To set sysctl values in OpenBSD, one simply runs `sysctl some.key.name=value`.  
For example, taken from `man sysctl`:  

```
To set the maximum number of processes allowed in the system to 1000:

           # sysctl kern.maxproc=1000
```

So a solution to this may not be as simple as the conditional for FreeBSD.  
That said, perhaps having `sysctl` parse `/etc/sysctl.conf` (or any other sysctl file put in place by the Ansible) could be a solution, though could be hacky/ugly.  

Just my two-cents on this, I'm not proficient in Python I'm afraid! Maybe I'll hack at it :)

**Comment by cmacrae** [comment]
Would something _like_ the following work?   

``` python
        elif get_platform().lower() == 'openbsd':
            # openbsd doesn't support -p, or have a sysctl service, so parse /etc/sysctl.conf
            for line in open(self.sysctl_file):
                li=line.strip()
                if not li.startswith("#"):
                    setting = line.rstrip()
                    rc,out,err = self.module.run_command(self.sysctl_cmd, setting)
```

Emphasis on "like"... because the above code doesn't work, but it gives you an idea of what I was thinking. Perhaps a rather illogical approach, seeing as the desired `sysctl` values are already being presented in dicts elsewhere.  

Like I said: I'm not proficient in Python, so, don't hesitate to point out if the above approach is idiotic!

**Comment by bcoca** [comment]
looks promising, putting on my list for check/implementation

**Comment by cmacrae** [comment]
Awesome, thanks @bcoca

**Comment by nusenu** [comment]
> A quick note on this (figured it may be handy): OpenBSD's `sysctl`
> utility doesn't have a 'reload' option, nor an associated daemon that
> could be restarted. To set sysctl values in OpenBSD, one simply runs
> `sysctl some.key.name=value`.

My opinion is actually that ansible should do that in all OS'es since I
might not want to activate the entire lines in sysctl.conf if I change a
single setting via ansible. Ansible should still write the setting to
sysctl.conf but why reload the entire file?
(if the admin reboots the entire file gets taken into account - as it is
expected)

**Comment by bcoca** [comment]
The reload parameter controls the reload behavior, I do not like the default but it's been grandfathered in. A note should be added that it does not work on OpenBSD.

**Comment by cmacrae** [comment]
@nusenu - yes, I agree. Hence why in my other response I state that my approach could be considered illogical, and that it should simply be parameters set by Andible that are presented via the dicts passed from evaluation, not simply parsing the file.

@bcoca - Adding a note rather than trying to have Ansible do the reload? Would the approach of having Ansible execute 'sysctl' on the sysctl key/value pairs passed to it not be an elegant solution?

**Comment by bcoca** [comment]
@cmacrae reload in the other cases implies a 'refresh' of the sysctl.conf file, not just of the parameters passed (which should already be applied).

**Comment by cmacrae** [comment]
@bcoca Cool, ok - so would the pseudo code I provided in [my comment above](https://github.com/ansible/ansible-modules-core/issues/1233#issuecomment-100522041) be somewhere in the ballpark for a solution?

**Comment by bcoca** [comment]
kind of, it seems a bit brute force to run through the file

**Comment by sysfu** [comment]
What's the status on this issue? I too would like to be able to apply sysctl.conf changes on OpenBSD without having to restart the system. As it stands I have a task to copy the sysctl.conf file to the remote system, and then four more tasks running sysctl commands to apply each of the four lines in the file without rebooting.

**Comment by bcoca** [comment]
@sysfu waiting for a PR that will fix it, closest thing is @cmacrae code but I've expressed my concerns above
