### ISSUE TITLE
OpenStack filters

### ISSUE THREAD

**Issue by xsuchy** [ansible/ansible-modules-core#1234]
Hi,
I created filters for OpenStack which transform id to name and vice versa.
  https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/filter_plugins/openstack.py
I would love to create PR, however I'm not sure in which path it should land.

**Comment by sivel** [comment]
An email to the ansible-devel mailing list is the best way to start, as opposed to an issue, since this really is a question.

**Comment by bcoca** [comment]
Also, this seems more appropriate as a lookup, filters are for data transformation, lookups are for querying external data sources.
