### ISSUE TITLE
core module: git - unsupported parameter: clone

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#1240]
Issue Type:

Bug Report

Ansible Version:

1.8.2-1ppa~precise

Ansible Environment:

Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:    12.04
Codename:   precise

Target Environment:

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty

Summary:

Trying to use 'clone=no' with the git module.

Steps To Reproduce:

```
[...]
- name: check if rattic has already been cloned
  git: dest={{ rattic_path }}/rattic repo=https://github.com/tildaslash/RatticWeb.git clone=no update=no
  register: clone_status
  failed_when: false
- debug: var=clone_status
  failed_when: true
[...]
```

Expected Results:
Task succeeds and registered variable indicates whether or not local clone exists (per documentation: http://docs.ansible.com/git_module.html)

Actual Results:

```
[...]
TASK: [servers/rattic | debug var=clone_status] ******************************* 
failed: [rattic-dev] => {"clone_status": {"failed": false, "failed_when_result": false, "invocation": {"module_args": "dest=/var/www/rattic repo=https://github.com/tildaslash/RatticWeb.git clone=no update=no", "module_name": "git"}, "msg": "unsupported parameter for module: clone"}, "failed": true, "failed_when_result": true, "verbose_always": true}

FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment]
If you read the docs, this feature is added in 1.9 and not available in 1.8.2. Closing this ticket as this seems like a misunderstanding.

**Comment by ghost** [comment]
Missed that inline comment. Apologies.

**Comment by bcoca** [comment]
no worries, it is a bit off  to the left, any suggestions to make that clearer in the docs will be appreciated.

**Comment by ghost** [comment]
Gut instinct is to add a new column, either before or after comments, though I'd lean towards after. Column header, "version" -- denoting the first version it was available with an empty field indicating it has always been available. I do not know if parameters are ever removed but if that is a possibility you could indicate this in the same field by using a "+" or "-" prior to the number, indicating when the parameter was added or removed (respectively).
