### ISSUE TITLE
Service module: with systemd doesn't use args correctly

### ISSUE THREAD

**Issue by iprok** [ansible/ansible-modules-core#1246]
I use ansible-1.9.0.1. 
When I try to use service module with daemon who takes and arguments like openvpn and it happend on OS using systemd, then problem occurs.
For example on non systemd system I use:
service: name=openvpn state=restarted name=serv
and get openvpn server called "serv" restarted. 

Under system with systemd it gives me an error cause I must use
service: name=openvpn@serv state=restarted

So maybe it would be better when trying to use "service" module on systemd systes to append value of "args" to service name just like openvpn@serv ?

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the first case when you are passing args this is passed to the init script which has to be written to accept them, this is not a generic interface for any service type. In the case of systemd, the proper name for the service is openvpn@serv as this is a systemd feature to allow you to run multiple named copies of the same service (with diff configurations). So both allow you to do the same thing but they are unrelated mechanisms.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
