### ISSUE TITLE
"file" module does not support sticky bit

### ISSUE THREAD

**Issue by dago** [ansible/ansible-modules-core#1248]
I am trying to set the sticky bit to specific directories without changing the other mode bits with

```
    file: dest={{ item }} mode=u+t
    with_items: world_writable.stdout_lines
```

However, the mode bits of the directories are not changed. I am using 1.9.0.1.

**Comment by blackreed9** [comment]
_My testing and examples are on CentOS_

I think what you want is _o+t_.

```
 tasks:
    - name: Set Sticky Bit
      file: dest=/opt/sticky_bit_dir mode=o+t
```

<hr>

#### Target directory before

```
@core-a1 11:34:25 /opt# ls -l
total 4
drwxrwxrwx 2 root root 4096 May  4 11:32 sticky_bit_dir
```

Run your playbook ( _with o+t_ )

#### Target directory after

```
@core-a1 11:35:54 /opt# ls -l
total 4
drwxrwxrwt 2 root root 4096 May  4 11:32 sticky_bit_dir
```

**Comment by dago** [comment]
I was confused as my `chmod` on Solaris only takes `u+t` and not `o+t`:

```
work# ls -ld foo
drwxr-xr-x   2 root     root           2 Apr 24 23:12 foo
work# chmod u+t foo; ls -ld foo
drwxr-xr-t   2 root     root           2 Apr 24 23:12 foo
work# chmod u-t foo; ls -ld foo
drwxr-xr-x   2 root     root           2 Apr 24 23:12 foo
work# chmod o+t foo; ls -ld foo
drwxr-xr-x   2 root     root           2 Apr 24 23:12 foo
work# chmod a+t foo; ls -ld foo
drwxr-xr-t   2 root     root           2 Apr 24 23:12 foo
```

So my system explicitly breaks POSIX here:
- http://pubs.opengroup.org/onlinepubs/9699919799//utilities/chmod.html (see issue 6 at the bottom)

As suggested the best way seems to use just `a+t` which works with Solaris chmod and also the file module.

Thanks for pointing me in the right direction! -- Dago
