### ISSUE TITLE
Suggestion: improve mysql_user fail message

### ISSUE THREAD

**Issue by karpy47** [ansible/ansible-modules-core#1267]
Right now it is rather hard to understand what is wrong when you get the message:
"msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials"
It might be given for many reasons, so it would be very helpful to get the exception from the MySQLdb.connect() method in a readable format instead.
I spent a long time trying various combinations before diving into the source code and finally understandning what was going on. 

Otherwise a nice product, thanks for the effort.

**Comment by Jmainguy** [comment]
@karpy47 would you rather have that long message + the exception, or just the exception?

**Comment by karpy47** [comment]
Not sure, in general the more info the better, but depends on the detail and readability of the exception message. The "long message" might give better help for the most common reason of failure.

A long message + exception seems like a good idea. Don't know if you have some standard on error reporting, but it would be good to somehow know that the exception message is a python message, ie not much more details available from going into the source code.

**Comment by Jmainguy** [comment]
@karpy47 look at https://github.com/ansible/ansible-modules-core/commit/8892aa2bf430f25be124b655cc12c975cd1bfbdc  we could do the same thing in mysql_user, sound good?

**Comment by karpy47** [comment]
Yes, looks good. Great to get more info when debugging. Havn't looked at mysql_user, but guess it would make sense there to.

**Comment by Jmainguy** [comment]
@karpy47 Looks like with above merge we should be able to close this out, what do you think?

**Comment by karpy47** [comment]
Thank you
