### ISSUE TITLE
mysql_user: which parameters to use in .my.cnf file

### ISSUE THREAD

**Issue by karpy47** [ansible/ansible-modules-core#1268]
I can't get the .my.cnf file to work. Looking into the source code I don't understand if the password parameter should be "passwd" or "password"? Anyway, neither works for me.
Documentation says:
[client]
user=root
password=n<_665{vS43y

It could be a problem with the "config_file" option in my case. In my debian-environment "~" is translated by most ansible-modules to "/root" instead of "/home/debian". However, I've solved it by using {{ ansible_env['HOME'] }} at several places. Don't know if it might affect how MySQLdb reads the config file...

**Comment by blackreed9** [comment]
What version of Ansible are you running?

Can we see your playbook?

**Comment by karpy47** [comment]
Sorry, just found a mistake on my side. Confused by a recent code release addressing this. Closing time...
