### ISSUE TITLE
Add support for docker labels

### ISSUE THREAD

**Issue by bobrik** [ansible/ansible-modules-core#1277]
I can come up with a PR, but I already have 2 from March 22 that were not merged yet.

**Comment by diefans** [comment]
+1

**Comment by ryanwalls** [comment]
+1

**Comment by MrMMorris** [comment]
@bobrik I can't find any PR's from you on this. If you have a patch I would LOVE this functionality as I don't name my containers and need to differentiate with Prometheus. 

Let me know if there is a PR I can throw a fat +1 at :yum:

**Comment by MrMMorris** [comment]
@smashwilson this would also be nice if you have time :smile:

**Comment by bobrik** [comment]
@MrMMorris I have tho PRs hanging from Mar 22, can't see any reason to add more. Anyway, check out [collectd-docker](https://github.com/bobrik/collectd-docker) it might be sufficient for you :)

**Comment by 0x736861** [comment]
+1

**Comment by lbradeen** [comment]
+1

**Comment by Cactusbone** [comment]
:+1:

**Comment by MrMMorris** [comment]
has there been any progress on this?

**Comment by leonty** [comment]
Someone please review.

**Comment by leonty** [comment]
Created a PR for v2 devel.

**Comment by solher** [comment]
+1

**Comment by paudam** [comment]
+3
