### ISSUE TITLE
Question about running the Oracle Client installer in silent mode

### ISSUE THREAD

**Issue by pschirch** [ansible/ansible-modules-core#1287]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.1
##### Environment:

N/A
##### Summary:

I allready described this issue [here](https://github.com/ansible/ansible/issues/8814). I created a role to perform a silent Oracle client setup. With ansible **1.6.10 it works**, but newer Ansible versions skips executing the [shell task](https://github.com/pschirch/ansible-role-oracle-client/blob/master/tasks/main.yml#L86). I also tried the module **command** and **raw**, same issue here.
##### Steps To Reproduce:

I created a [demo role](https://github.com/pschirch/ansible-role-oracle-client) to demonstrate this behaviour. Please read the [README.md](https://github.com/pschirch/ansible-role-oracle-client/blob/master/README.md) file.
##### Expected Results:

Continuing the Oracle client setup after executing the memory checks. You can find the installer script `runInstaller` in `/home/oracle/Downloads/client/`. At the end of the file this script starts the binary file `.oui` in `/home/oracle/Downloads/client/install` if the `-silent` flag is configured.

**Task Output** (Ansible 1.6.10)

``` bash
TASK: [pschirch.oracle-client | Installing Oracle Client.] ******************** 
<127.0.0.1> REMOTE_MODULE command /bin/bash /home/oracle/Downloads/client/runInstaller -silent -ignorePrereq -ignoreSysPrereqs -noconfig -responseFile /home/oracle/Downloads/client.rsp #USE_SHELL
changed: [127.0.0.1] => {"changed": true, "cmd": "/bin/bash /home/oracle/Downloads/client/runInstaller -silent -ignorePrereq -ignoreSysPrereqs -noconfig -responseFile /home/oracle/Downloads/client.rsp", "delta": "0:00:43.468758", "end": "2015-05-08 10:14:26.961675", "rc": 0, "start": "2015-05-08 10:13:43.492917", "stderr": "", "stdout": "Starting Oracle Universal Installer...\n\nChecking Temp space: must be greater than 120 MB.   Actual 15212 MB    Passed\nChecking swap space: must be greater than 150 MB.   Actual 523 MB    Passed\nPreparing to launch Oracle Universal Installer from /tmp/OraInstall2015-05-08_10-13-43AM. Please wait ...You can find the log of this install session at:\n /home/oracle/app/oraInventory/logs/installActions2015-05-08_10-13-43AM.log\nThe following configuration scripts need to be executed as the \"root\" user. \n #!/bin/sh \n #Root scripts to run\n\n/home/oracle/app/oraInventory/orainstRoot.sh\n/home/oracle/app/oracle/product/11.2.0/client_1/root.sh\nTo execute the configuration scripts:\n\t 1. Open a terminal window \n\t 2. Log in as \"root\" \n\t 3. Run the scripts \n\t 4. Return to this window and hit \"Enter\" key to continue \n\nConfiguration assistants have not been run. This can happen for following reasons - either root.sh is to be run before config or Oracle Universal Installer was invoked with the -noConfig option.\n\"/home/oracle/app/oracle/product/11.2.0/client_1/cfgtoollogs/configToolAllCommands\" script contains all commands to be executed by the configuration assistants. This file may be used to run the configuration assistants outside of OUI. Note that you may have to update this script with passwords (if any) before executing the same.\n\n\nSuccessfully Setup Software."}
```
##### Actual Results:

**Task Output** (Ansible 1.9.1)

``` bash
TASK: [pschirch.oracle-client | Installing Oracle Client.] ******************** 
<127.0.0.1> REMOTE_MODULE command /bin/bash /home/oracle/Downloads/client/runInstaller -silent -ignorePrereq -ignoreSysPrereqs -noconfig -responseFile /home/oracle/Downloads/client.rsp #USE_SHELL
changed: [127.0.0.1] => {"changed": true, "cmd": "/bin/bash /home/oracle/Downloads/client/runInstaller -silent -ignorePrereq -ignoreSysPrereqs -noconfig -responseFile /home/oracle/Downloads/client.rsp", "delta": "0:00:03.100993", "end": "2015-05-08 10:40:27.400644", "rc": 0, "start": "2015-05-08 10:40:24.299651", "stderr": "", "stdout": "Starting Oracle Universal Installer...\n\nChecking Temp space: must be greater than 120 MB.   Actual 15212 MB    Passed\nChecking swap space: must be greater than 150 MB.   Actual 523 MB    Passed\nPreparing to launch Oracle Universal Installer from /tmp/OraInstall2015-05-08_10-40-24AM. Please wait ...", "warnings": []}
```

Skipping shell executing after **"Please wait ..."**

**Comment by oravirt** [comment]
I had the same issue going from 1.6 to 1.7. 
The issue is that you need the -waitforcompletion flag added to your runInstaller command.
The installer will spawn a new process and put that in the background, but if you add the -waitfor... it wont, and the installer will wait for the installation to finish before the next ansible task runs. 

If I remember correctly I think the 'problem' in 1.6 was that in some rare cases unclosed file descriptors caused some weird behaviours, like yours. The behaviour in > 1.6 is the correct one.

**Comment by pschirch** [comment]
Hi oravirt,

thanks for that advice. I added the `-waitforcompletion` flag to the runInstaller script and it works now.

**Thank you so much!**

**Comment by leonardosantoslopes** [comment]
It's almost three years later and ... it saved me "some" time and headache.
Thanks.
