### ISSUE TITLE
sysctl bug - yaml dict format in sysctl task with an int value reports 'changed=true' every run.  

### ISSUE THREAD

**Issue by halberom** [ansible/ansible-modules-core#1344]
Issue Type: Bug Report
Ansible Version:

```
~/vagrant/centos $ ansible --version
ansible 1.9.1
```

Ansible Configuration: default

Environment:
mac osx controller using vagrant centos image

```
[vagrant@localhost ~]$ cat /etc/centos-release 
CentOS release 6.6 (Final)
```

Summary:
Using the yaml dict format in sysctl task with an int value reports 'changed=true' every run.  

Steps To Reproduce:
- use the following vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-6.6"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "play.yml"
  end 

end
```
- run the following playbook

```

---
- hosts: all 
  remote_user: vagrant
  sudo: true
  tasks:

    - yum: name=libselinux-python state=present
    - selinux: state=disabled

    - name: set vm swappiness
      sysctl:
        ignoreerrors: true
        name: vm.swappiness
        value: 10
      register: result

    - debug: var=result
```

e.g.

```
~/vagrant/centos $ ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook play.yml -i hosts -vvvv --private-key=.vagrant/machines/default/virtualbox/private_key
```
- re-run the playbook

Expected Results:
After re-running, it should not change anything

```
TASK: [set vm swappiness] ***************************************************** 
ok: [default]
```

Actual Results:
It reports it as changed

```
TASK: [set vm swappiness] ***************************************************** 
changed: [default]
```

Debugging:
The module appears to parse the sysctl.conf file into a json dict, and all values are strings, when the module is passed an int value, it fails on the comparison.

Full debugging is here - https://gist.github.com/halberom/6bd0abcff79a50af529e

**Comment by halberom** [comment]
Additional thoughts...

The examples in the module docs are key=value parameters.  Which in yaml is essentially a string value, so those work.  Only in the yaml dict structure does this fail as a number is interpreted as an int value.

**Comment by bcoca** [comment]
confirm that PR above fixes your issue

**Comment by halberom** [comment]
fetched, and tested

```
TASK: [set vm swappiness] ***************************************************** 
failed: [default] => {"failed": true}
msg: implementation error: unknown type <type 'str'> requested for value

FATAL: all hosts have already failed -- aborting
```

Should be type='str' (i.e. quoted).  Raised updated PR.

**Comment by bcoca** [comment]
updated with quotes

**Comment by halberom** [comment]
With type='str', it works correctly for this error.

I also tested setting a value with quotes, which worked fine if escaped in key=value format

```
    - name: set kernel domain
      sysctl: ignoreerrors=true name=kernel.domain value=\"example.com\"
      register: result
```

but I'm not sure what the correct syntax would be if done using yaml dict format, because I couldn't get it to work with " or \".   But that's outside the scope of this error. just thought I'd mention it
