### ISSUE TITLE
Quantum should be renamed to neutron

### ISSUE THREAD

**Issue by achanda** [ansible/ansible-modules-core#1361]
Some core modules are still named `quantum_*`, they should be renamed to `neutron_*`. I will be happy to work on this.

**Comment by bennojoy** [comment]
@achanda  thanks, there is some work already done towards this.. https://github.com/ansible/ansible-modules-extras/pull/92

**Comment by achanda** [comment]
@bennojoy The PR you linked does address my concern here. Closing this ticket.
