### ISSUE TITLE
ec2_vol: Commit 6b27cdc break some use case

### ISSUE THREAD

**Issue by patlachance** [ansible/ansible-modules-core#1362]
Commit 6b27cdc08eba5f2ff817b4e0470dd4b6034012c7 changed the volume creation logic to "find and name" volume at creation time but it breaks some use cases when name is not specified and more than one volumes are present with no name tag.

**Comment by bennojoy** [comment]
@patlachance  can you please attach the task that works before the commit and fails after the commit, from the code it seems like even before the commit if a name is not specified and multiples volumes exists in the AZ it would still fail

**Comment by patlachance** [comment]
@bennojoy : please find below the code that was working before and is broken by commit 6b27cdc.
Note that I also [proposed a fix](https://github.com/ansible/ansible-modules-core/pull/1363) this morning.

Failure arise when there are more than one volume without a name tag present in EBS 
- name: Attach an EBS bootdisk volume to instance
  ec2_vol:
     region: "{{ region }}"
     zone: "{{ zone }}"
     instance: "{{ item.id }}"
     state: present
     volume_size: "{{ chroot_bootdisk_size }}"
     device_name: "{{ chroot_bootdisk_devname }}"
  with_items: ec2.instances
  register: ec2_vol_bootdisk

**Comment by wimnat** [comment]
@patlachance i have experienced the issue you reported but I'm not sure how your proposed fix resolves the issue.

I have a PR which has fixes including this one here https://github.com/ansible/ansible-modules-core/pull/2180

Could you test and let me know if it works for you?
