### ISSUE TITLE
s3 plugin not compatible with boto package in ubuntu-14.04

### ISSUE THREAD

**Issue by ploxiln** [ansible/ansible-modules-core#1369]
I used the repo package "python-boto" from ubuntu-14.04, and it was apparently too old. So it was able to import boto, but then failed:

```
  File "/home/vagrant/..../s3", line 351, in main
    bucketrtn = bucket_check(module, s3, bucket)
  File "/home/vagrant/..../s3", line 162, in bucket_check
    except s3.provider.storage_response_error, e:
AttributeError: 'NoneType' object has no attribute 'provider'
```

Perhaps ansible would like to support the standard repo packaged boto on ubuntu 14.04?

**Comment by ploxiln** [comment]
I should mention, ubuntu-14.04 packages boto 2.20.1 as python-boto-2.20.1-2ubuntu2

**Comment by bennojoy** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!
