### ISSUE TITLE
Service module --check mode applies "enabled=" change on Ubuntu 14.04 instead of just checking

### ISSUE THREAD

**Issue by soltiz** [ansible/ansible-modules-core#1374]
check mode flag seems to be ignored when using enabled=  feature of service module
used version is ansible 1.9.1
target system uses UBUNTU 14.04.01 LTS

ubuntu@dummy:~$   ll /etc/rc_.d/_apache2
lrwxrwxrwx 1 root root 17 mai   20 09:20 /etc/rc0.d/K20apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:20 /etc/rc1.d/K20apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:20 /etc/rc2.d/K80apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:20 /etc/rc3.d/K80apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:20 /etc/rc4.d/K80apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:20 /etc/rc5.d/K80apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:20 /etc/rc6.d/K20apache2 -> ../init.d/apache2*

ansible --check dummy -s -u ubuntu -m service -a 'name=apache2 enabled=yes' 

dummy | success >> {
    "changed": true,
    "enabled": true,
    "name": "apache2"
}

ubuntu@dummy:~$ ll /etc/rc_.d/_apache2
lrwxrwxrwx 1 root root 17 mai   20 09:21 /etc/rc0.d/K20apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:21 /etc/rc1.d/K20apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:21 /etc/rc2.d/S20apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:21 /etc/rc3.d/S20apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:21 /etc/rc4.d/S20apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:21 /etc/rc5.d/S20apache2 -> ../init.d/apache2*
lrwxrwxrwx 1 root root 17 mai   20 09:21 /etc/rc6.d/K20apache2 -> ../init.d/apache2*

**Comment by Jmainguy** [comment]
@soltiz give #1407 a shot. Seems to work for me.

**Comment by bcoca** [comment]
closing this per merged #1407
