### ISSUE TITLE
apt_repository should allow the repo filename to be specified

### ISSUE THREAD

**Issue by gdevenyi** [ansible/ansible-modules-core#14]
See https://github.com/ansible/ansible/issues/8904

Issue Type: Feature Idea

Ansible Version: ansible 1.7.1

Environment: Ubuntu 14.04

Summary:

I request a feature to allow me to specify what filename the apt_repository creates

apt_repository: repo='deb http://archive.canonical.com/ubuntu hardy partner' state=present filename=hardy-partner.list

Steps To Reproduce:

When I add a repo such as:
deb http://dl.google.com/linux/talkplugin/deb/ stable main

A file is created named:
dl_google_com_linux_chrome_deb.list

When I install the package google-chrome-stable, which comes from this repo, it creates:
google-chrome.list

With the same repo content, so apt-get complains about duplicate entries

Expected Results:

Clean repository

Actual Results:

Duplicated repo entries

**Comment by mpdehaan** [comment]
Can you please copy the description over?

**Comment by pflorczyk** [comment]
Any progress on this ? This is real pain especially if you have repos with version number somewhere in the name (it generates new list file with each version) or change between current/stable releases. Sooner or later you will end with unexpected results. In current form using this module is just asking for trouble. I just ditched it and use 2 tasks (template + apt) to workaround this issue. It looks like adding simple "name" arg would fix this.

**Comment by nitzmahone** [comment]
fixed by PR #2696
