### ISSUE TITLE
issues with win_copy

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible-modules-core#1404]
Playing around with win_copy, I'm noticing these issue:
 'src=file.txt dest=C:\file.txt': OK on new file, OK on existing, FAILS on changed (reports unchanged)
"src=file.txt dest=C:/file.txt": Same as above
"src=file.txt dest=C:\": FAIL (seems like the \" combination doesnt escape properly on linux)
"src=file.txt dest=C:/": OK on new file, FAIL on existing ("path is not a file"), FAIL on changed (reports no change, expected result is updated file)

"src=folder dest=C:/" OK on new folder, FAIL on existing ("path is not a file"), FAIL on changed ("path is not a file")

**Comment by mkoshelev** [comment]
win_copy.ps1 needs to be patched to detect changes:

```
--- win_copy.ps1.orig   2014-12-11 13:50:17.000000000 -0800
+++ win_copy.ps1    2015-05-14 16:56:09.683278480 -0700
@@ -52,17 +52,17 @@

 If (Test-Path $dest)
 {
-    $dest_checksum = Get-FileChecksum ($dest);
-    $src_checksum = Get-FileChecksum ($src);
+    [string] $dest_checksum = Get-FileChecksum ($dest);
+    [string] $src_checksum = Get-FileChecksum ($src);

-    If (! $src_checksum.CompareTo($dest_checksum))
+    If ( $src_checksum.CompareTo($dest_checksum))
     {
         # New-Item -Force creates subdirs for recursive copies
         New-Item -Force $dest -Type file;
         Copy-Item -Path $src -Destination $dest -Force;
     }
-    $dest_checksum = Get-FileChecksum ($dest);
-    If ( $src_checksum.CompareTo($dest_checksum))
+    [string] $dest_checksum = Get-FileChecksum ($dest);
+    If (! $src_checksum.CompareTo($dest_checksum))
     {
         $result.changed = $TRUE;
     }
```

**Comment by trondhindenes** [comment]
A lack of checksumming would explain my two first fails. If we continue to only require PSv3 I'm not sure Get-FileChecksum would work, as that cmdlet isn't available on Win2008R2 (this needs to be verified). Tapping into .Net to create a custom checksum function shouldn't be too hard.

For the other bugs, the PowerShell module needs to check if the dst value is a container or file (leaf), in combination with what type of object the source is (dir or file), and have some logic around that to decide how to proceed. I don't know enough python to help on the action plugin side, but I can certainly help out improving the powershell files if needed.

**Comment by jhawkesworth** [comment]
I am away from any devices which have a physical keyboard at the moment so can't dig into this at the moment but I think there are a couple of observations I can make. 

1/ I think “c:\“ won't work because \ has special meaning in yaml. 

A 2 if I recall (and it is quite a long time since I worked on these modules, Get-FileChecksum is in the common powershell functions and is a wrapper around dotnet cryptographic function. That said I don't recall being able to test against powershell 3.

If anyone is able to get to this before me, please go ahead. Please run the windows integration tests and add any missing cases. Unfortunately the integration tests are in ansible core so would need two prs to change.

**Comment by jhawkesworth** [comment]
Ok I'm working on PRs to fix this up. 

Get-FileChecksum is in module_utils/powershell.ps1.  

Part of the problem at least is that it is not always returning a string, when it should.  So I will fix that and then the module code won't need lots of [string] casts each time Get-FileChecksum is used.

**Comment by jimi-c** [comment]
@jhawkesworth just following up with you on this, as I'd like to get 1.9.2-rc2 out as soon as possible.

**Comment by jhawkesworth** [comment]
Working on it, but its taking longer than I hoped to fix as I have
uncovered problems with recursive copies.
Gonna stay up now and see if I can crack it in the next couple of hours.
Jon

**Comment by jhawkesworth** [comment]
Ok.  I haven't been able to do anything about \ having a special meaning to yaml, other than documenting   the use of / as path separator (powershell accepts either \ or /), but I think I have fixed the other issues described above.

PRs https://github.com/ansible/ansible/pull/11086
and
https://github.com/ansible/ansible-modules-core/pull/1438

I see the first has merge conflicts.  Need sleep before attempting to resolve.

**Comment by jhawkesworth** [comment]
Merge conflicts resolved.  Please test.
I still don't have any powershell 3.0-powered machines to test against so would be grateful if anyone else can test these out.

You can give a basic test by running the winrm integration tests (although currently one of the 'script' module steps seems to be broken for me).

**Comment by cchurch** [comment]
@jhawkesworth I've just pushed a fix for the failing script test: https://github.com/ansible/ansible/pull/11092

**Comment by jhawkesworth** [comment]
For completeness, just to say I have replaced ansible/ansible#11086 with ansible/ansible#11115 as I managed to check in some other unwanted changes in the earlier PR.

**Comment by jhawkesworth** [comment]
@trondhindenes My fixes for win_copy have been merged into latest devel.  Any chance you can test and hopefully close this issue?  Many thanks,
Jon

**Comment by trondhindenes** [comment]
Hm, still seems problematic :-(
azureuser@ansibletest:~$ ansible all -m win_copy -a 'src=testfile.txt dest=C:\testfile.txt'
thhighperf4 | FAILED >> {
    "checksum": "0d2aae7d156d796b97ae11b4dba506a55f54a75e",
    "failed": true,
    "msg": "src checksum 0d2aae7d156d796b97ae11b4dba506a55f54a75e  did not match dest_checksum 0d2aae7d156d796b97ae11b4dba506a55f54a75e   Failed to place file testfile.txt in C:\testfile.txt"
}

it actually places the file but reports error. For some reasone the temp files are removed from the target node even if I've set ANSIBLE_KEEP_REMOTE_FILES=1 in ansible.cfg so its hard to troubleshoot. I'm running against the v1 version, can't seem to get v2 working at the moment. I don't know if that could affect my testing?

**Comment by jhawkesworth** [comment]
Hmm, away from the keyboard at the moment and not sure right now if core
and modules changes applied to v1 and v2.

If I recall there was a time when v1 and v2 were using different checksum
algorithms in the common powershell.ps1 file. This may or may not be
relevant.

I don't remember having a problem with v2 so I wonder if I made the changes
before v2 became current.

What happens when you try with v2?

**Comment by jhawkesworth** [comment]
Ok, not entirely sure what is going on here, as I don't get the same results as you.

v2 is not connecting, but the following works for me:

```
source v1/hacking/env-setup
echo "This is a test file" > ~/testfile.txt
ansible all -i ../ansible_saved_things/inventory.winrm -v -m win_copy -a 'src=../testfile.txt dest=C:\testfile.txt'
```

It is true the v1 and v2 powershell.ps1 files are different - in fact it is the ./v1/ansible/module_utils/powershell.ps1 which is correct.

So there are 2 things to address - getting the 'v2' version of powershell.ps1 (in lib/ansible/module_utils/powershell.ps1 to be the same as the one in v1) and getting v2 working for winrm connections.

I just rebased my devel branch to commit 5ed2e440260e2d06d234634305f4d61e82413f6c before running the above.

**Comment by trondhindenes** [comment]
Learning lots about git. It seems that the ansible devel branch has hardcoded submodule commits (instead of just reffing the devel branch of the respective submodule repos). So, I'll test again and update this space. I ran the following commands in order to get all 4 submodule refs to point to the devel branch of the submodule repos:

git config -f .gitmodules submodule.lib/ansible/modules/core.branch devel
git config -f .gitmodules submodule.lib/ansible/modules/extras.branch devel
git config -f .gitmodules submodule.v1/ansible/modules/core.branch devel
git config -f .gitmodules submodule.v1/ansible/modules/extras.branch devel
git submodule update --remote

**Comment by trondhindenes** [comment]
found the bug. Here's the current get-filechecksum in powershell.ps1 file in v1:
Function Get-FileChecksum($path)
{
    $hash = ""
    If (Test-Path -PathType Leaf $path)
    {
        $sp = new-object -TypeName System.Security.Cryptography.SHA1CryptoServiceProvider;
        $fp = [System.IO.File]::Open($path, [System.IO.Filemode]::Open, [System.IO.FileAccess]::Read);
        [System.BitConverter]::ToString($sp.ComputeHash($fp)).Replace("-", "").ToLower();
        $fp.Dispose();
    }
    ElseIf (Test-Path -PathType Container $path)
    {
        $hash= "3";
    }
    Else
    {
        $hash = "1";
    }
    return $hash
}

This function will actually output an array consisting of two strings: first the result of "[System.BitConverter]::ToString($sp.ComputeHash($fp)).Replace("-", "").ToLower();" since that line isn't stored in a var, and then the outout of "$hash" (the "return $hash" line) which will be an empty string. Which is why the checksum comparison between the two files will always be dodgy.

@jhawkesworth  The real question is how this could be working on your system at all :-). Could you be working with a powershell.ps1 file which is edited?

I also noticed that the v2 powershell.ps1 file doesn't have the get-filechecksum at all, but rather a get-filemd5. We MUST make sure these two files stay in sync, or else the whole Windows module set will become impossible to test.

**Comment by trondhindenes** [comment]
Submitted PR  #11281 to fix the get-filechecksum error.

**Comment by jhawkesworth** [comment]
Thanks @trondhindenes - yes you are right Get-FileChecksum needs to change to capture the returned checksum.  I have made this change in the past but somehow it is not present now in devel.  Perhaps I messed up when I attempted to fix merge conflicts.
I still don't understand how it works for me, I will investigate further.

**Comment by trondhindenes** [comment]
Yep, all working now after the updated powershell.ps1 was merged in yesterday. Obviously this still has no effect on users running v1 because the submodule ref is behind but that's outside the scope of this single issue I guess. Great job!
