### ISSUE TITLE
yum install @group always results in "changed"

### ISSUE THREAD

**Issue by anderskandersson** [ansible/ansible-modules-core#1441]
Using "yum: name='@group'" always results in "changed", even on subsequent invocations where no work needs to be done.

(https://github.com/ansible/ansible/issues/9030)

**Comment by jctanner** [comment]
Please retest this behavior on a recent verison of ansible. In (devel 3d7a7c1612) groups are not handled properly for update, but are handled for install. Once https://github.com/ansible/ansible-modules-core/issues/4119 is resolved, group updates should be handled correctly also.
