### ISSUE TITLE
Validate options in various file modules do not permit `nginx -t` validation

### ISSUE THREAD

**Issue by jeffwidman** [ansible/ansible-modules-core#1456]
Nginx validation happens with `nginx -t`; it will automatically check all nginx config files--both the primary and any tacked on via file includes--and doesn't support passing a specific config file to it. 

However, when I try to run `validate='nginx -t'` Ansible complains that validate requires `%s`... which is a nice safety feature, but prevents me from validating my nginx configuration changes.

**Comment by bcoca** [comment]
That would not work as validate happens BEFORE the file gets put into place (as docs clearly state), you would only be validating the previous configuration. Also the validate function only works well with single file configurations as this is what copy/template/etc operate on at each time.

Also note that nginx in newer versions supports -c to specify alternate configuration files, which works with this option.

**Comment by jeffwidman** [comment]
That makes sense.

I tried `nginx -tc %s` and it unfortunately doesn't work for my usecase--as you mentioned single-file configs are best for the validate option.

In my case, I'm uploading a vhost file, so it's an include to a broader nginx set of config files. Nginx using the -ct test on it fails, vs it works fine when I upload without validition. I suspect `nginx -c` assumes you're passing it a complete configuration file, rather than an include fragment.
