### ISSUE TITLE
setup module gathers facts four times

### ISSUE THREAD

**Issue by dgloe** [ansible/ansible-modules-core#1461]
While researching slowness in the setup module I discovered the setup module gathers facts four times:
        4    0.000    0.000   10.042    2.510 setup:1627(get_platform_facts)
        4    0.000    0.000   15.297    3.824 setup:1660(get_local_facts)

This is really slowing down our ansible runs since we're on 1.7.1 and can't cache facts.
The culprit is here:
    facts.update(Facts().populate())
    facts.update(Hardware().populate())
    facts.update(Network(module).populate())
    facts.update(Virtual().populate())

Each of those constructors calls the parent init, which gets local and platform facts.

By the way there's also a lot of time spent in select, when we only have one fact that runs almost instantaneously:
       68   15.334    0.226   15.334    0.226 {select.select}

**Comment by bcoca** [comment]
I'm not sure what we can do, we don't maintain 1.7.1 anymore any fixes would be applied to 1.9.x or 2.x

**Comment by jctanner** [comment]
Testcase ...

```
$ cat test.sh 
#!/bin/bash
VERSION=$(ansible --version | head -n1 | awk '{print $2}')
CMD="ansible-playbook -vvvv -i inventory site.yml"
rm -f time.txt
{ time $CMD ; } 2> time.txt
RC=$?
if [[ $RC != 0 ]]; then
    exit 99
fi    
REAL=$(cat time.txt | egrep ^real | awk '{print $2}')
echo "RESULT:$VERSION:$REAL"

$ cat site.yml 
- hosts: el6host
  gather_facts: True
  connection: local
  tasks:

$ cat inventory 
el6host ansible_ssh_host=10.0.0.106
```

**Comment by jctanner** [comment]
Test results (with facter installed but not ohai)...

| version | duration |
| --- | --- |
| 1.0 | 0m0.284s |
| 1.1 | 0m0.290s |
| 1.2 | 0m0.396s |
| 1.2.1 | 0m0.394s |
| 1.2.2 | 0m0.391s |
| 1.2.3 | 0m0.412s |
| 1.3.0 | 0m0.369s |
| 1.3.1 | 0m0.352s |
| 1.3.2 | 0m0.358s |
| 1.3.3 | 0m0.350s |
| 1.3.4 | 0m0.364s |
| 1.4 | 0m0.378s |
| 1.4.1 | 0m0.381s |
| 1.4.2 | 0m0.379s |
| 1.4.3 | 0m0.597s |
| 1.4.4 | 0m0.382s |
| 1.4.5 | 0m10.405s |
| 1.5 | 0m0.390s |
| 1.5.1 | 0m0.446s |
| 1.5.2 | 0m0.439s |
| 1.5.3 | 0m0.426s |
| 1.5.4 | 0m0.409s |
| 1.5.5 | 0m0.417s |
| 1.6 | 0m0.466s |
| 1.6.1 | 0m0.428s |
| 1.6.10 | 0m0.415s |
| 1.6.2 | 0m0.417s |
| 1.6.3 | 0m0.434s |
| 1.6.4 | 0m0.433s |
| 1.6.5 | 0m0.459s |
| 1.6.6 | 0m0.435s |
| 1.6.7 | 0m0.436s |
| 1.6.8 | 0m0.441s |
| 1.6.9 | 0m0.434s |
| 1.7 | 0m1.188s |
| 1.7.1 | 0m1.160s |
| 1.7.2 | 0m1.183s |
| 1.8 | 0m1.127s |
| 1.8.1 | 0m1.159s |
| 1.8.2 | 0m1.160s |
| 1.8.3 | 0m1.184s |
| 1.8.4 | 0m1.136s |
| 1.9.0 | 0m1.524s |
| 1.9.0 | 0m1.212s |
| 1.9.0 | 0m1.232s |
| 1.9.0 | 0m1.206s |
| 1.9.0.1 | 0m1.237s |
| 1.9.1 | 0m2.183s |
| 1.9.1 | 0m1.148s |
| 1.9.1 | 0m1.161s |
| 1.9.1 | 0m2.171s |
| 1.9.1 | 0m1.153s |
| 1.9.2 | 0m1.172s |
| 1.9.2 | 0m1.154s |
| 1.9.2 | 0m1.130s |
| 1.9.3 | 0m1.140s |
| 1.9.3 | 0m1.154s |
| 1.9.3 | 0m1.118s |
| 1.9.3 | 0m1.120s |
| 1.9.4 | 0m1.164s |
| 1.9.4 | 0m1.152s |
| 1.9.4 | 0m1.140s |
| 1.9.4 | 0m1.131s |
| 1.9.5 | 0m1.136s |
| 1.9.5 | 0m1.193s |
| 1.9.6 | 0m1.166s |
| 1.9.6 | 0m1.210s |
| 2.0.0 | 0m1.396s |
| 2.0.0 | 0m1.389s |
| 2.0.0 | 0m1.351s |
| 2.0.0 | 0m1.349s |
| 2.0.0.0 | 0m1.336s |
| 2.0.0.1 | 0m1.328s |
| 2.0.0.2 | 0m1.405s |
| 2.0.1.0 | 0m1.360s |
| 2.0.1.0 | 0m1.390s |
| 2.0.1.0 | 0m1.386s |
| 2.0.2.0 | 0m1.375s |
| 2.0.2.0 | 0m1.328s |
| 2.0.2.0 | 0m1.371s |
| 2.0.2.0 | 0m1.345s |
| 2.0.2.0 | 0m1.383s |
| 2.1.0.0 | 0m1.664s |

**Comment by jctanner** [comment]
I found a possible optimization that reduces total duration slightly. Futher information in https://github.com/ansible/ansible/pull/15716

**Comment by jctanner** [comment]
Hi!

A change has been applied for this ticket, which should resolve this item for you.

If you believe this ticket is not resolved, or have further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments on closed tickets, though the mailing list is a great way to get involved or discuss this one further.

Thanks!
