### ISSUE TITLE
ec2_group documentation is out of sync on website  

### ISSUE THREAD

**Issue by ryanwalls** [ansible/ansible-modules-core#1469]
Compare:
http://docs.ansible.com/ec2_group_module.html
with the DOCUMENTATION block here:
https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2_group.py

The website documentation is missing critical documentation like "state", "rules_egress", and "purge_rules."

I don't know how to fix this or I would create a PR.

**Comment by bcoca** [comment]
for some reason docstring quoting got embeded in the docs, breaking them

**Comment by bcoca** [comment]
seems it was unintended and misguided 'peppifying' in 5e694c490cca727e1bf22a8f4358c48ca29ec59b that munged the lines to the 80 column limit and messed with the docstring limits

**Comment by bcoca** [comment]
fixed via f5ff5ba348b1158b569d29125676553a6aa7d49a, this won't be visible on the website right away as we don't immediately publish changes.
