### ISSUE TITLE
docker module: Default network behavior does not mimic docker run

### ISSUE THREAD

**Issue by geauxvirtual** [ansible/ansible-modules-core#147]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8
##### Environment:

CentOS 6.5
##### Summary:

I'm filing this issue, though this may be a corner case that a majority of users may never see.

When starting a container with docker run from an image that does not expose ports, docker run will automatically expose the ports defined in -p option passed to the docker run command. With Ansible, just defining the ports for the container does not properly set up networking. The expose option must also be used to list what ports should be exposed. 
##### Steps To Reproduce:

Networking does not get setup.

```

---
- hosts: all
  tasks:
  - name: Start Network container
    docker: image=kubernetes/pause
            name=network
            ports=8080:8080,8443:8443
```

Docker run command automatically exposes the listed ports and sets up networking properly.

```
docker run -d -p 8080:8080 -p 8443:8443 --name network kubernetes/pause
```
##### Expected Results:

Container should have the port exposed and be listed in iptables showing routes for those ports to the container that was started.
##### Actual Results:

Container does not have networking routing setup unless 'expose' option is explicitly defined in the playbook.

**Comment by sveneh** [comment]
I can confirm this. Using the docker module is very frustrating, because it often behaves different than the command line client, and the docs are not helping. Case in point, only this bug report helped me solve my networking issue with expose.

Instead of using the ansible docker module, one often has to use ansible shell running docker command, because this will work.

**Comment by aindlq** [comment]
I can confirm this as well, it is actually very subtle and confusing bug. At least it would make sense to add this behavior to module docs. See https://github.com/ansible/ansible/issues/9648#issuecomment-68571501 for more details.

**Comment by tcurdt** [comment]
_sigh_ the docker module is just a PITA

**Comment by tobilarscheid** [comment]
This is urgent! Just cost us an hour to come here....

**Comment by chouseknecht** [comment]
Two suggestions... Check out the new [docker_container module](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker_container.py). If you're using Docker compose, check out the new [docker_service module](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker_service.py) which consumes compose directly. Both are part of 2.1RC2. Interested to hear your feedback.
