### ISSUE TITLE
IAM Module - and group updates - failure

### ISSUE THREAD

**Issue by toninog** [ansible/ansible-modules-core#1481]
Hi

I am using ansible version : 1.9.0.1 and the latest IAM module.  When running the example playbooks I get this error:

<127.0.0.1> REMOTE_MODULE iam iam_type=group name=Mario state=present
failed: [127.0.0.1] => (item=Mario) => {"failed": true, "item": "Mario", "parsed": false}
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1433757871.5-141229831843557/iam", line 2508, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1433757871.5-141229831843557/iam", line 666, in main
    new_group, changed = create_group(iam, name, path)
TypeError: create_group() takes exactly 4 arguments (3 given)

when running the add user to groups example - I get: 

failed: [127.0.0.1] => {"failed": true}
msg: unsupported parameter for module: group

FATAL: all hosts have already failed -- aborting

I found a version of the iam.py that has a fix for the first issue, but not the second.

What am I doing wrong ?  I copied the examples directly from the code.

Thanks

**Comment by bennojoy** [comment]
The example in the docs is wrong , the 'group' param needs to be changed to  use 'groups' and the method also needs to be fixed

**Comment by toninog** [comment]
all issues are resolved  - please see pull request : 

https://github.com/ansible/ansible-modules-core/pull/1486

Thanks bennojoy
