### ISSUE TITLE
Service Module does not use same Service Manager Package as Service command

### ISSUE THREAD

**Issue by dagnello** [ansible/ansible-modules-core#1512]
Target environment: Ubuntu 14.04.1 LTS
Ansible Host environment: Ubuntu 14.04.1 LTS, Ansible 1.9.1-1ppa~trusty

Repro:
1. use apt module to install zookeeper and zookeeperd
2. use service module to stop zookeeper
3. log into target machine, zookeeper is still running

What is happening:

zookeeper is installing init scripts for both init.d and upstart
service zookeeper start/stop/restart uses upstart init script (zookeeper is started by apt this way when installed)
using Ansible's service module to start/stop/restart zookeeper, the init.d script is used instead. This creates the potential for a second instance of zookeeper to be launched, and Ansible is unable to stop the first (upstart launched) instance.

**Comment by pzhuk** [comment]
observing exactly same issue. Deploying zookeeper from package has 2 configs - both upstart and init.d. When ansible tries to enable and start service - second instance is started.

That's how we do service enable:

  name: Enable zookeeper
  service: name=zookeeper state=started enabled=yes

**Comment by gregdek** [comment]
Test in devel? I think it's handled by #999

**Comment by bcoca** [comment]
closing as fixed by #999 and released with 1.9.2
