### ISSUE TITLE
command module in getting start document didn't work

### ISSUE THREAD

**Issue by yuanl** [ansible/ansible-modules-core#1535]
The very first command `$ ansible all -a "/bin/echo hello"` in getting start page will fail starting from release 1.8.0 with error message:

```
foo | FAILED | rc=0 >>
this module requires key=value arguments (['/bin/echo', 'hello'])
```

used to working good in 1.7.2 and previous.

**Comment by bennojoy** [comment]
@yuanl  could you please try it in the latest stable release as i am not able to reproduce this.

**Comment by yuanl** [comment]
@bennojoy I can do it with the pip 1.9.1 version now. maybe I didn't update the git one in a correct way.

**Comment by yuanl** [comment]
Please close this issue. problem are gone after I reclone the git. It turn out to be my mistake.
