### ISSUE TITLE
windows/win_copy

### ISSUE THREAD

**Issue by rremella** [ansible/ansible-modules-core#1540]
Win_copy not able copy large files around 20 mb and getting following error

TASK: [win_copy src=/root/windows/nimsoft-robot-x64.exe dest=c:\TEMP\nimsoft-robot-x64.exe] ***
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ansible/runner/connection_plugins/winrm.py", line 198, in put_file
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:])
  File "/usr/lib/python2.6/site-packages/ansible/runner/connection_plugins/winrm.py", line 125, in _winrm_exec
    command_id = self.protocol.run_command(self.shell_id, command, args)
  File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 232, in run_command
    rs = self.send_message(xmltodict.unparse(rq))
  File "/usr/lib/python2.6/site-packages/winrm/protocol.py", line 173, in send_message
    return self.transport.send_message(message)
  File "/usr/lib/python2.6/site-packages/winrm/transport.py", line 95, in send_message
    raise WinRMTransportError(error_message)
WinRMTransportError: Bad HTTP response returned from server. Code 500

**Comment by bcoca** [comment]
cc @jhawkesworth , should we just document that this is for small files only?

**Comment by rremella** [comment]
Small conf files have no issues

**Comment by bcoca** [comment]
@rremella this is a known limitation with the method the module uses to copy files, winrm does not seem to like large transfers. This is still a bug, we should detect the issue and return a 'nice' message to the user explaining the situation.

**Comment by jhawkesworth** [comment]
Yes, documentng would be good in the short term.  I put a note about it not
scaling in the doc but it should be explicit about what it can and can't do.
If I knew what / if there is a hard file size limit then it would be best
to check the file size locally and error nicely saying its too big to be
transferred with win_copy.

It may be the case that we can increase the max size by changing winrm
configuration parameters during the setup for remoting, in which case it
would not be great to enforce a hard limit in ansible.

Is anyone able to test what practical limit is against win 7 / server 2008
and server 2012 (they may be different)?

**Comment by rremella** [comment]
I tested using winrm parameter MaxMemoryPerShellMB = 1024 by increasing size .

It didn't help have same issue

**Comment by gbevan** [comment]
isn't the issue with powershell's base64 decoding, doing it all in memory?  see this link:
https://mnaoumov.wordpress.com/2013/08/20/efficient-base64-conversion-in-powershell/

**Comment by jhawkesworth** [comment]
Possibly, the module reuses the winrm connection plugin's put file logic.
That does appear to have to chop up the file into some pretty small pieces.
 without testing it, I've no idea whether the code you link to would be any
faster / more memory efficient though.

**Comment by jhawkesworth** [comment]
This issue has been languishing for a while now.  The module documentation now states that it isn't suitable for large files, so any objections if it is closed?

**Comment by cchurch** [comment]
I have a branch in the works that fixes this issue (https://github.com/cchurch/ansible/tree/winrm_put_file),  just not quite ready for a PR.

**Comment by jhawkesworth** [comment]
Delighted that you are working on this.  I was kind of out of ideas that didn't involve big changes.
I guess leaving this open is as a good a way as any to track then.

**Comment by jhawkesworth** [comment]
Delighted that you are working on this.  I was kind of out of ideas that didn't involve big changes.
I guess leaving this open is as a good a way as any to track then.

**Comment by h0nIg** [comment]
hey, i came across the same limitation. whats the status of this issue?

**Comment by jhawkesworth** [comment]
@h0nIg see https://groups.google.com/forum/#!topic/ansible-devel/aAFdMPvYiFs

**Comment by jhawkesworth** [comment]
Hi @rremella Since the change has been merged into 2.0.0 development branch can this ticket be closed now?

**Comment by nitzmahone** [comment]
fixed in 2.0
