### ISSUE TITLE
Digital Ocean image/size/region slugs

### ISSUE THREAD

**Issue by chbrown** [ansible/ansible-modules-core#157]
##### Environment:
- Running from Mac OS X Mavericks, ansible installed via Homebrew
- Administering CentOS 7 on Digital Ocean
##### Summary:

Digital Ocean's API now allows selecting your desired image / size / region via "slugs", which are just strings that have a 1-to-1 relationship with the desired image_id / size_id / region_id.
- [Regions](https://developers.digitalocean.com/v1/regions/)
- [Images](https://developers.digitalocean.com/v1/images/)
- [Sizes](https://developers.digitalocean.com/v1/sizes/)

It'd be handy to be able to use said slugs in the `digital_ocean` module.
##### Steps To Reproduce:

```
- hosts: localhost
  connection: local
  tasks:
    - name: Create Digital Ocean droplet size=512Mb image=Centos 7.0 x64 region=New York City 3
      digital_ocean: >
        state=present
        command=droplet
        name=especiallycoherent
        size_id=66
        ssh_key_ids="{{ digitalocean.ssh_key.id }}"
        region_id=nyc3 # or region=nyc3 or region_slug=nyc3 etc.
        image_id=6511101
        unique_name=yes
      register: digitalocean
```
##### Expected Results:

```
ok: [localhost] => {"changed": false, "droplet": {"backups_active": false, "created_at": "2014-10-07T17:36:19Z", "id": 2803097, "image_id": 6511101, "ip_address": "123.45.67.89", "locked": false, "name": "awesomebox", "private_ip_address": null, "region_id": 8, "size_id": 66, "status": "active"}}
```
##### Actual Results:

```
ValueError: invalid literal for int() with base 10: 'nyc3'
```

**Comment by leucos** [comment]
This is getting urgent, since IDs are disappearing in DO API v2 (v1 will be deprecated on Nov 1st)

**Comment by bcoca** [comment]
is there a PR that 'fixes' this?

**Comment by leucos** [comment]
It seems that @rvangundy is working on it per https://github.com/ansible/ansible/issues/8563

**Comment by leucos** [comment]
@bcoca this issue can be **closed**, since devel works fine with DO API v2 now and supports slugs at least for regions and sizes and DO_API_TOKEN (tested this morning).

**Comment by bcoca** [comment]
closing as per above

**Comment by brandonweiss** [comment]
Is this released yet? Does anyone know when it will be? The docs seem to be out-of-sync with what's released.

**Comment by leucos** [comment]
@brandonweiss it is in devel. I currently use it and it WorksForMe™. I guess 2.0.0 is not too far away, but as always, "it will be ready when it will be ready" ;)

**Comment by brandonweiss** [comment]
That's fine, but why are the docs out-of-sync then :(

**Comment by leucos** [comment]
I don't know, but I think the docs are for the current release (i.e. 1.9.1), not devel. For instance, you don't have anything regarding the 3 consul modules which are currently in devel.
You can read the doc in the module source, it's not that hard (https://github.com/ansible/ansible-modules-core/blob/devel/cloud/digital_ocean/digital_ocean.py) and should be always 'current', or use `ansible-doc digital_ocean` at the command line.

**Comment by bcoca** [comment]
actually docs are from current devel, we are working on splitting into devel and 'last stable'.

docs are not updated automatically, specially for modules, it requires 2 steps: 1 update refs in main repo, issue a 'production docs rebiuld' which we tend to do every week.

**Comment by brandonweiss** [comment]
Maybe the docs are just wrong, then? For example, it says the `digital_ocean` module uses v2 of the API and the `api_token` parameter, but that doesn't seem to work. I had to use the old `client_id` and `api_key` from v1. Also it says you can use slugs for `size_id`, `image_id`, and `region_id`, but I had to look up the actual integers and use those.

**Comment by brandonweiss** [comment]
@bcoca Ah, yeah that's what I suspected. Great!

**Comment by frob** [comment]
Why is this closed. The docs and the released version don't match. If someone (such as me) attempts to use the docs for this (like I as just doing for the past half hour) they would not get this to work (just like I didn't). At the very least the docs should be updated to talk about v2's impending release and that the docs are for the new version.

Really the docs being out-of-sync constitutes the docs being broken.

**Comment by pkaeding** [comment]
I agree with @frob, this is broken.  Where do I even look up region ids?  [https://api.digitalocean.com/v2/regions](https://developers.digitalocean.com/documentation/v2/#list-all-regions) does not seem to list them. The DO v1 docs linked at the top of this issue are gone.

**Comment by frob** [comment]
Unfortunately this is also a matter of DO's api just being somewhat poor and obfuscated. I did get this all working. However, somethings (such as region/image ids) are hidden and only accessible through curl commands. A table on a page would give use the info we needed.
