### ISSUE TITLE
unarchive: don't try to work on 0 byte files

### ISSUE THREAD

**Issue by ashemedai** [ansible/ansible-modules-core#1575]
When you call unarchive on an archive that's 0 bytes it will report "Failed to find handler to unarchive. Make sure the required command to extract the file is installed.", which is rather misleading.

A solution forward might be to check for 0 byte size before trying to work on the file.

**Comment by gregdek** [comment]
Makes sense -- could be a straightforward PR if you have the time...

**Comment by ashemedai** [comment]
Yeah, will definitely do that as soon as I find a few free minutes at the office this week.

**Comment by gregdek** [comment]
Thanks! Appreciate your time. :)

**Comment by verm666** [comment]
@bcoca can you review fixed version?
