### ISSUE TITLE
^C with apt leaves it in locked state

### ISSUE THREAD

**Issue by Phyks** [ansible/ansible-modules-core#1601]
Hi,

Doing a ^C while performing tasks with apt kills Ansible and leaves apt on the remote host in an inconsistent state, with the database locked.

Is it normal?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by bcoca** [comment]
in any case, no, the ctrl+c should only kill the local process and the remote one should finish off and be orphaned, but if using ssh pipelining this can be tricky and leave the other process hung/locked. You will have to log onto the machine and kill any ansible processes still lingering.
