### ISSUE TITLE
ansible_all_ipv4_addresses does not contain IP addresses of aliases on OpenBSD

### ISSUE THREAD

**Issue by nusenu** [ansible/ansible-modules-core#1627]
Hi,

I make use of `ansible_all_ipv4_addresses` in my role, but the setup module fails to see IP addresses of aliases. 
`ifconfig <interface>` shows the ip address but
 `ansible_all_ipv4_addresses` does not contain them.

ansible version: 1.9.1

Target host: OpenBSD 5.7

**Comment by bcoca** [comment]
we probably need to fix the fact gathering code to also look at ip aliases

**Comment by bcoca** [comment]
closed via #11482
