### ISSUE TITLE
Where is the keystore for uri:

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible/ansible-modules-core#1647]
In 1.9.2 the parameter validate_certs has a default value of 'yes', that is fine with us if we know where to import our own CA's certificate. I need to run local_action uri: on a Mac.

**Comment by abadger** [comment]
the uri module is currently using the httplib2 module.  that python module stores the certificates in a cacerts.txt file inside of the module by default.  I'm not sure where that is on the Mac but if it were in /usr/local, then the directory would be /usr/local/lib/python2.7/site-packages/httplib2/cacerts.py

Some packaging of httplib2 puts the cert file in a different place (for instance, on my Fedora box, the httplib2 module is patched to use the system's certificate path /etc/pki/tls/certs/ca-bundle.crt ).  There's also a way to set this for httplib2 globally by creating a small python module named ca_certs_locater.  You can look at the httplib2 source code to see what is involved in doing things that way: https://github.com/jcgregorio/httplib2/blob/master/python2/httplib2/__init__.py#L187

This is probably a conversation that is best done on the mailing list.  So if that information isn't enough to get this working for you that's the pace to go for further assistance.  I'll paste the mailing list information below.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
