### ISSUE TITLE
Ansible fails to find required executable pip

### ISSUE THREAD

**Issue by anthonygreen** [ansible/ansible-modules-core#1656]
Running ansible to provision a OSX 10.9.x

First I had to install pip

```
- name: Install pip
  easy_install: name=pip
```

but then 

```
- name: Install Python dependencies
  pip: name=httplib2
```

fails with

```
msg: Failed to find required executable pip
```

even though the install was successful

```
which pip
/usr/local/bin/pip
```

**Comment by bcoca** [comment]
this is why it has an 'executable' option with which you can point it to the correct pip.

closing this as there is no action required

**Comment by cdaringe** [comment]
```
apt: pkg=python-pip state=present
```

if you're on `apt` friendly systems

**Comment by kotofos** [comment]
On 10.11 OS X and ansible issue is still there. I can run pip3 in command line on target host, but ansible pip module can't find it. Even when I specify executable=pip3. So I have to specify full path to pip3.

**Comment by senorsmile** [comment]
On os x, specifying the following (for python2) does the trick
```    executable: /usr/local/bin/pip2```
