### ISSUE TITLE
Unable to set up NFS on EC2 instances launched using Ansible

### ISSUE THREAD

**Issue by lukevalenta** [ansible/ansible-modules-core#1677]
Hi,

I am unable to get NFS configured correctly on EC2 instances launched via the 'ec2' module in Ansible. When I launch instances using the exact same AMI from the AWS EC2 console, NFS works without a hitch.

First I'll describe my setup, and then how to reproduce the problem. I'm running Ansible from a Mac OSX Yosemite version 10.10.3.

```
$ ansible --version
    ansible 1.9.2
```

I was also able to reproduce the problem from a machine running Debian 8.1 with Ansible version 1.9.

This is the ansible playbook I'm using to launch 2 ec2 instances.

```
$ cat test-nfs.yml
    - hosts: localhost
      tasks:
       - ec2:
          key_name: my_key
          aws_region: us-east-1
          zone: us-east-1c
          image: ami-d05e75b8
          vpc_subnet_id: subnet-cba9efbc
          instance_type: t2.micro
          exact_count: 2
          count_tag:
            Name: nfs-test
          instance_tags:
            Name: nfs-test
          assign_public_ip: yes
          wait: yes
```

Launch two instances.

```
<command machine>$ ansible-playbook -i ./ec2.py test-nfs.yml
```

Then, SSH into the first instance and set up NFS.

```
<command machine>$ ssh ubuntu@<nfs-server ip>
<nfs-server>$ sudo mkdir -m 777 /test
<nfs-server>$ sudo apt-get install nfs-kernel-server
<nfs-server>$ sudo cat "/test    *(rw,async,no_subtree_check)" >> /etc/exports
<nfs-server>$ sudo service nfs-kernel-server restart
```

Attempt to mount NFS on the second instance.

```
<nfs-client>$ sudo mkdir -m 777 /test
<nfs-client>$ sudo apt-get install nfs-common
<nfs-client>$ sudo mount <nfs-server ip>:/test /test
```

The last step (mounting /test) hangs and times out if the instances were launched using the ansible ec2 module, but completes almost instantly when the instance are launched from the AWS EC2 console or using the AWS CLI.

```
$ aws ec2 run-instances --image-id ami-d05e75b8 --count 1 --instance-type t2.micro --key-name test --security-group-ids sg-8fd0f7eb --subnet-id subnet-cba9efbc
```

Any help would be greatly appreciated. I can provide additional information about the setup if requested.

**Comment by bcoca** [comment]
you should really direct questions like this to the lists, a lot more people that might have experience with this look at that over bug tickets that are not bugs but questions

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by iainlbc** [comment]
There's nothing special about how ansible is provisioning the instance. I
don't see groups specified, maybe the instances your spinning up from
ansible are being provisioned into a different group which doesnt have
access to the NFS server? Are you using EFS? Can you telnet to the nfs
server on any of the required rpc ports?

## 

Iain Wright

This email message is confidential, intended only for the recipient(s)
named above and may contain information that is privileged, exempt from
disclosure under applicable law. If you are not the intended recipient, do
not disclose or disseminate the message to anyone except the intended
recipient. If you have received this message in error, or are not the named
recipient(s), please immediately notify the sender by return email, and
delete all copies of this message.

**Comment by lukevalenta** [comment]
Hi,

Thanks for the response. You're exactly right -- I was not specifying the correct security group. I had the ansible group and the security group mixed up in my code.

Thanks!
