### ISSUE TITLE
"apt upgrade=dist" incorrectly reports changed=false if number of upgraded packages is a multiple of 10

### ISSUE THREAD

**Issue by cthiemann** [ansible/ansible-modules-core#1678]
That's because the string "0 upgraded" is in "10 upgraded":

 if (apt_cmd == APT_GET_CMD and APT_GET_ZERO in out) or (apt_cmd == APTITUDE_CMD and APTITUDE_ZERO in out):
   m.exit_json(changed=False, msg=out, stdout=out, stderr=err)
   m.exit_json(changed=True, msg=out, stdout=out, stderr=err)

https://github.com/ansible/ansible-modules-core/blob/devel/packaging/os/apt.py#L535

**Comment by bcoca** [comment]
he, the 'in out' is matching starting at the 0, need to check if that is start of line or has a space in front
