### ISSUE TITLE
apt_repository bugs in repos_urls()

### ISSUE THREAD

**Issue by abadger** [ansible/ansible-modules-core#1684]
@verm666 could you take a look at some problems in the repos_urls code?
- @jstasiak noted here: https://github.com/ansible/ansible-modules-core/issues/133#issuecomment-119273206 that the repos_url() property was only implemented for Ubuntu, not for Debian.
- I was looking at how to adapt it and found `source, ppa_owner, ppa_name = self._expand_ppa(i[3])
  `.  I couldn't figure out where `i` was getting set.  Is that a bug?

We'll need to either push the fix to stable-1.9 or revert it from there as well: https://github.com/ansible/ansible-modules-core/pull/1671#issuecomment-119273824

**Comment by verm666** [comment]
@abadger I'll fix it today

**Comment by verm666** [comment]
Fixed. I tested it only on Ubuntu. Can somebody test it on Debian?

**Comment by jstasiak** [comment]
Thank you, I'll test it on Debian.

**Comment by abadger** [comment]
@verm666 thanks!  Question - Since we're not expanding the ppa to a http url in repos_urls do we also need to change the logic on line 442?

**Comment by jstasiak** [comment]
@verm666 Works for me with Debian Wheezy targets.

**Comment by abadger** [comment]
@verm666 I didn't see a Pull Request for the code you posted from your repository.  Is it ready?  Also not sure if my question here: https://github.com/ansible/ansible-modules-core/issues/1684#issuecomment-119583446 had merit or not.

**Comment by verm666** [comment]
https://github.com/ansible/ansible-modules-core/pull/1738

**Comment by amenonsen** [comment]
The latest commit #1738 works for me.

**Comment by amenonsen** [comment]
@abadger's question about changing the startswith("ppa:") logic hasn't been answered as far as I can tell, but right now we know that the unpatched apt_repository is broken (→ unusable) on Debian, while the patch works for @jstasiak and on my Debian machine, and presumably works for @verm666 on Ubuntu. Could it please be merged so that the module at least works for normal sources? If PPAs need an additional fix, it can be applied separately.

**Comment by abadger** [comment]
@amenonsen Took a closer look and it looks like the logic is broken on Ubuntu.  @amenonsen I'll close this ticket and continue to figure this out on the PR

**Comment by dmora** [comment]
any update on this issue, i just got the same: 'SourcesList' object has no attribute 'repos_urls'  Error with the latest devel branch
