### ISSUE TITLE
yum module in ansible 1.9.2 fails when package already installed

### ISSUE THREAD

**Issue by abadger** [ansible/ansible-modules-core#1687]
Moved from: https://github.com/ansible/ansible/issues/11526
Original Reporter: @aabdnn 

Issue Type: Bug Report

Ansible Version:

$ ansible --version
ansible 1.9.2
  configured module search path = None

Ansible Configuration:

ANSIBLE_HOST_KEY_CHECKING=no
ANSIBLE_INVENTORY=/Users/anandb/repos/ripe/ansible/hosts
ANSIBLE_GATHERING=smart
ANSIBLE_REMOTE_TEMP=/tmp
ANSIBLE_SSH_CONTROL_PATH=/Users/anandb/.ssh/mux/%%r@%%h:%%p
ANSIBLE_HASH_BEHAVIOUR=merge
ANSIBLE_TIMEOUT=75
ANSIBLE_RETRY_FILES_ENABLED=no
ANSIBLE_SSH_PIPELINING=yes

Environment:

Managing CentOS 6 from OSX 10.10.4

Summary:

An ansible task to install 3 packages using "yum", that works under Ansible 1.9.1, fails under 1.9.2.

Steps To Reproduce:

On a newly-installed CentOS 6 system (which already has exim installed by kickstart), run the following task:
- yum: name={{ item }}
  with_items:
  - epel-release
  - exim
  - python-virtualenv

NB: "exim" and "python-virtualenv" are only available in the EPEL repository. That's why my task first installed the "epel-release" package, which makes available the epel yum repo files. The next 2 installation steps will be able to find "exim" and "python-virtualenv" in the EPEL repo and install/update/skip them as needed.

Expected Results:

Ansible should first install epel-release, then skip installing exim (which is already installed), and finally install python-virtualenv.

Actual Results:

failed: [ns1.nl-ams.as112.ripe.net] => (item=epel-release,exim,python-virtualenv) => {"changed": false, "failed": true, "item": "epel-release,exim,python-virtualenv", "rc": 0, "results": ["exim-4.72-7.el6.x86_64 providing exim is already installed"]}
msg: No Package matching 'python-virtualenv' found available, installed or updated

**Comment by abadger** [comment]
CC: @kustodian @EdTorbett

This is probably happening because of the speedup to the yum module achieved by installing all packages in a single pass.  Doing that also allows packages which need to be installed or updated together to work so simply reverting it is probably not a good option.

If it was backwards compatible I'd probably just say that we should just document that installing of packages which enable repositories be a separate task but since it was the way the yum module worked before maybe we need some in-built way to enable the old behaviour.  Anyone have any ideas?

**Comment by abadger** [comment]
PR that introduced installing package in a single pass: https://github.com/ansible/ansible-modules-core/pull/1501

**Comment by aabdnn** [comment]
While I appreciate the optimisation to the yum module, it changed the behaviour of the module in a fundamental way. More annoyingly, it was not even mentioned in the change log for 1.9.2 !! The change log is there for a reason, for us users to see if any of the modules we use have changed in any way.

Personally, I could work around this by having "epel-release" installed in a separate task, before trying to install packages from the repo. So this change has caused me an inconvenience, but doesn't stop me from using the yum module. I think anyone else with a use-case like ours could probably adapt too.

But for God's sake, please DOCUMENT IT!

**Comment by kustodian** [comment]
I thought the yum changes will be released with 2.0, not 1.9.2. Anyway there is nothing we should do, except documenting it in the changelog.

**Comment by EdTorbett** [comment]
The thing I'm unsure about is that the code should check which modules are already installed and only pass the uninstalled ones to a single invocation of yum. Has this behaviour changed or perhaps not working correctly?

Ed

—

**Comment by EdTorbett** [comment]
Sorry, having read the original error text I understand what's happening now. Please ignore my previous response.

Yes, this should have gone into the changelog.

Ed

—

**Comment by abadger** [comment]
<nod>  There wasn't supposed to be any change in behaviour due to this.  Unfortunately, enabling repos is a cornercase  that wasn't thought of.  We've talked this through and because it's primarily a bugfix we're going to keep the behaviour at this point.  I've pushed an update to the yum docs mentioning the change and will add a note to the ChangeLog as well.

**Comment by kustodian** [comment]
@abadger May I suggest that optimizations like this are not pushed to the minor (bugfix versions) of Ansible. At least when I update Ansible from 1.9.1 to 1.9.2 I only expect to have a more stable version with the same features of the current major version. Minor version updates should only contain bug/security fixes and nothing more.

**Comment by abadger** [comment]
- Changelog entry: https://github.com/ansible/ansible/commit/5d1fb380fca821ac2602c190240904999f25a063
- yum module documentation: https://github.com/ansible/ansible-modules-core/commit/d46c036b75a82a07c42731154677512d069c4386
- yum doc in stable: https://github.com/ansible/ansible-modules-core/commit/559791e1dfc7591931b699db5e6d47d746d23f5d

The docs on the website will be updated the next time we run the job to regenerate them from the repository.

Thanks for reporting this and sorry for the unannounced change in behaviour!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by abadger** [comment]
@kustodian, yeah, that's what we generally aim for.  Unfortunately, this change did fix a bug ( https://github.com/ansible/ansible-modules-core/issues/38 ) and no one noticed that it also had backwards incompatibility concerns.

**Comment by kustodian** [comment]
You are right, I totally forgot about that it fixed a bug.

**Comment by EdTorbett** [comment]
@abadger @kustodian I had a thought about this task, and it relates to the optimisation involving with_items. I know that with_items was introduced because each item could not previously be an array, but this is now no longer the case.

If the with_items optimisation were to be removed so that with_items still executes yum once for each item, this would allow a single task to be specified as follows:

``` yaml
yum:
  name: '{{ item }}'
  with_items:
  - epel-release
  - [ exim, python-virtualenv ]
```

At which point epel-release would be installed first and both exim and python-virtualenv installed second.
What's your opinion on this possibility?

**Comment by kustodian** [comment]
It's a cool idea, but I'm against it, since it would remove the optimization from regularly calling yum using:

```
with_items:
  - package1
  - package2
  ...
```

In my opinion I really like it how it is currently, you create one task to install epel-release, than the second task to install everything else (which requires epel). That is exactly what you would do if you are not using Ansible and executing commands manually. Ansible tasks are meant to be simple and easy, so that they follow the thought of the sysadmin as if he is executing them manually. This would just add a level of complexity which isn't that important, just so that you would have one tasks less in a play.
