### ISSUE TITLE
Update docker module to support newer versions of the server (mem_limit has been moved to host_config in API version 1.19)

### ISSUE THREAD

**Issue by anthonygreen** [ansible/ansible-modules-core#1707]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2
##### Environment:

Running from: OS X 10.95
Managing: Ubuntu 15.04
##### Summary:

Starting a container results in the error "mem_limit has been moved to host_config in API version 1.19" starting container
##### Steps To Reproduce:

Using Ansible to configure starting a Jenkins container 

```
- name: Jenkins data directory
  command: "docker create -v {{HOME}}/.jenkins:/var/jenkins_home:rw -v {{HOME}}/.ssh:/.ssh:ro -v {{HOME}}/.ssl:/.ssl:ro --name jenkins_data busybox"
  sudo: yes
  when: docker_containers.stdout.find('jenkins_data') == -1


- name: Start Jenkins container
  docker: 
    name: jenkins_master
    image: mediaplayout/jenkins
    volumes_from: jenkins_data
    pull: always
    state: started
    ports: 
      - 8080:8080
      - 50000:50000
  sudo: yes  
```

I'm getting the error

```
BECOME-SUCCESS-nnwoeoumeitqznkijaqrhohdpyhijpbr
Traceback (most recent call last):
  File "/home/mediaplayout/.ansible/tmp/ansible-tmp-1436530356.59-234590896125756/docker", line 3132, in <module>
    main()
  File "/home/mediaplayout/.ansible/tmp/ansible-tmp-1436530356.59-234590896125756/docker", line 1494, in main
    started(manager, containers, count, name)
  File "/home/mediaplayout/.ansible/tmp/ansible-tmp-1436530356.59-234590896125756/docker", line 1354, in started
    created = manager.create_containers(delta)
  File "/home/mediaplayout/.ansible/tmp/ansible-tmp-1436530356.59-234590896125756/docker", line 1227, in create_containers
    containers = do_create(count, params)
  File "/home/mediaplayout/.ansible/tmp/ansible-tmp-1436530356.59-234590896125756/docker", line 1217, in do_create
    result = self.client.create_container(**params)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 237, in create_container
    volume_driver
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 546, in create_container_config
    'mem_limit has been moved to host_config in API version 1.19'
docker.errors.InvalidVersion: mem_limit has been moved to host_config in API version 1.19
```

This task does work:

```
- name: Register running Docker containers
  register: running_docker_containers
  command: docker ps
  sudo: yes

- name: Start Jenkins container
  command: docker run -d -p 8080:8080 -p 50000:50000 --volumes-from jenkins_data --name jenkins_master mediaplayout/jenkins
  sudo: yes
  when: running_docker_containers.stdout.find('jenkins_master') == -1
```

**Comment by rcousens** [comment]
Just a little FYI: this error comes from a commit merged into docker-py on the 1st of July:

https://github.com/docker/docker-py/pull/644

mem_swap_limit/mem_limit needs to be passed as None to create_container_config, or not passed at all, as the limit setting has been moved to the create_host_config function call.

See https://github.com/docker/docker-py/pull/644/files#diff-193b0cbc51c3ae87519912dd6aeadec4R531

I got around it by pinning my version of docker-py to 1.2.3.

**Comment by bcoca** [comment]
probably the best solution is to pass it only on certain docker versions

**Comment by veggiemonk** [comment]
OK. It took me a while to figure out that it was on the _server_ that the version needed to be pinned. 
It works now!
Thanks a lot,

Cheers

**Comment by sodiumjoe** [comment]
i'm still running into this on ansible `1.9.2`

**Comment by bcoca** [comment]
@joebadmo and you'll continue to see in on 1.9.2, this patch was made well after it's release so it is currently only in the devel branch. It might get included in a possible 1.9.3 or more probably in a 2.0

**Comment by sodiumjoe** [comment]
@bcoca ah ok, thanks for the update!

**Comment by ghost** [comment]
@rcousens I had to downgrade to 1.2.2 (as opposed to 1.2.3 in your post).
 Thanks for the tip
**Environment**
Ansible 2.0
Python 2.7.9
Running from Debian 8
Managing Debian 7

**Comment by leedm777** [comment]
@joebadmo As a workaround, you can specify `docker_api_version: 1.18` in your docker task to specify the older API.

**Comment by alph486** [comment]
@AymericLabs docker-py 1.2.3 worked for me with ansible 1.9.2

**Comment by nicolaspanel** [comment]
@leedm777 : worked for me, tx :+1:

**Comment by nabheet** [comment]
:+1:  on the **`docker_api_version: 1.18`** suggestion ...

**Comment by r4j4h** [comment]
Thank you so much for the docker-py 1.2.3 suggestion. Worked a treat on ansible 1.9.3 :)
