### ISSUE TITLE
modules shell: echo error

### ISSUE THREAD

**Issue by adaiguoguo** [ansible/ansible-modules-core#1714]
ERROR: Syntax Error while loading YAML script, /root/ansible-power/roles/adduser/tasks/main.yml
Note: The error may actually appear before this position: line 11, column 43
- name: add sudoers
  shell: echo '{{user}} ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
                                          ^
  We could be wrong, but this one looks like it might be an issue with
  missing quotes.  Always quote template expression brackets when they
  start a value. For instance:
  
  with_items:
  - {{ foo }}

Should be written as:

```
with_items:
  - "{{ foo }}"
```

**Comment by bcoca** [comment]
write:

```
shell: "echo '{{user}} ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
```

YAML requires you quoting strings containing a : followed by a space
http://docs.ansible.com/YAMLSyntax.html#gotchas

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by adaiguoguo** [comment]
@bcoca Thank you
