### ISSUE TITLE
Report exception in error message in mysql modules c

### ISSUE THREAD

**Issue by alexgarel** [ansible/ansible-modules-core#173]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Ubuntu 14.04.1 LTS
##### Summary:

In mysql modules when connect fail, an error message is provided. It works most of the time but can be misleading in some case.
While retaining the actual error message, the actual exception message should also be provided.

This hurts me, see #165

See [mysql_variables](https://github.com/ansible/ansible-modules-core/blob/devel/database/mysql_variables.py#L230), [mysql_user](https://github.com/ansible/ansible-modules-core/blob/devel/database/mysql_user.py#L457), [mysql_db](https://github.com/ansible/ansible-modules-core/blob/devel/database/mysql_db.py#L320)
##### Steps To Reproduce:

On a started mysql server, move /var/mysql to another part. Forget to restart.

Run a recipe using mysql_user to change root password.
##### Expected Results:

Module shall tell you it can't connect because there is no mysql database.
##### Actual Results:

Module fail telling to verify your credentials.
If you log on the server you can connect with provided credentials hence the problem.

**Comment by alexgarel** [comment]
Sorry my fingers ripped on the keyboard, I have updated the description.

**Comment by mpdehaan** [comment]
Can you please share the actual error in the case of the failure scenario?

Thanks!

**Comment by alexgarel** [comment]
The error desplayed by ansibled was : 
`unable to connect, check login_user and login_password are correct, or alternatively check ~/.my.cnf contains credentials`

When the Exception message (that I printed myself) was something like "No such database : mysql".

**Comment by mpdehaan** [comment]
Ok, so likely we just need to add "that the database exists, ..."

but yes, show the actual message too, definitely.

**Comment by joshunger** [comment]
Is there a workaround to see the actual message?

**Comment by alexgarel** [comment]
@joshunger nop, just using pdb inside ansible code…

**Comment by Jmainguy** [comment]
I can add the actual message and submit a PR if you guys want it. @alexgarel @joshunger opinions? You want it to default print the actual error in addition to the long message going forward? I think it makes sense to.

**Comment by joshunger** [comment]
@Jmainguy I figured out my issue - mysql_db doesn't support ssl connections - but it would be great to get into the product.

**Comment by alexgarel** [comment]
@Jmainguy +1, I think providing the original error is always a plus.

**Comment by Jmainguy** [comment]
@alexgarel Don't shoot me for taking so long =). Looks like all three modules should meet your exception expectations with the latest merge above. Ok with closing this out? @joshunger ^^

**Comment by alexgarel** [comment]
Great ! No problem time is with us ;-)
