### ISSUE TITLE
Add support for --log-opt options for docker run command to docker module

### ISSUE THREAD

**Issue by icereval** [ansible/ansible-modules-core#1731]
No chance to look at writing a patch yet but thought I'd just point out the up and coming `--log-opt` parameter in Docker 1.8.

https://github.com/docker/docker/commit/dca9e02b15a3757272c90ec4cf0cc2b052a25fe3

**Comment by justnom** [comment]
I just found a need for this today - I have created a PR here #1745. Hope you find this useful.

**Comment by abadger** [comment]
We can track progress on this in the Pull Request so closing the issue. Look to https://github.com/ansible/ansible-modules-core/pull/1745 for the continuing work.
