### ISSUE TITLE
service module does not provide systemd existence as a fact?

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible-modules-core#1749]
The service module contains all the code necessary to identify the init system as being systemd or not, but doesn't seem to provide anyway of exposing that information as a fact?

How can I write a playbook which detects the init system and deploys either the service file or init.d script as necessary without writing and deploying a redundant fact-module to detect this?

**Comment by Smana** [comment]
+1

**Comment by bcoca** [comment]
fixed via http://github.com/ansible/ansible/commit/99d775a0c12ff16c53aa2a19860d9293a2ef5b3c, now gathering facts sets ansible_service_mgr
