### ISSUE TITLE
docker and docker_image should respect $DOCKER_HOST environment variable

### ISSUE THREAD

**Issue by zeus** [ansible/ansible-modules-core#176]
In cases like remote docker (e.g. in virtual machine like boot2docker for osx) with variable respected by docker itself it's expected behavior that docker modules will use it 'by default' instead of socket.

**Comment by mpdehaan** [comment]
Sorry our usual bot seems to be down, can you fill out the details in https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md ?

Thanks!

**Comment by abadger** [comment]
I'm going to close this in favor of @lorin 's pull request.  I think all the information contained in this ticket is also present there.
