### ISSUE TITLE
ansible-playbook fails with: DEFAULT_DOCKER_API_VERSION not defined

### ISSUE THREAD

**Issue by kenden** [ansible/ansible-modules-core#1792]
This issue was created from: https://github.com/ansible/ansible-modules-core/issues/1227
This is just a place so users can find it more easily.
### Issue:

ansible-playbook fails with the message:
NameError: global name 'DEFAULT_DOCKER_API_VERSION' is not defined
### Environment:

MacOSX: Darwin apollo 14.4.0 Darwin Kernel Version 14.4.0
ansible 1.9.2
docker-py (1.3.1)
Python 2.7.10
### Repro steps:

Have the playbook issue.yml with:

```

---
- hosts: all
  sudo: yes
  tasks:
  - name: start nginx container
    docker: name=nginx image=nginx state=started
```
### Results:

``````
$ ansible-playbook -i "localhost," -c local issue.yml --ask-become-pass
SUDO password:

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [start nginx container] *************************************************
failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-djuxzfwqwommrwzferghamqihsrlkgvv
Traceback (most recent call last):
  File "/Users/user/.ansible/tmp/ansible-tmp-1437743661.82-118468405235195/docker", line 3132, in <module>
    main()
  File "/Users/user/.ansible/tmp/ansible-tmp-1437743661.82-118468405235195/docker", line 1436, in main
    docker_api_version = dict(required=False, default=DEFAULT_DOCKER_API_VERSION, type='str'),
NameError: global name 'DEFAULT_DOCKER_API_VERSION' is not defined


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/user/play4.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1```
``````
### Workaround

(works to deploy on a remote Ubuntu 14.10 machine, not on localhost.
Add this to the playbook:

```
  - name: Install docker-py as a workaround for Ansible issue
    pip: name=docker-py version=1.2.3
```

**Comment by bcoca** [comment]
so you always need docker.py, which should have been the message you got, but if it is not present the code does not define DEFAULT_DOCKER_API_VERSION which is the error you got.

**Comment by bcoca** [comment]
fixed via dbdbcb33ccdbc14a6eb805181e7a1403399badc0

**Comment by andrevtg** [comment]
Workaround still failing when using docker-engine-cs (instead of the common docker distribution).

:(

**Comment by osman-masood** [comment]
@bcoca I'm getting this issue running a local script with Ansible on OS X. My versions are:
ansible 1.9.3
docker-py 1.2.3
python 2.7.9

My command:

```
ansible-playbook --connection=local ansible-run-local.yml
```

The output:

```
PLAY [Run service on localhost] *********************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Start flask service docker container] ********************************** 
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/oamasood/.ansible/tmp/ansible-tmp-1444425764.2-239039664213318/docker", line 3185, in <module>
    main()
  File "/Users/oamasood/.ansible/tmp/ansible-tmp-1444425764.2-239039664213318/docker", line 1482, in main
    docker_api_version = dict(required=False, default=DEFAULT_DOCKER_API_VERSION, type='str'),
NameError: global name 'DEFAULT_DOCKER_API_VERSION' is not defined


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/oamasood/ansible-run-local.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1   

```

And here's my `ansible-run-local.yml` file:

```
- name: Run service on localhost
  hosts: localhost
  vars:
    image: my-org/my-service
  sudo: no
  tasks:
    - name: Start docker container
      docker:
        image: "{{image}}"
        state: reloaded
        ports:
          - "80:80"
          - "443:443"
```

(I've also tried installing docker-py from the Ansible playbook itself, but no luck.)

Any help would be appreciated!

**Comment by soichih** [comment]
The workaround didn't fix either for CentOS 7 host. More and more of my services are containerized, so this problem is road blocking us big time.. Please help!

**Comment by andrevtg** [comment]
@soichih, as far as I remember both RHEL and CentOS have a "docker-python" available as a yum package (you have to "yum install docker-python"). You gotta be careful to install a specific version that matches the docker version you are using - but this is kinda automatic if both are installed from RHEL/CenTOS distributions.

If you are _not_ installing Docker from the RHEL/CentOS repos I advise you _not_ to install "docker-python" this way, but to install it using pip (as in "pip install docker-py"). Again, pick a "docker-py" version compatible with your docker version (must match API). This is kinda hard, because you have to do it by trial-and-error. For example, to use it with docker 1.6.x I had to install it with "pip install docker-py==1.2.3". With docker 1.7.x I believe you should "pip install docker-py==1.3.1". I cannot test it right now, unfortunately.

Good luck.

**Comment by soichih** [comment]
@andrevtg Thank you for the reply!

I've replaced the pip docker-py with yum docker-python, and now I am seeing a different error message.

```
NOTIFIED: [sensu-server | restart sensu-odi1 container] ***********************
failed: [core1.sca] => {"failed": true, "parsed": false}

BECOME-SUCCESS-hifgvuoemjojeslenucrerpbyjxdrhab
Traceback (most recent call last):
  File "/home/hayashis/.ansible/tmp/ansible-tmp-1444837449.24-128152879368937/docker", line 3132, in <module>
    main()
  File "/home/hayashis/.ansible/tmp/ansible-tmp-1444837449.24-128152879368937/docker", line 1464, in main
    check_dependencies(module)
  File "/home/hayashis/.ansible/tmp/ansible-tmp-1444837449.24-128152879368937/docker", line 482, in check_dependencies
    versioninfo = get_docker_py_versioninfo()
  File "/home/hayashis/.ansible/tmp/ansible-tmp-1444837449.24-128152879368937/docker", line 458, in get_docker_py_versioninfo
    version.append(int(digit))
ValueError: invalid literal for int() with base 10: '0-de'
Shared connection to core1.sca closed.
```

I am guessing this is from the ansible/docker module, but I might be doing something wrong, but following is my ansible handler.

```
- name: restart sensu-odi1 container
  docker: image=sensu-odi1 state=restarted
```

**Comment by andrevtg** [comment]
Oh my, got it working at home.

So here is the deal: even though what I said should be true (install CentOS repo's "ansible", "docker" and "docker-python" packages and all is good), there seems to be a bug on ansible that should be fixed on 1.9.3 (from what I understood). Well, 1.9.3 isn't available on the repos yet, so I'll tell you the plan B.

I assume you have installed these versions (as of current repo in this date):
- ansible 1.9.2
- docker 1.7.1
- docker-python 1.4.0

This led to the same error you described on my desktop. To fix this you have to remove "docker-python" (sorry for that) and install a specific docker-py with pip:

sudo yum remove docker-python
sudo yum install python-pip
sudo pip install docker-py==1.2.3

This setup works on my own CentOS 7.1.

Hope it helps!

**Comment by andrevtg** [comment]
Some more help:

As mentioned in "https://blog.confirm.ch/docker-ansible-on-rhel-centos-7/", you can have all that on your playbook:

```
---
- hosts: local
  sudo: yes
  tasks:
    - name: make sure docker-python RPM is not installed
      yum:
        name: docker-python
        state: absent

    - name: make sure pip is installed
      yum:
        name: python-pip
        state: present

    - name: make sure required PyPi packages are installed
      pip: name={{ item }} state=present
      with_items:
        - docker-py==1.2.3
        - six>=1.4.0

    - name: run hello-world docker container
      docker:
        name: hello-world
        image: hello-world
        state: present
```

**Comment by soichih** [comment]
@andrevtg

Thanks for your help!

> I assume you have installed these versions (as of current repo in this date):
> Yes, those are the exact versions of stuff that's installed on my target host.

I've updated my rules to following

```
- name: uninstall docker-python
  yum: name=docker-python state=absent
- name: Install docker-py as a workaround for Ansible issue
  pip: name=docker-py version=1.2.3

- name: put conf.d to sensu_odi
  copy: src=conf.d dest=/root/docker/monitor/sensu_odi/conf
  notify: restart sensu-odi1 container
```

The restart handler does following

```
- name: restart sensu-odi1 container
  docker: image=sensu-odi1 state=restarted

```

When I ran, I've ran into the very first problem reported by @kenden 

```
NOTIFIED: [sensu-server | restart sensu-odi1 container] ***********************
failed: [core1.sca] => {"failed": true, "parsed": false}

BECOME-SUCCESS-smxackmplppisbwylhwkjnmeonwwuezg
Traceback (most recent call last):
  File "/home/hayashis/.ansible/tmp/ansible-tmp-1446234686.65-133396418059734/docker", line 3132, in <module>
    main()
  File "/home/hayashis/.ansible/tmp/ansible-tmp-1446234686.65-133396418059734/docker", line 1436, in main
    docker_api_version = dict(required=False, default=DEFAULT_DOCKER_API_VERSION, type='str'),
NameError: global name 'DEFAULT_DOCKER_API_VERSION' is not defined
Shared connection to core1.sca closed.


FATAL: all hosts have already failed -- aborting
```

I think I will just wait for ansible 1.9.3. Do you know when it will be released?

**Comment by sjoerdmulder** [comment]
This doesn't seem to be fixed in ansible 1.9.4

Using the  `ubuntu/trusty64` vagrant box with docker-engine 1.9.0

When using Vagrant to test my ansible scripts i also get this:

```
==> default: failed: [default] => {"failed": true, "parsed": false}
==> default: Traceback (most recent call last):
==> default:   File "/root/.ansible/tmp/ansible-tmp-1447160447.83-17124376887001/docker", line 3185, in <module>
==> default:     main()
==> default:   File "/root/.ansible/tmp/ansible-tmp-1447160447.83-17124376887001/docker", line 1482, in main
==> default:     docker_api_version = dict(required=False, default=DEFAULT_DOCKER_API_VERSION, type='str'),
==> default: NameError: global name 'DEFAULT_DOCKER_API_VERSION' is not defined
```

**Comment by ghost** [comment]
Running into the same issue as @sjoerdmulder  ... I'm using `centos7` vagrant image for my tests.

**Comment by moshe0076** [comment]
Had the same problem with ubuntu 14.04 and ansible 1.9.4, pip install docker-py had solved it.

**Comment by tbonza** [comment]
had an issue similar to @andrevtg. Installing docker-py on my local machine fixed it (fedora 23).

**Comment by desperados1999** [comment]
Hi, I am a bit confused... from the comments it appears that docker-py needs to be installed on the managed node. Isn't this against the Ansible promise that no software (other than python) is needed on the managed host? Aren't all modules code supposed to reside on the control node and be copied to a tmp folder on the managed node for execution?

**Comment by Theaxiom** [comment]
I am still having this issue, even following the workarounds in this thread. Ansible 1.9.4 (checked out from repo)

**Comment by tbonza** [comment]
@desperados1999 when I used Ansible with Docker, I had to install docker-py on my local machine instead of my virtual machine. Then it started working.

**Comment by depend** [comment]
having the issue on 1.9.4. The workaround in https://blog.confirm.ch/docker-ansible-on-rhel-centos-7/ worked

**Comment by andrevtg** [comment]
Dear All:

Just tested again the whole thing on a plain new CentOS 7.2 running docker 1.8.2 (from CentOS distro) and the most recent Ansible (1.9.4) from EPEL. Just to make sure I installed everything from a bare CentOS 7.2 install on both target and control nodes. So, for the target node:

```
yum install docker
systemctl enable docker
systemctl start docker
```

And on the control node:

```
yum install epel-release
yum install ansible
```

The same "DEFAULT_DOCKER_API_VERSION" error ocurred (as expected) when running "docker" tasks against the target node, but there is a new package on CentOS that fixes it (and replaces "docker-python"):

```
yum install python-docker-py
```

With this installed on the target node the "docker" ansible tasks will work nicely.

Please understand that if you install a top-notch docker version (like 1.9 version from Docker itself) it will probably break this again. Red Hat and CentOS always lag behind, so it is possible that the "python-docker-py" will not work. In that case you will have to remove it and install a specific (or latest) version of the "docker-py" pip package (as pointed on the article linked above)..

**Comment by andrevtg** [comment]
@desperados1999 this is kinda "half truth". You see, all the "docker" tasks assume that docker itself has been previously installed on the target node, for example.

A "state-of-the-art" playbook would have to check and take care of everything (maybe even the Docker installation). So installing "python-docker-py" is not a big deal.
