### ISSUE TITLE
The synchronize mode parameter is in docs, but not in code anymore

### ISSUE THREAD

**Issue by limist** [ansible/ansible-modules-core#1805]
With Ansible 2, using the `mode` parameter with `synchronize` gives an error: "unsupported parameter for module: mode"  But the parameter is still listed here: http://docs.ansible.com/ansible/synchronize_module.html

**Comment by bcoca** [comment]
cc @jimi-c

**Comment by abadger** [comment]
@limist I think I fixed this about the time you reported it.  If you checkout the latest from the devel branch you shouldn't get that error anymore (but you probably will run into: https://github.com/ansible/ansible/issues/11649 -- about to push a PR that might address that).

**Comment by abadger** [comment]
Here's the commit that should have fixed mode: https://github.com/ansible/ansible/commit/b06353791c70ce714cc6d7e3b18cb27174b4ee2b

**Comment by gregdek** [comment]
Fixed in devel.
