### ISSUE TITLE
mount: Support for Check Mode

### ISSUE THREAD

**Issue by fti7** [ansible/ansible-modules-core#181]
##### Issue Type:

Feature Idea
##### Ansible Version:

Dev
##### Environment:

N/A
##### Summary:

Remote module does not support check mode
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by mpdehaan** [comment]
Sounds good, something you might like to work on perhaps?

**Comment by alxgu** [comment]
Can be closed - see https://github.com/ansible/ansible-modules-core/commit/6a872469fc1bda54126dfa91338cf7a26bde701c

**Comment by bcoca** [comment]
closing as per above
