### ISSUE TITLE
Support collectstatic --clear in django_manage.py

### ISSUE THREAD

**Issue by adamhadani** [ansible/ansible-modules-core#1811]
django's collectstatic supports a very useful --clear flag that should be supported in the django_manage module.
See more documentation here: https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#django-admin-option---clear

I've created a PR for this Issue as well ( #1810 )

**Comment by bcoca** [comment]
closing this and keeping track in the PR
