### ISSUE TITLE
vsphere_guest.py: creating VMs from templates

### ISSUE THREAD

**Issue by Boran** [ansible/ansible-modules-core#182]
In Vsphere GUI I'm used to creating (delpoying) Vms from "Templates" (which are pre-configure base VMs) and "customisation specifications" (for dns/gateway etc.). Is there any chance of such features being added to the asible module?

**Comment by mpdehaan** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

(also note - additionally, the answer to this question is "yes", this is a popular request that is likely coming in the future)

**Comment by tapanswain-zz** [comment]
when  state is reconfigured , editing cpu and memory is works. for adding new harddrive is not working . 

state: reconfigured
    vm_extra_config:
      vcpu.hotadd: yes
      mem.hotadd:  yes
      notes: This is a test VM
    vm_disk:
      disk1:
        size_gb: 10
        type: thin
        datastore: storage001
