### ISSUE TITLE
[boto] add support for RDS db_engine: Aurora - compatible with MySQL 5.6.10a

### ISSUE THREAD

**Issue by gadelkareem** [ansible/ansible-modules-core#1825]
Is there any support yet for the new db_engine 'Aurora - compatible with MySQL 5.6.10a' ?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
