### ISSUE TITLE
Setup module: Wrong distribution for OpenSuse and ArchLinux, wrong os family for ArchLinux

### ISSUE THREAD

**Issue by dimrozakis** [ansible/ansible-modules-core#185]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.7.2
```
##### Environment:
- Local host: LinuxMint 17 (doubt it makes a difference)
- Remote hosts:
  - Arch Linux
    - provider: Linode
    - image name: Arch Linux 2014.10
    - image id: 132
  - OpenSuse
    - provider: Linode
    - image name: openSUSE 13.1
    - image id: 120
##### Summary:

Setup module doesn't properly discover distribution for both images and os family for arch.
- ArchLinux
  - ansible_distribution: NA
  - ansible_os_family: NA
- OpenSuse
  - ansible_distribution: Suse
  - ansible_os_family: Suse

This relates to issue #34 but I'm also getting 'NA' for arch distribution, and I get wrong distribution for OpenSuse.
##### Steps To Reproduce:

Set up an inventory file with OpenSuse and ArchLinux machines, then run:

```
$ ansible all -m setup -a 'filter=ansible_distribution'
$ ansible all -m setup -a 'filter=ansible_os_family'
```
##### Expected Results:

```
$ ansible all -m setup -a 'filter=ansible_distribution'
arch | success >> {
    "ansible_facts": {
        "ansible_distribution": "Archlinux"    # or ArchLinux or Arch
    }, 
    "changed": false
}

opensuse | success >> {
    "ansible_facts": {
        "ansible_distribution": "OpenSuse"
    }, 
    "changed": false
}


$ ansible all -m setup -a 'filter=ansible_os_family'
arch | success >> {
    "ansible_facts": {
        "ansible_os_family": "Archlinux"    # or ArchLinux or Arch
    }, 
    "changed": false
}

opensuse | success >> {
    "ansible_facts": {
        "ansible_os_family": "Suse"
    }, 
    "changed": false
}
```
##### Actual Results:

```
$ ansible all -m setup -a 'filter=ansible_distribution'
arch | success >> {
    "ansible_facts": {
        "ansible_distribution": "NA"
    }, 
    "changed": false
}

opensuse | success >> {
    "ansible_facts": {
        "ansible_distribution": "Suse"
    }, 
    "changed": false
}


$ ansible all -m setup -a 'filter=ansible_os_family'
arch | success >> {
    "ansible_facts": {
        "ansible_os_family": "NA"
    }, 
    "changed": false
}

opensuse | success >> {
    "ansible_facts": {
        "ansible_os_family": "Suse"
    }, 
    "changed": false
}
```

**Comment by Jmainguy** [comment]
I can confirm this is an issue, tested on arch 2014.10.01 and opensuse 13.1, using ansible devel 1.8

**Comment by Jmainguy** [comment]
Took me alot longer then it should have. Created a PR to fix this for openSuSE specifically. 

@mantiz created https://github.com/ansible/ansible/pull/9375 which fixes ArchLinux

**Comment by bcoca** [comment]
merged both PRs so this should be sovled now
