### ISSUE TITLE
Module rpm_key doesn't look for rpm gpg key file in roles/x/files/

### ISSUE THREAD

**Issue by marbu** [ansible/ansible-modules-core#1853]
##### Ansible Version:

Ansible 1.9.2
##### Ansible Configuration and Environment

Fedora 22, default configuration from `ansible-1.9.2-1.fc22.noarch` package used
##### Summary:

Module `rpm_key` doesn't look for rpm gpg key file in `roles/x/files/`
when the module is used in a role.
##### Steps To Reproduce:

Create new ansible role with single task in `tasks/main.yml` file:

```

---

- name: Import rpm-gpg keys of additional yum repos                             
  rpm_key: state=present key={{ item }}                                         
  with_items:                                                                   
   - RPM-GPG-KEY-rpmfusion-free-fedora-22-primary                               
   - RPM-GPG-KEY-rpmfusion-nonfree-fedora-22-primary
```

And copy both gpg keys into `files/` directory of the new role.

Then use the role in a playbook.
##### Expected Results:

The task works wihtout any problems:

```
TASK: [fedora-common | Import rpm-gpg keys of additional yum repos] *********** 
ok: [127.0.0.1] => (item=RPM-GPG-KEY-rpmfusion-free-fedora-22-primary)
ok: [127.0.0.1] => (item=RPM-GPG-KEY-rpmfusion-nonfree-fedora-22-primary)
```
##### Actual Results:

The task fails because it can't find the files with gpg keys:

```
TASK: [fedora-common | Import rpm-gpg keys of additional yum repos] *********** 
failed: [127.0.0.1] => (item=RPM-GPG-KEY-rpmfusion-free-fedora-22-primary) => {"failed": true, "item": "RPM-GPG-KEY-rpmfusion-free-fedora-22-primary"}
msg: Not a valid key RPM-GPG-KEY-rpmfusion-free-fedora-22-primary
failed: [127.0.0.1] => (item=RPM-GPG-KEY-rpmfusion-nonfree-fedora-22-primary) => {"failed": true, "item": "RPM-GPG-KEY-rpmfusion-nonfree-fedora-22-primary"}
msg: Not a valid key RPM-GPG-KEY-rpmfusion-nonfree-fedora-22-primary

FATAL: all hosts have already failed -- aborting
```

Moreover see that the error message looks as if the file was declared invalid
after some examination, which obviously didn't happen. It would be better to 
state that the file was not found.

**Comment by chrrrles** [comment]
There is no immediate need to implement logic to guess the supposed type (URL, file path, or key_id) for an invalid `key` string...  and it would be tricky to do so.

**Comment by marbu** [comment]
Oops, while I complain about the misleading error message in the last paragraph of the report, that's not where the problem actually is, but rather additional observation of related less serious issue.

Here I have [a simple reproducer](https://github.com/marbu/ansible-modules-core-issue-1853-reproducer).

When you try to run it on a fedora machine, it fails as described in this bug report. But it's not because the keys are invalid, but because module `rpm_key` doesn't look for rpm gpg key file in `roles/x/files/` directory. 

You can also see that when you check my current [workaround of this bug](https://github.com/marbu/ansible-modules-core-issue-1853-reproducer/commit/41727b465533717015d8d55904c5a102fe248bc4).
