### ISSUE TITLE
query the ec2_asg module so we create new ASG's with the same size as the existing ones.

### ISSUE THREAD

**Issue by danbf** [ansible/ansible-modules-core#1859]
Even though get_properties os an ASG are available within the ec2_asg module, it's not exposed externally.  So it's not possible to first query an existing ASG, and modify it with a new LC with the same size and other parameters as the existing one.  

Can the results of get_properties be exposed as a set of useable facts to that can be used outside the ec2_asg module?

**Comment by danbf** [comment]
Or something which makes it unneeded to expose the variable, can you add a flag to "create with the same parameters"?  I.e. same min/max/desired as is currently in place without having to query those externally to the playbook.

**Comment by jjshoe** [comment]
https://github.com/ansible/ansible-modules-core/issues/542

**Comment by bcoca** [comment]
closing via #542
