### ISSUE TITLE
Custom Windows facts

### ISSUE THREAD

**Issue by davidobrien1985** [ansible/ansible-modules-core#1865]
Hi everybody,

I would like to create custom facts on Windows machines.
The current implementation of setup.ps1 is a good start but lacks the capability to capture custom facts.

The setup module's parameter fact_path doesn't work on Windows yet. (http://docs.ansible.com/ansible/setup_module.html)

I was thinking about editing the setup.ps1 to parse a default location where admins can drop custom scripts (*.ps1) and the setup.ps1 would execute each script and add each script's output to the output JSON.
I'd like to propose C:\Windows\Ansible\facts as this default location.

Also, I'd like this to be customisable via fact_path.

Is the Ansible team already working on this? If not, please discuss my proposal. I'm happy to do the work and later on do a PR.

Cheers
David

**Comment by nitzmahone** [comment]
Merged for 2.1, closing...
