### ISSUE TITLE
GCE module create instance scopes are hardcoded and are out of date

### ISSUE THREAD

**Issue by ifigotin** [ansible/ansible-modules-core#1888]
The scopes are checked against a predefined set (I believe the map is defined in apache-cloud library). Right now, there are quite a few new scopes, but since a check is made against a predefined map, these new scopes are rejected.

Ideally, scopes should not be checked against a pre-defined map.

**Comment by bcoca** [comment]
cc @erjohnso

**Comment by ryansb** [comment]
(closed #2295) cc/ @supertom

**Comment by supertom** [comment]
Unfortunately, there is no way currently to keep this list updated other than libcloud.  (For perspective, even the Google SDK itself uses a hard-coded map).  As noted, it comes from libcloud, and Ansible uses the map provided by libcloud to check for valid scopes.

I recommend we close this issue.

/cc @ryansb

**Comment by ryansb** [comment]
Yep, libcloud is responsible for handling this scope list, and we don't keep a copy. Closing this issue.
