### ISSUE TITLE
win_file documentation wrong

### ISSUE THREAD

**Issue by davidobrien1985** [ansible/ansible-modules-core#1893]
Hi,

win_file documentation (http://docs.ansible.com/ansible/win_file_module.html) says that it's new in 1.8.
However, on our Ansible server (installed through package management), we installed 1.9.0 and can't find the win_file module.

However, if I install from source, then all is fine.

Could you please update the documentation or explain where I am going wrong?

Thanks.

**Comment by bcoca** [comment]
it was added right before 1.8 but removed before release, it got readded in 1.9.2 but the doc was not updated.

**Comment by davidobrien1985** [comment]
Thanks, can you also update it here?
http://docs.ansible.com/ansible/win_file_module.html

**Comment by bcoca** [comment]
i did, its not immediate
