### ISSUE TITLE
should systemctl do daemon-reload automatically?

### ISSUE THREAD

**Issue by oaken-source** [ansible/ansible-modules-core#191]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7.2, but tested against the github version
##### Environment:

host OS: Gentoo Linux
managed OS: Arch Linux
##### Summary:

On /etc/init.d scripts, the start/stop/enable routines always use the service files on disk, which makes it easy to schedule service restart on redeployment of changed service files.
I feel that systemd should behave similarily from within the service module, that is, when I have a rule like

```
service: name=foo state=started
```

I would want service to go ahead and tell systemd to load the latest service files from disk if necessary. At the moment, I would have to invoke `systemctl daemon-reload` manually, or reboot, which does not feel right.
##### Steps To Reproduce:

update a .service file via a copy rule, then call:

```
service: name=foo state=started
```
##### Expected Results:

the service should start using the new .service file
##### Actual Results:

the service files are not reloaded and the old version is used instead

**Comment by oaken-source** [comment]
thanks, updated.

**Comment by breun** [comment]
I've ran into this as well with directories with versions in their names in systemd service scripts (generated from an Ansible template of course). As a workaround I've had Ansible create a symlink called `current` pointing to the directory with the version number and referring to the `current` symlink from the systemd service script, but if the service module would call `systemctl daemon-reload` then that workaround wouldn't be necessary anymore.

**Comment by bcoca** [comment]
if you are changing the service file why not call service with 'restarted'?

**Comment by breun** [comment]
Before our symlink workaround our Ansible playbook used the service module to stop the service, upgraded the application, updated the systemd service script (using the template module) and started the service again (again using the service module). This did not work, because the old systemd service script was still used by systemd and `systemctl daemon-reload` was not called, so systemd tried to start the application using the start command from the previous service script.

Instead of using the symlink workaround (which causes the start and stop command paths to not change, thus not requiring a `systemctl daemon-reload`) we could also of course use the command module to just always call `systemctl daemon-reload` after the template task which puts in the systemd service script, but not needing to do that is exactly what this issue is about.

**Comment by batmat** [comment]
+1. We use the service module to restart Docker after we've updated its config (to add things like or internal registry, http proxy conf, etc.) and currently _status=restarted_ will just be insufficient.

IMO, as I read above and agree, this does not feel right. Ansible should just hide that complexity and do the right thing: restart the service (and implicitly: make it usable with its new config, I cannot imagine any other reason I would want to have a service restarted...)

Thanks a lot

**Comment by grahamrhay** [comment]
We've recently started moving to Debian 8, and therefore systemd; and simply restarting the service is no longer sufficient, if the unit file has changed. Some way of forcing daemon-reload, implicitly or explicitly, would be useful.

**Comment by holms** [comment]
:+1: Voting for this!  Centos7 requires daemon-reload

**Comment by bcoca** [comment]
So to clear up for non systemd folks (as I myself was confused by this), this is not analogous to the reload/reloaded state for most deamons, this has systemd stop the deamon using and old configuration and start it using the new one after the configuration has been updated. 

Otherwise you would need to manually stop with current config, change config, start again with new config, which might be tricky with some of the configs that are triggered by other services/messages/time/etc and you run into all types of race conditions.

**Comment by Faheetah** [comment]
+1 here, or at least give a way for service to force a daemon-reload similar to how the apt module can force a cache update. This could be through an extra arg daemon_reload=true (default: false, required: no) to have the module push a systemctl daemon-reload before running the service command.

**Comment by pieterlexis** [comment]
:+1:

**Comment by razvanphp** [comment]
+1 for this, run into it today with Jessie.

I don't even know how to do it elegantly, since from my task I call notify, and I don't want every time to use daemon-reload. Maybe 2 handlers?

**Comment by holms** [comment]
If anybody could point me about @pieterlexis pull request state: if it's valid or invalid, should be rewritten, or what's the delay. I'd PR something in here then... @bcoca maybe you could do a code review please for pull-request above?

**Comment by IonicSecurity-JC** [comment]
+1 for this.
modifying a service file will merit the reload

**Comment by caylorme** [comment]
+1 for this

**Comment by tcwalther** [comment]
Another +1, also on jessie.

**Comment by sapun** [comment]
+1

**Comment by schms** [comment]
+1,

**Comment by AlexanderPavlenko** [comment]
+1

**Comment by efine** [comment]
+1

**Comment by domibarton** [comment]
+1

**Comment by pstauffer** [comment]
1+

**Comment by mxmo0rhuhn** [comment]
+1

**Comment by ptqa** [comment]
+1

**Comment by knobli** [comment]
+1

**Comment by corebug** [comment]
+1

**Comment by pavetok** [comment]
+1

**Comment by kzarzycki-advertine** [comment]
+1, I also hit the issue.

**Comment by stevemcquaid** [comment]
+1

**Comment by aviau** [comment]
+1

**Comment by vlastv** [comment]
+1

**Comment by gibsonm** [comment]
+1

**Comment by oguya** [comment]
:+1:  I definitely need this, more so with custom systemd service files.

**Comment by a-h** [comment]
+1

**Comment by jkahrs** [comment]
+1

**Comment by rey** [comment]
+1

**Comment by jsantos17** [comment]
+1

**Comment by reactormonk** [comment]
+1

**Comment by j3ffrw** [comment]
+1

**Comment by carmi** [comment]
+1

**Comment by bram70** [comment]
+1

**Comment by cyberj** [comment]
+1

**Comment by larsla** [comment]
+1

**Comment by r1k0** [comment]
+1

**Comment by davisonio** [comment]
:+1:

**Comment by jswart** [comment]
+1

**Comment by jfchevrette** [comment]
+1

**Comment by Antikythera** [comment]
+1

**Comment by gustawho** [comment]
+1

**Comment by mkmik** [comment]
+1

**Comment by msimerson** [comment]
+1

**Comment by xytis** [comment]
+1

**Comment by nervo** [comment]
:+1:

**Comment by aurelw** [comment]
Concerning changes to the service file, the module behaves very differently depending on if it is a /etc/init.d/ script or a systemd service. Hidden, inconsistent behavior makes this module actually much less generic than a simple additional option for deamon reloadine would.

But actually, someone would expect an implicit daemon reload. Anything else does not make sense and is imho simply broken. However, by not responding early and properly enough to such a somewhat important issue which hangs around for 1.5 - 2 years, the oppertunity to fixing this properly may have been missed already. Implicit daemon reload may cause issues with existing setups because downward-compatibility brakes at this point. 

So I guess an additional reload option is now the most practical, tho by far not a good solution.

**Comment by geowa4** [comment]
I was thinking about this, and I agree with @aurelw. To get around this issue, I've done something like the following.

```
- template: src=my.service.j2 dest=/etc/systemd/system/my.service
  register: service_file

- shell: systemctl daemon-reload
  when: service_file.changed

- service: name=my.service state=started
```

I think there are two things that would make sense to change in Ansible to enhance this workflow:
- add `notify_now` so I can notify a handler and have it immediately execute when there is a change
- make the name optional in the service module if the state is set to "reloaded" (e.g. `service: state=reloaded`).

**Comment by grahamrhay** [comment]
I just use 2 handlers, like this: http://lookonmyworks.co.uk/2015/06/24/ansible-systemctl-daemon-reload/

There is a meta task "flush_handlers", if you need them to run immediately.

I don't see what harm adding implicit reload would do, you'd just end up calling it twice if you had implemented a workaround yourself.

**Comment by oaken-source** [comment]
I personally fixed this by using a local copy of the service module. No need to add extra clutter to your playbooks.

**Comment by grahamrhay** [comment]
do you have a fork with the changes you made?

**Comment by geowa4** [comment]
@grahamrhay i did not know about `flush_handlers`. Thanks for the tip.

Sometimes, I wish Ansible supported automatically pulling from executables a la Git. If I had an executable on my PATH (installed via pip?) called `ansible-module-oaken-service`, it would give me a module named `oaken-service`. That way, we could more easily and reliably share these kinds of changes and definitely wouldn't need to wait for the next Ansible release.

**Comment by oaken-source** [comment]
@geowa4 you can do something similar. If you add a directory `library` to the top level of the project, ansible will make the modules in there available in your playbooks. 

@grahamrhay I just created one. Althought the changes are very crude and should probably be improved. Here is a diff:

```
diff --git a/system/service.py b/system/service.py
index 2b8dbb8..737c787 100644
--- a/system/service.py 
+++ b/system/service.py  
@@ -3,6 +3,9 @@

 # (c) 2012, Michael DeHaan <michael.dehaan@gmail.com>
 #  
+# edited by Andreas Grapentin to add `systemctl daemon-reload` calls
+# prior to service control  
+# 
 # This file is part of Ansible
 #
 # Ansible is free software: you can redistribute it and/or modify
@@ -865,6 +868,9 @@ class LinuxService(Service):


     def service_control(self):
+        # if we are on systemd, run deamon-reload prior to control
+        if self.svc_cmd and self.svc_cmd.endswith("systemctl"):
+            self.module.run_command([self.svc_cmd, 'daemon-reload'], check_rc=True)

         # Decide what command to run
         svc_cmd = ''
```

**Comment by grahamrhay** [comment]
@oaken-source thanks, I might give it a try. although I find relying on a patched version to be more hassle than it's worth, sometimes

**Comment by pabelanger** [comment]
+1

**Comment by geowa4** [comment]
@oaken-source Yeah, I knew that, but to me, that's a temporary band-aid at best. At that point, I'm essentially taking a snapshot. If there's an update, I can't just `pip install -U the-module`.

**Comment by Smana** [comment]
+1

**Comment by c-garcia** [comment]
+1

**Comment by enxebre** [comment]
+1

**Comment by eroldan** [comment]
+1

**Comment by dmexe** [comment]
+1

**Comment by hanswesterbeek** [comment]
+1

**Comment by SuperQ** [comment]
+1

**Comment by farazhussain** [comment]
+1

**Comment by geerlingguy** [comment]
:+1:

**Comment by 4everinbeta** [comment]
+1

**Comment by ninthnails** [comment]
+1

**Comment by nemesifier** [comment]
Here's a workaround if anybody needs it:
https://github.com/nemesisdesign/Stouts.openvpn/commit/fe8ae777f3d404192895d74a5e90eaf4d716d75d

**Comment by matthewhartstonge** [comment]
:+1:

**Comment by nanjiang29** [comment]
+1

**Comment by raqqun** [comment]
i use something like this in my playbook if the varnish.service unit file has been changed. 

```
- name: Ensure varnish.service is latest
  template: src=varnish.service dest=/etc/systemd/system/varnish.service
  register: result
  notify:
    - restart varnish

- name: Ensure systemd is reloaded if varnish.service has changed
  shell: systemctl daemon-reload
  when: result|changed
```

**Comment by yvbeek** [comment]
Why not simply use notify here too?
Side-note: Ansible [recommends](http://docs.ansible.com/ansible/command_module.html) to use `command` instead of `shell` whenever possible.

```
- name: Create systemd scripts
  template: src=test.service dest=/etc/systemd/system/test.service
  notify: Reload systemd

- name: Reload systemd
  command: systemctl daemon-reload
```

**Comment by holms** [comment]
@Zyphrax  because that's a hack, and it's fine to use it  as hack, but not as solution. Normally you need to twist your brain the way that this "command" wouldn't violate Idempotence.. and that's wrong. This should be in a module itself, and it's about time to fix this.. cause that's basic functionality of Debian system which must be done after copying configuration. Why use hacking solution each time?

**Comment by yvbeek** [comment]
@holms I agree, the module should handle this. My goal was to provide a simple workaround. I saw raqqun's solution which works fine, but is a bit more complex than necessary and won't work in combinations with `with_items` and a few other constructs.

**Comment by muirdok** [comment]
+1 to add additional action for "reloaded" or "started" state.

**Comment by TerryHowe** [comment]
:+1:

**Comment by kennethmyers** [comment]
+1

**Comment by WinstonSureChill** [comment]
+1

**Comment by holms** [comment]
Guys, there's a thumb up vote on original post.. no need to do +1 anymore. This was created intensely to avoid voting flood.

**Comment by hho** [comment]
@Zyphrax Unfortunately, your solution doesn't really work if I want to add, enable and start a service in the same playbook. The handler reloading the systemd daemon would only be executed _after_ the playbook – and by then it is too late.

**Comment by nemesifier** [comment]
comments with +1 are useless, either write some code, a workaround or anything other interesting or refrain from commenting please!

**Comment by akostadinov** [comment]
+1 are **useful**, please add them especially now you can just use a reaction icon under on a post. They can help project owners give priority to particular features/bugs. Especially with issue like this, where solution is not as hard as having project owners agree on how things should work.
Everybody is free to manage his/her own projects as he/she desires, but advising on a generic practice to refrain from giving feedback (even if it is simple +/-1) is not doing a favor to anybody.

**Comment by nervo** [comment]
@nemesisdesign 👍

**Comment by nemesifier** [comment]
@akostadinov all this +1 one comments without any meaningful comment just make it hard for people who want to know about solutions employed or opened pull request to follow the discussion. Congratulations! Write some more hundreds of +1 comments and it will be fixed faster!

**Comment by akostadinov** [comment]
@nemesisdesign , agreed, I think @holms addressed that concern though.

**Comment by nemesifier** [comment]
Running into this on a fresh Ubuntu 16 system. It's painful and ugly to apply the workaround to generic roles. I do not understand if it's possible to fix it in core and if there's somebody who is working on it.

**Comment by ghost** [comment]
Well a PR was submitted and closed on this issue. I believe it's rather strange now that systemd is on most major systems that we don't have some way to do a systemctl daemon-reload (a critical function) inside the service module.

**Comment by akostadinov** [comment]
I think @bcoca working on this with #1616 but not sure what the status is. Can priority of this issue be raised a little bit (P4 sounds somehow low)?

**Comment by flavius** [comment]
+1

**Comment by bcoca** [comment]
fixed via https://github.com/ansible/ansible-modules-core/pull/3660
