### ISSUE TITLE
Windows: setup.ps1 - ansible_os_name fact has trailing space at end. Easy fix.

### ISSUE THREAD

**Issue by JimFicarra** [ansible/ansible-modules-core#1927]
When the facts are gathered ansible_os_name has an extra space at the end.  This causes a problem when trying to match a when clause on the string due to the extra space.

https://github.com/ansible/ansible-modules-core/blob/devel/windows/setup.ps1

Line 63 in the above file can be changed from:

```
Set-Attr $result.ansible_facts "ansible_os_name" $win32_os.Name.Split('|')[0]
```

to 

```
Set-Attr $result.ansible_facts "ansible_os_name" ($win32_os.Name.Split('|')[0]).TrimEnd()
```

in order to clean up the trailing space.

**Comment by cchurch** [comment]
Fixed via #1956.
