### ISSUE TITLE
win_file creates directory, but not file?

### ISSUE THREAD

**Issue by bleloch** [ansible/ansible-modules-core#1928]
Issue Type:
Bug Report

Ansible Version:
1.9.2

Ansible Configuration:
Vanilla config, except for control_path which has been truncated

Environment:
CentOS 7.1

Summary:
I'm executing a playbook which creates a directory, then a file within that directory, and then checks the status of the file with win_stat. While the directory creation works without a hitch, the file creation just doesn't work, despite the playbook debug saying the server state has changed.

I'm authenticating to my Windows host using an AD-authed domain admin account, if it helps any.

For reference here's the play I'm using:
- name: Build some folder structure
  hosts: windows
  gather_facts: false
  tasks:
  - name: Create a folder in c:\temp
    win_file: path=C:\temp\folder\subfolder state=directory
  - name: Create a file in our new folder
    win_file: path=C:\temp\folder\subfolder\foo.txt state=touch
  - name: Test the existence of our new file
    win_stat: path="C:\temp\folder\subfolder\foo.txt"
    register: stat_file
  - debug: var=stat_file
  - name: check stat_file result
    assert:
        that:
           - "stat_file.stat.exists"
           - "not stat_file.stat.isdir"
           - "stat_file.stat.size > 0"
           - "stat_file.stat.md5"

Steps To Reproduce:
Run the above play against a Windows host, while authenticating with a domain administrator-level account

Expected Results:
I would hope that foo.txt is created... ;)

Actual Results:
See summary!

**Comment by cchurch** [comment]
This one has been fixed in devel branch via https://github.com/ansible/ansible-modules-core/commit/02ea210db9f60ab68b5ae4e18f7150f3e5993954
