### ISSUE TITLE
How to pass raw params to Windows cmd without any encoding/decoding?

### ISSUE THREAD

**Issue by vladimirmartsul** [ansible/ansible-modules-core#1929]
I'm trying to set permissions to some windows directory like this

```
# ansible example.com -m raw -a 'icacls D:\somedir\ /grant "! ЗАО. Руководство":F' -vvvvv
```

and get windows error about invalid parameters

```
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
File lookup using /etc/ansible/host_files/example.com/mvs as file
<example.com> ESTABLISH WINRM CONNECTION FOR USER: mvs on PORT 5985 TO example.com
<example.com> WINRM CONNECT: transport=plaintext endpoint=http://example.com:5985/wsman

<example.com> EXEC icacls D:\somedir\ /grant "! .  C:>2>4AB2>" :F

<example.com> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-EncodedCommand', 'aQBjAGEAYwBsAHMAIABEADoAXAAxAGMAXAAgAC8AZwByAGEAbgB0ACAAIgAhACAAFwQQBB4ELgAgACAEQwQ6BD4EMgQ+BDQEQQRCBDIEPgQiACAAOgBGAA==']
<example.com> WINRM RESULT u'<Response code 1, out "", err "Invalid parameter "!">'
example.com | FAILED | rc=1 >>
Invalid parameter "! ���. �㪮����⢮"
```

Direct windows command in cmd.exe works fine.

I see 2 problems:
1. Strange encoding or decoding of cyrillic parameter "! ЗАО.
   Руководство" (this is a group name in the windows) that passing from
   Ansible to windows host.
2. Adding extra space beetwen group name and permission
   
   "encoded bla-bla-bla": F

instead of

```
"encoded bla-bla-bla":F
```

How to fix it?

Ansible using from source (checked out at 17 August 2015)

```
# ansible --version
ansible 2.0.0 (devel 4068598c15) last updated 2015/08/17 23:09:54 (GMT +600)
  lib/ansible/modules/core: (detached HEAD dea5f5d15e) last updated 2015/08/17 23:10:13 (GMT +600)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/17 23:10:35 (GMT +600)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/17 23:10:53 (GMT +600)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/17 23:11:11 (GMT +600)
  config file =
  configured module search path = None
```

and running on Gentoo Linux

```
# uname -a
Linux web 3.10.4-gentoo #1 SMP Sat Aug 3 02:25:18 NOVT 2013 x86_64 Intel(R) Core(TM)2 Quad CPU @ 2.40GHz GenuineIntel GNU/Linux
```

On other side - Windows Server 2012 R2 Standard in KVM (on vultr.com)

**Comment by cchurch** [comment]
I did find a bug in displaying the debug output (the `<example.com> EXEC` line), which explains why that line doesn't match your command.

I see another issue related to splitting the command line using `shlex` and joining it back together, which explains the extra space inserted in the last argument.  However, even when passing the raw command verbatim, PowerShell still seems to split the arguments after that last double quote.

I'll let you know when I have a fix.

**Comment by vladimirmartsul** [comment]
> I did find a bug in displaying the debug output (the <example.com> EXEC line), which explains why that line doesn't match your command.

Yes, it's look like displaying-only bug that not affecting real command params and execution.

> However, even when passing the raw command verbatim, PowerShell still seems to split the arguments after that last double quote.

I found simple workaround: PowerShell doesn't split the arguments and doesn't add space if _grants_'s argument is a string, so command like

```
ansible example.com -m raw -a "icacls D:\somedir\ /grant '\"Users\":F'" -vvvvv
```

works fine. Single quotes around `\"Users\":F` cast it into string and its inner double quotes need to be escaping.

**Comment by cchurch** [comment]
I've added a command similar to your example as part of the integration tests and merged a fix for both issues indicated above (via https://github.com/ansible/ansible/pull/12051).  This should resolve your problem.
