### ISSUE TITLE
Add support for S3 permissions

### ISSUE THREAD

**Issue by jcowley** [ansible/ansible-modules-core#1939]
The amazon s3 module does not currently support setting permissions on buckets or objects. By default, all buckets are private.

Boto's S3 interface does support the use of canned ACL's.
See: http://boto.readthedocs.org/en/latest/s3_tut.html

**Comment by wimnat** [comment]
Hi @jcowley, what do you think about adding acl support as a separate module? I've added some new s3 modules in the ansible extras repo (check out PRs starting with s3_) but I didn't do ACLs so your work here could fill that gap.
