### ISSUE TITLE
google-cloud modules fail to find the "correct" python

### ISSUE THREAD

**Issue by alex-leonhardt** [ansible/ansible-modules-core#1959]
GCE modules seem to be fixed to /usr/bin/python when it shouldn't as sometimes you may want to run more than 1 python (or use brew to install python on mac os x). This creates issues finding the python modules necessary for GCE to work. 

Example: 
https://github.com/ansible/ansible-modules-core/blob/devel/cloud/google/gce.py#L1

Should be: 

```
/usr/bin/env python
```

Regards,
Alex

**Comment by bcoca** [comment]
No, there is a reason for that, as documented in the FAQ.

http://docs.ansible.com/ansible/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine

**Comment by alex-leonhardt** [comment]
Ok - so, if the #! line is being replaced when setting  ansible_python_interpreter  variable and using /usr/bin/env python would "mostly" make it easier to get "the right" python, then even if not always the correct one, wouldn't it make locally running these modules easier ?
