### ISSUE TITLE
Fix the binary copy wart (modules edition)

### ISSUE THREAD

**Issue by garthk** [ansible/ansible-modules-core#1961]
Neither of the following obvious approaches work for storing `/etc/ssh/ssh_host_key` in an Ansible vault, i.e. a vars file:
- YAML 1.1's `!binary` ([spec](http://yaml.org/spec/1.1/), [tag draft](http://yaml.org/type/binary.html)), because the parser fails
- `copy` with `content` set to `"{{ ssh_host_key|b64decode }}"`, because the Jinja2 template engine [corrupts the result](https://groups.google.com/forum/#!topic/ansible-devel/lR0k2S0GIQw/discussion)

All the workarounds I've found involve writing to temporary files and decoding them, plus use of `register` and `changed_when` to detect whether the target really changed or not.

Is there a way to fix this in the `copy` module itself?

See also: ansible/ansible#12060

**Comment by abadger** [comment]
I don't believe so.  I don't think there's a way to get the binary data out of core and into the module without passing through jinja2.  For vault in particular, @bcoca has some ideas of a future enhancement he'd like to see added. Those would have to be core changes so I'll close this ticket on the modules repo.
