### ISSUE TITLE
Docker containers do not upgrade when state is "restarted"

### ISSUE THREAD

**Issue by yannh** [ansible/ansible-modules-core#1967]
The docker module documentation states the following:

"reloaded" (added in Ansible 1.9) asserts that all matching containers are running and restarts any that have any images or configuration out of date. "restarted" unconditionally restarts (or starts) the matching containers

From this, I understand that:
- with pull=always and state=reloaded, ansible will update and restart a container if there is a new version or configuration avaialble, and do nothing otherwise.
- with pull=always and state=restarted, ansible will update the container if there is a new version of that container, and always restart it, even if there are no changes in the docker container or config.

Actual behaviour is that state=restarted will restart the container but never update it if there is a new version, even if pull=always is set.

Could you confirm that the behaviour I understand is the one that is intended? If yes I'd be happy to provide a pull request! :)

Thanks!

**Comment by yannh** [comment]
Currently working on a patch, I need to test this more
https://github.com/yannh/ansible-modules-core/commit/8f03f1e4e142bf40ff84e7e163651bd83cad3885

PR: https://github.com/ansible/ansible-modules-core/pull/1972

**Comment by abadger** [comment]
Added the description to the PR and closing this ticket in favor of the PR.
