### ISSUE TITLE
assemble module: Add template=yes option

### ISSUE THREAD

**Issue by xrl** [ansible/ansible-modules-core#1970]
**Issue Type**: **Feature Idea**

Ansible Version: N/A

Ansible Configuration: N/A

Environment: N/A

**Summary**: I would like to assemble a local folder of templates to be evaluated by jinja2. I am injecting hostvars in to the templates and would like to then assemble them in to one large config file.

Steps To Reproduce: N/A

**Expected Results**: I would like all the jinja2 rules to be applied to file passed to assemble. Evaluate and concat or concat and evaluate, either should work.

Actual Results: N/A

**Comment by bcoca** [comment]
jinja can use it's include to do the same thing, we really do not want to duplicate that functionality in the assemble module when the template module can do this already.

**Comment by xrl** [comment]
Can jinja2's include bring in all the files in a folder? I'm not finding relevant examples on how to include/evaluate all templates in a folder in to one output file.

**Comment by bcoca** [comment]
lookup('fileglob', '/path/to/folder') will work inside jinja2

**Comment by xrl** [comment]
Thanks for the hint on that. I had the hardest time finding any resource that went over how to do this in detail, especially for a beginning such as myself. Did a writeup here: http://tureus.github.io/devops/2015/08/28/ansible-compiling-conf.d-pattern.html .
