### ISSUE TITLE
Support apt-get autoremove

### ISSUE THREAD

**Issue by lukehoersten** [ansible/ansible-modules-core#1976]
`apt-get autoremove` is needed after removing packages to clean out a unused dependency packages etc. In HEAD, warnings are now issued when using `command: apt-get` directly so we should probably support the full suite here.

From `man`:

> autoremove is used to remove packages that were automatically installed to satisfy dependencies for other packages and are now no longer needed.

**Comment by abadger** [comment]
Sounds good -- you thinking of making it an additional parameter to the module?

**Comment by lukehoersten** [comment]
Seems like that would be easiest. Similar to the way dist update works?

**Comment by abadger** [comment]
Yeah, I think so.  I don't think we have time right now to implement this (lots of work to get v2 ready) but it seems like a PR wouldn't be too hard to review so if someone wants to implement it we can try to get it merged.

**Comment by tersmitten** [comment]
+1

**Comment by thuandt** [comment]
+1

**Comment by binaryanomaly** [comment]
+1

getting a warning with 2.0.1 now but autoremove leaves no other option than running apt-get

**Comment by willruss1** [comment]
+1 as well

**Comment by marccarre** [comment]
+1 

I'd like to be able to run `apt-get -y autoremove --purge <package name>`.
I guess if/once the `autoremove` option is added, it would look like:

```
apt: name=<package name> force=yes autoremove=yes purge=yes state=absent
```

**Comment by gambala** [comment]
+1

**Comment by endlesslight0** [comment]
+1

**Comment by bjoernt** [comment]
:+1:

**Comment by hkratz** [comment]
+1

**Comment by evantahler** [comment]
I'm a bit confused... the docs say this exists (http://docs.ansible.com/ansible/apt_module.html) but on the current ansible version, it doesn't work:

```
> ansible --version
ansible 2.0.1.0
  config file = /Users/evantahler/Projects/taskrabbit/ansbile/ansible.cfg
  configured module search path = Default w/o overrides
```

=> `FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: autoremove"}`

**Comment by sivel** [comment]
`autoremove` was just recently added and will be included in 2.1.  However the docs were not correctly tagged with `version_added: "2.1"` until recently.

Since this was merged in https://github.com/ansible/ansible-modules-core/pull/2974 I am going to go ahead and close this issue.

**Comment by evantahler** [comment]
Ahh.  Thanks!

**Comment by p3t3r67x0** [comment]
+1

**Comment by jeffrey4l** [comment]
seems the `apt-get autoclean` is different with `apt-get clean`.
So could Ansible support clean action?

**Comment by rfdparker** [comment]
As per my comment just made on #2340, are there plans to support `apt-get clean` ?

The comment made upon that issue's closure seems to say support for `apt-get clean` is already a requested feature, but the only other issue referenced in that issue is this issue – which appears concerned with `apt-get autoremove` and is already closed.
