### ISSUE TITLE
docker: Tries to pull image from DockerHub when build locally with docker_image

### ISSUE THREAD

**Issue by neocortical** [ansible/ansible-modules-core#1977]
Issue type: bug report

Description: The docker task attempts to download the named image from DockerHub, but I am building the image locally using docker_image. The docker task fails with the following error message: 

``` yml
fatal: [10.0.21.114]: FAILED! => {"changed": false, "changes": ["{\"status\":\"Pulling repository docker.io/htv/myapp\"}\r\n", "{\"errorDetail\":{\"message\":\"Error: image myapp:latest not found\"},\"error\":\"Error: image myapp:latest not found\"}\r\n"], "failed": true, "msg": "Unrecognized status from pull.", "status": ""}
```

Expected behavior: The docker task should attempt to load locally built images before checking DockerHub. 

Environment: 

Local machine: 
Mac OS X Yosemite

```
ansible 2.0.0 (devel 6c9dc78d8c) last updated 2015/08/27 10:30:36 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 85ddb1b902) last updated 2015/08/27 10:30:46 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 7a0bfd91bb) last updated 2015/08/27 10:30:53 (GMT -700)
```

```
Python 2.7.9
```

Target machine: 

```
Linux ip-10-0-21-114 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
Python 2.7.6
docker-py 1.3.1
Docker version 1.8.1, build d12ea79
```

Tasks: 

``` yml
- name: Build docker image
  docker_image: path="/home/ubuntu/myapp"
                name="myapp"
                tag="myapp"
                state=build

- name: Run app container
  docker: image=myapp
          name=myapp
          memory_limit=4096MB
          ports=4000:4000
          volumes=/var/log/myapp:/var/log/myapp
          state=reloaded
```

It seems that maybe this issue is related to https://github.com/ansible/ansible-modules-core/issues/1794

**Comment by neocortical** [comment]
OK, I figured it out (I'm dumb). 

The issue is that I was tagging my image with the app name in `docker_image` and not specifying a tag name in the `docker` task. This caused docker to not find the image locally and then to search for myapp:latest remotely. Changing the above to `tag=v1.0` in `docker_image` and `image=myapp:v1.0` in `docker` solved the issue for me. 

This bug can be closed as a Layer 8 issue. Hopefully some other hapless soul will find this on Google and save themselves some time.

**Comment by abadger** [comment]
Thanks for exploring this to a solution ;-)
