### ISSUE TITLE
service: use "check" instead of "status" for checking state on OpenBSD

### ISSUE THREAD

**Issue by gangelop** [ansible/ansible-modules-core#200]
##### Issue Type:

Feature Idea
##### Ansible Version:

`ansible 1.7.2`
##### Environment:

running from: N/A
applied on: OpenBSD
##### Summary:

The `service` module uses the `status` command of service scripts to check their status. However, on OpenBSD, rc scripts by default use the operations defined in `rc.subr(8)`. So instead of `status` used in linux, in OpenBSD we have `check`.

From [man 8 rc.subr](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man8/rc.subr.8?query=rc.subr&sec=8)

```
 check
    Call rc_check. Return 0 if the daemon is running or 1 if it is not.
```

Maybe the `service` module can be made to run `check` instead of `status` for OpenBSD hosts so I don't have to define process patterns for all the services. Maybe this also applies to other BSDs? I've only checked OpenBSD.

**Comment by eest** [comment]
Can you be more specific about what line of code you are referring to? This is currently in the module (with line numbers addded):

```
966     def get_service_status(self):
967         rc, stdout, stderr = self.execute_command("%s %s" % (self.svc_cmd, 'check'))
```

**Comment by gangelop** [comment]
Apparently, I'm totally wrong. I still have an issue but this is not it. Thnx @eest and sorry for the noise.

**Comment by gangelop** [comment]
For anyone who stumbles on this thread in the future, even though it's not directly relevant, this is the problem I'm having:

http://marc.info/?l=openbsd-ports&m=141381575414032&w=2

When postgresql is stopped, '/etc/rc.d/postgresql check' returns 3, but
according to rc.subr(8) it should return 1.

The rc.script basically uses:

/usr/local/bin/pg_ctl -D /var/postgresql/data/ status

According to pg_ctl(1), an exit status of 3 does indeed mean that
postgresql is not running.

> ```
>   status mode checks whether a server is running in the specified data
>   directory. If it is, the PID and the command line options that were
>   used to invoke it are displayed. If the server is not running, the
>   process returns an exit status of 3.
> ```

However, according to rc.subr(8), the rc script should return 1.

> check    Call rc_check.  Return 0 if the daemon is running or
>                         1 if it is not.

My personal problem is that I use ansible for checking service status.
Ansible assumes that '/etc/rc.d/postgresql check' will will return
either 0 or 1, and fails if it returns everything else. As I understand
it, this is correct according to rc.subr(8), but maybe ansible should be
more lenient and just check for non-zero exit instead of '1'. Who's
really at fault here?

Also, here's the bit of code from `system/service.py` that checks the exit status:

``` python
 def get_service_status(self):
    rc, stdout, stderr = self.execute_command("%s %s" % (self.svc_cmd, 'check'))
    if rc == 1:
        self.running = False
    elif rc == 0:
        self.running = True

```

**Comment by eest** [comment]
Thanks a lot for finding the root cause of the issue :).

At this point in time I feel the rc.d script is doing the wrong thing. It is clearly in violation of the man page as you point out. The rc.d script (or man page) is wrong, and I would like to see what happens upstream before we add more complexity to the module.

Does that make sense to you?

Again, I am not part of the ansible team, so they will do what they please, but given that this part of the module has been written by me I hope my word carries some weight :).

**Comment by gangelop** [comment]
> Does that make sense to you?

Yes. I also think it's the rc script. I have nothing more to add so I'll just have to wait. :)
