### ISSUE TITLE
unexpected state in yum module (1.9.3)

### ISSUE THREAD

**Issue by steynovich** [ansible/ansible-modules-core#2013]
Updating YUM packages is broken in Ansible 1.9.3.

env:
Ubuntu 15.04 vivid
Ansible version: 1.9.3-1ppa~vivid (deb-src http://ppa.launchpad.net/ansible/ansible/ubuntu)

Snippet of my playbook:

``` yaml
- name: YUM upgrade
  yum: name=* state=latest update_cache=yes
```

Unexpected result:

```
TASK: [centos | YUM upgrade] **************************************************
failed: [centos_host] => {"changed": false, "errors": "unexpected state", "failed": true, "results": ""}
msg: we should never get here unless this all failed
```

Debugging showed that the value state is 'latest', which is an expected state.

Expected result (was working in 1.9.2):

```
TASK: [centos | YUM upgrade] **************************************************
ok: [centos_host]
```

**Comment by gunzy83** [comment]
Confirming the above, updating all packages using the yum module is broken in 1.9.3.

My environment:
Amazon Linux AMI 2015.03.1 x86_64
Ansible version 1.9.3 installed via pip

Broken task:

```
- name: Ensure all base packages are updated
  yum:
    name: "*"
    state: "latest"
```

Result:

```
TASK: [base | Ensure all base packages are updated] ***********************
failed: [127.0.0.1] => {"changed": false, "errors": "unexpected state", "failed": true, "results": ""}
msg: we should never get here unless this all failed
```

Downgrading to 1.9.2 fixes the issue.

**Comment by abadger** [comment]
I just pushed https://github.com/ansible/ansible-modules-core/commit/411adff00687842dd1c379fd78b6b2562c6f97e4 which I think will fix this.  Testing now.  If you'd like to test as well, that would be appreciated.

**Comment by steynovich** [comment]
Your commit 411adff seems to fix the issue for me.

```
TASK: [centos | YUM upgrade] **************************************************
ok: [centos_host]
```

Thanks for your swift reply.

**Comment by abadger** [comment]
Thanks for the quick test.  Works here too.  We're working out when to make a 1.9.4 release with this fix in it now.

**Comment by abadger** [comment]
Okay, we've tagged 1.9.4-rc1.  If no more major bugs are found a 1.9.4 final should be out soon with this fix in it.

**Comment by josebv** [comment]
This only affects when yum update is used inside roles, not at the top level yml

**Comment by lero** [comment]
almost one month and still no new release to fix it? I don't want to use rc versions.

**Comment by milad-soufastai** [comment]
@josebv It affects when yum is listed in the pre_tasks on a top level yml too

**Comment by jbelafa** [comment]
Hi 
Is it risky to downgrade our platform to 1.9.2  as it's not affected ?

**Comment by extremeshok** [comment]
Guys please push a fix, aka release 1.9.4 or a patched 1.9.3.1

**Comment by sivel** [comment]
1.9.4-rc3 was just announced 3 days ago

https://groups.google.com/forum/m/#!topic/ansible-devel/JmtlaIbLrlo

I imagine a 1.9.4 release soon.

**Comment by extremeshok** [comment]
The following command will fix the yum error on debian, centos will need the path changed.

``` bash
sed -i "s/return res/module.exit_json(**res)/g" /usr/local/lib/python2.7/dist-packages/ansible/modules/core/packaging/os/yum.py
```

**Comment by cad** [comment]
How come it is not tested?

**Comment by thehungrycoder** [comment]
Just wanted to confirm that I ran into same problem with `1.9.3`. I, however, downgraded to `1.9.1` which fixed the issue.

**Comment by pavgup** [comment]
@extremeshok has the right idea.  On my fancy pants macbook with ansible installed via homebrew, the fix was:

```
sed -i "s/return res/module.exit_json(**res)/g" /usr/local/Cellar/ansible/1.9.3/libexec/lib/python2.7/site-packages/ansible/modules/core/packaging/os/yum.py
```

**Comment by ghost** [comment]
Solution provided by @extremeshok worked. On Ubuntu 14+, the path is slightly different:

```
sudo sed -i "s/return res/module.exit_json(**res)/g" /usr/lib/pymodules/python2.7/ansible/modules/core/packaging/os/yum.py
```

**Comment by sivel** [comment]
1.9.4 was just released that contains this fix.

**Comment by plombardi89** [comment]
Still occurs with Ansible 1.9.4 on CentOS 7 installed via pip:

> TASK: [common | ensure centos is updated] ************************************* 
> failed: [default] => {"changed": false, "errors": "unexpected state", "failed": true, "results": ""}
> msg: we should never get here unless this all failed
> 
> FATAL: all hosts have already failed -- aborting                                                                                                                                                               

> [vagrant@localhost ~]$ ansible --version
> ansible 1.9.4
>   configured module search path = None
