### ISSUE TITLE
rsync src path / goes into system /

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#2024]
i am not sure if this behavior is intended by the rsync module. 

if i do the following it works like i would expect it. 

```
- name: blub        
  synchronize: src=/test
               dest=/custom_dest/
               archive=yes
```

/home/user/ansible/roles/playbook_name/files/test is synced with /custom_dest/ on the remote server.

if i use just / as source path. 

```
- name: blub        
  synchronize: src=/
               dest=/custom_dest/
               archive=yes
```

system / is synced to /custom_dest/ on the remote machine. 

my expectation would be to sync just /home/user/ansible/roles/playbook_name/files. 

my ansible version is 1.9.1 on a centos 6.6 box. 

cheers markus

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

i would not expect that at all, use `src=files/` if that is what you actually want, any path that starts with a / is absolute, not relative.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by ghost** [comment]
Hi, 

If you are right i have to get an error with my path mentioned in my example /test has to go to the absolute path /test, which does not exist in my system but goes to files/test. 

cheers markus

**Comment by bcoca** [comment]
that would be a bug, any path starting with a / should not be made relative

**Comment by ghost** [comment]
good so we agree. :)

**Comment by bcoca** [comment]
I checked and this works as I expect in devel, so there is not action to take at this point
