### ISSUE TITLE
Ansible bug supporting Azure SDK for Python 1.0.0

### ISSUE THREAD

**Issue by ToddBooth** [ansible/ansible-modules-core#2032]
Hi.  Here is the [Ansible Azure module doc url](http://docs.ansible.com/ansible/azure_module.html), which says "azure >= 0.7.1".  Neither Ansible 1.9.3 nor Ansible 2.0.0 (devel 246e602fce) supports the Azure SDK for Python 1.0.0.  So we have a bug.  If Ansible does not suport 1.0.0, I suggest they simply update the web documentation to state something like:

0.7.1 <= Azure SDK for Python <= 0.11.1 (2015-06-16)

Note: Support for 1.0.0 (2015-08-31) is expected in:

```
For Ansible version 1.x ...

For Ansible version 2.x ...
```

Thanks for the great product!

**Comment by gregdek** [comment]
ping @nitzmahone

**Comment by nitzmahone** [comment]
This appears to be resolved in 2.0 as of RC1 - I've tested with Azure 0.7.1, 1.0.0 and 1.0.2.
