### ISSUE TITLE
Default docker_api_version to 'auto'

### ISSUE THREAD

**Issue by DirkHeinke** [ansible/ansible-modules-core#2033]
I'm not sure if this is a "bug", but is there a reason, why the docker module defaults to ['docker.constants.DEFAULT_DOCKER_API_VERSION'](https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker.py#L444) and not to 'auto' [docker-py docs](https://docker-py.readthedocs.org/en/latest/api/)?

**Comment by abadger** [comment]
Auto is a relatively recent addition (maybe within the last six months?) So
it isn't something we can really on users having.  That said,I think a case
could be made for defaulting to auto if it's available.  Do you know of a
way to test if that's available?  Do you think that's a good plan?  It does
mean that the middle has different defaults depending on the version of
docker-py that is installed which could lead to some head scratching
occasionally.

**Comment by DirkHeinke** [comment]
The 'auto' option was added with [1.1.0](https://docker-py.readthedocs.org/en/latest/change_log/#110). In the initialization we test for 'docker.constants', which was added in [1.2](https://github.com/docker/docker-py/commit/ae329cb3acb3ff38bd986215c99b1136a6183f78#diff-259a47dfd7aba2b57d1733f22af86030). Even though it's not optimal, we can just replace in the line [465](https://github.com/ansible/ansible-modules-core/blob/a0a374b8cad5da9af0aca4ac24e212318267ce14/cloud/docker/docker.py#L465) `DEFAULT_DOCKER_API_VERSION = docker.constants.DEFAULT_DOCKER_API_VERSION
` with `DEFAULT_DOCKER_API_VERSION = 'auto'`
Otherwise we have to test if version is > 1.1.0 at the end of the file and replace `DEFAULT_DOCKER_API_VERSION`.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
