### ISSUE TITLE
add selection support to unarchive

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible-modules-core#2037]
##### ISSUE TYPE

Feature Idea
##### COMPONENT NAME

unarchive module
##### ANSIBLE VERSION

N/A
##### SUMMARY

Add a list of files or patterns to extract from the archive instead of extracting the whole thing, by default it is none/empty and won't filter.

**Comment by ghost** [comment]
Thanks

**Comment by pileofrogs** [comment]
I'm thinking I need to add an arg for passing extra args to the unarchive program.  Then when someone wants to use preserve owner or use numeric file id ownership or something unzip-ish that I've never heard of, they'll be able to.

Is that a good idea or a bad idea?

**Comment by Jmainguy** [comment]
@pileofrogs thats pretty much exactly what I was thinking, just give them an options= and pass whatever options they add, if it errors out, the can read the error which should explain they passed it a bad flag or that the version of tar/gtar doesn't support that flag etc etc.

**Comment by bcoca** [comment]
just adding options= makes it really hard to check for changed status in this module, i would prefer to add them as actual options, otherwise there is really little added value over using shell: directly.

**Comment by Jmainguy** [comment]
@bcoca yeah that makes sense, leaves open the possibility of a ton of options we end up adding, but otherwise yeah, might as well use shell.

**Comment by pileofrogs** [comment]
Sortof.  Having gone the shell route for these kinds of things many times
before I can point out one nice feature that gives unarchive value over
shell.  The unarchive module handles the copying of the archive to the host
and the removal of the archive afterword.

I would suggest adding an options= arg for folks who want it and specific
named args for frequently used features.

**Comment by dagwieers** [comment]
@bcoca We can close this issue now. This is possible since #3307 is merged.

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible-modules-core/pull/3307

**Comment by jurajseffer** [comment]
How does #3307 fixe the case of wanting to select a single file from an archive? I've looked through the documentation and the PR and cannot see how I can pass in what would be the first argument to tar.
