### ISSUE TITLE
ec2_asg termination_policies 'termination_policies is not defined'

### ISSUE THREAD

**Issue by cgrigor** [ansible/ansible-modules-core#2044]
Hi,

I've just pulled the latest devel and creating an aws asg group (at least for me) fails when this worked in the past.

The following is a code snippet of the playbook task:

```
- name: Create AutoScaling Group Rundeck
    ec2_asg:
      name: "LP_{{env|upper}}_Rundeck_ASG_1"
      launch_config_name: "LP_{{env|upper}}_LaunchConfig"
      state: present
      health_check_period: 450
      health_check_type: EC2
      min_size: "{{ rundeck.asg.min }}"
      max_size: "{{ rundeck.asg.max }}"
      desired_capacity: "{{ rundeck.asg.desired }}"
      region: "{{ aws.region }}"
      vpc_zone_identifier: "{{ subnets.subnet_ids.0 }}"
      wait_for_instances: yes
    register: rdasg
  - debug: var=rdasg
```

An exception occurred during task execution. The full traceback is:

```
Traceback (most recent call last):
  File "/Users/chris.grigor/.ansible/tmp/ansible-tmp-1441737019.6-242492325232173/ec2_asg", line 2744, in <module>
    main()
  File "/Users/chris.grigor/.ansible/tmp/ansible-tmp-1441737019.6-242492325232173/ec2_asg", line 2733, in main
    create_changed, asg_properties=create_autoscaling_group(connection, module)
  File "/Users/chris.grigor/.ansible/tmp/ansible-tmp-1441737019.6-242492325232173/ec2_asg", line 2345, in create_autoscaling_group
    termination_policies=termination_policies)
NameError: global name 'termination_policies' is not defined

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}
```

The docs section of ec2_asg.py says that termination_policies default is set to a value of Default, so my guess is that it's not required in my task definition.
termination_policies and default_cool_down were introduced in the following commit ansible/ansible-modules-core@f7f6218#diff-689b2e5ce09076c21c9915e50f8a9140

Can anyone else verify if they get the same error? My colleague also reproduced this issue with the same error.

**Comment by fvant** [comment]
Yeah, running into the same issue. Looks like this commit introduced the feature:

> Added termination_policies option devel (#1951)
> commit f7f621839ad2063c707506f7eaf5663f113664a7 1 parent 2af3f34
> Bruno Galindro da Costa authored 20 days ago

I found the problem and will create a PR

**Comment by rejj** [comment]
I've hit the same problem.
Looks like there is a PR to fix this, #2075 thanks to @evanccnyc

**Comment by fvant** [comment]
I immediately created  PR  #2045, not merged so far but it breaks the basic functionality of this module.

**Comment by evanccnyc** [comment]
#2075 was merged in so this can be closed.

**Comment by bcoca** [comment]
closing as per above
