### ISSUE TITLE
RDS module : cannot use Reboot command

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#2050]
Hi there,

According to the documentation, there is a Reboot command. But it returned an error when used.

failed: [127.0.0.1] => {"failed": true}
msg: value of command must be one of: create,replicate,delete,facts,modify,promote,snapshot,restore, got: reboot

Using Ansible version 1.9.3

Regards,

**Comment by bcoca** [comment]
reboot was added in 2.0, documentation should have reflected that.
