### ISSUE TITLE
iam module fails with exception if called with appropriate iam permissions itself

### ISSUE THREAD

**Issue by wimnat** [ansible/ansible-modules-core#2066]
None of the lines to get original iam types are wrapped in a try: block so ansible fails ungracefully if the correct iam permission is not set on the caller itself.

E.g.

failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-omdpgswcjpemmihbjxsfriyxltacncwz

Traceback (most recent call last):

  File "/home/ec2-user/.ansible/tmp/ansible-tmp-1442208292.85-72883325741064/iam", line 2512, in <module>

```
main()
```

  File "/home/ec2-user/.ansible/tmp/ansible-tmp-1442208292.85-72883325741064/iam", line 576, in main

```
orig_user_list = [ul['user_name'] for ul in iam.get_all_users().
```

  File "/usr/lib/python2.7/site-packages/boto/iam/connection.py", line 337, in get_all_users

```
return self.get_response('ListUsers', params, list_marker='Users')
```

  File "/usr/lib/python2.7/site-packages/boto/iam/connection.py", line 102, in get_response

```
raise self.ResponseError(response.status, response.reason, body)
```

boto.exception.BotoServerError: BotoServerError: 403 Forbidden

<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">

  <Error>

```
<Type>Sender</Type>

<Code>AccessDenied</Code>

<Message>User: arn:aws:sts::019114397287:assumed-role/support-tower/i-f5ee442b is not authorized to perform: iam:ListUsers on resource: arn:aws:iam::019114397287:user/</Message>
```

  </Error>

  <RequestId>ee416bb7-5aa0-11e5-b968-83180be162d5</RequestId>

</ErrorResponse>

**Comment by wimnat** [comment]
PR to fix https://github.com/ansible/ansible-modules-core/pull/2067

Adding @defionscode as module author

**Comment by juliedavila** [comment]
PR Looks good

**Comment by gregdek** [comment]
PR was merged, so closing this one.
