### ISSUE TITLE
add support for routing policy to route53 module

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible-modules-core#207]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7.2
##### Environment:

Ubuntu 14.04
##### Summary:

route53 module does not let you set routing policy. http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html

(Filing on behalf of user).

**Comment by j1n6** [comment]
+1

**Comment by j1n6** [comment]
@jimi-c would you accept PR?

**Comment by bcoca** [comment]
we promise to review it, if you submit it

**Comment by lamielle** [comment]
This would be awesome.  I'd like to update a weighted routing policy with the hosts of number of load balancers.  The number may change over time, so not having to hit the AWS console to update this config is pretty important.

**Comment by tcouper** [comment]
+1

**Comment by fstehle** [comment]
:+1:

**Comment by unixunion** [comment]
+1

**Comment by zimbatm** [comment]
Just a heads up that I'm working on this. I'll be submitting a PR when I have something working. In the mean time, feel free to ping me if you want to help out.

**Comment by zimbatm** [comment]
Okay it's done. The PR also contains changes that improves the module's performance.

**Comment by bennojoy** [comment]
@zimbatm  can you please squash to a singe commit thanks,,,

**Comment by zimbatm** [comment]
@bennojoy I've squashed the first commit so the last commit is all about introducing the routing policies. The previous commits all logical commits that stand on their own and introduce optimisations
