### ISSUE TITLE
Module 'group' failing on OSX

### ISSUE THREAD

**Issue by Grazfather** [ansible/ansible-modules-core#2073]
Simply trying to create a group on a yosemite target:

``` yaml
- name: Create bla group
  group: name="{{ groupname }}" system=yes
```

Fails with an unhandled exception in run_command: https://github.com/ansible/ansible/blob/00b1a2c8651b7a2772cfbaec465c8d03e857402c/lib/ansible/module_utils/basic.py#L1547

Looks like it's because the args include a 'None' for some reason:

```
['/usr/sbin/dseditgroup', '-o', 'create', '-i', None, '-L', 'blagroup']
```

Not sure where the None is coming from, but it looks like 'blagroup' should be there.

**Comment by Grazfather** [comment]
Looks like GID is required when the target is darwin. Docs do not specify this.

**Comment by thudry** [comment]
What version of ansible do you use ?
Because it should be included in 1.9.3 (#1086)

**Comment by Grazfather** [comment]
I'm running 1.9.2, which is the newest on homebrew.

It does indeed look like you fixed it :) How far does homebrew lag behind?

**Comment by Grazfather** [comment]
Installed in homebrew with --HEAD (2.0.0) and it looks good.

Since homebrew is still using a broken version (I'd argue this is pretty important functionality) should we file an issue with homebrew to update the recipe?

**Comment by Grazfather** [comment]
It's on homebrew. Closing.
