### ISSUE TITLE
group_mod does not take **kwargs on darwin

### ISSUE THREAD

**Issue by Grazfather** [ansible/ansible-modules-core#2074]
[Here](https://github.com/renard/ansible-modules-core/blob/67ce4cf416b6b1f21c0d28523e512851a28c1733/system/group.py#L286) we see the darwin `group_mod` implementation, but `group_mod` is called with kwargs [here](https://github.com/ansible/ansible-modules-core/blob/286ef6875aaf7efad96d94cbe546c56030d5e919/system/group.py#L427)

@renard

**Comment by thudry** [comment]
Here you have what's on the ansible repository not renard's 
https://github.com/ansible/ansible-modules-core/blob/devel/system/group.py#L289

**Comment by Grazfather** [comment]
Yeah, was using 2.9.2, fixed in 2.9.3. I'll close this but #2073 is open still... hoping to update the homebrew recipe.

**Comment by Grazfather** [comment]
my `brew` was out of date. newest recipe is 2.9.3.
