### ISSUE TITLE
Add --ssl-ca parameter for login connections in mysql_variables, mysql_user, mysql_db

### ISSUE THREAD

**Issue by joshunger** [ansible/ansible-modules-core#2084]
Currently, mysql_variables, mysql_user, and mysql_db modules don't support SSL connections.  And, they also don't read /etc/my.cnf and !includedirs.  If you have "require ssl" on a mysql account and then try to use this account as the login account, the module will fail with access denied.

Would it be possible to add support for SSL for login by passing --ssl-ca?

This could be implemented by (a) reading existing my.cnf files (and !includedir) (b) adding a parameter or (c) having `config_file` parameter support ssl-\* settings as well as username and password.

You'll also want to look at supporting ssl-cert and ssl-key for client certificates.  Should this issue include these two parameters or be a separate issue?

**Comment by Jmainguy** [comment]
@joshunger See https://github.com/ansible/ansible-modules-core/pull/2447 let me know what you think.

**Comment by Jmainguy** [comment]
@joshunger I believe this can be closed now.

**Comment by Jmainguy** [comment]
@bcoca I think this can be closed.

**Comment by bcoca** [comment]
closing as per above
