### ISSUE TITLE
gce_net dont update existing firewall rule

### ISSUE THREAD

**Issue by bjolivot** [ansible/ansible-modules-core#2111]
#### Issue type

Bug Report
#### Ansible Version

ansible 1.9.3
#### Environnement

 Ubuntu 15.04
#### Summary

Update firewall rule succeed without doing the job
#### Steps to reproduce

$ ansible localhost -i inventory, -m gce_net -a "name=mynet fwname=testrule allowed=tcp:22"

``` sh
 localhost | success >> {
    "allowed": "tcp:22",
    "changed": true,
    "fwname": "testrule",
    "ipv4_range": "172.17.0.0/24",
    "name": "mynet",
    "src_range": null,
    "src_tags": null,
    "state": "present",
    "target_tags": null
 }
```

$ ansible localhost -i inventory, -m gce_net -a "name=mynet fwname=testrule allowed=tcp:25"

``` sh
 localhost | success >> {
    "allowed": "tcp:25",
    "changed": false,
    "fwname": "testrule",
    "ipv4_range": "172.17.0.0/24",
    "name": "mynet",
    "src_range": null,
    "src_tags": null,
    "state": "present",
    "target_tags": null
 }
```
#### Expected result

The rule is not allowing tcp:22 port but tcp:25 (or the task failled)
#### Actual result

 $ gcloud compute firewall-rules describe testrule

``` sh
allowed:
- IPProtocol: tcp
  ports:
 - '22'
creationTimestamp: '2015-09-18T14:54:07.154-07:00'
description: ''
id: '5595550375581137168'
kind: compute#firewall
name: testrule
network: mynet
sourceRanges:
- 0.0.0.0/0
```

**Comment by bcoca** [comment]
cc @erjohnso

**Comment by bjolivot** [comment]
Great ! thank you :)
