### ISSUE TITLE
feature request - delete instance by tag

### ISSUE THREAD

**Issue by hutchic** [ansible/ansible-modules-core#2119]
When developing a teardown playbook the only way to know the ec2 instances you setup is to save them locally.

Alternatives would be either the ability to delete instance(s) by tag or to find instance(s) by tag to register then subsequently delete

**Comment by hutchic** [comment]
~~... or possibly I'm looking for _ec2_facts_~~

ec2_facts will suffice in a pinch but I think my feature request would still be beneficial so leaving this open

**Comment by bcoca** [comment]
if using the ec2 inventory script, you already have instances grouped by tag, so using ansible groups should work.

**Comment by hutchic** [comment]
fair enough
