### ISSUE TITLE
Possibility to use register per item

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#2128]
Hi,
 will it possible to be able to do something like this ?

```
- name: tar.gz ?
  command: file --mime-type -b {{ temp_folder }}/{{ item.url | basename }}
  register: targz_{{ item.app_name }}
  with_items: "{{ applications }}"

- name: Extract application from tar.gz
  command: chdir={{ temp_folder }} tar xvzf {{ temp_folder }}/{{ item.url | basename }} {{ item.path }}
  when: targz_{{ item.app_name }}.stdout == 'application/gzip'
  with_items: "{{ applications }}"

[...] if not a gzip just copy the file
```

notice : i use ansible 1.9.x

**Comment by bcoca** [comment]
# Main Repo Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about an ansible feature, this repo is for ansible core modules.  We would appreciate if you can submit this there instead.
- https://github.com/ansible/ansible

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by ghost** [comment]
In fact its sad that github doesnot own a feature that permits to merge issue from a repo to another, 'cause i never put the issue on the right place.

**Comment by bcoca** [comment]
yes, its something we've been looking at automating on our side, but have not found a good solution, though several exist.

**Comment by ghost** [comment]
I've made an opensource application like ifttt, that reacts on specific events... If you're interested, i can make a try to provide this feature for you. Or you can simply try with ifttt itself. I'm sure it will be able to do that. 
If you tag a ticket it should be able to create the same ticket on the repo of your choice.
