### ISSUE TITLE
new module feature request

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#2129]
Hi,
here is an idea that could help : 

```
- name: 
  copy_or_extract: mimetype={{ my_mime_type }} src=/path/to/{{ my_file }} dest=/home/foxmask/ansible/
```

`mimetype` could be one of the compressed format 
if `mimetype` is not provided : just copy `src` to `dest`
otherwise uncompress `my_file` from `src` to `dest`

**Comment by Jmainguy** [comment]
@foxmask so a feature to add to the copy module

mimetype:

when mimetype specified, copy compressed file to remote server, then uncompress to dest on remote server. 

Sounds about right?  How many compression methods should we support, bzip,gzip,zip,tar, anything else?

**Comment by ghost** [comment]
Idont know, but If it is not to your taste close this issue

**Comment by Jmainguy** [comment]
@foxmask your request makes alot of sense, I just wanted to make sure I was capturing it right. I think this would work great with the copy module as a feature to add on there. Would that be ok with you? And if so, are those 4 compression methods enough, or would you want to see more?

**Comment by ghost** [comment]
OK, so, May be a last one : 7zip

**Comment by Jmainguy** [comment]
ack, I will work on adding 7zip and the others to the copy module, will ping you when I have something to test

**Comment by ghost** [comment]
Fine, i.'ll be glad to test.

**Comment by jctanner** [comment]
This seems to be describing the unarchive module http://docs.ansible.com/ansible/unarchive_module.html
