### ISSUE TITLE
It is not possible to create a new keystone user with a role

### ISSUE THREAD

**Issue by berendt** [ansible/ansible-modules-core#213]
##### Issue Type:

Bug Report
##### Component Name:

keystone_user
##### Ansible Version:

ansible 1.7.1
##### Environment:

openSUSE 13.1
##### Summary:

It is not possible to create a new Keystone user with a role. The following task will fail.
##### Steps To Reproduce:

```
- keystone_user: user=nova tenant=service password=password role=admin
                 login_password=password login_tenant_name=admin login_user=admin
```
##### Expected Results:

At new user 'nova' with the tenant'service' and the user-role 'nova-service-admin'.
##### Actual Results:

```
msg: exception: 'No keystone users with name glance'
```

At the moment it is necessary to first create the new user. Afterwards it is possible to assign the role.

```
- keystone_user: user=nova tenant=service password=password
                 login_password=password login_tenant_name=admin login_user=admin
- keystone_user: user=nova tenant=service role=admin
                 login_password=password login_tenant_name=admin login_user=admin
```

**Comment by jimi-c** [comment]
@berendt you say this is with a role, but do the above examples work outside of a role?

**Comment by jimi-c** [comment]
cc @emonty

**Comment by emonty** [comment]
@jimi-c I believe he's referring to keystone roles - WOE to the world of same words meaning different things. Totally agre, this needs to be fixed. The current PR for it, however, is aiming at the old openstack structure. I'll work with @berendt to make sure we get this functionality into the new modules.

**Comment by jctanner** [comment]
ping @emonty and @berendt can you re-evaluate this?

**Comment by Shrews** [comment]
This can be performed with the newer os_user and os_user_role modules.
