### ISSUE TITLE
ec2_vpc_net not using EC2_REGION environment variable

### ISSUE THREAD

**Issue by jbrockett** [ansible/ansible-modules-core#2132]
## Issue Type:

Bug Report
## Ansible Version:

ansible 1.9.3
## Ansible Configuration:

ansible 1.9.3 installed via pip, but using the ec2_vpc_net module in my library directory as it only comes with ansible v2.
## Environment:

Mac OS X 10.10
## Summary:

I have the environment variable EC2_REGION set to us-east-1 and am not specifying the region key to the ec2_vpc_net module.  It should pickup the value of this environment variable and use it as the region parameter.
## Expected Results & Actual Results:

I expect that the ec2_vpc_net module should create a vpc without having to specify the region parameter as long as I have EC2_REGION set in my environment variables.

The actual result is that I have to specify the region parameter to the ec2_vpc_net module in order for it to create the vpc.  If I only have the EC2_REGION environment variable set, I get the following error:

TASK: [ec2 | create vpc and subnets] ******************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: missing required arguments: region

FATAL: all hosts have already failed -- aborting

I ran the ec2_vpc module without specifying region and it picked up the environment variable properly.

**Comment by Constantin07** [comment]
Have you tried to use the AWS_DEFAULT_REGION env. variable instead?

**Comment by jbrockett** [comment]
I tried it with AWS_DEFAULT_REGION and it didn't work either.  I am also able to use the ec2_vpc_igw, ec2_vpc_subnet and ec2_vpc_route_table modules using the EC2_REGION environment variable without issue.  Only the ec2_vpc_net module has this issue.

**Comment by wimnat** [comment]
Are you using the latest module from devel?  There was a change to how the module connects to aws in commit 786ec1dca156323a2ce83ba3bbe507d85ba22840

**Comment by wimnat** [comment]
@jbrockett did you get a chance to test the latest version?

**Comment by jbrockett** [comment]
I apologize for the delay.  I just tested this with the most recent version and everything is working properly now.  Thanks!
