### ISSUE TITLE
win_get_url with force=no appears broken.

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible-modules-core#2146]
##### Ansible Version:

ansible 1.9.1
  configured module search path = /etc/ansible/library

 (but likely same problem with 2.0 dev)
##### Ansible Configuration:

Probably not relevant
##### Environment:

controller: Centos 6.5
target: windows 
##### Summary:

Fails if file already exists.

This line is the cause of the immediate failure:
$stream = New-Object System.IO.StreamReader($response.GetResponseStream())

There is no variable called $response, it should probably be $webResponse.

I think this is because the code has been copied verbatim from this stackoverflow answer, which also has the same bug: http://stackoverflow.com/questions/26533819/how-can-i-download-a-file-only-if-it-has-changed-using-powershell

Second problem is that it doesn't actually work, at least for downloading binary files.

I think the code needs to change to request the headers and then compare the date of the last-modified header with the file last modified.

If the source date time is older than the file modified then I think it should fetch the file using the same $client.DownloadFile call - if you use on a zip file, the following lines create a corrupted zip file which is a different size from the file fetched with  $client.DownloadFile
##### Steps To Reproduce:

download a zip file using win_get_url
download the same file again.
##### Expected Results:

1st run: changed should be set to true
2nd and subsequent runs: changed should be set to false
##### Actual Results:

1st run is successful.
2nd run fails with 
"You cannot call a method on a null-valued expression."

**Comment by jhawkesworth** [comment]
Functional but messy and full of copy - and - paste code below that runs on 1.9.1.  needs some of the mess in comments removing and the download logic moving to a function so it isn't repeated twice.  Also not entirely convinced the date comparison logic is correct yet.

@talcloudshare - are you in a position to fix this up?

**Comment by jhawkesworth** [comment]
``` powershell
# WANT_JSON
# POWERSHELL_COMMON

$params = Parse-Args $args;

$result = New-Object psobject @{
    win_get_url = New-Object psobject
    changed = $false
}

If ($params.url) {
    $url = $params.url
}
Else {
    Fail-Json $result "mising required argument: url"
}

If ($params.dest) {
    $dest = $params.dest
}
Else {
    Fail-Json $result "missing required argument: dest"
}

$skip_certificate_validation = Get-Attr $params "skip_certificate_validation" $false | ConvertTo-Bool
$username = Get-Attr $params "username"
$password = Get-Attr $params "password"

if($skip_certificate_validation){
  [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
}

$force = Get-Attr -obj $params -name "force" "yes" | ConvertTo-Bool

If ($force -or -not (Test-Path $dest)) {
    $client = New-Object System.Net.WebClient

    if($username -and $password){
        $client.Credentials = New-Object System.Net.NetworkCredential($username, $password)
    }

    Try {
        $client.DownloadFile($url, $dest)
        $result.changed = $true
    }
    Catch {
        Fail-Json $result "Error downloading $url to $dest $($_.Exception.Message)"
    }
}
Else {
    Try {
        $webRequest = [System.Net.HttpWebRequest]::Create($url)

        if($username -and $password){
            $webRequest.Credentials = New-Object System.Net.NetworkCredential($username, $password)
        }

        $fileLastMod = ([System.IO.FileInfo]$dest).LastWriteTimeUtc

        #write-host "the file was last written to on: $fileLastMod"

        $webRequest.Method = "HEAD"
        [System.Net.HttpWebResponse]$webResponse = $webRequest.GetResponse()

        #write-host "outside FORCE: after get response"
        $webLastMod = $webResponse.GetResponseHeader("Last-Modified")

        #write-host " was last modded on " + $webLastMod

        $webResponse.Close()

        If ((Get-Date -Date $webLastMod ) -lt $fileLastMod) {
           # don't download
           $result.changed = $false
        } Else {
         # DO download

            $client = New-Object System.Net.WebClient
            if($username -and $password){
                $client.Credentials = New-Object System.Net.NetworkCredential($username, $password)
            }
            Try {
                $client.DownloadFile($url, $dest)
                $result.changed = $true
            }
            Catch {
                Fail-Json $result "1 Error downloading $url to $dest $($_.Exception.Message)"
            }
        }
    }
    Catch [System.Net.WebException] {
        If ($_.Exception.Response.StatusCode -eq [System.Net.HttpStatusCode]::NotModified) {
            $result.changed = $false
        }
        Else {
            Fail-Json $result "Error downloading $url to $dest $($_.Exception.Message)"
        }
    }
    Catch {
        Fail-Json $result "Error downloading $url to $dest $($_.Exception.Message)"
    }
}

Set-Attr $result.win_get_url "url" $url
Set-Attr $result.win_get_url "dest" $dest

Exit-Json $result;
```

**Comment by talcloudshare** [comment]
Sorry for the inconvenience. I just got back from a long vacation, so it'll take me some time to finish other tasks that came in while I was gone. Will try to take care of that in my spare time this week, no guarantees.

**Comment by jhawkesworth** [comment]
Thanks for picking this up.
Hopefully the above will help you get started.  I needed to get something functioning but code needs to have redundancy removed.  Probably orth saying I've not tried above with v2 yet.

**Comment by jhawkesworth** [comment]
for info https://github.com/ansible/ansible-modules-core/pull/2644

**Comment by jhawkesworth** [comment]
I have pushed https://github.com/ansible/ansible-modules-core/pull/3273 to fix the issues described here
