### ISSUE TITLE
win_file failing with $fileinfo.Directory property not existing on directory creation.

### ISSUE THREAD

**Issue by ccelebi** [ansible/ansible-modules-core#2147]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0 (devel 24b9e2e6d1) last updated 2015/09/24 10:23:50 (GMT -400)
  lib/ansible/modules/core: (detached HEAD e8227dea7a) last updated 2015/09/24 10:23:57 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD f2faf70996) last updated 2015/09/24 10:23:57 (GMT -400)
  config file = /Users/ccelebi/ansible/ansible.cfg
  configured module search path = None
```
##### Ansible Configuration:

```
host_key_checking=true
```
##### Environment:

running on OSX, virtualenv for python and managing windows with powershell v4.

```
> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```
##### Summary:

Trying to create a directory on a windows machine using core module win_file. When manually run on the windows host I do not see the object property .Directory. As stated in the code, only files have a .Directory property.
##### Steps To Reproduce:

Task below:

```
- name: Create temp directory
  win_file:
      path=C:/temp
      state=directory
```

or 

```
- name: Create temp directory
  win_file:
      path=C:\\temp
      state=directory
```

results in the error message:

```
+         If ( $state -eq "directory" -and $fileinfo.Directory )
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "failed": true, "msg": "The property 'Directory' cannot be found on this object. Verify that the property exists."}
```

I verified this on the windows host with the following: 

```
PS C:\Users\Administrator> $fileinfo = Get-Item C:\temp

PS C:\Users\Administrator> Get-ItemProperty -Path $fileinfo | Format-list -Property * -Force

PSPath            : Microsoft.PowerShell.Core\FileSystem::C:\temp
PSParentPath      : Microsoft.PowerShell.Core\FileSystem::C:\
PSChildName       : temp
PSDrive           : C
PSProvider        : Microsoft.PowerShell.Core\FileSystem
BaseName          : temp
Mode              : d----
Name              : temp
Parent            :
Exists            : True
Root              : C:\
FullName          : C:\temp
Extension         :
CreationTime      : 9/24/2015 11:19:17 AM
CreationTimeUtc   : 9/24/2015 3:19:17 PM
LastAccessTime    : 9/24/2015 11:19:17 AM
LastAccessTimeUtc : 9/24/2015 3:19:17 PM
LastWriteTime     : 9/24/2015 11:19:17 AM
LastWriteTimeUtc  : 9/24/2015 3:19:17 PM
Attributes        : Directory
```
##### Expected Results:

Directory should be created 
##### Actual Results:

Playbook run fails due to the powershell failing on directory creation.

Fails on looking for a directory property on a path that is a directory and not a file. The logic doesn't continue on to the logic to handle the directory creation.

```
+         If ( $state -eq "directory" -and $fileinfo.Directory )
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: [10.1.10.102]: FAILED! => {"changed": false, "failed": true, "msg": "The property 'Directory' cannot be found on this object. Verify that the property exists."}

```

Code:

```
If ( $state -eq "directory" -and $fileinfo.Directory )
        {
            Fail-Json (New-Object psobject) "path is not a directory"
        }
```

**Comment by ccelebi** [comment]
Disregard, apparently utilizing \\ works in this case. I apologize for not testing other methods as the same doesn't apply to win_template.

**Comment by ccelebi** [comment]
Strangely this doesn't handle existing directories very well as it considers it to be a file object and can't find a Directory property.

**Comment by jhawkesworth** [comment]
Ok.  I think we should document that you need a trailing  \  for use with directory, its not necessarily obvious that c: \ temp could either be a file name or a directory name.

Please can you provide an example play that demonstrates the second problem you describe with 'not handling existing directories very well'.  I have plays that both add and remove directories so want to see a specific example so I can reproduce what you are seeing.

Many thanks,

Jon

**Comment by ccelebi** [comment]
Sure. The directory does exist on the remote system as I've run this playbook to converge these systems.

Sorry I forgot to provide the successful first run which constructs the directory, I'll provide that once this build is done.

The role:

```
---

- name: Create temp directory for prf
  win_file:
      path=C:\\temp
      state=directory

- name: Setting up Outlook email PRF
  win_template:
      src=outlook_imap.prf.j2
      dest=C:\\temp\\outlook.prf
```

And the task execution:

```
TASK [mnb-setup : Create temp directory for prf] *******************************
<xxx.xxx.xxx.xxx> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO xxx.xxx.xxx.xxx
<xxx.xxx.xxx.xxx> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1443475145.96-116776178340718").FullName | Write-Host -Separator '';
<xxx.xxx.xxx.xxx> PUT "/var/folders/6r/70vp6md93px82csgmxc873300000gp/T/tmpBEnctL" TO "C:\Users\barkly\AppData\Local\Temp\ansible-tmp-1443475145.96-116776178340718\win_file"
<xxx.xxx.xxx.xxx> EXEC Set-StrictMode -Version Latest
Try
{
& "C:\Users\admin\AppData\Local\Temp\ansible-tmp-1443475145.96-116776178340718\win_file.ps1"
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\admin\AppData\Local\Temp\ansible-tmp-1443475145.96-116776178340718" -Force -Recurse -ErrorAction SilentlyContinue }
An exception occurred during task execution. The full traceback is:
At C:\Users\admin\AppData\Local\Temp\ansible-tmp-1443475145.96-116776178340718\win_file.ps1:275 char:14
+         If ( $state -eq "directory" -and $fileinfo.Directory )
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "failed": true, "msg": "The property 'Directory' cannot be found on this object. Verify that the property exists."}
```

I can pull the powershell script that is constructed and provide that if needed.

**Comment by marcind** [comment]
We're running into the same problem. The issue is that the current script just plain does not work in PowerShell 4 when you are trying to create directories (regardless of whether the path ends with a slash or not).

We worked around this by modifying the code to do the following

```
If ( $state -eq "directory" -and -not $fileinfo.PsIsContainer)
{
   Fail-Json (New-Object psobject) "path is not a directory"
}

If ( $state -eq "file" -and $fileinfo.PsIsContainer)
{
   Fail-Json (New-Object psobject) "path is not a file"
}
```

We are running in PowerShell 4. Not tested in PowerShell 3

**Comment by jhawkesworth** [comment]
Just to say I'm working on this.  Fix above looks viable but I will add integration tests (if the test I'm running now doesn't break any existing tests).

**Comment by jhawkesworth** [comment]
So... fix described above seems to work fine on PS4 but I have created some extra integration tests and have found a problem with creating directories using powershell 3.0.

**Comment by jhawkesworth** [comment]
So... fix described above seems to work fine on PS4 but I have created some extra integration tests and have found a problem with creating directories using powershell 3.0.

**Comment by jhawkesworth** [comment]
My mistake, have now verified it is working against powershell 3.0 and 4.0.

**Comment by jhawkesworth** [comment]
@ccelebi can this be closed now, https://github.com/ansible/ansible-modules-core/pull/2256 has been merged which should fix.  Can you verify?  Many thanks,  Jon

**Comment by ccelebi** [comment]
Will verify. Sorry to not have responded.

**Comment by ccelebi** [comment]
Looks good! Sweet, thanks!

changed: [XXXX] => {"changed": true, "invocation": {"module_args": {"path": "C:\temp", "state": "directory"}, "module_name": "win_file"}}

**Comment by jhawkesworth** [comment]
thanks for closing this off @ccelebi
