### ISSUE TITLE
Synchronize module asking for a password during playbook run

### ISSUE THREAD

**Issue by dbohdan** [ansible/ansible-modules-core#2156]
(Reposing from https://github.com/ansible/ansible/issues/7071. All credit for the report goes to @IronTetsubo.)
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

RHEL 5 & 6
##### Summary:

When using the synchronize module, it prompts for a password, then fails to synchronize.
##### Steps To Reproduce:

https://gist.github.com/IronTetsubo/11071900 - this includes the playbook, the command used to execute, and the -vvvv output of the run.
##### Expected Results:

Synchronize/Rsync works using the password supplied when running the playbook.
##### Actual Results:

see https://gist.github.com/IronTetsubo/11071900 - rsync attempts to ask for the password via stdout, then fails when it doesn't get it.

From my cursory understanding of the synchronize code/rsync command, this seems to be because synchronize assumes you're using public key authentication, and doesn't support password auth. if this is true (and intended, for whatever reason), it'd be nice to note that in the module docs. From the rsync man page:

```
   Some  modules  on the remote daemon may require authentication. If so, you will receive a password prompt when you connect. You can avoid the password prompt by setting the environment variable RSYNC_PASSWORD to the password
   you want to use or using the --password-file option. This may be useful when scripting rsync.
```

This might be a dup of https://github.com/ansible/ansible/issues/5934.

**Comment by dbohdan** [comment]
If you're looking for a solution right now take a look at http://stackoverflow.com/q/24763343/3142963.

**Comment by robynbergeron** [comment]
Hi @dbohdan -- thanks for filing this report, and to @irontetsubo as well for the background and investigation :)

@ansible/core -- pinging you to bring this bug report to your attention. I believe this is for the files/synchronize.py module in core and not the action plugin ... if they are magically related somehow beyond my knowledge and this issue needs to be redirected to ansible/ansible then please let @dbohdan know :)

Thanks, everyone!

**Comment by robynbergeron** [comment]
[module: files/synchronize.py]

**Comment by crane-denny** [comment]
Having the same issue

```
ansible 2.0.0 (devel 82b9af22fd) last updated 2015/11/27 19:02:09 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 0e043f8c58) last updated 2015/11/27 19:02:24 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD e46e2e1d6f) last updated 2015/11/27 19:02:38 (GMT +200)
```

**Comment by akrylysov** [comment]
The same issue on 2.0.0.1:

```
FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

Works good on 1.9.4.

**Comment by pwaring** [comment]
I've just upgraded Ansible to 2.0.0.1 (and 2.0.0.2) and I'm getting the same error message:

```
TASK [synchronize default vhost] ***********************************************
fatal: [davros]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

This seems to be a regression, as the same task worked fine before upgrading Ansible.

Is there anything I can do to help fix this bug? It's a major issue for me as I use synchronize to update half a dozen static sites.

**Comment by llob** [comment]
This is biting me as well. 
Tasks working without problem in 1.9.x are now prompting me for a password.

**Comment by yauh** [comment]
We're also running into this issue (paired with the `ppa` limitation of not being able to downgrade to 1.9.4 easily it took longer than I had hoped to work around). I assume many people are affected by this regression, @robynbergeron and @ansible/core do you have any plans to address it in the (hopefully) next release?

**Comment by opetrovskyi** [comment]
asking password is normal behave according to the synchronize module's Notes
"The user and permissions for the synchronize src are those of the user running the Ansible task on the local host, or the become_user if become: yes is active. synchronize will attempt to escalate privileges to the become_user on the local host."  Set "become = false" to skip escalation of privileges at localhost and use this if you want to sync to folder with specific ownership
rsync_path:
      - "sudo rsync"

as for me there is another problem after upgrade -  it does not synchronize local and remote folders. 
at debug msg after register there are no  key_file specified and no remote "user@"  part near destination folder. part of debug msg with cmd:
u'cmd': u:'rsync --delay-updates -F --compress --archive --rsh \'ssh  -S none -o StrictHostKeyChecking=no -o Port=2222\' --rsync-path=\"[u\'sudo rsync\']\" --exclude=.git\* --verbose --out-format=\'<<CHANGED>>%i %n%L\' \"/home/localhost/backend/\" \"/var/www/desthost/releases\ "'

if i set a remote folder as existing folder at localhost  the task sync between this folders.
PS here is a task itself
- name: Upload project
  become: false
  synchronize:
    src: "{{ project_folder }}/"
    dest: "{{project_root}}/releases/{{project_release}}"
    rsync_opts:
      - "--exclude=.git*"
      - "--verbose"
    rsync_path:
      - "sudo rsync"

PPS: a few days after i faced this  strange behave i had tried to use synchronize with separate remote server and it works fine. but the problem still exist while i use it with vagrant at local machine.

**Comment by pwaring** [comment]
Is there anything we can do to help fix this bug? Unfortunately my Python knowledge isn't sufficient to hack on the code, but I'm happy to test out any proposed patches to see if they fix the problem.

**Comment by abadger** [comment]
There's several different issues being reported here.  Some of which have
fixes that need testing and others that do not sure to the way that
synchronize uses rsync.

The original reporter of this bug is experiencing a problem with sudo and
passwords.  In the -vvvv output you can see that sudo is the one giving the
error and requiring a tty to continue.  This issue has yet to be resolved.
Only passwordless sudo is working as a privilege escalation method with
synchronize at the moment.  This is a tough nut to crack (we have to both
address passwords for privilege escalation and other methods of privilege
escalation besides sudo).

Many people coming here recently have a different problem: that synchronize
in 2.0.0.(0,1,2) is requesting an ssh password when using rsync.  If this
is happening for you on 2.0.0.x but not in 1.9.x then you should look at
this bug:
https://github.com/ansible/ansible/issues/13825 and the branch linked from
there.  2.0.0.x's synchronize ran sudo on the originating host rather than
the destination host which meant it was looking for credentials on the root
user account rather than the normal user account.  We're working on and
testing the branch on that other bug report with the aim of getting the fix
into 2.0.1 (the next bugfix release).

Additional help testing that branch is appreciated.

**Comment by pwaring** [comment]
I didn't realise there was another issue - thanks for the pointer. The suggested solution in 13825 fixed the problem for me (in case anyone else comes across this bug).

**Comment by cescox** [comment]
Same issue here on:
OSX 10.11 (as local)
Google Cloud Engine VM (as remote)

An output here

```
TASK [ansible-odoo : Syncronize local folder to remote server '/home/odoo/odoo' path] ***
task path: /Users/my-username/Code/project-pip/tasks/web/roles/ansible-odoo/tasks/deploy.yml:3
ESTABLISH LOCAL CONNECTION FOR USER: my-username
104.155.xx.xx EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1454112098.6-100072182751939 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1454112098.6-100072182751939 )" )
104.155.xx.xx PUT /var/folders/z3/cyqlc7px569586p0qq_xbyl00000gq/T/tmpOELbF6 TO /Users/my-username/.ansible/tmp/ansible-tmp-1454112098.6-100072182751939/synchronize
104.155.xx.xx EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-uffnoibmmlaombdxqhycwiokosxrprej; LANG=en_US.utf-8 LC_ALL=en_US.utf-8 LC_MESSAGES=en_US.utf-8 /usr/bin/python /Users/my-username/.ansible/tmp/ansible-tmp-1454112098.6-100072182751939/synchronize; rm -rf "/Users/my-username/.ansible/tmp/ansible-tmp-1454112098.6-100072182751939/" > /dev/null 2>&1'"'"''
fatal: [104.155.xx.xx]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"_local_rsync_path": "rsync", "delete": true, "dest": "project-deployer@104.155.xx.xx:/home/odoo/odoo", "perms": true, "recursive": true, "rsync_opts": ["--exclude=.*", "--exclude=tmp'", "--exclude=venv*'", "--exclude=virt*'"], "rsync_path": "\"sudo rsync\"", "src": "/Users/my-username/Code/project-pip/tasks/web/roles/ansible-odoo/tasks"}, "module_name": "synchronize"}, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

PLAY RECAP *********************************************************************
104.155.xx.xx              : ok=10   changed=0    unreachable=0    failed=1`
```

**Comment by bushev** [comment]
I need to sync ~10 folders. And I must type a password 10 times? Copying works very slow, ~20 minutes for ~200 files.

May be you know any other work around?

**Comment by opetrovskyi** [comment]
try ansible 2.0.1.0. issue with rsync with 127.0.0.1 as recipient host is fixed.

**Comment by gvenka008c** [comment]
@here, I am seeing the same error while using ansible-pull as well. Any work arounds?

```
ESTABLISH LOCAL CONNECTION FOR USER: gvenka008c
xx.xxx.xx.x EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1458321852.2-131365816314280 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1458321852.2-131365816314280 )" )
xx.xxx.xx.x PUT /var/folders/kh/q0lj3nhn0s5gwh4yv41klb5r_2w2f4/T/tmpjDpxYM TO /Users/gvenka008c/.ansible/tmp/ansible-tmp-1458321852.2-131365816314280/setup
xx.xxx.xx.x EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-wwgpoieteincbwkoettzgwxqdgazyosj; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/gvenka008c/.ansible/tmp/ansible-tmp-1458321852.2-131365816314280/setup; rm -rf "/Users/gvenka008c/.ansible/tmp/ansible-tmp-1458321852.2-131365816314280/" > /dev/null 2>&1'"'"''
fatal: [xx.xxx.xx.x]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "setup"}, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by makmanalp** [comment]
Can confirm that ansible 2.0.1.0 fixed the issue for me.

**Comment by gregdek** [comment]
Thanks @makmanalp -- closing as fixed.
