### ISSUE TITLE
mysql-client package required when using mysql_db & state=import

### ISSUE THREAD

**Issue by Mazo** [ansible/ansible-modules-core#2164]
**Issue Type:** Bug Report
**Ansible Version:**1.7.2
**Environment:** Debian 8.2 (jessie)
**Summary:**The ansible docs at http://docs.ansible.com/ansible/mysql_db_module.html mention that the MySQLdb Python package is required for that module, however it seems that when using state=import the mysql-client package is also required.
**Steps To Reproduce:**
    - name: Import tables.sql into mysql
      mysql_db:
        name: "{{db_name}}"
        login_password: "{{db_password}}"
        login_user: "{{db_user}}"
        login_host: 192.168.1.201
        state: import
        target: /tmp/tables.sql

**Expected Results:**Command completes and sql file is imported
**Actual Results:**
    msg: Failed to find required executable mysql

**Comment by robynbergeron** [comment]
[module: database/mysql/mysql_db.py]

**Comment by robynbergeron** [comment]
Hi @Mazo -- thanks for submitting this bug report.

@marktheunissen -- pinging you to bring this bug report for the mysql_db module to your attention. Thanks in advance for taking a look at this and for your ongoing work in maintaining this module.

**Comment by marktheunissen** [comment]
@robynbergeron I am not the maintainer of this module. There is a difference between maintainer and copyright holder.

**Comment by Jmainguy** [comment]
@robynbergeron @Mazo please see #2365  and let me know what you think. There is definitely a requirement for the mysql command in this module.

**Comment by Jmainguy** [comment]
Can this be closed now, looks like #2365 got merged.
