### ISSUE TITLE
Bug report - win_copy fails to copy an empty file

### ISSUE THREAD

**Issue by wimnat** [ansible/ansible-modules-core#2165]
Version: 1.9.2

Summary: When using win_copy to copy an empty file, the module reports changed but no empty file is created on the target

Steps to reproduce: Create an empty file on the Ansible server and then use win_copy module to copy it to a target Windows machine.  My target was Windows Server 2012.

Expected result: An empty file is created on the target

Actual result: The module reports changed but the empty file is not present on the target

@jhawkesworth mention as module author

**Comment by cchurch** [comment]
This is really an issue in the winrm connection plugin, and it has been fixed in devel via https://github.com/ansible/ansible/commit/43b15ab9a4c668f06b967213529d3d4637423303

I've submitted https://github.com/ansible/ansible/pull/12566 to address this issue in 1.9.x.

**Comment by jhawkesworth** [comment]
Thanks for picking this up and fixing @cchurch
