### ISSUE TITLE
vsphere_guest module: Adding/deleting NIC on a existing VM does not work

### ISSUE THREAD

**Issue by lenfree** [ansible/ansible-modules-core#218]
Issue Type:

Bug Report

Ansible Version:

ansible >= 1.6

Summary:
vm_nic option in vsphere_guest does not reconfigure the networks of an existing VM. NIC can only be created during VM provisioning but can't be deleted or modified.

**Comment by aioue** [comment]
Proposed documentation fix until full reconfigure functionality is added to the module.
https://github.com/ansible/ansible-modules-core/pull/1403

**Comment by chrrrles** [comment]
Should be addressed by: https://github.com/ansible/ansible-modules-core/pull/2409
