### ISSUE TITLE
Mount fails if ansible user has no read permission inside mount

### ISSUE THREAD

**Issue by robinro** [ansible/ansible-modules-core#2186]
##### Summary:

A bug in python os.path makes the mount module fail when
- state=mounted
- filesystem: nfs (probably most others as well)
- the mount is already present
- the ansible user has no read permission inside the mount

The reason for this is that ansible uses os.path.ismount(mountpath) which fails if pointed at a mount inside which the user has no read permission, see http://bugs.python.org/issue2466.
This is quite common if you use nfs with root_squash or kerberos.

The python-bug is quite old and unfixed, so maybe it's worthwhile to have a workaround in ansible. The function in question is 10 lines of python.
##### Steps To Reproduce:

See Summary
##### Expected Results:

Should return 'ok'
##### Actual Results:

returns failed

**Comment by robynbergeron** [comment]
[module: system/mount.py]

**Comment by robynbergeron** [comment]
Hi @robinro -- thanks for submitting this bug report.

@ansible/core team -- pinging you to bring this bug report to your attention.

**Comment by robinro** [comment]
Python is rather slow in merging this. Is it an option to put the fixed version of os.path.ismount directly in ansible and use it for all python versions where this is broken?

**Comment by bcoca** [comment]
@robinro submit a PR

**Comment by robinro** [comment]
@bcoca @robynbergeron any update on merging this?

**Comment by robinro** [comment]
This is actually not yet fixed as #2737 also has to be merged. I probably triggered this mistakenly by the description in https://github.com/ansible/ansible/issues/14374
