### ISSUE TITLE
EC2 Instance Provisioning fails with Instance tagging failed => InvalidInstanceID.NotFound

### ISSUE THREAD

**Issue by mgarren** [ansible/ansible-modules-core#2191]
Provisioning multiple ansible instances (I didn't use with_items, just the same role a bunch of times with different parameters) fails saying that it cannot find the instance id's that were created.  I verified that the instances did successfully create and showed in our EC2 Console.

It looks like there are other similar issues (7906, 9918), but they are for older versions and/or have been closed.

Ansible version: 1.9.2
OS: Red Hat 7.1

**Comment by jimi-c** [comment]
Hi @mgarren, did you specify the wait=yes parameter? If not, could you please provide additional information about your playbook to help reproduce this?

**Comment by mgarren** [comment]
@jimi-c, thanks for the response.  I have not seen the issue in a while (I was using wait=yes), so I guess I'll chalk it up to a timing issue that has sense worked itself out.  At the moment I would be unable to reproduce.  Even at the time, it only happened ocasionally.

Matt

**Comment by jimi-c** [comment]
Ok, thanks for the follow-up!
