### ISSUE TITLE
scp/sftp PUT failes

### ISSUE THREAD

**Issue by ramelito** [ansible/ansible-modules-core#2195]
```
<meteorolog> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/ansi/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ramelito -o ConnectTimeout=10 meteorolog /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1443876262.55-7774777153857 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1443876262.55-7774777153857 && echo $HOME/.ansible/tmp/ansible-tmp-1443876262.55-7774777153857'
<meteorolog> PUT /tmp/tmpUTzB5L TO /home/ramelito/.ansible/tmp/ansible-tmp-1443876262.55-7774777153857/apt
fatal: [meteorolog] => ERROR! failed to transfer file to /home/ramelito/.ansible/tmp/ansible-tmp-1443876262.55-7774777153857/apt:

lost connection


FATAL: all hosts have already failed -- aborting
```

version ansible-playbook 1.9.3 (detached HEAD d444ab507e)
remote OS - cubieboard:~# uname -a 
Linux cubieboard 3.4.79 #2 PREEMPT Sat Nov 15 14:20:48 CST 2014 armv7l GNU/Linux
cat /etc/issue.net 
Debian GNU/Linux 7

manual scp/sftp is working fine

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
