### ISSUE TITLE
ec2 module: throws error on instance status change

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible-modules-core#2205]
##### Issue Type:

Bug.
##### Ansible Version:

ansible-1.9.2-1.el7.noarch
##### Ansible Configuration:

```
- name: Change the status of instance(s)
  ec2:
    region: "{{ aws_region }}"
    instance_ids: "{{ instance_ids }}"
    state: "{{ state }}"
    source_dest_check: yes
    wait: yes
  register: ec2_res
  when: instance_ids != "[]"
  tags: startstop
```
##### Environment:

CentOS 7. Ansible installed from EPEL repo with the latest "ec2.py" module from development branch (commit 1857263b63e56feecf820b7990b7bffebfef14aa).
##### Summary:

The start/stop of instance fails with an error: NameError: global name 'source_dest_check' is not defined
##### Steps To Reproduce:
1. Launch an EC2 instance in AWS.
2. Run the above playbook to stop (or start a stopped) instance.
##### Expected Results:

The instance should be stopped or started.
##### Actual Results:

```
TASK: [startstop | Change the status of instance(s)] **************************
<127.0.0.1> REMOTE_MODULE ec2 instance_ids=i-1632c1b4 state=running region=us-east-1
failed: [127.0.0.1] => (item=i-1632c1b4) => {"failed": true, "item": "i-1632c1b4", "parsed": false}
Traceback (most recent call last):
  File "/home/Mgmt/.ansible/tmp/ansible-tmp-1444044960.88-103455925405949/ec2", line 3203, in <module>
    main()
  File "/home/Mgmt/.ansible/tmp/ansible-tmp-1444044960.88-103455925405949/ec2", line 1381, in main
    (changed, instance_dict_array, new_instance_ids) = startstop_instances(module, ec2, instance_ids, state, instance_tags)
  File "/home/Mgmt/.ansible/tmp/ansible-tmp-1444044960.88-103455925405949/ec2", line 1253, in startstop_instances
    if inst.get_attribute('sourceDestCheck')['sourceDestCheck'] != source_dest_check:
NameError: global name 'source_dest_check' is not defined

FATAL: all hosts have already failed -- aborting
```

Thanks,
Constantin

**Comment by fperks** [comment]
This is a really frusturating bug for me. But it is relatively simple to fix.

The issue appears in v2.0.0-0.3.beta1 for me. 

https://github.com/fperks/ansible-modules-core/commit/cc6a3a7786cb959f56005465f4edd73aaba4b91a

I don't really know how PR's are done here. But this is all i had to change to fix it and make it work properly.

**Comment by evanccnyc** [comment]
@fperks you should be able to generate a pull request by following the instructions are here https://help.github.com/articles/creating-a-pull-request/ (use the devel branch here) and then it will automatically be added for review.

**Comment by fperks** [comment]
@evanccnyc Thanks i opened a PR for the issue.

**Comment by Constantin07** [comment]
Thanks @fperks. Just tested and it works fine.
