### ISSUE TITLE
pip module's chdir option does not expand ~/tilde correctly

### ISSUE THREAD

**Issue by ktaragorn** [ansible/ansible-modules-core#2224]
If i give `chdir=/home/ubuntu/app` it works but giving `chdir=~/app` doesnt seem to work.

After some digging it is because of the code joining this option with the temp directory

```
        this_dir = tempfile.gettempdir()
        if chdir:
            this_dir = os.path.join(this_dir, chdir)
```

From simple testing, this method doesnt work for ~ but it works for absolute paths

```
In [8]: os.path.join("/tmp", "~/bin")
Out[8]: '/tmp/~/bin'

In [9]: os.path.join("/tmp", "/bin")
Out[9]: '/bin'
```

This probably can be fixed instead of documenting.. I dont see why anybody would like to `chdir` relative to the temp directory in `pip`.

From [stackoverflow](http://stackoverflow.com/a/2057072/1520364) the best way to keep old behavior but fix case of tilde might be to do below

```
In [12]: os.path.join("/tmp", os.path.expanduser("~/bin"))
Out[12]: '/Users/karthikt/bin'
```

Moved from https://github.com/ansible/ansible/issues/12658

**Comment by bcoca** [comment]
fixed via 8c353d051668110417fd5b1b6d8dc50ea41cd333
