### ISSUE TITLE
nics parameter in os_servers module should not be fixed to 'list' type

### ISSUE THREAD

**Issue by dagnello** [ansible/ansible-modules-core#2231]
Reference:  https://github.com/ansible/ansible-modules-core/blob/devel/cloud/openstack/os_server.py#L438

nics parameter to this module can be accepted as either a list:
nics:
         - net-id: 34605f38-e52a-25d2-b6ec-754a13ffb723
         - net-name: another_network
or a string:
nics: "net-id=4cb08b20-62fe-11e5-9d70-feff819cdc9f,net-id=542f0430-62fe-11e5-9d70-feff819cdc9f..."

By defining nics as a list type, this breaks the string parsing for nics.  The parameter is then received in this format:
nics: ["net-id=4cb08b20-62fe-11e5-9d70-feff819cdc9f", "net-id=542f0430-62fe-11e5-9d70-feff819cdc9f...", ...]

Since this module supports both list and string type for this parameter, the 'list' type should be omitted.

**Comment by robynbergeron** [comment]
[module: cloud/openstack/os_server.py]

**Comment by robynbergeron** [comment]
Hi @dagnello -- thanks for submitting this bug report. 

@shrews @dguerri @juliakreger @j2sol @rcarrillocruz @emonty -- pinging you, the lovely openstack humans, to let you know about this bug report.

**Comment by bcoca** [comment]
list type will take a comma separated string as input also, it just guarantees the module always gets a list.

**Comment by emonty** [comment]
Yah ... This takes a list of ducts though, so we have to do extra works
On Oct 12, 2015 8:22 PM, Brian Coca notifications@github.com wrote:list type will take a comma separated string as input also, it just guarantees the module always gets a list.

**Comment by dagnello** [comment]
One solution, to just remove the 'List' type as in @j2sol patch the other would require string to dict conversion for each element in the 'nics' list to be carried out, therefore a slight change to the current parsing code.

**Comment by omgjlk** [comment]
The change I made follows the style being proposed to handle metadata as a string or as a hash. So if it was wrong for metadata PR to do it ( #2238 ) to do it, then it is wrong for my PR to do it. Otherwise, they're both right.
