### ISSUE TITLE
pip module installing a specific git commit should not be editable

### ISSUE THREAD

**Issue by albertca** [ansible/ansible-modules-core#226]
(Issue migrated from https://github.com/ansible/ansible/issues/8493)
##### Issue Type:

Feature Idea / Limitation
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary

When installing an egg from a specific git commit (e.g. git+https://github.com/klynch/something-python@dece755dde8b9395f66a2eba85bae2f6cc3002d1#egg=something), pip does not force editable mode.

However, the ansible pip module blindly forces editable. Ansible should follow pip's lead, or an optional flag should be provided.
##### Steps To Reproduce:

```
- name: install python package
  pip:
    name: "git+https://github.com/klynch/something-python@dece755dde8b9395f66a2eba85bae2f6cc3002d1#egg=something"
```
##### Expected Results:

Ability to install a pip package from a git commit without having the code be installed in "editable" mode.
##### Actual Results:

The pip package is installed in editable mode. Installing directly via pip does not install the package in editable mode.

**Comment by aulvi** [comment]
I'm interested in seeing this merged, could I get a status update? Thanks!

**Comment by felix-engelmann** [comment]
#1988 got merged

There is an editable flag now, which defaults to yes for compatibility but you can disable it with:

```
pip: name='git+http://myrepo/app/MyApp' editable=false
```

**Comment by aulvi** [comment]
@felix-engelmann Many thanks, this has been a blocker for me and I appreciate the merge :clap:

**Comment by nhooey** [comment]
Can this issue be closed, then?

**Comment by felix-engelmann** [comment]
yes, the new parameter can be used to achieve exactly this behaviour

**Comment by bcoca** [comment]
closing as per above
