### ISSUE TITLE
Stat module does not return sha256

### ISSUE THREAD

**Issue by ryansydnor** [ansible/ansible-modules-core#2260]

**Comment by robynbergeron** [comment]
[module: files/stat.py]

**Comment by robynbergeron** [comment]
Hi @SL4YT1M3 -- Thanks for submitting this feature request. It might be helpful to elaborate more on why you think this would be useful (even if it seems obvious... at least to be clear :D)

@bpennypacker - Pinging you to bring this feature request to your attention. Please note that you are under no particular obligation to add this feature.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by ryansydnor** [comment]
To sum it up, a sha256 is more trustworthy than a sha1. (source: https://sites.google.com/site/itstheshappening/). 

What I want is to use the stat module to do a comparison of a file's actual sha256 vs. an expected sha256. 

The get_url module is already capable of this behavior, so the actual implementation of this is minimal (I've already completed a little spike and should have a PR opened shortly). Given this fact, I'm considering implementing similar behavior on the s3 module as well (which is where my above file originated).

**Comment by ryansydnor** [comment]
PR: https://github.com/ansible/ansible-modules-core/pull/2327

**Comment by ryansydnor** [comment]
PR merged. Closing issue.
