### ISSUE TITLE
Allow service module to run custom command

### ISSUE THREAD

**Issue by TaiSHiNet** [ansible/ansible-modules-core#2266]
Some init scripts have an 'init' function, much like zookeeper's 'service zookeeper-server init'
It would be useful to let service module handle that instead of running previous mentioned command

**Comment by robynbergeron** [comment]
[module: system/service.py]

**Comment by robynbergeron** [comment]
Hi @TaiSHiNet -- thanks for submitting this feature idea. 

@ansible/core team -- Pinging you to bring this feature request to your attention. 

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by kustodian** [comment]
As I asked in #2271, what exactly would be the benefit of this? For custom commands you would still need to define a `creates` parameter (like the `command`/`shell` modules have), so having the `service` module do this, would be no different than using the `command`/`shell` modules.

**Comment by TaiSHiNet** [comment]
I just popped this up due to the warnings provided by ansible itself, I tend to use modules that are designed for each task (service in this case). Which is why I thought of this, if you see no use for it feel free to close it

**Comment by kustodian** [comment]
That is a good reason to make that suggestion to be honest. In my opinion it would be better than to change Ansible to not recommend the service module unless you are using `service` with `start`, `stop`, `restart` and `reload`, since those are the states `service` module supports.

**Comment by bcoca** [comment]
This is not a feature we contemplate on adding as it does not really make sense as part of the service module, this is part of the service installation, not it's execution.

We also agree that the command module should not warn in this case, we will be reviewing that separately.

**Comment by TaiSHiNet** [comment]
Agreed @bcoca, please refer me if an issue is opened regarding that warning.

Cheers
