### ISSUE TITLE
win_lineinfile; integration tests fail

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible-modules-core#2270]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 8277747a04) last updated 2015/10/13 06:40:09 (GMT +100)
  lib/ansible/modules/core: (devel 657363e011) last updated 2015/10/13 06:41:29 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 0ff1776a84) last updated 2015/10/13 06:28:09 (GMT +100)
  config file = 
  configured module search path = None
##### Ansible Configuration:

stock configuration
##### Environment:

Ansible controller: Lubuntu 14.04
Targets: Windows Server 2012 R2 (powershell 4.0) , Windows Server 2008 R3 (powershell 3.0)
##### Summary:

Integration tests for win_lineinfile no longer run through
##### Steps To Reproduce:

from a current git checkout run:

source hacking/env-setup
cd test/integration
export TEST_FLAGS="-t test_win_lineinefile"
make test_winrm
##### Expected Results:

Integration tests complete
##### Actual Results:

Fails with 
"The variable "$regex" cannot be retrieved because it has not been set"

**Comment by jhawkesworth** [comment]
I suspect that the issue is because
         If ($regex -eq $FALSE -and $line -eq $FALSE) {
on line 452 should be
          If ($regexp -eq $FALSE -and $line -eq $FALSE) {

However, I tried that and the module then fails later in the integration tests with 

"Cannot index into a null array."

at the test step named   

test_win_lineinfile : testempty insert a line at the end of the file

**Comment by jhawkesworth** [comment]
Oh, meant to say behaviour is the same on both powershell 3.0 and powershell 4.0 hosts.

Its very likely that this is because of the recent change to use strict mode.

**Comment by robynbergeron** [comment]
Hi @jhawkesworth -- thanks for the bug report.

@brianlloyd -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by robynbergeron** [comment]
[module: windows/win_lineinfile.py]

**Comment by cchurch** [comment]
@jhawkesworth I just merged https://github.com/ansible/ansible-modules-core/pull/2083, which I think should fix those tests.

**Comment by jhawkesworth** [comment]
Thanks for jumping in and fixing this @cchurch

**Comment by jhawkesworth** [comment]
I know this is closed now but just to confirm this is fixed in 
ansible 2.0.0 (devel bafcd7becd) last updated 2015/10/14 18:13:46 (GMT +100)
