### ISSUE TITLE
os_server: unsupported parameter for module: public_ip - documentation specifies it

### ISSUE THREAD

**Issue by ashemedai** [ansible/ansible-modules-core#2301]
Not sure whether it is a bug or a documentation remnant, so excuse a clearer issue.

http://docs.ansible.com/ansible/os_server_module.html lists:
public_ip - Ensure instance has public ip however the cloud wants to do that

Running with this option specified yields:
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: public_ip"}

I am not sure whether this is intended to map _nova_compute.py to os_server.py in a backwards compatibility fashion or whether the documentation simply needs to remove this option.

Ansible version:
ansible 2.0.0 (devel 89b0c3f) last updated 2015/10/16 11:38:00 (GMT +200)
lib/ansible/modules/core: (detached HEAD 84b1a1a2b7) last updated 2015/10/16 11:38:20 (GMT +200)
lib/ansible/modules/extras: (detached HEAD 8ce3104bc5) last updated 2015/10/16 11:38:24 (GMT +200)

**Comment by sivel** [comment]
@emonty

**Comment by emonty** [comment]
It's definitely a bug - and it's actually both - a bad param and bad docs. I'll get a patch up soon.

**Comment by ashemedai** [comment]
@emonty By the way, to what version do we want the os_\* modules to support various OpenStack versions? My current provider is on Icehouse and I am not sure of their upgrade timeline. Definitely willing to help brush up the modules for this version.

**Comment by emonty** [comment]
@ashemedai they should support all existing versions of OpenStack - and my expectation is that a user of os_\* modules should not have to know what version their provider is running. Help definitely appreciated!!!

**Comment by ashemedai** [comment]
@emonty Gotcha, already finding issues in the shade library that I am digging into with @Shrews. Will check my notes tomorrow and see what else was going wrong.

**Comment by emonty** [comment]
Sweet! Finding issues is the first step to fixing issues :)
