### ISSUE TITLE
Broken pipe with shell/command modules

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible-modules-core#2305]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.4 (same thing happens on 2.0)
##### Ansible Configuration:

Nothing special
##### Environment:

Centos 6
##### Summary:

When using `shell` module in two situations I get a `write error: Broken pipe` error and it shouldn't generate an error. Here are the two examples:

```
# ansible -i hosts -m shell -a "tr -dc _A-Z-a-z-0-9 < /dev/urandom | head -c 30" host01
host01 | success | rc=0 >>
CagX4LwsM4jPtxxkw97LPZy7EvLzubtr: write error: Broken pipe
tr: write error
```

If I use `zgrep -m 1` (return first matched result) with `shell` and `command` modules, it fails the same:

```
# ansible -i hosts -m shell -a "zgrep -m 1 '.' debug.log.gz" host01
host01 | FAILED | rc=2 >>
2015-10-18 00:00:00,000 Some log line...
gzip: stdout: Broken pipe

# ansible -i hosts -m command -a "zgrep -m 1 '.' debug.log.gz" host01
host01 | FAILED | rc=2 >>
2015-10-18 00:00:00,000 Some log line...
gzip: stdout: Broken pipe
```

Redirecting `STDERR` to `/dev/null` fixes the problem, but why is this happening in the first place, since these commands execute without any errors when I run them directly, not over Ansible.
##### Steps To Reproduce:

Check the examples above.
##### Expected Results:

Check the examples above.
##### Actual Results:

Check the examples above.

**Comment by robynbergeron** [comment]
[module: commands/command.py]
[module: commands/shell.py]

**Comment by robynbergeron** [comment]
Greetings, @kustodian -- thanks for filing this bug report. 

@ansible/core team -- pinging you to let you this bug report for the shell and command modules.

**Comment by johnjelinek** [comment]
:+1:

**Comment by vanga** [comment]
I am also having this issue I think
Running following command with shell module fails
`find  ./dir1 ./dir2 -name "*.js" | awk 'BEGIN {print "["} {printf "%s\"%s\"",sep,$1; sep=","} END {print "\n]"}' > files.json`

```
"awk: cmd. line:1: BEGIN {print \"[\"} {printf \"%s\"%s\"\",sep,$1; sep=\",\"} END {print \"\nawk: cmd. line:1:                                                                ^ unterminated string\nawk: cmd. line:1: BEGIN {print \"[\"} {printf \"%s\"%s\"\",sep,$1; sep=\",\"} END {print \"\nawk: cmd. line:1:                                                                ^ syntax error\nfind: `standard output': Broken pipe\nfind: write error"
```

Ansible Version
`ansible 2.1.0 (devel d5446f9804)`

**Comment by vanga** [comment]
any workarounds for the time being?
Btw, I don't see this error with ansible 2.0.0 (devel de52cfb5d7)

**Comment by vanga** [comment]
updated above comment ^^

**Comment by bcoca** [comment]
@kustodian looking at the command i would expect tr to get a sigpipe after head reads first 30 lines, i'm guessing the difference between interactive and non interactive is why we see an error.

@vanga, can you show how you are using the command? your issue looks more like a quoting problem.

**Comment by vanga** [comment]
@bcoca This works perfectly fine with 2.0.0 (devel de52cfb5d7) 

```
- name: get file list
  shell: find ./xyz/{{item}}-entry-point.js ./{{item}} ./commons -name "*.js" | awk 'BEGIN {print "["} {printf "%s\"%s\"",sep,$1; sep=","} END {print "\n]"}' > {{item}}-files.json
         chdir={{item_dir}}
  with_items:
    - item1
    - item2
    - item3
```

**Comment by bcoca** [comment]
@kustodian no real way we can fix the problem on the ansible side, its just a race condition between EPIPE/SIGPIPE being sent and `tr` not dieing before its stdout being closed.

There is one trick that has served me in shell before, using `tail`:
`tr -dc _A-Z-a-z-0-9 < /dev/urandom|tail -n +1 | head -c 30`

tail is 'smarter' and checks its filehandles before using them.

closing this issue as the one problem is endemic to shell and the other works already in current devel.

**Comment by kustodian** [comment]
@bcoca I usually do `tr -dc _A-Z-a-z-0-9 < /dev/urandom 2>/dev/null | head -c 30`, but the reason why I reported this bug is because running these commands in a real shell works without a problem, but in Ansible it doesn't. What is strange to me is why does it matter if you redirect `STDERR` or not?

**Comment by serverhorror** [comment]
Hi,

it's not really a race condition. See this:
- http://www.chiark.greenend.org.uk/~cjwatson/blog/python-sigpipe.html and
- http://bugs.python.org/issue1652

@bcoca ping (not sure if you receive a message after closing so excuse the spam if you do anyhow)

**Comment by bcoca** [comment]
@serverhorror except the pipes involved are not created by subprocess but in the shell

**Comment by bcoca** [comment]
@kustodian ansible checks return code and stderr to determine if command failed, that is why redirecting to /dev/null makes a difference

**Comment by serverhorror** [comment]
@bcoca Yes. The way I read it (especially the first link) was that exactly when the shell is actually a pipe of commands and this is not set then it happens or rather can happen.

This is why it works when running in the shell and it doesn't work when running the same thing in the ansible shell module

**Comment by bcoca** [comment]
Then we would be seeing an IOError exception, which we don't. tr itself is seeing and capturing the error.

I've had this happen with batch scripts  way before Ansible existed,it was the main reason i used #!/bin/bash over #!/bin/sh on my scripts because I could use it's PIPEFAIL facility.

**Comment by Nottt** [comment]
I'm still having the same issue trying to generate a random password with : 

- name : Generating random password
  shell : "tr -dc _A-Z-a-z-0-9 < /dev/urandom|tail -n +1 | head -c 30"
  register: password
