### ISSUE TITLE
Hostname not set correctly on Ubuntu

### ISSUE THREAD

**Issue by eproxus** [ansible/ansible-modules-core#2308]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0
```
##### Ansible Configuration:

```
[defaults]
hostfile = plugins/inventory/ec2.py
hash_behaviour = merge
```
##### Environment:

Host OS: Mac OS X 10.10.5
Target OS: Ubuntu 14.04 LTS
##### Summary:

The hostname task only updates `/etc/hostname`. Because of this when you try to run a command as sudo, it will produce the following error: `sudo: unable to resolve host myhostname`
##### Steps To Reproduce:
1. Set hostname using the hostname task.
2. Run command `sudo hostname`
##### Expected Results:

```
$ sudo hostname
myhostname
```
##### Actual Results:

```
$ sudo hostname
sudo: unable to resolve host myhostname
myhostname
```

**Comment by robynbergeron** [comment]
[module: system/hostname.py]

**Comment by robynbergeron** [comment]
Hi @eproxus -- thanks for filing this bug report.

@hnakamur @saito-hideki -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by hnakamur** [comment]
I have read the following two answers and it seems that you have to edit `/etc/hosts` too.
- http://askubuntu.com/questions/9540/how-do-i-change-the-computer-name/9614#9614
- http://askubuntu.com/questions/87665/how-do-i-change-the-hostname-without-a-restart/516898#516898

However the Ansible hostname module does not know which part of `/etc/hosts` to modify.
So I think it is not responsibility of the hostname module.
I think you should edit `/etc/hosts` yourself with using the replace or lineinfile module.

What do you think?

**Comment by eproxus** [comment]
Depends on what you argue the purpose of that module is. If it is to edit `/etc/hostname` it does its job. If it is "to set the hostname properly on the target machine" it does not, in my opinion. 

However, then you could also argue that `lineinfile` or `copy` is already doing the job that `hostname` is doing (if its purpose is to only change the single line of one file).

The description of the module is "Set system’s hostname [sic]Currently implemented on Debian, Ubuntu, [...]". To me, that implies that it's purpose is to correctly set the hostname (without making every shell produce an error output) according to what's needed for the current OS. :smile:

**Comment by hnakamur** [comment]
I tried to reproduce the problem but failed.
https://github.com/hnakamur/ansible-hostname-example/tree/55d913ca832efd85bb6bb7989d5de1fd42316e06
Maybe `/etc/hosts` is not related to this problem.

Could you tell us the more detailed steps to reproduce the problem?

**Comment by eproxus** [comment]
Thank you for creating the repository! I tried it and also cannot reproduce it with Vagrant. The most minimal test case I can come up with right now is running this on EC2.

It can be reproduced with Ubuntu 14.04 LTS on EC2 using `ec2.py` and the following playbook, together with a host with the tag `Name` set to `hostname-test`:

``` yaml
---
- hosts: tag_Name_hostname-test
  user: ubuntu
  become: yes
  tasks:
    - name: Set hostname
      hostname: name=foo
```

Logging in yields:

```
ubuntu@foo:~$ sudo hostname
sudo: unable to resolve host foo
foo
```

**Comment by hnakamur** [comment]
Thank you for your playbook. I tried it and reproduced the problem.
I used "Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-936d9d93" AMI and a m3.medium spot instance.

I don't know but `hostname` without `sudo` succeeds.

```
ubuntu@foo:~$ hostname
foo
ubuntu@foo:~$ sudo hostname
sudo: unable to resolve host foo
foo
```

I looked at `/etc/hosts` and it does not have the old and new hostname.

```
ubuntu@foo:~$ cat /etc/hosts
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

The os version info:

```
ubuntu@foo:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

Umm, I don't know why `sudo hostname` prints `sudo: unable to resolve host foo`.

**Comment by hnakamur** [comment]
I forgot to mention that `sudo hostname` succeeded before running `ansible-playbook`.

```
ubuntu@ip-10-168-2-174:~$ sudo hostname
ip-10-168-2-174
```

**Comment by hnakamur** [comment]
I read the following pages and added `127.0.1.1 foo` after `127.0.0.1 localhost`.
- https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution
- https://bugs.launchpad.net/ubuntu/+source/sudo/+bug/32906

Now `sudo hostname` does not print `sudo: unable to resolve host foo`.

```
$ sudo hostname
foo
```

**Comment by eproxus** [comment]
Yes, this is the solution we have right now:

```
- name: Update hosts file
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{ec2_tag_Name}}"
              insertafter="^127\.0\.0\.1 localhost.*$"
  when: ec2_tag_Name is defined
```

Should this somehow be part of the `hostname` module or not? I'm not sure why Ubuntu on EC2 acts like it does and what's different from a local Ubuntu installation. Perhaps Amazon have done something to the DNS resolution that breaks this?

**Comment by hnakamur** [comment]
I think modifying `/etc/hosts` should not be part of `hostname` module because there are many cases how to modify `/etc/hosts` that I cannot make sure all cases are covered correctly.

**Comment by eproxus** [comment]
Ok, that's fine with me.

**Comment by meshy** [comment]
Just had this issue -- I understand the decision to not modify the `/etc/hosts` file, but I really think that the docs should provide some warning that this step will be required.
