### ISSUE TITLE
s3 - Delobj

### ISSUE THREAD

**Issue by luhkevin** [ansible/ansible-modules-core#2318]
I was told to post this issue to ansible-modules-core: 

The documentation says that "delobj" is still a valid mode for the s3 module, but I just got this error:

msg: value of mode must be one of: get,put,delete,create,geturl,getstr, got: delobj

I'm on ansible version 1.9.4

I tried using the "delete" mode on a dummy-object...it deleted the entire bucket instead.

Is there currently a way to delete objects? This is somewhat urgent if not...

To reproduce, I just had this in a playbook:

`- name: Dummy delete`
`s3:    bucket=dummy-bucket object="/dummy_folder"    mode=delete    aws_access_key="{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"    aws_secret_key="{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"``

And like I said above, delobj didn't work. I used pretty much the same commands for that:

`- name: Dummy delete`
`s3:    bucket=dummy-bucket object="/dummy_folder"    mode=delobj    aws_access_key="{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"    aws_secret_key="{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"``

**Comment by sivel** [comment]
The `delobj` mode was added for the 2.0 release of ansible.  That mode is not available in any current release of ansible. But will be included in the 2.0 release.

See https://github.com/ansible/ansible-modules-core/commit/51bc602f42d5c772e4de1e9202f3fe5e74de2d88

There should probably be some documentation added specifying that it is new in 2.0.

**Comment by luhkevin** [comment]
I see. 

Yes, the documentation currently doesn't specify that delobj is 2.0+
http://docs.ansible.com/ansible/s3_module.html

**Comment by robynbergeron** [comment]
Hi @luhkevin -- thanks for submitting this bug report / docs report. 

@sivel -- thanks for your feedback :)

@lwade @ralph-tice -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module. Looks like this could be a quick fix.

**Comment by robynbergeron** [comment]
[module: cloud/amazon/s3.py]

**Comment by anthcourtney** [comment]
I just hit this as well. Frustrating that it is not documented correctly.
