### ISSUE TITLE
mode=pull not implemented in synchronize module

### ISSUE THREAD

**Issue by larry-s** [ansible/ansible-modules-core#2329]
The pull option for mode does not appear to be implemented for the synchronize module.

Inspecting the code I cannot see where the pull mode is implemented.

Further, there does not appear to be any way to specify the remote host for the source of the pull. I need this to be a third machine (not the localhost or the target machine).

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

FYI, the pull mode is implemented in the action plugin, which then calls the module with the hosts switched.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
