### ISSUE TITLE
Docker: when not detached, task will be marked as success even if command failed

### ISSUE THREAD

**Issue by yannh** [ansible/ansible-modules-core#2334]
Using the docker module, when running a command in non-detached mode and the command fails, the tasks succeeds.  The documentation states:

> Enable detached mode to leave the container running in background. 
> If disabled, fail unless the process exits cleanly."
## How to reproduce:

Run a command that returns 1 using the docker module. For example:

ansible vagrant --private-key=/home/yann/.vagrant.d/insecure_private_key --user=vagrant --connection=ssh --inventory-file=inventory -m docker -a "image=ubuntu:14.04 command=\"/bin/false\" detach=false"
## Expected result:

This should fail the playbook.
## Actual result:

vagrant | success >> {
    "ansible_facts": {
        "docker_containers": [
            {
                "Id": "bb795428cc4cab0b15eea2d1d51eb31df22bc1b7d8970203c6f3012f5aa4a5e6",
                "Warnings": null
            }
        ]
    },
    "changed": true,
    "containers": [
        {
            "Id": "bb795428cc4cab0b15eea2d1d51eb31df22bc1b7d8970203c6f3012f5aa4a5e6",
            "Warnings": null
        }
    ],
    "msg": "started 1 container, created 1 container.",
    "reload_reasons": null,
    "summary": {
        "created": 1,
        "killed": 0,
        "pulled": 0,
        "removed": 0,
        "restarted": 0,
        "started": 1,
        "stopped": 0
    }
}

**Comment by yannh** [comment]
Hello! this is a rather serious issue for us as it prevents us from getting results when running commands via docker.. What would be the best way for me to help? I am happy spending more time and posting additional informations, or working on a pull request, if the issue is acknowledged! Just get in touch! :)

**Comment by smashwilson** [comment]
This looks like the scenario that was addressed with #1031. Are you using a version of Ansible that includes that code? (Checking the description of the `detach` parameter in `ansible-doc docker` would be a quick way to check that.)

**Comment by yannh** [comment]
Indeed, apparently not running a version with that patch - using ansible 1.9.4 installed with pip on Ubuntu 15.4. WIll try to upgrade, thanks!

**Comment by yannh** [comment]
Could not reproduce with HEAD (v2), so already fixed with the PR you gave me :) Thanks a lot!
