### ISSUE TITLE
copy module fails when you try to copy large file but not with the get_url

### ISSUE THREAD

**Issue by bertrandcedric** [ansible/ansible-modules-core#2346]
I tried to copy big file (more than 1gb) and it failed because of restriction on the size of the remote_tmp folder (limitation on VMs in my infrastructure).

With the get_url module, I can execute the download of the same big file by setting the environment variables TMPDIR.

It seems that the same behaviour doesn't exist for the module copy.

Can we have the same kind of implementation on the copy module and more globally on all modules that can managed big files ?

**Comment by azaghal** [comment]
In order for this to work, it would be necessary to do some changes in Ansible itself, namely the shell plugins would need updates (sh.py and powershell.py), ActionBase, copy action, and then in the end the copy (core) module.

I'm not sure if this would be viable for pursuing, though. I have a quick and dirty patch that I _think_ works (did just some provisional debugging with epdb).

**Please do not run this on any kind of production, it is a very dirty quick hack!**

Here is the patch for the Ansible itself:

```
diff --git a/lib/ansible/modules/core b/lib/ansible/modules/core
--- a/lib/ansible/modules/core
+++ b/lib/ansible/modules/core
@@ -1 +1 @@
-Subproject commit 002028748f080961ade801c30e194bfd4ba043ce
+Subproject commit 002028748f080961ade801c30e194bfd4ba043ce-dirty
diff --git a/lib/ansible/plugins/action/__init__.py b/lib/ansible/plugins/action/__init__.py
index 5383f8a..f49a343 100644
--- a/lib/ansible/plugins/action/__init__.py
+++ b/lib/ansible/plugins/action/__init__.py
@@ -191,7 +191,7 @@ class ActionBase(with_metaclass(ABCMeta, object)):
             return True
         return False

-    def _make_tmp_path(self):
+    def _make_tmp_path(self, basetmp=None):
         '''
         Create and return a temporary path on a remote box.
         '''
@@ -206,7 +206,7 @@ class ActionBase(with_metaclass(ABCMeta, object)):
         if self._play_context.remote_user != 'root' or self._play_context.become and self._play_context.become_user != 'root':
             tmp_mode = 0o755

-        cmd = self._connection._shell.mkdtemp(basefile, use_system_tmp, tmp_mode)
+        cmd = self._connection._shell.mkdtemp(basefile, use_system_tmp, tmp_mode, basetmp=basetmp)
         result = self._low_level_execute_command(cmd, sudoable=False)

         # error handling on this seems a little aggressive?
diff --git a/lib/ansible/plugins/action/copy.py b/lib/ansible/plugins/action/copy.py
index 17c2286..1138388 100644
--- a/lib/ansible/plugins/action/copy.py
+++ b/lib/ansible/plugins/action/copy.py
@@ -46,6 +46,7 @@ class ActionModule(ActionBase):
         force   = boolean(self._task.args.get('force', 'yes'))
         faf     = self._task.first_available_file
         remote_src = boolean(self._task.args.get('remote_src', False))
+        tmp_dest = self._task.args.get('tmp_dest', None)

         if (source is None and content is None and faf is None) or dest is None:
             result['failed'] = True
@@ -142,7 +143,7 @@ class ActionModule(ActionBase):
         # If this is a recursive action create a tmp path that we can share as the _exec_module create is too late.
         if not delete_remote_tmp:
             if tmp is None or "-tmp-" not in tmp:
-                tmp = self._make_tmp_path()
+                tmp = self._make_tmp_path(basetmp=tmp_dest)

         # expand any user home dir specifier
         dest = self._remote_expand_user(dest)
@@ -195,7 +196,7 @@ class ActionModule(ActionBase):
                 # If this is recursive we already have a tmp path.
                 if delete_remote_tmp:
                     if tmp is None or "-tmp-" not in tmp:
-                        tmp = self._make_tmp_path()
+                        tmp = self._make_tmp_path(basetmp=tmp_dest)

                 if self._play_context.diff and not raw:
                     diffs.append(self._get_diff_data(dest_file, source_full, task_vars))
diff --git a/lib/ansible/plugins/shell/sh.py b/lib/ansible/plugins/shell/sh.py
index 7fbfa81..7dd8183 100644
--- a/lib/ansible/plugins/shell/sh.py
+++ b/lib/ansible/plugins/shell/sh.py
@@ -71,10 +71,11 @@ class ShellModule(object):
             cmd += '-r '
         return cmd + "%s %s" % (path, self._SHELL_REDIRECT_ALLNULL)

-    def mkdtemp(self, basefile=None, system=False, mode=None):
+    def mkdtemp(self, basefile=None, system=False, mode=None, basetmp=None):
         if not basefile:
             basefile = 'ansible-tmp-%s-%s' % (time.time(), random.randint(0, 2**48))
-        basetmp = self.join_path(C.DEFAULT_REMOTE_TMP, basefile)
+        if not basetmp:
+            basetmp = self.join_path(C.DEFAULT_REMOTE_TMP, basefile)
         if system and (basetmp.startswith('$HOME') or basetmp.startswith('~/')):
             basetmp = self.join_path('/tmp', basefile)
         cmd = 'mkdir -p %s echo %s %s' % (self._SHELL_SUB_LEFT, basetmp, self._SHELL_SUB_RIGHT)
```

Here is the (tiny) patch for the copy module itself (just to add the extra argument, essentially):

```
diff --git a/files/copy.py b/files/copy.py
index 122d980..61d474a 100644
--- a/files/copy.py
+++ b/files/copy.py
@@ -216,6 +216,7 @@ def main():
             validate          = dict(required=False, type='str'),
             directory_mode    = dict(required=False),
             remote_src        = dict(required=False, type='bool'),
+            tmp_dest          = dict(required=False, type='str'),
         ),
         add_file_common_args=True,
         supports_check_mode=True,
```

Any opinions from the core devs of Ansible on this one? I could have a more proper look into this, and while at it try to run the tests locally to see what breaks or not :)

I am _assuming_ that the extra parameter should be sufficient in correct places. Changes would be necessary to the powershell.py as well, but, truth be told, I have no idea how that one behaves, and someone with Windows machine might be needed for testing/implementing it eventually.

**Comment by bcoca** [comment]
you can set the `remote_tmp` in ansible.cfg or use the envvar `ANSIBLE_REMOTE_TMP`

**Comment by bcoca** [comment]
@azaghal you are modifying the way all modules are created, not just files copied by the copy module. A simpler solution might be to add a group/host var ansible_remote_tmp that compliments the config item I showed above.

**Comment by azaghal** [comment]
@bcoca Thanks for feedback, I do understand this affects the Ansible core, although I tried to keep the default behaviour unchanged, and only the ActionModule in `copy.py` utilises the new option (unless I have done something terribly wrong, mind you :). If I understood right, these action plugins behave as a kind of (more tightly integrated) module within Ansible? Is the code in `lib/ansible/plugins/action/copy.py` used by/for anything else?

As for the environment approach, it does not offer the same granularity as the hack (not saying this hack is the right thing to do) - i.e. it's per host/group instead of a task. In some cases, perhaps the user does not want Ansible's own files (like python files etc - you'll excuse my ignorance of details on what gets copied) to be copied outside of default `ANSIBLE_REMOTE_TMP`, but just one specific (big) file. Is it possible to override an Ansible variable on per-task basis instead?

**Comment by bcoca** [comment]
i'm thinking we do need an option to set this for modules, copy is not the only one transferring files and overloading the remote_tmp does not seem to work for all cases.

**Comment by bertrandcedric** [comment]
I closed the issue because overloading the remote_tmp is find for me. If you think it can be useful to continue to work on this issue, it can be reopen.

**Comment by azaghal** [comment]
@bertrandcedric Ok, good to know :)

@bcoca Well, while this is still relatively fresh in my head, perhaps I should give it a go - if you think it is useful in the long run? In such a case, feel free to point out if the direction I took is ok. If so, I will check on how I can run tests locally and see if there is any unit tests etc that might be necessary (please do point out any hints in this direction if you have them :).

Perhaps one question would be whether the default for copy module should be to copy the file directly into directory (as a tmp file), and then move it, like in case of remote source. This way you use-up a little bit less disk bandwidth and the behaviour is more harmonised - although there could be some issues when perhaps using things like SELinux/AppArmor and the like.

There remains question on who could implement and test this for powershell, though.
