### ISSUE TITLE
add_host not adding host to in-memory inventory

### ISSUE THREAD

**Issue by mching-bp3** [ansible/ansible-modules-core#2370]
I'm currently running ansible-1.9.2 from the EPEL releases on CentOS.   

I am launching an EC2 instance through a role (standard stuff from the ec2 module), I use add_host to add to a launched group.   

When I move into the hosts: launched section, the in memory inventory does not have the EC2 instance listed.  (Verified using a debug output.)  

This results in an ssh error about an unresolved hostname.  

Anything ring a bell?  I can post details of the playbook and roles if needed. 

Mark

**Comment by sivel** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by mching-bp3** [comment]
While I understand that this is typically a user question.   This playbook worked before upgrading to 1.9.4.   so I figured it was a bug..

**Comment by mching-bp3** [comment]
Sivel:  You are correct, it was a user issue.   yml and an errant space.
