### ISSUE TITLE
add support for plain gzip files to unarchive

### ISSUE THREAD

**Issue by aMoniker** [ansible/ansible-modules-core#2420]
unarchive should be able to handle plain gzipped files that haven't been tarred.

**Comment by bcoca** [comment]
technically those are not archives but compressed files, unlike zip format which is an archive

**Comment by robynbergeron** [comment]
[module: files/unarchive.py]

**Comment by robynbergeron** [comment]
@aMoniker Thanks for submitting this feature idea.

@pileofrogs Pinging you to bring this feature request to your attention. Please note that you are under no particular obligation to add this feature.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by Jmainguy** [comment]
@bcoca @pileofrogs I don't mind writing the code to make this possible, should be pretty quick, but I would yalls ok with it first. I think that while technically gzip, bzip, 7zip etc are not archives, that this is the most logical module for them to go into, and while we could add a unzip module, seems kind of arbitrary to train consumers to use two different modules for basically the same behavior. What do yall think?

**Comment by pileofrogs** [comment]
Sounds fine to me.  If you're doing the work, I got no complaints.

On Wed, Nov 25, 2015 at 10:39 AM, Jonathan Mainguy <notifications@github.com

**Comment by bcoca** [comment]
i'm fine with adding it here, zips and 7zip ARE archives with compression, the spec allows for multiple files, unlike gzip, bzip, lzw, xv and others which are pure compression utilities and need something like tar/cpio for the 'archive' part. 

I do think a uncompress/compress pair of modules might make more sense as well as an 'archive' module that has also been requested.

**Comment by Jmainguy** [comment]
just linking https://github.com/ansible/ansible-modules-core/issues/1035 here as its the same issue. I think I will take a stab at making the uncompress/compress pair to solve this issue.

**Comment by bcoca** [comment]
closing this as dupe then, conversation is saved and linked to the previous ticket
