### ISSUE TITLE
win_file: unable to create directory

### ISSUE THREAD

**Issue by h0nIg** [ansible/ansible-modules-core#2424]
Hey,

i'm unable to run the win_file task in combination with an existing directory:

```
TASK [win_file path=C:\internal state=directory] *******************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: +              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: [mcfly]: FAILED! => {"changed": false, "failed": true, "msg": "Die Eigenschaft \"Directory\" wurde für dieses Objekt nicht gefunden. Vergewissern Sie sich, dass die Eigenschaft vorhanden ist."}
```

it seems that the Directory attribute is not available for the fileinfo's (maybe due to strict mode?)

```
If ( $state -eq "directory" -and $fileinfo.Directory )
.....
If ( $state -eq "file" -and -not $fileinfo.Directory )
```

**Comment by h0nIg** [comment]
checked for Directory attribute on an existing directory but its not available

```
PS C:\............> Get-Item C:\internal\ | select *

PSPath            : Microsoft.PowerShell.Core\FileSystem::C:\internal\
PSParentPath      : Microsoft.PowerShell.Core\FileSystem::C:\
PSChildName       : internal
PSDrive           : C
PSProvider        : Microsoft.PowerShell.Core\FileSystem
PSIsContainer     : True
BaseName          : internal
Mode              : d----
Name              : internal
Parent            :
Exists            : True
Root              : C:\
FullName          : C:\internal\
Extension         :
CreationTime      : 05.11.2015 15:11:40
CreationTimeUtc   : 05.11.2015 14:11:40
LastAccessTime    : 05.11.2015 15:11:40
LastAccessTimeUtc : 05.11.2015 14:11:40
LastWriteTime     : 05.11.2015 15:11:40
LastWriteTimeUtc  : 05.11.2015 14:11:40
Attributes        : Directory
```

**Comment by h0nIg** [comment]
@jhawkesworth could you please take a look?

**Comment by jhawkesworth** [comment]
Might have to use is container check.

I am surprised this isn't covered by the integration tests, but am away
from the keyboard at the moment.  Will try to find some time to investigate
over the weekend.

**Comment by h0nIg** [comment]
Server version is 2012

**Comment by jhawkesworth** [comment]
Actually, which exact version of ansible are you using? I think there may
have recently been a similar issue in win_copy.

Jon

**Comment by h0nIg** [comment]
its ansible 2.0 beta1 or beta2

Zitat von jhawkesworth notifications@github.com:

> Actually, which exact version of ansible are you using? I think there may
> have recently been a similar issue in win_copy.
> 
> Jon
> On Nov 7, 2015 10:55 AM, "Hans-Joachim Kliemeck"
> notifications@github.com
> wrote:
> 
> > Server version is 2012
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/ansible/ansible-modules-core/issues/2424#issuecomment-154691169
> > .
> 
>   —
> Reply to this email directly or view it on GitHub[1].
>       

## Links:

[1]  
https://github.com/ansible/ansible-modules-core/issues/2424#issuecomment-154716915

**Comment by jhawkesworth** [comment]
Just to say I haven't forgotten about this.  I am trying to get powershell
to work with registry keys including spaces at the moment, once I have
worked out why Test-Path seems to behave differently inside a script and
outside a script I will look at this.

I think likely it will need similar fix to last change to win_copy.

Jon

**Comment by jhawkesworth** [comment]
Hi @h0nIg I believe this has already been fixed in devel branch of ansible on 13th Oct.

Commit details below:

https://github.com/ansible/ansible-modules-core/commit/833bf77be1101fe77f691b859d4c74e892ed167e

Please can you try latest devel?

If you are still getting the same behaviour please check that you are not picking up a local copy of win_file.ps1 

Otherwise I think this is the same as https://github.com/ansible/ansible-modules-core/issues/2147 which is now closed.

**Comment by robynbergeron** [comment]
[module: windows/win_file.py]

**Comment by robynbergeron** [comment]
@h0nIg Thanks for submitting this bug report. Please check out @jhawkesworth's recommendations re: trying the fix listed above and let us know if it worked.

@jhawkesworth -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module. Looks like you are on top of this already (thanks!)
