### ISSUE TITLE
IAM module does not paginate results

### ISSUE THREAD

**Issue by jsternberg** [ansible/ansible-modules-core#2440]
The IAM module does not paginate results. This means if you have more than 100 roles, the IAM module may not find the role if it's not returned as part of the first 100 items. The module will then determine the IAM role doesn't exist and try to create it. You'll then get a 409 Conflict from the Amazon API instead of just an `ok` response.

Here's documentation on the pagination: http://docs.aws.amazon.com/IAM/latest/APIReference/API_ListGroups.html

**Comment by robynbergeron** [comment]
[module: cloud/amazon/iam.py]

**Comment by robynbergeron** [comment]
@jsternberg Thanks for submitting this feature idea / possible bug report :)

@defionscode @seiffert Pinging you to bring this feature request to your attention. Please note that you are under no particular obligation to add this feature. (Could be considered a bug -- will let you all decide, but marking as a feature idea for now.)

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by jsternberg** [comment]
As we were running into this problem, we already fixed it in our local copy. I'll submit a PR with what we did.

**Comment by bcoca** [comment]
I'm actually looking to create a generic 'aws paging' as i recently implemented this for the ec2_elb module also and noticed most aws modules need this. That said, please submit what you have, it will fix the immediate issue and probably give us a better pattern to follow for the generic function.
