### ISSUE TITLE
Universal Package - "use"

### ISSUE THREAD

**Issue by coxley** [ansible/ansible-modules-core#2448]
The docs for the new `package` module mention a `use` argument to explicitly say which provider to use. Can this be arbitrary? For example, I use a module for Archlinux's `packer` utility for accessing the AUR. Could I use `use=packer` assuming the third party module is "compatible" in some way?

Also, I looked at the source for package.py and it was 100% docstring. What's up with that?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
