### ISSUE TITLE
Provide return value example

### ISSUE THREAD

**Issue by tsturzl** [ansible/ansible-modules-core#2471]
In order to figure out how certain modules were returning values I had to dig into the source. I feel it would be much easier, and much more convenient to just include an example return value of the module.

Would you accept PR's which provide return value examples in the documentation?

**Comment by bcoca** [comment]
No need to put them in the examples, in 1.9 we introduced the RETURNDOCS which documents a module's return structure, in 2.1 we plan to make this mandatory for any new modules. Currently we are adding them to existing modules but it is a slow process and we do appreciate any help.

Check stat and copy modules to see examples, many of the new cloud modules are also have this documented.

In any case this is a question more appropriate for IRC or the mailing lists, so closing this ticket as it is neither a bug nor a feature request.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
