### ISSUE TITLE
ini_file module: bracklets in key break idempotence

### ISSUE THREAD

**Issue by theraser** [ansible/ansible-modules-core#2475]
Issue Type: Bug Report
Ansible Version: ansible-playbook 2.0.0 (devel 5d645f3a8b) last updated 2015/11/13 13:27:13 (GMT +200)
Environment: Ubuntu 15.04
Summary: When using ini_file for modifying /etc/php5/fpm/pool.d/www.conf it will not recognize strings  which include "[" or "]" in key and append it again to the file. Using Ansible 1.9.4 this works just as expected.

Example: You want to set

```
php_admin_value[sendmail_path]: "/usr/sbin/sendmail -t -i -f an@onymo.us"
```

using this hash:

``` yaml
php_admin_value[sendmail_path]:
    value: '"/usr/sbin/sendmail -t -i -f an@onymo.us"'
```

On first run Ansible will append this string to the file just as expected. On second run it will append it again, even though it's already present. When removing the bracklets it will only be inserted once.

Removing the bracklets from value will work as expected (not changed one second run)

**Comment by robynbergeron** [comment]
[module: files/ini_file.py]

**Comment by robynbergeron** [comment]
@theraser Thanks for submitting this bug report.

@jpmens @noseka1 -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by noseka1** [comment]
Thanks for reporting the issue. I think I could fix the problem. The respective pull request is here:
https://github.com/ansible/ansible-modules-core/pull/2590
