### ISSUE TITLE
docker module reloads unnecessary if log_driver for daemon is not default

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible-modules-core#2479]
Running devel, this of code is the exact problem:

``` python
if self.ensure_capability('log_driver', False):
                expected_log_driver = self.module.params.get('log_driver') or 'json-file'
                actual_log_driver = container['HostConfig']['LogConfig']['Type']
                if actual_log_driver != expected_log_driver:
                    self.reload_reasons.append('log_driver ({0} => {1})'.format(actual_log_driver, expected_log_driver))
                    differing.append(container)
                    continue
```

When running with `state=reloaded`, if your docker-daemon has a default log and you have not specified the log_driver then a comparison is always made to `'json-file'`. So in my case where I have journald as the default on all my hosts, the driver will always restart my containers - even though it doesn't actually pass `'json-file'` to the containers on the restart.

If expected log_driver is `self.module.params.get('log_driver')` is None, it should be assumed that no changes are actually specified - or (but I do not yet know how to do this) - the daemon default driver should be used instead.

Related to #1251

EDIT: Looks like the driver should just add a call to docker_py's info() module to check the default settings.

**Comment by robynbergeron** [comment]
[module: cloud/docker/docker.py]

**Comment by robynbergeron** [comment]
@wrouesnel Thanks for submitting this bug report.

@cove @joshuaconner @smashwilson @softzilla -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.
