### ISSUE TITLE
ec2_remote_facts - documentation is not updated

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible-modules-core#2487]
Hi All,

The documentation here http://docs.ansible.com/ansible/ec2_remote_facts_module.html states that there is 'filter' option whereas the actual module has no such option at all. Probably replacement for 'lookup'.

This is confusing. Could you please sync the docs with the actual state of module?

Regards,
Constantin

**Comment by robynbergeron** [comment]
@Constantin07 --

The ec2_remote_facts module is an extras module -- please file your issue here: https://github.com/ansible/ansible-modules-extras

Thanks!

**Comment by Constantin07** [comment]
Thanks. Done.
