### ISSUE TITLE
The nova-compute module can not associate floatng ip address to instance of VM

### ISSUE THREAD

**Issue by saito-hideki** [ansible/ansible-modules-core#249]
##### Issue Type:

Bug Report
##### Ansible Version:
- ansible 1.8(devel)
- nova-compute(master)
##### Environment:

OpenStack 2014.2 Juno with RDO,DevStack
(exclude hpcloud)
##### Summary:

The nova-compute module with floating_ip_pools option retrieve the floating ip address from unused floating ip list that is created by response of nova-api.
If a floating ip address is already assigned, instance_id field contains uuid of virtual machine instance.
But  in the current Juno release of OpenStack, a value of instance_id in response of nova-api is always null, so it should be adopted the fixed_ip instead.
Using the fixed_ip is safer than instance_id in almost version.
##### Steps To Reproduce:
- floating-ip: 172.16.0.6 (in-use)
- fliaging-ip: 172.16.0.7 (unassigned)

```
$ nova --debug floating-ip-list
...
REQ: curl -i 'http://172.16.0.100:8774/v2/832e34a525d948b7b5d5a40e8df792ef/os-floating-ips'
 -X GET -H "Accept: application/json" -H "User-Agent: python-novaclient"
 -H "X-Auth-Project-Id: demo"
 -H "X-Auth-Token: {SHA1}515e73dc756b13c2f4209ff75c75f12ff0477a8d"

RESP: [200] {'date': 'Thu, 30 Oct 2014 14:39:45 GMT',
 'connection': 'keep-alive', 'content-type': 'application/json',
 'content-length': '274',
 'x-compute-request-id': 'req-1253acd4-88f5-4ef1-813a-d080eabc65c7'}
RESP BODY: {
 "floating_ips": [
 {"instance_id": null,
  "ip": "172.16.1.7",
  "fixed_ip": null,
  "id": "082d3444-60eb-4fb0-9791-b9e88b45e7ee",
  "pool": "public"},
 {"instance_id": null,    <- it is already assigned but instance_id is null.
  "ip": "172.16.1.6",
  "fixed_ip": "10.0.0.3",
  "id": "51f86251-d7ed-4ef7-8de9-24698beb555c",
  "pool": "public"}
 ]}
+------------+-----------+----------+--------+
| Ip         | Server Id | Fixed Ip | Pool   |
+------------+-----------+----------+--------+
| 172.16.1.7 | -         | -        | public |
| 172.16.1.6 | -         | 10.0.0.3 | public |
+------------+-----------+----------+--------+
```
##### Expected Results:

The nova-compute module will use from top of unused floating ip list.
If unused list is empty then it allocate new floating ip from pool.
##### Actual Results:

The nova-compute module creates list of all floating ip because instanceid is always null.
At this time, it will use from top of all floating ip list that contains in-use and un-use address.

**Comment by bcoca** [comment]
closing this as we have the PR to track the issue
