### ISSUE TITLE
Show stdout from validating command in template module

### ISSUE THREAD

**Issue by komuta** [ansible/ansible-modules-core#2498]
##### Summary:

The `validate` option of template module allow checking the final file before moving it to the destination, but the output from Ansible is not very useful right now. Only stderr and the return code are shown, but a lot of tools prompt everything to stdout, and the option doesn't allow to use shell tricks. It would be very nice to get both stdout and stderr of the validating command from Ansible.
##### Steps To Reproduce:

Tried with a configuration file (named.conf) for bind9. A validation error results in:

```
failed: [myhost] => {"failed": true}
msg: failed to validate: rc:1 error:
```
##### Expected Results:

In the previous case, the prompted error should be:

```
failed: [myhost] => {"failed": true}
msg: failed to validate: rc:1 error: /etc/bind/named.conf:63: option 'allow-query' is not allowed in 'forward' zone 'my.zone'
```

**Comment by robynbergeron** [comment]
[module: files/template.py]

**Comment by robynbergeron** [comment]
@komuta Thanks for submitting this feature idea.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

@ansible/core team -- for the template module.

**Comment by bcoca** [comment]
I would expand this to all modules that use validate, also rc, stdout and stderr should be returned to the registered var

**Comment by komuta** [comment]
Alright. I've already a local patch, so I'll submit a pull request. On which target branch should I submit the patch ? I'm currently branched on **stable-1.9**, is this fine?

**Comment by bertvv** [comment]
I ran into this issue as well, I submitted PR #2647 to fix this.
