### ISSUE TITLE
apache2_module hangs with "WARNING: The following essential module will be disabled."

### ISSUE THREAD

**Issue by BlaM** [ansible/ansible-modules-core#2499]
I have this code in my playbook:

```
- apache2_module: name={{item}} state=absent
  with_items:
    - autoindex
    - negotiation
```

However someone decided that autoindex and negotiation both are "essential", so when I try to disable them I get this warning:

```
# a2dismod autoindex
WARNING: The following essential module will be disabled.
This might result in unexpected behavior and should NOT be done
unless you know exactly what you are doing!
 autoindex

To continue type in the phrase 'Yes, do as I say!' or retry by passing '-f':
```

and expects me to actually type "Yes, do as I say!" (WTF?!?) if I don't provide "-f". The ansible module does not provide that -f parameter, so it locks up.

As weird as that is, I think there _at least_ should be a "force=true" option in apache2_module - or -f should be default.

(Not sure if that's true for all "a2dismod" instances because there is a suspiciously low amount of Google results (none). It is at least there for apache2 currently installed from dotdeb.org)

**Comment by robynbergeron** [comment]
[module: web_infrastructure/apache2_module.py]

**Comment by robynbergeron** [comment]
@BlaM Thanks for submitting this bug report.

@berendt thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.
