### ISSUE TITLE
S3 Module with IAM Policies

### ISSUE THREAD

**Issue by TroyFluegge** [ansible/ansible-modules-core#2508]
I have been having problems getting the s3 module work with a custom IAM policy.  I keep getting 403 Forbidden errors.  I have tested this policy with the aws cli using the same access key.  It works with the aws cli but will give 403's with the s3 module.

The goal is to have a single bucket with multiple folders for backups.  There will be IAM service accounts created for types of backups that only have access to it's particular backup folder.  The back jobs will be ran with Ansible and pushed to s3

I followed this blog that did something similar for user folders (http://blogs.aws.amazon.com/security/post/Tx1P2T3LFXXCNB5/Writing-IAM-policies-Grant-access-to-user-specific-folders-in-an-Amazon-S3-bucke) 

Simple test..
- name: s3 Test  
  s3: aws_access_key= {{ my_key }} aws_secret_key={{ my_secret }} bucket=sysbackups object=/svc-data-backups/s3testfile.txt src=s3testfile.txt region=us-east-1 mode=put

Error..
failed: [localhost] => {"failed": true}
msg: S3ResponseError: 403 Forbidden

Here is the policy...
{
  "Version":"2012-10-17",
  "Statement": [
    {
      "Sid": "AllowGroupToSeeBucketListInTheConsole",
      "Action": ["s3:ListAllMyBuckets", "s3:GetBucketLocation"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::_"]
    },
    {
      "Sid": "AllowRootAndFolderListingOfBucket",
      "Action": ["s3:ListBucket"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::sysbackups"],
      "Condition":{"StringEquals":{"s3:prefix":["","${aws:username}/"],"s3:delimiter":["/"]}}
    },
    {
      "Sid": "AllowListingOfBackupFolder",
      "Action": ["s3:ListBucket"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::sysbackups"],
      "Condition":{"StringLike":{"s3:prefix":["${aws:username}/_"]}}
    },
    {
       "Sid": "AllowAllS3ActionsInBackupFolder",
       "Action":["s3:_"],
       "Effect":"Allow",
       "Resource": ["arn:aws:s3:::sysbackups/${aws:username}/_"]
    }
  ]
}

I have noticed that if I changed the last policy action to ....
    {
       "Sid": "AllowAllS3ActionsInBackupFolder",
       "Action":["s3:_"],
       "Effect":"Allow",
       "Resource": ["arn:aws:s3:::_"]
    }

....it will work with the s3 module. 

Not sure if this is a bug but I have not clue what to try next.  Tried many variations of the policy and command.   AWS cli works... modules does not.  It makes think the module need more rights/allowed actions then the AWS cli and I am missing what else is needed.

Please just tell me I am doing something stupid.. :)

**Comment by TroyFluegge** [comment]
I figured out a work around/fix.  The S3 module appears to required "s3:ListBucket" rights also.  This is not required for the console or for the AWS cli.  This simplified policy does what I need it to.  I figured I would post to help anyone else in the same situation.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowGroupToSeeBucketListInTheConsole",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::_"
            ]
        },
        {
            "Sid": "AllowAllS3ActionsInBackupFolder",
            "Action": [
                "s3:_"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::sysbackups/${aws:username}/*"
            ]
        }
    ]
}

**Comment by jimi-c** [comment]
Hi @v1s0n, this is due to the fact that the s3 module also requests information about the bucket, while the CLI command apparently doesn't. Thanks for tracking down the work-around for this, and I'll go ahead and close this now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
