### ISSUE TITLE
CRITICAL BUG REPORT: using the user module on Mac OS X will kill your groups

### ISSUE THREAD

**Issue by domibarton** [ansible/ansible-modules-core#2537]
This bug report is just for tracking purposes.
Please have a look at the [origin bug report](https://github.com/ansible/ansible/issues/13266) in the ansible repo.

**Comment by robynbergeron** [comment]
[module: system/user.py]

**Comment by robynbergeron** [comment]
@domibarton --Thanks for submitting this bug report, and for the accompanying PR :)

@sfromm --  thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module. Please note there is an associated PR to help fix things up :)

**Comment by nitzmahone** [comment]
merged to devel as https://github.com/ansible/ansible-modules-core/commit/6128845b696b41d90862f6255b9a0e08557101c3 (I added a case in the next commit to handle the additional groups as well). Thanks!

**Comment by domibarton** [comment]
@robynbergeron: You're welcome. 

Thanks for your work guys!

**Comment by bcoca** [comment]
backported to stable-1.9 via 611084c92f70944346ebd3f2154884148fdddec0

## 

Brian Coca
