### ISSUE TITLE
pip module does not work with_items in Ansible 2.0

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible-modules-core#2552]
Here is the task I want to execute:

```
- name: install docker tools
  sudo: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-compose
    - docker-py
```

And here is the error output I get since Ansible 2.0:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! privilege output closed while waiting for password prompt:\nBECOME-SUCCESS-ebgrkuckgcfsbjxzsgqdryehkgxkotcd\n{\"virtualenv\": null, \"changed\": false, \"requirements\": null, \"name\": \"docker-py\", \"stdout\": \"Requirement already satisfied (use --upgrade to upgrade): docker-py in /usr/local/lib/python2.7/dist-packages\\nRequirement already satisfied (use --upgrade to upgrade): requests>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from docker-py)\\nRequirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from docker-py)\\nRequirement already satisfied (use --upgrade to upgrade): websocket-client>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-py)\\n\", \"cmd\": \"/usr/local/bin/pip install docker-py\", \"state\": \"present\", \"version\": null, \"stderr\": \"\"}\n"}
```

Before, with Ansible 1.9.4, this task works fine. I have no idea whats happening. When I execute the pip task manually, it runs fine:

```
sudo pip install --upgrade docker-compose docker-py
```

**Comment by dotsdl** [comment]
Does it hang for you as well? Mine makes it all the way through the list of things but then just sits there afterward, never appearing to move on to the next task.

**Comment by bcoca** [comment]
I ran your play against a debian 7 box and it 'just worked' TM, can you provide more information?

```
< PLAY >
 ------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 _____________________________ 
< TASK [install docker tools] >
 ----------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [deb7test] => (item=docker-compose)
ok: [deb7test] => (item=docker-py)
```

**Comment by ThomasSteinbach** [comment]
Yes. It is hard to reproduce. I ran the playbook on my Ubuntu 15.10 with Python 2.7.10 and it didn't work (The Ubuntu machine was control machine and target host likewise). Then I ran the same playbook from the Ubuntu machine but with an Ubuntu 14.04 server as target host and it works.

The behavior is, that the pip command didn't get the right password. It doesn't bother if I enter the correct password or any random password.

I jumped the commits back and forth and the error was introduced with commit https://github.com/ansible/ansible/commit/53e86f3130145ce40606cec32aef2858756a20ab, which merges PR https://github.com/ansible/ansible/pull/13261. With the prevous commit https://github.com/ansible/ansible/commit/e06b107d2dfd4682d807b7e871d3bcba501d4636 everything works fine.

Please tell me, if I can do more research.

**Comment by ThomasSteinbach** [comment]
... and I can just reproduce it when running the playbook on localhost with `ansible_ssh_connection=local`.

**Comment by ThomasSteinbach** [comment]
Meanwhile I believe it is not a pip problem but a problem with `local` connector. See https://github.com/ansible/ansible/issues/13624

**Comment by bcoca** [comment]
i suspect you meant `ansible_connection=local` as `ansible_ssh_connection` has never been a var in use.

One reason this might hang is due to pip locking, if you are on the same host (local) running multiple pip install/remove operations (1 fork per parallel host which the play targets), they'll block each other and probably prompt for input (I have not tested with pip, but this happens with other package managers).

**Comment by ThomasSteinbach** [comment]
@bcoca of couse I mean `ansible_connection=local`.

I think we can close this issue, as the bug is not with the pip module but with the local connection plugin as stated here https://github.com/ansible/ansible/issues/13624.

An evidence is that the playbook above works fine with `localhost ansible_ssh_host=127.0.0.1` setting in the inventory instead of `localhost ansible_connection=local`.

**Comment by bcoca** [comment]
closing in favor of the local plugin issue in  ansible/ansible#13624

**Comment by ThomasSteinbach** [comment]
However, I have this issue in Ansible 2.1 when deploying the task as described above on a vagrant 'ubuntu/trusty64' machine.
