### ISSUE TITLE
a preemptible instance

### ISSUE THREAD

**Issue by kernelt** [ansible/ansible-modules-core#2561]
Google cloud has a preemptible instance type. However an ansible can't run this instance and this option is not described in its docs http://docs.ansible.com/ansible/gce_module.html
It would be nice if we can to run a preemptible instance via ansible.

**Comment by jimi-c** [comment]
cc @erjohnso

**Comment by resmo** [comment]
feature has been merged in.

**Comment by qw1mb0** [comment]
This opportunity to appear in the next release 2.1? whether there is a release time frames ? And now, we can't use preemptible instance type?

**Comment by resmo** [comment]
expect 2.1 rc1 in hours
