### ISSUE TITLE
Question - How to pass arguments with Docker Module?

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#2566]
I need to pass arguments to the docker command and I have tried the following, but this makes the plugin crash. 

Is there a way to pass arguments using the ansible docker module? or is this not supported? 

In the mean time, I have shifted to using Shell module for now.

```
command:
- "-server -advertise 192.168.33.10 -bootstrap-expect 1 -ui-dir /ui"
```

is this the correct way to pass arguments to the docker command being run?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
