### ISSUE TITLE
Cloudformation module: requiring template during stack deletion

### ISSUE THREAD

**Issue by awasilyev** [ansible/ansible-modules-core#2575]
ansible 1.9.4, OS X 10.11

According to the documentation 'template' argument for cloudformation module required only when state=present. But execution failed when I try to delete stack without specifying template:

```
 ansible -i hosts localhost -m cloudformation -a 'stack_name=my state=absent'
 127.0.0.1 | FAILED >> {
     "failed": true, 
     "msg": "missing required arguments: template"
 }
```

**Comment by robynbergeron** [comment]
[module: cloud/amazon/cloudformation.py]

**Comment by robynbergeron** [comment]
@awasilyev -- Thanks for submitting this bug report.

@jsmartin --  thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by PaKempf** [comment]
You can workaround this issue by setting any existing template (or creating a fake one). The code will read it but it won't be used afterwise, yet still allows you to delete the stack.
