### ISSUE TITLE
Cannot create S3 buckets in us-east-1

### ISSUE THREAD

**Issue by edsonmarquezani** [ansible/ansible-modules-core#2578]
I can't create S3 buckets in _us-east-1_ region (US Standard) with _s3_bucket_ module. Setting _region_ attribute as another region makes it work, but using _us-east-1_ throws the following error:

`<Error><Code>InvalidLocationConstraint</Code><Message>The specified location-constraint is not valid</Message><LocationConstraint>us-east-1</LocationConstraint><RequestId>062E949D00F5D730</RequestId><HostId>fNQfoM+k/ug690XEwWY0MKYlXXOJDHaip6rXLDqfaxKcYJiPSebymIPVVIWYmQ7t</HostId></Error>`

I know it is from S3 API, which doesn't accept the value _us-east-1_, and if you want to create a bucket in that region, you should omit it. Ok. So, maybe you could blame Boto for it.

But, when I don't set a region (not in the task nor environment), I get another error, which I found to be Boto's too.

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: cannot concatenate 'str' and 'NoneType' objects`

Somehow a null location variable is ending up in this piece of code.

In **boto/s3/connection.py**:

```
     if location == Location.DEFAULT:
        data = ''
    else:
        data = '<CreateBucketConfiguration><LocationConstraint>' + \ 
                location + '</LocationConstraint></CreateBucketConfiguration>'
```

I went through Ansible's code, and couldn't understand why this is happening, once it seems to handle that condition.

In **ansible/modules/extras/cloud/amazon/s3_bucket.py**:

```
if region in ('us-east-1', '', None):
    # S3ism for the US Standard region
    location = Location.DEFAULT
else:
    # Boto uses symbolic names for locations but region strings will
    # actually work fine for everything except us-east-1 (US Standard)
    location = region
```

So, is that still a bug, or am I doing something very wrong?

I'm using the devel branch as for the time of this post and Boto 2.38. I made sure I didn't have an older version of both running here before I filled this bug report. I tried every form of setting the region attribute (with and without quotes, as variable and hardcoded, environment variable). I really can't understand why this is happening.

I hope you can reproduce it.

Thank you.

**Comment by robynbergeron** [comment]
Hi @edsonmarquezani -- 

The s3_bucket module is actually an extras module -- can you open the issue in the appropriate spot? :) Thanks! (https://github.com/ansible/ansible-modules-extras/issues/new)

**Comment by edsonmarquezani** [comment]
Ok, done. I wasn't sure where it belonged, so I posted it here. Thanks.

**Comment by robynbergeron** [comment]
Thanks for moving it. I'll close this one :)
