### ISSUE TITLE
yum missing validate_certs 

### ISSUE THREAD

**Issue by vmindru** [ansible/ansible-modules-core#2582]
yum is missing validate_certs option for localinstall , yum will fail to download an RPM from a selfsigned https URL.

**Comment by robynbergeron** [comment]
[module: packaging/os/yum.py]

@vmindru -- Thanks for submitting this feature idea (and the accompanying PR!)

@ansible/core team -- this one is in your court :)

**Comment by vmindru** [comment]
@robynbergeron  urw - there are 4-5 more core modules that need the same thing , i will send PR during next couple of days.

**Comment by abadger** [comment]
I'll go ahead and close this one since I've merged your yum fix but feel free to continue submitting PRs for the other modules you are interested in!
