### ISSUE TITLE
Typo in file module

### ISSUE THREAD

**Issue by mmulich** [ansible/ansible-modules-core#2585]
`errno.EEXISTS` should be `errno.EEXIST` (remove the 'S') here https://github.com/ansible/ansible-modules-core/blob/devel/files/file.py#L291 

This leads to something like:

``` python
{"changed": false, "failed": true,
 "msg": "There was an issue creating <path> as requested: 'module' object has no attribute 'EEXISTS'",
 "path": ...}
```

**Comment by mmulich** [comment]
Maybe a duplicate of #2473.

**Comment by robynbergeron** [comment]
[module: files/file.py]

**Comment by robynbergeron** [comment]
@pumazi -- Thanks for submitting this bug report.

@ansible/core team --- this module is yours :)

**Comment by andrenarchy** [comment]
Will the fix ship with a release anytime soon? I'm desperately trying to create a directory and get this error message with Ansible 2.0.0.2.

**Comment by leifmadsen** [comment]
This also breaks a couple of deployments that I'm attempting to deal with.

**Comment by alexbowers** [comment]
Any fix for this yet?

**Comment by mikeputnam** [comment]
Looks like the fix will land with releases tag [v2.0.1.0-0.1.rc1](https://github.com/ansible/ansible/commit/870a4b8dc1cd3b077946129b104815b9c7eca62c) which includes a core modules bump to b4a4f74724ae7d6b27cc5e6d793388ccfbd359eb which includes the actual fix https://github.com/ansible/ansible-modules-core/commit/483c9dac14ad50b93a8171370496a490d1351d20  No idea when it will reach pip, etc.

EDIT: I was able to proceed by just hand editing the python file on my Ansible 2.0.0.2 installation `sudo vim /usr/local/lib/python2.7/dist-packages/ansible/modules/core/files/file.py`  When the fix lands and I upgrade, my manual change will be replaced/negated by the new version.

**Comment by geerlingguy** [comment]
(Same as above, just for posterity—if you're on a Mac and used `sudo pip install ansible` to install, the file's located in `/Library/Python/2.7/site-packages/ansible/modules/core/files/file.py`).

Can't wait for the 2.0.1 release–I've now hit this error in seven different playbooks, and have also had to switch explicitly to 1.9.4 in tests for about 10 of my roles on Galaxy until it's fixed :)

**Comment by leifmadsen** [comment]
Same. I've reverted everything to 1.9.4 at this point. The current 2.x release is unusable.

Honestly, this feels like something that needs to be released as a hot fix as soon as possible.
