### ISSUE TITLE
Be able to unarchive the downloaded file from internet without storing it on the disk

### ISSUE THREAD

**Issue by zshamrock** [ansible/ansible-modules-core#2603]
##### Issue Type:
- Feature Idea
##### Ansible Version:

$ ansible --version
ansible 1.9.4
  configured module search path = None
##### Summary:

What I do a lot in my tasks

```
---                                                                                                                                                                               
- name: install Go lang
  become: yes
  shell: wget -O - --quiet https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz | tar -C /usr/local -xzf -
```

To download and unpack the file downloaded from the internet. It would be nice if it was possible to do this with ansible (in one) action without having manually store the file on the disk. As right now it is not possible to combine multiple tasks under the same name (will new `block` feature make it possible?)

**Comment by Jmainguy** [comment]
Unarchive module can download from the internet, unarchive it to where you want, and the original archive is deleted once the play ends, unless you have ANSIBLE_KEEP_REMOTE_FILES=1 set.

**Comment by bcoca** [comment]
also the by downloading the file you can make sure you get the entire archive before you start extracting, avoiding having network issues leave you with a partials extracted tree

**Comment by zshamrock** [comment]
@Jmainguy all right, have double checked now, but it comes with 2.0, but nice the option is already there:

```
If copy=no and src contains ://, the remote machine will download the file from the url first. (version_added 2.0)
```

@bcoca yes this could be the option, but in my use case it is not what I want to do (I use ansible to setup my Debian desktop ;) https://github.com/zshamrock/ididitagain

**Comment by Jmainguy** [comment]
@zshamrock Since this is added in 2.0, you ok with closing this out?

**Comment by zshamrock** [comment]
Yes, thank you as long as there is an option preventing the file to be downloaded a second time role is run (like `creates` option in other actions)
