### ISSUE TITLE
Documentation Core module user - Parameter skeleton miss version added

### ISSUE THREAD

**Issue by meersau** [ansible/ansible-modules-core#2605]
With ansible version 1.7.2 the parameter skeleton does not work:

$ ansible -i ansi-test test -m user -a "name=testuser createhome=yes skeleton=/etc/skel"
10.10.10.22 | FAILED >> {
    "failed": true, 
    "msg": "unsupported parameter for module: skeleton"
}

$ ansible --version
ansible 1.7.2

Parameter added with pull request #62 to devel.

On docs.ansible.com there is no hint, that the parameter was added with specific version or devel.

Thank in advance.
Alex

**Comment by robynbergeron** [comment]
[module: system/user.py]

**Comment by robynbergeron** [comment]
@meersau -- Thanks for submitting this bug report.

@sfromm -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.
