### ISSUE TITLE
"ssh connection closed waiting for sudo or su password prompt" error from running a template task again (the first time was fine)

### ISSUE THREAD

**Issue by tamakisquare** [ansible/ansible-modules-core#261]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Local machine: OS X 10.9.5
Remote machine: Ubuntu 14.04
##### Summary:

I have a `template` task with `sudo=yes`, `dest=/etc/supervisor/conf.d/foo.conf`, and `mode=0664`. It runs fine if the conf file does not already exist. Otherwise, I would get a **fatal error message**, _"ssh connection closed waiting for sudo or su password prompt"_. 

The task is executed with user 'vagrant', which has passwordless sudo enabled.

As a workaround for the time being, I place a `file` task right before the `template` task to ensure the conf file does not exist. 
##### Steps To Reproduce:

``` yaml
- name: Install Supervisor config file
  sudo: yes
  template: >
    src=foo.conf.j2
    dest=/etc/supervisor/conf.d/foo.conf
    mode=0664
```
1. Run the task
2. Ensure _foo.conf_ is created at the destination
3. Run the task again 
##### Expected Results:

The existing _foo.conf_ should get overwritten when the task ran the second time.

If it's by design that the `template` module does not overwrite existing file, then I would expect to see the kind of error message that tells its audience what's going on.
##### Actual Results:

Got a **fatal error message**, _"ssh connection closed waiting for sudo or su password prompt"_, which is confusing.

**Comment by tamakisquare** [comment]
False alarm. The error has nothing to do with whether or not the dest file already exists. The actual cause is the passwordless sudo setup for the remote user being used. When passwordless sudo is enabled for the remote user, the error occurs intermittently. Although I don't understand why the intermittent error, I think it's a minor issue in my case as I can simply disable the passwordless sudo.

**Comment by LennyLip** [comment]
same error, when 'sudo' is not installed on target system
