### ISSUE TITLE
 Unrecognized status from pull

### ISSUE THREAD

**Issue by chromerobv** [ansible/ansible-modules-core#2611]
i've looked at similar issues with the same errors and all say to go back to 1.8.2. the thing is i am using docker 1.8.2 and i still get this error...

docker: 1.8.2
docker-py: 1.1.0
ansible: 1.9.4

the really weird thing is i have 4 machines all the same, 2 throw the error the other 2 are fine same versions of everything on all.

failed: [c2-compute005] => {"changes": ["{\"stream\":\"Trying to pull repository docker.io/ehazlett/interlock ... \"}\r\n", "{\"status\":\"Pulling from ehazlett/interlock\",\"id\":\"latest\"}\r\n", "{\"status\":\"Already exists\",\"progressDetail\":{},\"id\":\"902b87aaaec9\"}", "{\"status\":\"Already exists\",\"progressDetail\":{},\"id\":\"9a61b6b1315e\"}", "{\"status\":\"Already exists\",\"progressDetail\":{},\"id\":\"afdaa3484cc6\"}", "{\"status\":\"Already exists\",\"progressDetail\":{},\"id\":\"59ed6f19b661\"}", "{\"status\":\"Already exists\",\"progressDetail\":{},\"id\":\"d9cd7ddad5de\"}", "{\"status\":\"Already exists\",\"progressDetail\":{},\"id\":\"45a524fd4303\"}", "{\"status\":\"Already exists\",\"progressDetail\":{},\"id\":\"c226738b7a52\"}", "{\"status\":\"Digest: sha256:b7ee0fe41a098df1e3f1d4f3da180c086ea1f38524c11a2cb7347775ed8a7a69\"}\r\n", "{\"status\":\"Status: Image is up to date for docker.io/ehazlett/interlock:latest\"}\r\n", "{}\r\n"], "failed": true, "status": ""}
msg: Unrecognized status from pull.

FATAL: all hosts have already failed -- aborting

**Comment by robynbergeron** [comment]
[module: cloud/docker/docker.py]

**Comment by robynbergeron** [comment]
@chromerobv -- Thanks for submitting this bug report.

@cove @softzilla @joshuaconner @smashwilson @zfil @thomassteinbach - thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by dustymabe** [comment]
This was fixed in https://github.com/ansible/ansible-modules-core/commit/64b8596250e58a55eee8f2d4323d35ca32a8cd53. Please close

**Comment by bcoca** [comment]
closingas per above
