### ISSUE TITLE
ansible 1.9.4 copy module - input file not found at src

### ISSUE THREAD

**Issue by ifelsefi** [ansible/ansible-modules-core#2620]
## ansible command

```
sysadmin@samgt[~/repos/playbooks]$ ansible-playbook ~/repos/playbooks/apache.yml -u root -e hosts=remotehost
```
## apache.yml

```

---
- hosts: "{{hosts}}"
  gather_facts: True
  roles:
    - apache
```
## failed task

```
- name: copy certificate and keys from samgt /work/certs
  copy: src=/work/certs/{{ cert }} dest=/etc/pki/tls/certs/{{ cert }}
```
## failed output

```
TASK: [apache | copy certificate and keys from samgt /work/certs] ************* 
fatal: [remotehost] => input file not found at /work/certs/remotehost.cer or /work/certs/remotehost.cer

FATAL: all hosts have already failed -- aborting
```
## file exists at samgt src on machine [samgt] from where ansible-playbook being ran

```
sysadmin@samgt[~/repos/playbooks]$ sudo ltr /work/certs/remotehost.cer
-rw-r--r-- 1 root root 2.4K Dec  3 11:25 /work/certs/remotehost.cer
```

Any idea why file not being found in src when it does exist?

**Comment by azaghal** [comment]
You should probably run the `ls -ltr` command as the very same user that actually runs Ansible on the `samgt` machine in order to verify it can access the file. Possibly the directories `/work` or `/work/certs` are not readable by this user. Take not you are running with `sudo` to list the file, so that will always work.

**Comment by jimi-c** [comment]
@JusticeForMikeBrown this does appear to be a sudo issue, as you're clearly using sudo in your last `ls` command but not when running the `ansible-playbook` command.  Can you confirm whether running ansible-playbook via sudo resolves the issue?
