### ISSUE TITLE
hg module not verifying https certs correctly (probably because of ignoring ~/.hgrc)

### ISSUE THREAD

**Issue by Petrox** [ansible/ansible-modules-core#2628]
We've got a hg repo with https access. The site is self signed, but we've got a cert.

So:

in .hgrc there exists this reference:

```
[web]
cacerts = ~/ca.cer
```

theres an [auth] block too, with username and password required.
also the ~/ca.cer exists.

I can clone the repo with:

```
hg clone https://url 
```

and it works fine.

In ansible:

```
hg: repo: https://url dest: somelocalpath
```

and I get:

```
failed: [oclear] => (item={'repo': 'https://url', 'dest': 'somelocalpath', 'force': True}) => {"failed": true, "item": {"dest": "somelocalpath", "force": true, "repo": "https://url"}}
msg: abort: error: _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

ansible 1.9.4
python 2.7.10
ubuntu14.04 (armhf)

Also this same setup (.hgrc [web] and [auth] contents) work fine with tortoisehg on windows too.

I believe ansible hg module should respect the .hgrc settings of the user as other tools do. 
(Like all libmysqlclient using software respects .my.cnf )

**Comment by Petrox** [comment]
Update: this might be in connection with ansible running as root, not the current user. Still need a solution though

**Comment by bcoca** [comment]
which server is the .hgrc file on? which server are you targeting with the play? what user has the .hgrc file, what are the remote_user and become_users set to?

if the .hgrc is not in the home of the same user that executes the action, i would not expect it to be read.

**Comment by Petrox** [comment]
As I have worked around this already and it's possible, that it was misconfiguration of become or sudo, I'll just close this as invalid, to let it sink. 

Thank you for your time.
