### ISSUE TITLE
Unhelpful error messages by OpenStack cloud module

### ISSUE THREAD

**Issue by teolupus** [ansible/ansible-modules-core#2640]
Error messages provided by the OpenStack cloud module are not helpful to indicate what is going wrong. For example, misspelling a key name or forgetting to specify a network (when more than one exist and this becomes a mandatory attribute) would both result in the following error:

TASK [Create a compute instance on the Catalyst Cloud] *************************
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "Error in creating instance"}

It would be nice to provide a more detailed error message, such as "invalid key name" or "more than one network available".

**Comment by bcoca** [comment]
cc @emonty @Shrews

**Comment by Shrews** [comment]
This should be fixed with PR: https://github.com/ansible/ansible-modules-core/pull/2805

**Comment by Shrews** [comment]
Since #2805 has merged, which I believe addresses your issue, and there has been no further comment on this, I'm going to close this report.
