### ISSUE TITLE
Bug: service module: "unable to set rcvar" in Check Mode due to mishandled SystemExit exception

### ISSUE THREAD

**Issue by apparentorder** [ansible/ansible-modules-core#2664]
**Issue Type**: Bug report
**Ansible version**: 1.9.4 (but seems to be present in HEAD as well)
**Environment**: FreeBSD 10.1 target

**Summary**:
The service module fails with message `unable to set rcvar` in Check Mode against FreeBSD (and probably any rc.conf-based system) without any error actually occurring

**Steps to reproduce**:

```
$ ansible -C foo -m service -a "name=ntpd state=started enabled=yes"
[...]
foo | FAILED >> {
    "failed": true, 
    "msg": "{\"msg\": \"changing service enablement\", \"changed\": true}\r\n{\"msg\": \"unable to set rcvar\", \"failed\": true}[...]
```

**Cause**:
- service_enable_rcconf() is run inside a try: block
- if changed is True and we are in check_mode, exit_json() is called (L993)
- exit_json() uses sys.exit(), which raises a SystemExit exception
- the calling try: block mishandles the SystemExit exception as the above error

While the issue could be easily fixed like this ...

```
    try:
        return self.service_enable_rcconf()
    except SystemExit:
        pass
    except:
        self.module.fail_json(msg='unable to set rcvar')
```

... I think the larger issue is that every service routine (not just _rcconf()) uses this scheme for an early exit from check_mode and thus would misbehave inside a try: block.

But the above change certainly is an interim solution.

**Comment by problame** [comment]
I did a little bit of debugging and found another problem on FreeBSD:

Multiline rcvars are allowed (check [here](https://www.freebsd.org/cgi/man.cgi?rc.conf%285%29))

```
ifconfig_lo0_aliases="\
        inet 10.123.234.1 netmask 0xffffff00 \
        inet 10.123.234.2 netmask 0xffffff00"
```

This does not work with shlex, hence shlex raises an exception, resulting in a confusing error message.

Checkout my PR https://github.com/ansible/ansible-modules-core/issues/4042, I fixed the problem by changing the module implementation to use `sysrc`.
