### ISSUE TITLE
synchronize module: rsync_opts problem

### ISSUE THREAD

**Issue by m-emelchenkov** [ansible/ansible-modules-core#267]
Issue Type:

Bug Report

Ansible Version:

ansible 1.7.2

Environment:

Mac OS 10.10 (with rsync 3.1.1 from Homebrew) / Ubuntu 14.04

Summary:

I've found a problem with rsync_opts in module synchronize. There is an option in rsync which contains comma, and this option will not be handled by the module correctly due to module design.

Steps To Reproduce:

Add rsync_opts="--iconv=UTF8-MAC,UTF-8"

Expected Results:

Comma should not be replaced by whitespace.

Actual Results:

Comma is replaced by whitespace and command halts.

Synchronize module contains these:
if rsync_opts:
cmd = cmd + " " + " ".join(rsync_opts)

That means in the result command we get space character instead comma and the command will halt due to this:
--iconv=UTF8-MAC UTF-8

Maybe I do not understand something, but why not to pass rsync_opts as string, not as a list? Then there will not be this problem exists, and separating parameters will be performed using space character.

I use workaround by patching "synchronize" file:
if rsync_opts:
cmd = cmd + " " + ",".join(rsync_opts)

Bug was opened on Jul 9, 2014 and time passed since then. I hope someone will take it into work.
https://github.com/ansible/ansible/issues/8074

**Comment by jody-frankowski** [comment]
--chmod=D700,F600 for example, seems to be problematic too.

**Comment by m-emelchenkov** [comment]
Please assign someone to this issue. If we just make workaround this may break something. i'm tired patching locally every new version.

**Comment by bcoca** [comment]
@mikhailguru has a PR been submitted?

**Comment by m-emelchenkov** [comment]
@bcoca What is PR?

**Comment by bcoca** [comment]
Pull Request, sorry, too used to the abbrevs ...

**Comment by m-emelchenkov** [comment]
@bcoca Ah, no. I don't feel it is a good patch, because it needs further investigation that it does not have any drawbacks, so I called it "workaround" in this issue instead submitting to the codebase. It will be nice to connect the module's author to this discussion to get feedback from him.

**Comment by bcoca** [comment]
the issue might not be with the module itself but with how module arguments get parsed in general

**Comment by davidvasandani** [comment]
Running into the same issue when trying to run the synchronize module though a bastion host.

```
rsync_opts='-e "ssh -o 'ProxyCommand ssh -q -A xxx.xxx.xxx.xxx -F /opt/wp/app/hegemon/apps/aws/ssh.config nc %h %p'"'
```

**Comment by davidvasandani** [comment]
I was doubling up my ProxyCommand config by calling it in the ssh.config and in the cli. Slimming it down to just the following fixed the issue.

```
rsync_opts='-e "ssh -F /opt/wp/app/hegemon/apps/aws/ssh.config"'
```

**Comment by m-emelchenkov** [comment]
In non-approved patch #877 was found the solution:

```
- synchronize:
    src: "../../../Sources/www/"
    dest: "/var/www/{{ domain }}/"
    delete: "yes"
    perms: "no"
    rsync_path: "sudo -u www-{{ host }} rsync"
    rsync_opts: ["--iconv=UTF8-MAC,UTF-8"]
```

I believe the issue can be closed because resolved.

**Comment by bcoca** [comment]
closing as per above
