### ISSUE TITLE
vmware_guest: feature request for snapshots

### ISSUE THREAD

**Issue by ronator** [ansible/ansible-modules-core#2671]
##### ISSUE TYPE

Feature Idea
##### COMPONENT NAME

vmware_guest module
##### ANSIBLE VERSION

N/A
##### SUMMARY

vmware_guest is an awesome core module to create, manage or delete VMware guests. This is already cool, but I _really_ miss a feature to create, manage and delete snapshots of certain VMware guests. 

When you have lots of Linux guests and want to keep your servers up-to-date I would consider snapshoting as a **killer** feature since there is no real way to roll back upgrades made to your Linux servers except you already use btrfs which I don't.

Enabling snapshoting with vmware_guests (which already needs/uses vmware-cmd) could minimize the risks of upgrading a Linux system and would become a big advantage for ansible compared to other "deployment solutions" ...

(sorry, I do not know how to label this as feature_idea)

**Comment by jctanner** [comment]
bot_broken

**Comment by jctanner** [comment]
@ronator I believe you may be correct that many people would want a snapshotting module, but we have consolidated all the newer vmware modules into the extras repo. If you are still interested in this feature, please file a new issue in https://github.com/ansible/ansible-modules-extras/issues

**Comment by ronator** [comment]
@jctanner Thank you a lot for your feedback. I will do so right away.

By the way, this module is called vsphere_guest and it is still listed there as a core module in ansible doc.
