### ISSUE TITLE
Module to create NAT gateway to AWS VPC

### ISSUE THREAD

**Issue by eeroniemi** [ansible/ansible-modules-core#2707]
Amazon introduced NAT gateways that can be created to VPC. This makes creating separate NAT EC2 instances obsolete in most cases. It would be great if I could create NAT gateways from Ansible, currently I don't think it's possible (please correct if I'm wrong).

More information about this feature: https://aws.amazon.com/blogs/aws/new-managed-nat-network-address-translation-gateway-for-aws/

**Comment by sivel** [comment]
As this is a request for a new module, it should be opened in -extras instead of -core

**Comment by eeroniemi** [comment]
Ok. Seems like someone opened issues about this to -extras repo - https://github.com/ansible/ansible-modules-extras/issues/1401
