### ISSUE TITLE
ec2_elb_lb is not idempotent when stickiness is defined / bug report

### ISSUE THREAD

**Issue by abrugnon** [ansible/ansible-modules-core#2709]
**Ansible  version**

```
ansible 2.1.0 (devel d203438a2c) last updated 2015/12/15 17:02:49 (GMT +200)
  lib/ansible/modules/core: (detached HEAD b1c0249045) last updated 2015/11/18 16:55:01 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 7da1f8d4ca) last updated 2015/11/18 16:55:01 (GMT +200)
```

**Environment:**
ubuntu 14.04

**Summary:**
When an ELB is created with stickiness, it runs well at the first time, but it fails on all subsequent calls.

**Steps to reproduce**

Here is a playbook that fails on second run

```
- hosts: 127.0.0.1
  connection: local

  tasks :
    - name : Nginx load balancer
      local_action:
        module : ec2_elb_lb
        name : elb-test-sticky
        state: present
        region : eu-west-1
        zones: 
            - eu-west-1a
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
        stickiness:
          enabled : yes
          type: application
          cookie : JSESSIONID
```

**Actual result :**
Result on 1st run : OK

Result on 2nd Run

```
 <Error>
    <Type>Sender</Type>
    <Code>LoadBalancerNotFound</Code>
    <Message>Cannot find Load Balancer e</Message>
  </Error>
```

**Expected Result**
No changes - no error

**Comment by tomfotherby** [comment]
I had this problem but it went away when I upgraded boto with `sudo pip install boto --upgrade`. It didn't work when I was on `2.20.1` and after the upgrade I was on `2.39.0`.

**Comment by jimi-c** [comment]
@abrugnon can you confirm which version of boto you're seeing this one, per the above comment?

**Comment by abrugnon** [comment]
as @tomfotherby said, I was in 2.20.1 (standard Ubuntu pkg). I removed it `sudo dpkg -r python-boto` and install the latest one with pip (`2.39.0`). Works fine now.

**Comment by jimi-c** [comment]
Thanks for the follow-up!
