### ISSUE TITLE
os_object parameters and docs don't align (file/filename)

### ISSUE THREAD

**Issue by j3p0uk** [ansible/ansible-modules-core#2721]
Trying to use the os_object module and the parameter is filename in code, but file in docs.

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: file"}

**Comment by Labutin** [comment]
Pull request: https://github.com/ansible/ansible-modules-core/pull/2740

**Comment by jimi-c** [comment]
Hi @j3p0uk, the above commit was merged, can you confirm whether or not you're still seeing this issue?

**Comment by j3p0uk** [comment]
I can see that the docs now say "filename" here: http://docs.ansible.com/ansible/os_object_module.html

So this is fixed.
