### ISSUE TITLE
git: Unclear error message "Failed to checkout" if there is a permission error

### ISSUE THREAD

**Issue by kevinburke** [ansible/ansible-modules-core#2736]
If I try to check out a Git repository into a directory that I don't have permission to write, I get the confusing message:

```
failed: [myhost] => {"failed": true}
msg: Failed to checkout branch master

FATAL: all hosts have already failed -- aborting
```

It's pretty unclear why the failure occurred or what needs to happen to fix it. This is due to the following lines in `source_control/git.py`, which obscure the error message from Git:

``` python
    if version != 'HEAD':
        if is_remote_branch(git_path, module, dest, remote, version):
            if not is_local_branch(git_path, module, dest, version):
                cmd = "%s checkout --track -b %s %s/%s" % (git_path, version, remote, version)
            else:
                (rc, out, err) = module.run_command("%s checkout --force %s" % (git_path, version), cwd=dest)
                if rc != 0:
                    module.fail_json(msg="Failed to checkout branch %s" % version)
                cmd = "%s reset --hard %s/%s" % (git_path, remote, version)
        else:
            cmd = "%s checkout --force %s" % (git_path, version)
```

I added logging in `git.py` and got the following for `out`.

``` json
{"stdout": "", "cmd": "/usr/bin/git clone --origin origin '' /home/twentyms/vrusability", "failed": true, "stderr": "fatal: could not create work tree dir '/home/twentyms/vrusability': Permission denied\n", "rc": 128, "msg": "fatal: could not create work tree dir '/home/twentyms/vrusability': Permission denied"}
```

Searching the issue history turned up the following commit, which appends useful information to the error message in a different place in `git.py`: https://github.com/stansonhealth/ansible-modules-core/commit/2a1b1aa82068b156a1279b4476b0941b251c307e

Maybe a similar approach needs to be applied to the `fail_json` call in question? Happy to work on this, but wondering if there was a reason that the message was being obscured.

**Comment by limbera** [comment]
I am experiencing this too. Commenting to be notified.

**Comment by stefanandres** [comment]
This is great.
It would be even better if the actual git command would appear in the log too.
I've had this problem a few times these days and needed to put my own debug code into git.py to find out that git-2.7 doesn't properly work with the ansible-git module.

**Comment by resmo** [comment]
Since #3022 has been merge, I mark this issue as resolved. Thanks!
