### ISSUE TITLE
docker-py not found in a virtualenv

### ISSUE THREAD

**Issue by pearofducks** [ansible/ansible-modules-core#2756]
Issue Type: Bug Report

Ansible Version: v2.0.0-0.7.rc2

Ansible Configuration: default

Environment: N/A

Summary:

The docker-py module is not found when running Ansible in a virtualenv.

Steps To Reproduce:
- Activate a new virtualenv
- `pip install ansible`
- `pip install docker-py`
- `ansible -i localhost, -c local -m docker -a "name=foo image=hello-world state=present" all`

Expected Results:

Ansible can run the `docker` module and find docker-py

Actual Results:

```
localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "`docker-py` doesn't seem to be installed, but is required for the Ansible Docker module."
}
```

**Comment by pearofducks** [comment]
This issue persists on 2.0.0.2, editing reproduction steps

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by Singletoned** [comment]
How is this a user question?  It's clearly a bug if ansible can't correctly detect that docker-py is installed.

**Comment by phylor** [comment]
Had the same problem. The following worked:

```
pip install six==1.10.0 docker-py==1.2.3
```

**Comment by eddie-dunn** [comment]
Please reopen this. Ansible should honor a user's virtualenv.

**Comment by bqbn** [comment]
As a workaround, I was able to run the ansible command with 

```
-e "ansible_python_interpreter=\"/usr/bin/env python\"" 
```

option. It also worked for me by adding the following line to the inventory file:

```
localhost ansible_python_interpreter="/usr/bin/env python"
```

I think the issue is ansible by default would use "/usr/bin/python" for its remote host environment. In this case, the "remote" is localhost, but "/usr/bin/python" is not the virtualenv.

**Comment by t1anchen** [comment]
This issue still existed on `docker-py==1.2.3`, `ansible==2.1.1.0`, `six==1.10.0` under virtualenv and broke my CI testing ...

**Comment by purplesmoke05** [comment]
I have same problem...
docker-py==1.10.1, ansible==2.1.1.0, six==1.10.0 on Ubuntu15.04
