### ISSUE TITLE
os_floating_ip module: can't associate a floating ip to an instance which has multiple ports

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#2779]
#### Issue Type:

Bug Report
#### Ansible Version:

2.1.0
commit: 45355cd5660da17350811d92a5144077910ea434
#### Ansible Configuration:

Default
#### Environment:

N/A
#### Summary:

For a nova instance having multiple ports, I specified a "fixed_address" and "network" which is the name of the external network but I got the following error.

```
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "unable to bind a floating ip to server 3b39ac58-44af-4578-9419-fef805d47202: More than one port was found for server {server} and no fixed_address was specified. It is not possible to infer correct behavior. Please specify a fixed_address - or file a bug in shade describing how you think this should work. (Inner Exception: No module named systemd)"}
```

`cloud/openstack/os_floating_ip.py` causes this. This module accepts `network` which is the name of the external network from which floating ips are created, but doesn't pass it to shade.

```
if state == 'present':
    server = cloud.add_ips_to_server(
        server=server, ips=floating_ip_address, reuse=reuse,
        fixed_address=fixed_address, wait=wait, timeout=timeout)
```

This should be like following:

```
  if state == 'present':
      server = cloud.add_ips_to_server(
          server=server, ips=floating_ip_address, reuse=reuse,
-         fixed_address=fixed_address, wait=wait, timeout=timeout)
+         fixed_address=fixed_address, wait=wait, timeout=timeout,
+         ip_pool=network)
```

**Work well if you specify `floating_ip_address`.**
#### Steps To Reproduce:

```
- name: associate a floating ip to the instance
  os_floating_ip:
    cloud: testing
    server: vm1
    fixed_address: 192.168.0.100
    network: ext_net
    reuse: yes
```

`reuse` doesn't affect the result
#### Expected Results:

Associated a floating ip to the instance
#### Actual Results:

Same as "Summary" above

```
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "unable to bind a floating ip to server 3b39ac58-44af-4578-9419-fef805d47202: More than one port was found for server {server} and no fixed_address was specified. It is not possible to infer correct behavior. Please specify a fixed_address - or file a bug in shade describing how you think this should work. (Inner Exception: No module named systemd)"}
```

**Comment by palmerabollo** [comment]
Same behaviour here with ansible 2.0.0.2 (insalled with brew).

**Comment by ghost** [comment]
@palmerabollo 

#2681 fixed this bug and was already merged. You won't have trouble if you use the latest commit. I'll close this issue.

**Comment by palmerabollo** [comment]
I see, thank you @tktk8924. Do you know if a new version 2.0.0.3 including this change will be released anytime soon?

**Comment by ghost** [comment]
@palmerabollo I'm not sure the exactly time. I recommend getting from source.

**Comment by palmerabollo** [comment]
Do you know why, even when ansible 2.0.1.0 is released, this issue is still present? I've tried it with `pip install ansible==2.0.1.0` and I get the same error

`More than one port was found for server {server} and no fixed_address was specified. It is not possible to infer correct behavior. Please specify a fixed_address - or file a bug in shade describing how you think this should work.`

``` sh
$ pip freeze | grep ansible
ansible==2.0.1.0
shade-ansible==1.0.0
```
