### ISSUE TITLE
mysql_user module syntax error deleting anonymous users

### ISSUE THREAD

**Issue by leehuk** [ansible/ansible-modules-core#2811]
When trying to delete anonymous users we're receiving the following error:

[13:49 root@ansible.ssh:/etc/ansible/playbooks]$ ansible -m mysql_user -a "user='' host_all=yes state=absent login_user=root login_password=***\* login_unix_socket=/var/lib/mysql/mysql.sock"  sysdev-leeh.frog.local  
sysdev-leeh.frog.local | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1452779357.18-216311000218666/mysql_user\", line 2733, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1452779357.18-216311000218666/mysql_user\", line 555, in main\r\n    changed = user_delete(cursor, user, host, host_all, module.check_mode)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1452779357.18-216311000218666/mysql_user\", line 330, in user_delete\r\n    if module.check_mode:\r\nNameError: global name 'module' is not defined\r\n", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}

**Comment by Jmainguy** [comment]
Can confirm, this exists

**Comment by leehuk** [comment]
Resolved by merged #2812
