### ISSUE TITLE
rax_dns_record module fails when adding PTR type record

### ISSUE THREAD

**Issue by wbentley15** [ansible/ansible-modules-core#282]
Issue Type: Bug Report
Ansible Version: Ansible 1.7.2

Environment: MAC OS X
Summary: When attempting to add a PTR type record, the module fails
Steps To Reproduce: create a DNS record with type of PTR and include the loadbalancer parameter.  Must have root domain already created (test.com).

```
- name: Create DNS PTR record for Load Balancer
  rax_dns_record: name=test.test.com data=<IP address> type=PTR loadbalancer=<ID of Load Balancer> region=IAD
```

Expected Results: new PTR DNS record should be created for Load Balancer
Actual Results: module fails with following error - 

```
line 161, in rax_dns_record_ptr
if len(found) != 1: UnboundLocalError: local variable 'found' referenced before assignment
```

**Comment by sivel** [comment]
I have submitted a bug fix at https://github.com/ansible/ansible/pull/9511

The code where this is impacted is now in shared module code that exists in the ansible project.

**Comment by wbentley15** [comment]
Thanks!!

**Comment by sivel** [comment]
The change has been merged in.

**Comment by wbentley15** [comment]
@sivel Thank you for the fast response.  What is the recommended way to pull these changes in now?

**Comment by sivel** [comment]
The recommended way of running the level version can be found at: http://docs.ansible.com/intro_installation.html#running-from-source
