### ISSUE TITLE
keystone_user should use Keystone v3 (stable)

### ISSUE THREAD

**Issue by adamn** [ansible/ansible-modules-core#283]
The OpenStack Identity API v3 is currently stable and keystone_user module should be upgraded to implement that version as the primary endpoint (falling back to v2.0).

[API v3](http://developer.openstack.org/api-ref-identity-v3.html)
[Unofficial Openstack modules for reference - no v2 there either](https://github.com/openstack-ansible/openstack-ansible-modules)

**Comment by eandersson** [comment]
Any update on this? The upcoming domain-token support for Keystone is only supported in V3.

**Comment by emonty** [comment]
@eandersson we have a set of replacement modules coming: #1598 ... it's fully v3 compatible.
