### ISSUE TITLE
URI module fails with variables in the JSON body

### ISSUE THREAD

**Issue by gbarnard2** [ansible/ansible-modules-core#2836]
From #13954:

The following task in a playbook errors because of the body option. If you replace the username and password variables with hard coded values, it works fine. Note my version was the one just before 2.0 was released. (Formatting is correct, but doesn't come out well in web app).

-- name: Connect to ansible with creds provided

```
uri:
url: https://{{ url }}/api/v1/authtoken/
method: POST
HEADER_Content-Type: application/json
body: '{ "username" : "{{ username }}", "password" : "{{ password }}" }'
validate_certs: no
return_content: yes
```

The following output from Ansible:

```
TASK: [Connect to ansible with creds provided] ********************************
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
File "/home/gbarnard/.ansible/tmp/ansible-tmp-1452538099.69-278641758230235/uri", line 2081, in
main()
File "/home/gbarnard/.ansible/tmp/ansible-tmp-1452538099.69-278641758230235/uri", line 416, in main
resp, content, dest = uri(module, url, dest, user, password, body, method, dict_headers, redirects, socket_timeut, validate_certs)
File "/home/gbarnard/.ansible/tmp/ansible-tmp-1452538099.69-278641758230235/uri", line 312, in uri
resp, content = h.request(url, method=method, body=body, headers=headers)
File "/usr/lib/python2.7/site-packages/httplib2/init.py", line 1605, in request
(response, content) = self.request(conn, authority, uri, request_uri, method, body, headers, redirections, cacekey)
File "/usr/lib/python2.7/site-packages/httplib2/__init_.py", line 1353, in request
(response, content) = self.conn_request(conn, request_uri, method, body, headers)
File "/usr/lib/python2.7/site-packages/httplib2/__init.py", line 1290, in _conn_request
conn.request(method, request_uri, body, headers)
File "/usr/lib64/python2.7/httplib.py", line 979, in request
self._send_request(method, url, body, headers)
File "/usr/lib64/python2.7/httplib.py", line 1013, in _send_request
self.endheaders(body)
File "/usr/lib64/python2.7/httplib.py", line 975, in endheaders
self._send_output(message_body)
File "/usr/lib64/python2.7/httplib.py", line 839, in _send_output
self.send(message_body)
File "/usr/lib64/python2.7/httplib.py", line 811, in send
self.sock.sendall(data)
File "/usr/lib64/python2.7/ssl.py", line 723, in sendall
v = self.send(data[count:])
TypeError: unhashable type

FATAL: all hosts have already failed -- aborting
```

@bcoca
Collaborator

**Comment by sivel** [comment]
Have you tried setting `body_type: json` ?  I believe that was one specific thing that `body_type` was added for.

**Comment by bcoca** [comment]
also either use |to_json filter or put a space before the first '{' to prevent YAML from picking up a dict:
`body: ' { "username" : "{{ username }}", "password" : "{{ password }}" }'`

**Comment by gbarnard2** [comment]
Yes! Absolutely I tried it. Did not work. Here’s a basic playbook for you to try. Just substitute the variables for those in your environment.

---
- name: Connect to Ansible API
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
      serverURL: "10.0.0.4"
      serverUser: "gbarnard2"
      serverPwd: "abc"
  
  tasks:
  - name: Connect to ansible with creds provided
    uri:
      url:  https://{{ serverURL }}/api/v1/authtoken/
      method: POST
      HEADER_Content-Type: application/json
      body: '{ "username" : "{{ serverUser }}", "password" : "{{ serverPwd }}" }'
      body_format: json
      validate_certs: no
      return_content: yes

Cheers,
Glenn Barnard
Developer
CSC / Cybersecurity Serviceshttp://www.csc.com/cybersecurity/offerings/45397/66069-managed_security_services

OUT OF OFFICE NOTICE:

CSC | t: 561-503-8539 | gbarnard2@csc.com | www.csc.comhttp://www.csc.com

**Comment by gbarnard2** [comment]
Brian, the space between ‘ and { worked. For my edification, could you show how to use |to_json filter?

Cheers,
Glenn Barnard
Developer
CSC / Cybersecurity Serviceshttp://www.csc.com/cybersecurity/offerings/45397/66069-managed_security_services

OUT OF OFFICE NOTICE:

CSC | t: 561-503-8539 | gbarnard2@csc.com | www.csc.comhttp://www.csc.com

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
