### ISSUE TITLE
django_manage breaks backwards compatibilitywith <2.0

### ISSUE THREAD

**Issue by geertn** [ansible/ansible-modules-core#2856]
The version of django_manage in ansible 2.0 assumes manage.py is executable. Before 2.0 it worked without manage.py being executable.

2.0:
fatal: [hostname]: FAILED! => {"changed": false, "cmd": "./manage.py collectstatic --noinput --settings=main.settings", "failed": true, "invocation": {"module_args": {"app_path": "/apppath", "apps": null, "cache_table": null, "clear": null, "command": "collectstatic", "database": null, "failfast": false, "fixtures": null, "link": null, "liveserver": null, "merge": null, "pythonpath": null, "settings": "main.settings", "skip": null, "testrunner": null, "virtualenv": "/apppath/.ve"}, "module_name": "django_manage"}, "msg": "[Errno 13] Permission denied", "rc": 13}

<2.0:
ok: [hostname] => {"app_path": "/apppath/", "changed": false, "cmd": "python manage.py collectstatic --noinput --settings=main.settings", "out": "\n0 static files copied to '/apppath/static', 897 unmodified.\n", "pythonpath": null, "settings": "main.settings", "virtualenv": "/apppath/.ve"}

Regardless if manage.py should or shouldn't be executable this breaks backwards compatibility.

**Comment by grahamu** [comment]
@geertn you are correct, this issue makes the ansible v2.x django_manage command unusable in virtual environments which have their own python path. For example, often we deploy identical code to a "staging" virtual environment and to a "production" virtual environment. When "staging" is activated we see:

```
(staging)$ which python
alias python='python2.7'
    ~/.virtualenvs/staging/bin/python2.7
```

Similarly, when "production" is activated we see:

```
(production)$ which python
alias python='python2.7'
    ~/.virtualenvs/production/bin/python2.7
```

Since python executables are different in different virtual environments, the python path cannot be specified in the manage.py shebang, which requires an absolute path to system executables.

This issue was introduced by [this commit](https://github.com/ansible/ansible-modules-core/commit/3b954edab2bf54c710b86d95482548b893d648fa).

To fix this I propose we restore `cmd = "python manage.py %s" % (command, )` when django_manage detects use of a virtual environment, and use `cmd = "./manage.py %s" % (command, )` if no virtual environment is detected.

I'm very interested to hear what @ludat thinks about this idea.

**Comment by ludat** [comment]
[This is the PR in question](https://github.com/ansible/ansible-modules-core/pull/1165)

IMHO the most elegant solution is to change the shebang in the manage.py (which by default has `#!/bin/pyhon` I think) with `#!/bin/env python` so [env](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/env.html) will parse the `PATH` (which was set by virtualenv) and use the correct python.

This way of referencing the python interpreter (or any interpreter in *nix) is [pretty old](https://mail.python.org/pipermail/tutor/2007-June/054816.html) and always [recommended](https://mail.python.org/pipermail/tutor/2007-June/054816.html), I'm not sure why django doesn't set it by default.

Thanks for tagging me :smile: and I hope I was helpful

**Comment by grahamu** [comment]
Thanks for your insight @ludat. After much experimentation I finally achieved a working solution for the updated django_manage in ansible 2.x. Here is my answer:

First, ensure the manage.py shebang is `#!/usr/bin/env python`. As seen in this [stackoverflow thread](http://unix.stackexchange.com/questions/12736/how-does-usr-bin-env-know-which-program-to-use), invoking /usr/bin/env is a portable method of specifying the appropriate python interpreter. In my testing this works in virtual environments as well as Mac OS X.

Second, ensure manage.py has correct permissions. My project initially showed:

```
-rw-r--r--   1 graham  staff  185 Jan 21 18:40 manage.py
```

which resulted in a permission error:

```
$ ./manage.py
-bash: ./manage.py: Permission denied
```

Invoking `chmod 755 manage.py` to get:

```
-rwxr-xr-x   1 graham  staff  178 Jan 23 11:03 manage.py
```

allowed execution of manage.py.

Finally, my manage.py file had an errant, invisible `\r` character at the end of the shebang line which caused /usr/bin/env to fail:

```
$ ./manage.py
env: python\r: No such file or directory
```

Once I created a new manage.py without the \r, assigned correct permissions, and used `/usr/bin/env python`, ansible 2.0.0.2 django_manage command worked fine.

Yes this is a backwards incompatible change. On the other hand I agree that using the shebang in manage.py is a much more portable and flexible construct for manage.py invocation. I will attach a PR for the django_manage documentation to explain the revised manage.py requirements.

**Comment by grahamu** [comment]
Added documentation pull request: https://github.com/ansible/ansible-modules-core/pull/2865.

**Comment by jimi-c** [comment]
As the above PR was merged in, are there any objects to closing this issue?

**Comment by ludat** [comment]
No objections from me.

**Comment by geertn** [comment]
No objections, thanks.

**Comment by grahamu** [comment]
No objection, thanks @jimi-c.

**Comment by jimi-c** [comment]
Thanks all, closing now.

**Comment by swasher** [comment]
When django  project developed under Vagrant, this may be difficult set executive permission to manage.py, due Vagrant has no support per-file permission.  This puts a user in a difficult position: either set up  executive permission for everything in share folder or do not use this module and run `manage` via shell module

**Comment by ludat** [comment]
I develop everyday using vagrant and I don't have that problem, @swasher are you using windows as the host OS?

**Comment by swasher** [comment]
Yes, Windows as the host. What permission(`mount_option`) you have in Vagrantgile in `config.vm.synced_folder` section?

**Comment by ludat** [comment]
I didn't express myself properly, I'm using Linux. I wanted to make clear that windows is the problem. Besides that you can use ansible to set the execution flag
