### ISSUE TITLE
Cannot set file mode in string syntax

### ISSUE THREAD

**Issue by KamilLelonek** [ansible/ansible-modules-core#289]
According to [documentation](http://docs.ansible.com/file_module.html) I should be able to set file's permission as follows:

```
- file: path=/etc/foo.conf state=touch mode="u+rw,g-wx,o-rwx"
```

However I get:

```
failed: [my_machine] => {"details": "invalid literal for int() with base 8: 'u=rw,g=r,o=r'", "failed": true, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/squid3/passwd", "size": 43, "state": "file", "uid": 0}
msg: mode needs to be something octalish

FATAL: all hosts have already failed -- aborting
```

Can I set file mode in string syntax rather than octalish one?

**Comment by bcoca** [comment]
what version of ansible are you running?

**Comment by KamilLelonek** [comment]
`ansible 1.7.2`

**Comment by blackreed9** [comment]
ansible 1.8.0 added the support for converting symbolic to octal.

This was verified in 1.9.1 against CentOS 6.4

**Comment by bcoca** [comment]
closing the issue as the documentation clearly states "as of 1.8"
