### ISSUE TITLE
mysql_user won't create user if password is empty

### ISSUE THREAD

**Issue by walro** [ansible/ansible-modules-core#2895]
**Bug Report**

**Ansible version**: 2.0.0.2

**Ansible Configuration**: See below

**Environment**: Running OS X 10.11.3, managing MySQL 5.5.46 on FreeBSD 10.2.

**Summary**: It seems like the `mysql_user` module won't create a user if the password is empty, this worked fine in 1.9.4.

**Steps To Reproduce**:

`ANSIBLE_CONFIG=ansible.vagrant.cfg ansible freebsd-mysql -m mysql_user -a "name='ha-check' password='' host='%'" --become`

**Expected results**: User is created.

**Actual results**: User is not created.

---

Contents of `ansible.vagrant.cfg`:

```
ask_sudo_pass=False
hostfile=.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
log_path=logs/ansible.vagrant.log
host_key_checking=False
remote_user=vagrant
private_key_file=~/.vagrant.d/insecure_private_key
retry_files_enabled=False
```

**Comment by bob-rove** [comment]
+1

**Comment by Jmainguy** [comment]
Whats the point in having a user where you don't know the password?

**Comment by walro** [comment]
> Whats the point in having a user where you don't know the password?

I do know the password, it's empty/not set/blank. HAProxy needs such a user to perform its [MySQL health check](https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-option%20mysql-check).

**Comment by Jmainguy** [comment]
@walro @bob-rove checkout #3368

**Comment by walro** [comment]
hey @Jmainguy as of Ansible 2.1 this seems to be working again, thanks!

I'll let you decide what to do with the issue, but from my point of view it may be closed.
