### ISSUE TITLE
'ansible-playbook --check' actually changes user UID on FreeBSD remote host

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible-modules-core#2918]
##### Issue Type:

Bug report
##### Ansible Version:

2.0.0.2-1ppa~trusty
##### Ansible Configuration:

[defaults]
gathering = smart
hash_behaviour = merge 
[privilege_escalation]
become=True
become_method=sudo 
become_user=root 
become_ask_pass=True 
##### Environment:

Ubuntu Trusty server, remote host on FreeBSD
##### Summary:

'ansible-playbook --check'  actually makes changes on FreeBSD host
Specifically, it changes user's UID when uid: parameter for user is changed in play
##### Steps To Reproduce:

change user's UID in play, run 'ansible-playbook --check' 
##### Expected Results:

Dry run with would-be changes.
##### Actual Results:

Change is actually applied in system.

**Comment by mattclay** [comment]
This appears to be the same issue as https://github.com/ansible/ansible/issues/14184.

**Comment by Vladimir-csp** [comment]
It seems so. Closing.
