### ISSUE TITLE
Custom TCP connection module 

### ISSUE THREAD

**Issue by luqasz** [ansible/ansible-modules-core#2937]
Hi.

I want to develop a module that will connect to MikroTik devices via its TCP API. I want my module to connect once and use that connection.

Sorry for posting this issue here, but I could not find any response on devel list
https://groups.google.com/forum/#!searchin/ansible-devel/mikrotik/ansible-devel/8KSudIIBzjE/5j-FtrrEGAAJ

Can you please help me find some documentation,examples ?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
