### ISSUE TITLE
win_ping module: exception handling error

### ISSUE THREAD

**Issue by tatobi** [ansible/ansible-modules-core#294]
Version:
ansible --version -vvvv
ansible 1.7.2

Run:
 tobi@unknown$ ansible win -i d2test_hosts -m win_ping -vvvv
<ec2-*********.eu-west-1.compute.amazonaws.com> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO ec2-********_.eu-west-1.compute.amazonaws.com
<ec2-**_*****_.eu-west-1.compute.amazonaws.com> WINRM CONNECT: transport=plaintext endpoint=https://ec2-**_*****_.eu-west-1.compute.amazonaws.com:5986/wsman
ec2-**_******.eu-west-1.compute.amazonaws.com | FAILED => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/**init**.py", line 561, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 666, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 837, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
  File "/usr/lib/pymodules/python2.7/ansible/runner/connection.py", line 34, in connect
    self.active = conn.connect()
  File "/usr/lib/pymodules/python2.7/ansible/runner/connection_plugins/winrm.py", line 132, in connect
    self.protocol = self._winrm_connect()
  File "/usr/lib/pymodules/python2.7/ansible/runner/connection_plugins/winrm.py", line 90, in _winrm_connect
    err_msg = str(exc.args[0])
IndexError: tuple index out of range

Fix: sudo mcedit /usr/lib/pymodules/python2.7/ansible/runner/connection_plugins/winrm.py
Using: err_msg = str(exc) is more secure to handle errors here
## Code:

```
       try:
            protocol.send_message('')
            _winrm_cache[cache_key] = protocol
            return protocol
        except WinRMTransportError, exc:
            #err_msg = str(exc.args[0])
            err_msg = str(exc)
```

---

**Comment by sivel** [comment]
I believe this is actually already taken care of in devel 

See https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/connection_plugins/winrm.py#L90

**Comment by tatobi** [comment]
Ahh, ok sorry, I overlooked it.

**Comment by cchurch** [comment]
What @sivel said.

Fixed by https://github.com/ansible/ansible/commit/07f12539eee2faac5fe831cd31f1f0a5d3e7e661
