### ISSUE TITLE
Authorized_key doesn't support 'exclusive' parameter

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#2969]
##### Issue Type:

 Bug Report
##### Ansible Version:

1.9.4 and 2.0.0.2
##### Ansible Configuration:

N/A
##### Environment:

Debian Jessie (LMDE2)
##### Summary:

The authorized_key module doesn't support 'exclusive' parameter
##### Steps To Reproduce:

```
- name: Install admin public keys
  authorized_key: user={{ item.name }}
    key="{{ item.ssh_key }}"
    exclusive=true
  with_items: global.admins
  when: item.ssh_key is defined
```
##### Expected Results:

Remove old keys from ~/.ssh/authorized_keys before adding this one and keep old key when none specified.
##### Actual Results:

When I add the exclusive=yes parameter to the authorized_key module, the playbook fails with:

> msg: unsupported parameter for module: exclusive

I have Ansible installed through PIP on Debian with version 1.9.4.
While the documentation states this is supported from version 1.9 and above, I still get the same error after upgrading to version 2.0.0.2

**Comment by scottbrown** [comment]
I don't see an error when I use the `exclusive` parameter with my role in Ansible 2.0.0.2.

Here's a snippet from my role.  Note that I'm using the nested attribute structure.  It shouldn't make a difference, only more readable to me.

```
- name: users | copy ssh keys to user
  authorized_key:
    user: "scott"
    key: "{{ ssh_key }}"
    exclusive: true
  become: yes
```

and checking the stable 2.0.0.1 branch shows that the `exclusive` parameter is an optional attribute on the module:

https://github.com/ansible/ansible-modules-core/blob/stable-2.0.0.1/system/authorized_key.py#L462

And Feb. 5, 2015 is when it was added to the project: https://github.com/ansible/ansible-modules-core/commit/e0c5b4340ddd9698c4321dca3edaf1a55bf3e3f2

You can check in the bowels of where pip stores the ansible code on your computer to make sure that it has the code I referenced above, but I bet it's the same if you say that you upgraded to 2.0.0.2

**Comment by jimi-c** [comment]
@tkteun could you please validate that you are in fact seeing this on 2.0? It appears to be a 2.0 option only and should be working fine there.

**Comment by ghost** [comment]
~~un~~fortunately, I cannot reproduce this issue anymore with the current Ansible 2.1.0.0 or when I downgrade to 2.0.0.2.
