### ISSUE TITLE
Feature Idea: Specify name when creating aws vpc

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/ansible-modules-core#2986]
##### Summary:

When vpc's are created today they are not named, making viewing via aws console cryptic as the name field is blank.  Adding a name option and using that value to populate the Name field in the console would be a nice improvement.

**Comment by groorj** [comment]
Hi,

You can do that by setting tags:

```
        state: present
        cidr_block: "{{ aws_vpc_cidr_block }}"
        resource_tags:
          Name: "{{ aws_vpc_name }}"
          Environment: "{{ aws_vpc_envname }}"
```

Regards,
--Gustavo

**Comment by MichaelBaydoun** [comment]
Thanks @groorj
