### ISSUE TITLE
Oracle Open Stack (kollacli deploy)

### ISSUE THREAD

**Issue by skylabreddy** [ansible/ansible-modules-core#3001]
While I am installing oracle Open Stack on oracle Linux I see below error. 
[root@osmn /]# kollacli deploy

FLUSHING FACT CACHE ***********************************************************

PLAY [haproxy;mysqlcluster-api;rabbitmq;cinder-api;glance-api;keystone;nova-api;neutron-server;swift-proxy-server] ***

GATHERING FACTS ***************************************************************
ok: [osmn.ssa.softlayer.com]

TASK: [common | Starting Ansible container] ***********************************
failed: [osmn.ssa.softlayer.com] => {"error": "APIError(HTTPError('500 Server Error: Internal Server Error',),)", "failed": true}
msg: Failed to pull the specified image: ico04.ssa.softlayer.com:5443/oracle/ol-openstack-kolla-ansible:2.0.2

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/usr/share/kolla/site.retry

osmn.ssa.softlayer.com     : ok=1    changed=0    unreachable=0    failed=1

ERROR: Command Failed
[root@osmn /]#

Can some one help on this issue. its great help to me. thanks.

**Comment by nitzmahone** [comment]
# Should This Be Filed Elsewhere?

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be something that should be filed against another project or bug tracker, and let us explain our reasons for thinking this: 

Kolla is not maintained by Ansible - please file issues at the Kolla repo: https://github.com/openstack/kolla

If you can stop by the tracker or forum for one of those projects, we'd appreciate it.  

Should you still wish to discuss things further, or if you disagree with our thought process, please stop by one of our two mailing lists:
- https://groups.google.com/forum/#!forum/ansible-project
- https://groups.google.com/forum/#!forum/ansible-devel

We'd be happy to discuss things.

Thank you once again!

**Comment by skylabreddy** [comment]
Hi 

Thanks for quick replay. 

I've resolved the issue. The issue is add your CA certificate to Docker. 
I didn't executed those steps ,After executed those steps its moving forward without any issue. 
Those steps are below. 
5. To enable authentication with the Docker registry, add your CA certificate to Docker. Replace
registry_hostname with the fully qualified domain name (FQDN) of the machine hosting the Docker
registry. The registry port is assumed to be running on port 5000, but yours may be running on port
5443, or some other number. The final command here assumes path is the location on the host of the
CA certificate for your domain. The final command copies and renames the domain certificate to the
location required by Docker.
$ mkdir -p /etc/docker/certs.d/registry_hostname:port
$ cp path/domain.crt /etc/docker/certs.d/registry_hostname:port/ca.crt
If you want to use a self-signed CA certificate, you must distribute the public certificate to all master
and target nodes, in the location:
/etc/docker/certs.d/registry_hostname:port/ca.crt
For example, to create a self-signed certificate:
$ mkdir -p /var/lib/registry/conf.d
$ cd /var/lib/registry/conf.d
$ openssl req -newkey rsa:4096 -nodes -sha256 -keyout domain.key -x509 -days 365 -out domain.crt
$ chmod 600 domain.key
$ mkdir -p /etc/docker/certs.d/registry_hostname:port
$ cp /var/lib/registry/conf.d/domain.crt /etc/docker/certs.d/registry_hostname:port/ca.crt
Make sure the domain name you use when creating the CA certificate is identical to the FQDN of the
Docker registry host.
Copy the ca.crt file to all master and target nodes to the /etc/docker/
certs.d/registry_hostname:port/ directory. This step is not required when using a verified CA
certificate, it is only required for self-signed certificates.
$ sudo scp /etc/docker/certs.d/registry_hostname:port/ca.crt \
root@myremotenode:/etc/docker/certs.d/registry_hostname:port/ca.crt
