### ISSUE TITLE
yum reinstall results rpm "does not update installed package"

### ISSUE THREAD

**Issue by gustavomcarmo** [ansible/ansible-modules-core#3066]
##### Issue Type:

Bug Report
##### Ansible Version:

2.0.0.2
##### Environment:

Red Hat Enterprise Linux Server release 6.7
##### Summary:

Since I've upgraded the version from 1.9.4 to 2.0.0.2, the yum task executed more than once results the error:

/var/tmp/yum-root-ABkoEr/jdk-7u79-linux-x64.rpm: does not update installed package.
##### Steps To Reproduce:

playbook.yml:

  tasks:
- name: Install oracle java 1.7.0_79
  yum: name={{pkgrepo}}/java/jdk/jdk-7u79-linux-x64.rpm state=present
##### Expected Results:

ok
##### Actual Results:

failed

**Comment by Jmainguy** [comment]
Unable to reproduce on latest devel and 2.0.0.2

Target was centos6, maybe this is a bug related to just RHEL and not Centos?

```
[root@phy01 test]# ansible -i hosts all -m yum -a "name=https://pulp.soh.re/pulp/repos/sohre/el6/haproxy-1.5.10-1.el6.x86_64.rpm state=present"
centos6.soh.re | SUCCESS => {
    "changed": true, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "Loaded plugins: fastestmirror\nSetting up Install Process\nExamining /var/tmp/yum-root-AWKAJ8/haproxy-1.5.10-1.el6.x86_64.rpm: haproxy-1.5.10-1.el6.x86_64\nMarking /var/tmp/yum-root-AWKAJ8/haproxy-1.5.10-1.el6.x86_64.rpm to be installed\nDetermining fastest mirrors\n * base: mirror.jgotteswinter.com\n * epel: mirrors.n-ix.net\n * extras: mirror.softaculous.com\n * updates: centos.datente.com\nResolving Dependencies\n--> Running transaction check\n---> Package haproxy.x86_64 0:1.5.10-1.el6 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package     Arch       Version          Repository                        Size\n================================================================================\nInstalling:\n haproxy     x86_64     1.5.10-1.el6     /haproxy-1.5.10-1.el6.x86_64     2.0 M\n\nTransaction Summary\n================================================================================\nInstall       1 Package(s)\n\nTotal size: 2.0 M\nInstalled size: 2.0 M\nDownloading Packages:\nRunning rpm_check_debug\nRunning Transaction Test\nTransaction Test Succeeded\nRunning Transaction\n\r  Installing : haproxy-1.5.10-1.el6.x86_64                                  1/1 \n\r  Verifying  : haproxy-1.5.10-1.el6.x86_64                                  1/1 \n\nInstalled:\n  haproxy.x86_64 0:1.5.10-1.el6                                                 \n\nComplete!\n"
    ]
}
[root@phy01 test]# ansible -i hosts all -m yum -a "name=https://pulp.soh.re/pulp/repos/sohre/el6/haproxy-1.5.10-1.el6.x86_64.rpm state=present"
centos6.soh.re | SUCCESS => {
    "changed": false, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "https://pulp.soh.re/pulp/repos/sohre/el6/haproxy-1.5.10-1.el6.x86_64.rpm: Nothing to do"
    ]
}
[root@phy01 test]# ansible -i hosts all -m yum -a "name=/tmp/haproxy-1.5.10-1.el6.x86_64.rpm state=present"                                                                                   
centos6.soh.re | SUCCESS => {
    "changed": false, 
    "msg": "", 
    "rc": 0, 
    "results": []
}
[root@phy01 test]# rpm -qa ansible
ansible-2.1.0-0.git201602191535.11f081c.devel.el7.centos.noarch
[root@phy01 test]# ansible -i hosts all -m yum -a "name=/tmp/haproxy-1.5.10-1.el6.x86_64.rpm state=present"
centos6.soh.re | SUCCESS => {
    "changed": false, 
    "msg": "", 
    "rc": 0, 
    "results": []
}
[root@phy01 test]# ansible -i hosts all -m yum -a "name=/tmp/haproxy-1.5.10-1.el6.x86_64.rpm state=present"
centos6.soh.re | SUCCESS => {
    "changed": false, 
    "msg": "", 
    "rc": 0, 
    "results": []
}
[root@phy01 test]# rpm -qa ansible
ansible-2.0.0.2-0.git201601142217.7de237c.HEAD.el7.centos.noarch
```

**Comment by sdodson** [comment]
I ran into similar problems with RHEL 7.1 and I found that upgrading both yum-3.4.3-132.el7 and yum-utils-1.1.31-34.el7 resolved the issue. Obviously the versions of yum and yum-utils in RHEL 6.7 are much different but have you tried to see if they're the latest available?

**Comment by gustavomcarmo** [comment]
I believe this is a bug related do RHEL 6.7.

And unfortunatelly, "no packages marked for update".

Name        : yum
Arch        : noarch
Version     : 3.2.29
Release     : 69.el6
Size        : 4.6 M
Repo        : installed
From repo   : anaconda-RedHatEnterpriseLinux-201507020259.x86_64
Summary     : RPM package installer/updater/manager
URL         : http://yum.baseurl.org/
License     : GPLv2+

Name        : yum-utils
Arch        : noarch
Version     : 1.1.30
Release     : 30.el6
Size        : 307 k
Repo        : installed
From repo   : anaconda-RedHatEnterpriseLinux-201507020259.x86_64
Summary     : Utilities based around the yum package manager
URL         : http://yum.baseurl.org/download/yum-utils/
License     : GPLv2+

**Comment by bcourtine** [comment]
I noticed the same problem, but for me, it is a module bug, not correlated to yum/yum-utils version: the same playbook works with Ansible 1.9.X and fails with Ansible 2.X.

Here is the report I submitted by mistake on the Ansible core project (https://github.com/ansible/ansible/issues/14997). I hope it can help:

##### Issue Type:
- Bug Report

##### Ansible Version:

```
ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides
```

##### Ansible Configuration:

No configuration tunning.

##### Environment:

Running Ansible compiled from source on Linux Mint, targetting a CentOS host.

##### Summary:

With Ansible 1.9.4, using yum module to install a remote rpm works.
When running the playbook several times, the tasks appears as "changed" every time, but it doesn't fail.

With Ansible 2.0.0.2, it is broken.
At the first run, the rpm is installed.
When I run the playbook again, the tasks fails.

##### Steps To Reproduce:

Here is a minimal playbook that reproduce the problem (the problem can probably be reproduced with other remote rpm files):

```
---
- hosts: test_host
  tasks:
    - name: Postgresql repository installation
      yum:
        name: "http://yum.postgresql.org/9.5/redhat/rhel-6-x86_64/pgdg-centos95-9.5-2.noarch.rpm"
        state: present
```

##### Expected Results:

Output for this playbook with Ansible 1.9.4:

```
PLAY [test_host] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [test_host]

TASK: [Postgresql repository installation] ************************************ 
ok: [test_host]

PLAY RECAP ******************************************************************** 
test_host                  : ok=2    changed=0    unreachable=0    failed=0
```

##### Actual Results:

Same playbook with Ansible 2.0.0.2:

```
PLAY [test_host] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [test_host]

TASK: [Postgresql repository installation] ************************************
fatal: [test_host]: FAILED! => {"changed": true, "failed": true, "msg": "Erreur : Rien à faire\n", "rc": 1, "results": ["Modules complémentaires chargés : fastestmirror, security\nConfiguration du processus d'installation\nExamen de /var/tmp/yum-root-PAp4J1/pgdg-centos95-9.5-2.noarch.rpm : pgdg-centos95-9.5-2.noarch\n/var/tmp/yum-root-PAp4J1/pgdg-centos95-9.5-2.noarch.rpm : ne met pas à jour le paquet installé.\n"]}

PLAY RECAP ******************************************************************** 
test_host                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by Jmainguy** [comment]
unable to reproduce @bcourtine report.

```
[root@phy01 test]# ansible-playbook -i hosts site.yml 

PLAY [test_host] ***************************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************

[root@phy01 test]# vi site.yml 
[root@phy01 test]# ls^C
[root@phy01 test]# ansible-playbook -i hosts site.yml 

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [centos6.soh.re]

TASK [Postgresql repository installation] **************************************
changed: [centos6.soh.re]

PLAY RECAP *********************************************************************
centos6.soh.re             : ok=2    changed=1    unreachable=0    failed=0   

[root@phy01 test]# ansible-playbook -i hosts site.yml 

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [centos6.soh.re]

TASK [Postgresql repository installation] **************************************
ok: [centos6.soh.re]

PLAY RECAP *********************************************************************
centos6.soh.re             : ok=2    changed=0    unreachable=0    failed=0   

[root@phy01 test]# cat hosts
centos6.soh.re
[root@phy01 test]# cat site.yml 
---
- hosts: all
  tasks:
    - name: Postgresql repository installation
      yum:
        name: "http://yum.postgresql.org/9.5/redhat/rhel-6-x86_64/pgdg-centos95-9.5-2.noarch.rpm"
        state: present
[root@phy01 test]# rpm -qa ansible
ansible-2.1.0-0.git201604051806.4b0aa12.devel.el7.centos.noarch
```

**Comment by gustavomcarmo** [comment]
Now that No-Cost RHEL Developer Subscription is available (http://developers.redhat.com/blog/2016/03/31/no-cost-rhel-developer-subscription-now-available/), please try to reproduce on RHEL.

**Comment by TheLastWilson** [comment]
I am new to ansible but have found what I think is the same issue. It appears it is effected by centos vs redhat. Worked fine for me on centos but the new RHEL devel subscription does appear to have the issue.

[root@node01 ~]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[root@node03 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Comment by DamienGombaultRecia** [comment]
Hi.

Today, I have updated my Fedora system with **ansible-2.0.1.0-2.fc23.noarch** (from ansible-**1.9.4-1.fc23.noarch**)

Since the Ansible update, on my CentOS 7 (up to date) systems I get this error when the rpm is already installed:

```
TASK [packages/zabbix : install zabbix-release package] ************************
fatal: [wiki-infra]: FAILED! => {"changed": true, "failed": true, "msg": "Erreur : Rien à faire\n", "rc": 1, "results": ["Modules complémentaires chargés : fastestmirror\nExamen de /var/tmp/yum-root-DIrj2C/zabbix-release-3.0-1.el7.noarch.rpm : zabbix-release-3.0-1.el7.noarch\n/var/tmp/yum-root-DIrj2C/zabbix-release-3.0-1.el7.noarch.rpm : ne met pas à jour le paquet installé.\n"]}
```

with this task :

```
- name: install zabbix-release package
  yum: name=http://repo.zabbix.com/zabbix/{{zabbix_version}}/rhel/{{ansible_distribution_major_version}}/x86_64/zabbix-release-{{zabbix_version}}-{{zabbix_release_build}}.el{{ansible_distribution_major_version}}.noarch.rpm state=present
  when: ansible_distribution == 'CentOS'
  tags: repositories
```

Variables :

```
zabbix_version: 3.0
zabbix_release_build: 1
```

**Comment by DamienGombaultRecia** [comment]
Hi.
I have updated Ansible to version 2.0.2.0 (ansible-2.0.2.0-1.fc23.noarch RPM from koji build).
I cannot reproduce the problem.

**Comment by Id2ndR** [comment]
This only happen with french language, and rhel7.1 play host (ansible-2.0.1.0-2.fc23).
$ LANG=fr_FR.UTF-8 ansible-playbook playbook.yml # failed (but worked with rhel6.5 play host)
$ LANG=fr_FR ansible-playbook playbook.yml # failed (but worked with rhel6.5 play host)
$ LANG=en_US ansible-playbook playbook.yml # worked (with both rhel65 and rhel7.1 play hosts)

**Comment by tobilg** [comment]
I fails when using german, too:

```
- name: Add the repository
  yum: name=http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm state=present
```

results in 

```
fatal: [host-11102]: FAILED! => {"changed": true, "failed": true, "msg": "Fehler: Nichts zu tun\n", "rc": 1, "results": ["Geladene Plugins: fastestmirror\n/var/tmp/yum-root-PGqMWs/mesosphere-el-repo-7-1.noarch.rpm wird untersucht: mesosphere-el-repo-7-1.noarch\n/var/tmp/yum-root-PGqMWs/mesosphere-el-repo-7-1.noarch.rpm: aktualisiert installierte Pakete nicht.\n"]}
```

on 

```
$ ansible --version
ansible 2.0.1.0
```

**Comment by Liberski** [comment]
Polish: 

```
- name: ensure nodejs repo in place
  yum:
    name='https://rpm.nodesource.com/pub_4.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'
    state=present
    update_cache=yes
```

Results in:

```
fatal: [integrations-staging2]: FAILED! => {"changed": true, "failed": true, "msg": "Błąd: Nie ma niczego do zrobienia\n", "rc": 1, "results": ["Wczytane wtyczki: fastestmirror\nSprawdzanie /var/tmp/yum-root-r1LNXL/nodesource-release-el7-1.noarch.rpm: nodesource-release-el7-1.noarch\n/var/tmp/yum-root-r1LNXL/nodesource-release-el7-1.noarch.rpm: nie aktualizuj zainstalowanego pakietu.\n"]} 
```

on:

```
$ ansible --version 
ansible 2.0.1.0
```

When I added:
`module_lang = en_US.UTF-8`
In ansible.cfg, everything passed correctly.

**Comment by gustavomcarmo** [comment]
I've just noticed that the version 2.0.2.0 has fixed the issue. Thanks!

**Comment by batkins61** [comment]
I am seeing this same problem on Ansible 2.2.1.0, en_US.UTF-8, yum version 3.4.3, RHEL version 7.3

The problem appears to be that yum exits with RC=1 and considers "Nothing to do" an error:

 `"msg": "Error: Nothing to do\n", "rc": 1`

Here's the full error:

`failed: [rhel-host4] (item=[u'/tmp/Storagegrid/StorageGRID-Webscale-Service-10-4-0-10.4.0-20170214.2329.6131640.x86_64.rpm', u'/tmp/Storagegrid/StorageGRID-Webscale-Images-10-4-0-10.4.0-20170215.1643.924b05b.x86_64.rpm']) => {"changed": true, "failed": true, "item": ["/tmp/Storagegrid/StorageGRID-Webscale-Service-10-4-0-10.4.0-20170214.2329.6131640.x86_64.rpm", "/tmp/Storagegrid/StorageGRID-Webscale-Images-10-4-0-10.4.0-20170215.1643.924b05b.x86_64.rpm"], "msg": "Error: Nothing to do\n", "rc": 1, "results": ["Loaded plugins: product-id, search-disabled-repos, subscription-manager\nThis system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.\nExamining /tmp/Storagegrid/StorageGRID-Webscale-Service-10-4-0-10.4.0-20170214.2329.6131640.x86_64.rpm: StorageGRID-Webscale-Service-10-4-0-10.4.0-20170214.2329.6131640.x86_64\n/tmp/Storagegrid/StorageGRID-Webscale-Service-10-4-0-10.4.0-20170214.2329.6131640.x86_64.rpm: does not update installed package.\nExamining /tmp/Storagegrid/StorageGRID-Webscale-Images-10-4-0-10.4.0-20170215.1643.924b05b.x86_64.rpm: StorageGRID-Webscale-Images-10-4-0-10.4.0-20170215.1643.924b05b.x86_64\n/tmp/Storagegrid/StorageGRID-Webscale-Images-10-4-0-10.4.0-20170215.1643.924b05b.x86_64.rpm: does not update installed package.\n"]}`

Note, this only happens with _state: latest_.  It works fine with _state: present_.

**Comment by mightypenguin** [comment]
I'm seeing this error with 2.4.0.0 but not with 2.3.2.0.
Should probably reopen this issue.

**Comment by seblatre** [comment]
This does not add anything to the problem but I'm getting the same issue with Ansible 2.4 when applying playbook to CentOs 6.8.

**Comment by willthames** [comment]
Please raise a new issue on the ansible/ansible repo (if there's not one already)

**Comment by dvershinin** [comment]
To anyone experiencing the issue. The error really says what it is. I was a bit puzzled at it but here's how it happened to me:

* My playbook installs percona-release RPM installed and the URL to it is hardcoded in playbook (i.e. ```http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm```)
* Sometime ago I **manually** did ```yum upgrade``` which also upgraded percona-release to ```0.1.4``` (this is where problems start!)
* Now running the ansible playbook, it tries to install percona-release ```0.1.3``` again (of course, because it is hardcoded to URL of that). Thus: ```does not update installed package``` message.
* By coincidence it happened the same time when I upgraded Ansible to 2.4 :)

So if you have a *-release package installed form external RPM URL, make sure it's not already newer on the system to what you're trying to install with Ansible and update your URL in playbook.

So my fix was to put different (more up-to-date) release URL to playbook:

```http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm```

**Comment by mightypenguin** [comment]
It appears that an issue has already been created that covers this:
https://github.com/ansible/ansible/issues/31350

**Comment by seblatre** [comment]
I added my comments to the ticket ansible/ansible#31350. Thanks @mightypenguin.
