### ISSUE TITLE
docker_image: support --pull option

### ISSUE THREAD

**Issue by rwky** [ansible/ansible-modules-core#3086]
##### Issue Type:

Please pick one and delete the rest:
- Feature Idea
##### Plugin Name:

docker_image
##### Summary:

It would be good if this module supported the `--pull                          Always attempt to pull a newer version of the image` option

**Comment by bcoca** [comment]
cc @chouseknecht

**Comment by chouseknecht** [comment]
Agreed. Will update the doc.

**Comment by bcoca** [comment]
I think a `force=no|yes` option would be a good way to control this

**Comment by bcoca** [comment]
I was thinking that the tls_ and docker_  params should be moved to
module_utils

On Tue, Mar 1, 2016 at 8:42 AM, Chris Houseknecht notifications@github.com
wrote:

> Yeah, I've been thinking about this. I didn't want to bring image stuff
> into this module. I thought a perfectly clean separation of concerns was a
> good idea. But... I know the current module does. It is quite convenient to
> take care of multiple steps in one task. It would be a nice value-add.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible-modules-core/issues/3086#issuecomment-190728425
> .

## 

---

Brian Coca

**Comment by chouseknecht** [comment]
This is now part of docker_image and will ship in 2.1.0.0rc2
