### ISSUE TITLE
Typo in file module (os.isdir instead of os.path.isdir)

### ISSUE THREAD

**Issue by ansianne** [ansible/ansible-modules-core#3089]
##### Issue Type:
- Bug Report
##### Plugin Name:

file
##### Ansible Version:

2.0.0.2 / devel
##### Ansible Configuration:

default
##### Environment:

N/A
##### Summary:

There may be a typo in file.py 
https://github.com/ansible/ansible-modules-core/blob/devel/files/file.py#L312
`if not (ex.errno == errno.EEXIST and os.isdir(curpath)):`

os.isdir should be os.path.isdir

This results in 
`'module' object has no attribute 'isdir'`

when the condition is hit

**Comment by geerlingguy** [comment]
Noticed the same with Ansible 2.0.1:

```
TASK [Ensure Drupal files folder exists.] **************************************
fatal: [10.0.1.61]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "There was an issue creating /mnt/nfs/files as requested: 'module' object has no attribute 'isdir'", "owner": "root", "path": "/mnt/nfs/files", "size": 4096, "state": "directory", "uid": 0}
changed: [10.0.1.62]
```

The patch referenced above fixed it. Thanks!

**Comment by dbolotin** [comment]
The same issue arises in latest ansible 2.0.2.0-0.3.rc3 release.
