### ISSUE TITLE
Wrong type of quote used in win_template documentation on webpage for jinja2 newline_sequence header

### ISSUE THREAD

**Issue by tothdavid** [ansible/ansible-modules-core#3105]
##### Issue Type:

Documentation Report
##### Plugin Name:

win_template
##### Ansible Version:

ansible 1.9.4
  configured module search path = None

But actually this is irrelevant, as the current documentation on the website is wrong.
##### Ansible Configuration:

Irrelevant.
##### Environment:

N/A
##### Summary:

The documentation on the website for win_template module says the following:
In order to ensure windows line endings are in the generated file, add the following header as the first line of your template: #jinja2: newline_sequence:’\r\n’ and ensure each line of the template ends with \r\n

However if you copy paste this to the actual template you create it will fail with the following error message:
fatal: [hostname] => {'msg': 'SyntaxError: invalid syntax (<unknown>, line 1)', 'failed': True}

Which is because if you look close you will see that the wrong kind of quote is used on the page: ’ instead of '.
This is mainly an issue, because it is really hard to notice and the error message is also does not describe the problem well.

Also I it seems like the right quote is used in the module documentation py file, it's just the webpage that is wrong.
##### Steps To Reproduce:

copy paste the header from the note on the win_template module page to a j2 file and use this file to deploy a template to a windows machine using the win_template module.
##### Expected Results:

Create the file from template with correct windows line endings.
##### Actual Results:

fatal: [hostname] => {'msg': 'SyntaxError: invalid syntax (<unknown>, line 1)', 'failed': True}

**Comment by jhawkesworth** [comment]
Thanks for spotting this.

I probably just need to put the whole thing inside double back quotes so that the rendering doesn't attempt to make smart quotes.
