### ISSUE TITLE
Variable created by the module "register" is erased if it is used a second times with "when" condition

### ISSUE THREAD

**Issue by bipbip007** [ansible/ansible-modules-core#3106]
##### Issue Type:
- Bug Report
##### Plugin Name:

register or test condition
##### Ansible Version:

```
ansible 1.9.4
```
##### Ansible Configuration:

N/A
##### Environment:

Redhat7
##### Summary:

Variable created by the module "register" is erased if it is used a second times with "when" condition
##### Steps To Reproduce:

  ansible-playbook -vvl test32 -e user_group=linux test_group.yml

```
 - name: Check if group is present when user_group is defined
    shell: /usr/bin/getent group {{ user_group }} | /usr/bin/wc -l | tr -d ' '
    register: group_exist
    when: user_group is defined

  - debug: var=group_exist

  - name: Check if group is present when user_group is not defined
    shell: /usr/bin/getent group {{ user_account }} | /usr/bin/wc -l | tr -d ' '
    register: group_exist
    when: user_group is not defined

  - debug: var=group_exist
```
##### Expected Results:

If the first command is executed and register a value. After the second test condition, the variable should have again the value.
For the moment, the variable is erased.
The workaround is to create a new variable with the second test condition.
##### Actual Results:

I use 2 times the same variable. If the first condition result is registered because user_group is defined. In the second command, the variable should not be erased because the test condition is not correct.

```
GATHERING FACTS ***************************************************************
<test32> REMOTE_MODULE setup
ok: [test32]

TASK: [Check if group is present when user_group is defined] ******************
<test32> REMOTE_MODULE command /usr/bin/getent group linux | /usr/bin/wc -l | tr -d ' ' #USE_SHELL
changed: [test32] => {"changed": true, "cmd": "/usr/bin/getent group linux | /usr/bin/wc -l | tr -d ' '", "delta": "0:00:00.009792", "end": "2016-02-24 13:11:45.877598", "rc": 0, "start": "2016-02-24 13:11:45.867806", "stderr": "", "stdout": "1", "warnings": []}

TASK: [debug var=group_exist] *************************************************
ok: [test32] => {
    "var": {
        "group_exist": {
            "changed": true,
            "cmd": "/usr/bin/getent group linux | /usr/bin/wc -l | tr -d ' '",
            "delta": "0:00:00.009792",
            "end": "2016-02-24 13:11:45.877598",
            "rc": 0,
            "start": "2016-02-24 13:11:45.867806",
            "stderr": "",
            "stdout": "1",
            "stdout_lines": [
                "1"
            ],
            "warnings": []
        }
    }
}

TASK: [Check if group is present when user_group is not defined] **************

TASK: [debug var=group_exist] *************************************************
ok: [test32] => {
    "var": {
        "group_exist": {
            "changed": false,
            "skipped": true
        }
    }
}

PLAY RECAP ********************************************************************
test32                     : ok=4    changed=1    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Registration is not conditional, when a task is skipped the registered var will have `{'skipped' = True}` so subsequent tasks can check if it was skipped or not.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
