### ISSUE TITLE
ec2_vpc_route_table doesn't remove route tables

### ISSUE THREAD

**Issue by mkocikowski** [ansible/ansible-modules-core#3125]
Issue Type:

bug report

Module name: 
ec2_vpc_route_table

Ansible Version:

ansible 2.0.0.2

Summary:

running ec2_vpc_route_table with state=absent doesn't remove the route table.

**Comment by mscherer** [comment]
Could you give more information, like the playbook snippet you used, etc ? I do not use aws so I cannot verify this, but it might help someone to reproduce the issue.

**Comment by mkocikowski** [comment]
Please delete the issue, I don't know why it got created, as I was writing the description I got it to work, my apologies, I must have fat fingered the submit issue.
