### ISSUE TITLE
New feature Needed in os_server module

### ISSUE THREAD

**Issue by ksingh7** [ansible/ansible-modules-core#3155]
##### Issue Type:

- Feature Idea
##### Plugin Name:

os_server
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Environment:

N/A
##### Summary:

os_server module does not provide any parameter to specify openstack instance system-group information. This is very much needed to setting affinity to newly launched instance.

The equivalent argument provided by nova boot as well as openstack server create command is `--hint group=b75981a0-b5f2-4365-bcb0-b9d1dfc24111`

It nice to have a parameter in ansible os_server module like 
group: "{{ system_group_name_or_ID }}"

We need this feature in os_server module

https://raymii.org/s/articles/Openstack_Affinity_Groups-make-sure-instances-are-on-the-same-or-a-different-hypervisor-host.html

**Comment by davidaah** [comment]
@ksingh7 check out #3172 , I believe this is what you are looking for

**Comment by davidaah** [comment]
Example:

```
  ...  
  scheduler_hints:
      group: "<group id>"
```

**Comment by ksingh7** [comment]
@davidaah  yes this is what it need, Thanks :)

**Comment by mscherer** [comment]
Since #3172  was merged, I am closing this one
