### ISSUE TITLE
yum package and locale settings

### ISSUE THREAD

**Issue by cmodijk** [ansible/ansible-modules-core#3235]
##### Issue Type:
- Bug Report
##### Plugin Name:

yum.py
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /Users/cliff/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

N/A
##### Environment:

OS X 10.11.3
CentOS 7.x
##### Summary:

I'm using ansible from my Mac and it send my current locale to CentOS and al the error's are know in dutch. So when i'm using a rpm to be installed from a url i get the error `Fout: Niets te doen` but the code checks for the error `Nothing to do`
- https://github.com/ansible/ansible-modules-core/blob/devel/packaging/os/yum.py#L668
- https://access.redhat.com/solutions/974273

I have tried different server side settings to change the LOCALE but i'm not succesvol to do so. I also think ansible could set there own locale to always match the right locale. 
##### Steps To Reproduce:

Use CentOS 7 and OS X with dutch locale 

```
- yum:    name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          state=present
```
##### Expected Results:

The command should not do anything 
##### Actual Results:

```
fatal: [default]: FAILED! => {"changed": true, "failed": true, "msg": "Fout: Niets te doen\n", "rc": 1, "results": ["Geladen plugins: fastestmirror\nOnderzoeken /var/tmp/yum-root-dueMAo/epel-release-latest-7.noarch.rpm: epel-release-7-5.noarch\n/var/tmp/yum-root-dueMAo/epel-release-latest-7.noarch.rpm: is geen update voor geïnstalleerd pakket.\n"]}
```

**Comment by mscherer** [comment]
This was likely fixed by https://github.com/ansible/ansible-modules-core/commit/d7fac82f97c153af08dbea2b2ae9718b19abeb8a

**Comment by cmodijk** [comment]
@mscherer it seems like a fix how could i test this? Is it already released?

**Comment by mscherer** [comment]
The easiest is to take ansible from git and run it from here. ( git clone https://github.com/ansible/ansible.git ; cd ansible ; git submodule update --init --recursive ; source hacking env-setup  and that's it, you can run the checkout from the current shell )

**Comment by cmodijk** [comment]
Hi @mscherer i think there is a typo in the command the source commands needs a slash like this the following: 

```
git clone https://github.com/ansible/ansible.git ; cd ansible ; git submodule update --init --recursive ; source hacking/env-setup
```

But with this version it's fixed thx for the help!
