### ISSUE TITLE
[WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running sudo

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#3287]
I have EC2 instances and need to run commands with sudo. How to avoid this warning?

[WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running sudo

You cannot "become" root and there is no password involved.  The ec2_user is allowed to sudo without a password.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
