### ISSUE TITLE
azure: Rename module to azure-vm to support future expansion

### ISSUE THREAD

**Issue by nyasara** [ansible/ansible-modules-core#329]
Issue Type: Feature Idea
Ansible Version: Ansible 1.5.4
Environment: N/A
Summary: To allow future expansion into more control over Azure, the module name should be changed to "azure-vm" to make it easier to integrate future modules (i.e. creating a service should actually be handled by a theoretical "azure-service" module).  Doing it now before the azure module adoption is too wide and this becomes a breaking change would probably be for the best.
Steps To Reproduce: N/A
Expected Results: N/A
Actual Results: N/A

**Comment by rcarmo** [comment]
I think this issue should be closed, since the Azure APIs have been transitioning to Resource Manager abstractions for a while now.

**Comment by gregdek** [comment]
Agreed with @rcarmo, closing.
