### ISSUE TITLE
Allowed_address_pairs in os_port can't be set to only an ip range since fix parameters type commit

### ISSUE THREAD

**Issue by fxk8y** [ansible/ansible-modules-core#3301]
##### Issue Type:
- Bug Report
##### Plugin Name:

os_port
##### Ansible Version:

```
ansible 2.1.0
  config file = /home/fxk8y/Dokumente/kubernetesAutoDeployment/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
host_key_checking = False
command_warnings = False

[privilege_escalation]
become = True
become_method = sudo
become_user = root

[ssh_connection]
ssh_args = -o ControlMaster=no
```
##### Environment:

Provisioning Ubuntu 15.04 instances from Ubuntu 15.10.
shade version: 1.5.1

shade runs on localhost, that's the Ubuntu 15.10 one.
##### Summary:

Since commit f71542ccf22583bf7eb214ed6abbcdaf5f18df96 of 12. feb it isn't possible anymore to only specify an ip address range for allowed_address_pairs in os_port module.
The problem came up while writing a Kubernetes deployment playbook for OpenStack which first boots the instances and then provisions them in one rush.
Both the OpenStack API and the shade library permit supplying only the ip but since the fix parameter type issue os_port prohibits this so we would have to first create the ports, query their dynamically assigned macs and then set the address range, but if you do supply only the  ip range to neutron it automatically uses the newly generated mac as second parameter while creating the network port.

Kubernetes needs allowed_address_pairs to be set to 10.0.0.0/8 in OpenStack otherwise the firewall would block the internal network communication of the Pods inside the cluster.
##### Steps To Reproduce:

Run the following snippet with ansible 2.1.0:

```
- name: Create network ports
  os_port:
    cloud: ts
    name: "{{item}}"
    network: "{{network_name}}"
    allowed_address_pairs:
      - ip_address: 10.0.0.0/8
    security_groups:
      - kubernetes
    state: present
  with_sequence: start=0 end={{instance_cnt}} format=kubernetes%d-port
```

The mac address of the port can't be supplied here because it is not known at the moment and not predictable.
##### Expected Results:

I expected the creation of the ports to complete without errors as it does in Ansible 2.0.1.0

```
changed: [localhost] => (item=kubernetes0-port)
```
##### Actual Results:

normal output:

```
TASK [Create network ports] ****************************************************
failed: [localhost] (item=kubernetes0-port) => {"failed": true, "item": "kubernetes0-port", "msg": "argument allowed_address_pairs is of type <type 'list'> and we were unable to convert to dict"}
```

debug output:

```
TASK [Create network ports] ****************************************************
task path: /home/fxk8y/Dokumente/kubernetesAutoDeployment/main.yml:14
ESTABLISH LOCAL CONNECTION FOR USER: root
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1458642387.89-250376251738384 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1458642387.89-250376251738384 `" )'
localhost PUT /tmp/tmpmEXGIb TO /root/.ansible/tmp/ansible-tmp-1458642387.89-250376251738384/os_port
localhost EXEC /bin/sh -c 'LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1458642387.89-250376251738384/os_port; rm -rf "/root/.ansible/tmp/ansible-tmp-1458642387.89-250376251738384/" > /dev/null 2>&1'
failed: [localhost] (item=kubernetes0-port) => {"failed": true, "invocation": {"module_args": {"allowed_address_pairs": [{"ip_address": "10.0.0.0/8"}], "cloud": "ts", "endpoint_type": "public", "name": "kubernetes0-port", "network": "Net1", "no_security_groups": false, "security_groups": ["kubernetes"], "state": "present", "timeout": 180, "verify": true, "wait": true}, "module_name": "os_port"}, "item": "kubernetes0-port", "msg": "argument allowed_address_pairs is of type <type 'list'> and we were unable to convert to dict"}
```

**Comment by Shrews** [comment]
Ah, looks like we set the wrong type. It should be a 'list'. Will look at getting this fixed ASAP. Thanks for the report.

**Comment by Shrews** [comment]
PR #3303 should fix this for you. I've also added new tests in shade that will test these options to make sure that they actually work and do not break them again:

https://review.openstack.org/295760

**Comment by fxk8y** [comment]
Yep now it works as intended thank you for your fast help!
