### ISSUE TITLE
apt_key module doesn't pick up the proxy environment and roles can't add apt key

### ISSUE THREAD

**Issue by David-Gil** [ansible/ansible-modules-core#3336]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

apt_key
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

Linux ed2f0deff4ed 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I'm using Docker with this image: scottmiller171/ansible-docker-images:ubuntu-14.04
##### SUMMARY

I configure the proxy in the environment of the container changing /etc/environment and /etc/apt/apt.conf.d/apt.conf to hold the environment variables. The apt module can update the cache and install without problems in roles from Ansible Galaxy.

But when one of those roles has a apt_key task, it doesn't pick up the proxy environment variables and fails. I have to manually modify the role and add an environment  with the proxy to the apt_key task for the role to properly work.

Roles should work out of the box.
##### STEPS TO REPRODUCE
- Configure proxy variables (/etc/environment and /etc/apt/apt.conf.d/apt.conf)
- Run, for example, the role greendayonfire.mongodb, which uses the apt_key module
##### EXPECTED RESULTS

apt_key module should pick up the proxy environment variables as apt module does
##### ACTUAL RESULTS

Key download times out:

```
TASK [greendayonfire.mongodb : Add APT key] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to download key at http://docs.mongodb.org/10gen-gpg-key.asc: Request failed: <urlopen error timed out>"}
```

**Comment by David-Gil** [comment]
Works in development version 2.1.0

**Comment by gersilex** [comment]
The problem seems to be back in 2.2.0.0. I can confirm it working with Release 2.1.0.0.
