### ISSUE TITLE
Synchronize module do not expand ansible_ssh_private_key_file variable

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible-modules-core#3339]
##### Issue Type:
- Bug Report
##### Component Name:

synchronize module
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /home/david/gitbi/lifemall/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

(nothing)
##### Environment:

Ubuntu 15.10
##### Summary:

Origin : https://github.com/ansible/ansible/issues/15015

I am using variable in ansible_ssh_private_key_file variable and the module do not "render" it in order to have a constant string. E.g. "{{ playbook_dir }}/some/path" is not rendered to "/playbook/path/some/path"
##### Steps To Reproduce:

Set ansible_ssh_private_key_file to some content with variables
Use synchronize module ... It fail.

Then hack:

```
- name: Make synchronize works
  set_fact:
    ansible_ssh_private_key_file: '{{ ansible_ssh_private_key_file }}'

- name: Go!
  synchronize: ...
```
##### Expected Results:

It works!
##### Actual Results:

```
fatal: [server]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --archive --rsh '/usr/bin/ssh -i {{ environment_directory }}/ssh/keys/local_rsa -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/home/david/project/\" \"vagrant@192.168.56.4:/var/www/project/test/source/\"", "failed": true, "msg": "Warning: Identity file {{ not accessible: No such file or directory.\nssh: Could not resolve hostname environment_directory: Name or service not known\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]\n", "rc": 255}
```

**Comment by markusthoemmes** [comment]
Seeing the very same issue.

**Comment by woodcoder** [comment]
Also seeing this in Ansible 2.0.1.0 on OS X.

The `ansible_ssh_private_key_file` set in a vars_file including a variable of `{{ keypair_name }}` is not expanded in the rsync call in the synchronize module.  Even though it is correct when using ssh and in debug messages.

The given workaround:

```
- name: workaround to make synchronize work
  set_fact:
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
```

works for me.

**Comment by magnetik** [comment]
Same with ansible 2.1.0 on ubuntu 14.04

**Comment by tima** [comment]
@davidfischer-ch I see in the actual results what you mean, but I need more specific to how you're calling the module.

EDIT: needs_info

**Comment by tima** [comment]
@davidfischer-ch and others: I believe https://github.com/ansible/ansible/pull/16349 may resolve this. Could you please verify here?

**Comment by tima** [comment]
resolved_by_pr ansible/ansible#16349
