### ISSUE TITLE
eos_template with replace parameter set , replaces entire configuration with the output['updates']

### ISSUE THREAD

**Issue by petereh** [ansible/ansible-modules-core#3366]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

ansible 2.1.0
  config file = 
  configured module search path = Default w/o overrides
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The replace parameter in eos_template does not work as expected/documented , instead of replacing the config on the device with the configuration specified with the src:  parameter , it replaces the entire config on the device with the output['updates']  , and in most cases this  results in loss of connection to  the device and wiping out almost all configuration on the device .

Replace parameter is key for many reasons such as if you are running a version of code that does not support merging configs and diff generation , i also saw another issue with eos_template where ACL rules with same sequence number cannot be modified ( this is another case where the replace parameter working properly will solve that problem)

@privateip please can you look into this 
##### STEPS TO REPRODUCE

see test playbook below

---
- hosts: DEVICEA
  gather_facts: no
  connection: local
  tasks:
  - name: push  Configs
    eos_template:
      username: user
      password: pass
      host: DEVICEA
      transport: eapi
      use_ssl: false
      port: 80
      src: /usr/share/ztpserver/files/configs/DEVICEA.cfg
      replace: true
    register: output
  - debug: var=output['updates']
  - name: save config
    eos_command:
      username: user
      password: pass
      host: DEVICEA
      commands:
        - copy running-config startup-config
##### EXPECTED RESULTS

I expected the configuration on DEVICEA  to be replaced with the configuration specified with src: parameter
##### ACTUAL RESULTS

the configuration on DEVICEA was replaced with output ['updates'](this is a bag bug that could have negative operational impact)

**Comment by privateip** [comment]
fixed in 6b8a920
