### ISSUE TITLE
ansible_os_family = "NA" on Archlinux host (1.8-git)

### ISSUE THREAD

**Issue by firecat53** [ansible/ansible-modules-core#34]
##### Issue Type:

Bug report (originally reported https://github.com/ansible/ansible/issues/8732)
##### Ansible Version:

$ ansible --version
ansible 1.8
##### Environment:

Archlinux host
##### Summary:

ansible_os_family no longer returns "Archlinux" for my Arch machines. It now returns "NA"
##### Steps To Reproduce:

ansible -m setup <any configured Arch hostname>|grep ansible_os_family
##### Expected Results:

```
    "ansible_os_family": "Archlinux", 
```
##### Actual Results:

```
    "ansible_os_family": "NA", 
```

**Comment by Jmainguy** [comment]
This can be closed out once @mantiz fix is merged. Great work mantiz.

**Comment by bcoca** [comment]
closing as both PRs above should have fixed
