### ISSUE TITLE
cloud/docker.py not supporting "omit" policy

### ISSUE THREAD

**Issue by undying** [ansible/ansible-modules-core#340]
Hello!
Just trying do run docker containers in such way:

``` yaml
- name: starting docker container
  docker: >
    image={{ image }}:{{ version }}
    env={{ env|default(omit) }}
```

but in that way I'm getting an error:
One or more undefined variables: 'omit' is undefined

I'm also tried such hints but no use:

``` yaml
- name: starting docker container
  docker: >
    image={{ image }}:{{ version }}
    {%if env is defined %}env={{ env }}{% endif %}
```

Error I've got is: A variable inserted a new parameter into the module args

When I'm trying this way:

``` yaml
- name: starting docker container
  docker: >
    image={{ image }}:{{ version }}
    env={% if env is defined %}{{ env }}{% else %}{{ None }}{% endif %}
```

I have another error:

``` sh
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-orsyqhficegebvdjxmbzpkjukyawuaiu
Traceback (most recent call last):
  File "/home/kron/.ansible/tmp/ansible-tmp-1416233616.15-142824592042916/docker", line 2130, in <module>
    main()
  File "/home/kron/.ansible/tmp/ansible-tmp-1416233616.15-142824592042916/docker", line 700, in main
    manager = DockerManager(module)
  File "/home/kron/.ansible/tmp/ansible-tmp-1416233616.15-142824592042916/docker", line 394, in __init__
    self.env = dict(map(lambda x: x.split("=", 1), self.module.params.get('env')))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

So, how can I ommit variable if it is not set?

Thank you.

**Comment by mpdehaan** [comment]
So there's nothing in the docker module that understands "omit" per se, nor does there have to be.  It just keeps the variable from being passed.

If you upgrade to 1.8 (devel branch, releasing very soon) you'll be able to use the omit trick.

There really isn't a way without, other than having two "docker:" stanzas one for each form, so omit is definitely the easier way to go.

If you have further questions, feel free to stop by ansible-project list to discuss.  Thanks!
