### ISSUE TITLE
Update ec2 module to use boto3?

### ISSUE THREAD

**Issue by raags** [ansible/ansible-modules-core#3421]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

ec2 module
##### SUMMARY

Are there plans or any on going effort to port the ec2 module to use boto3? Certain functionality is only available in boto3 now, and boto team isn't taking any feature requests. For example spot block requests which are only supported in boto3.

This issue is to get feedback if such plans are afoot, or if there is any reason to not do so. Thanks.

**Comment by bcoca** [comment]
New modules and features can use boto3, but we are NOT migrating the existing functionality from boto as many users cannot easily upgrade.

We hope to have all existing modules work with both versions.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible-devel on irc.freenode.net  
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
