### ISSUE TITLE
Junos_template module failing

### ISSUE THREAD

**Issue by jf1cloutier** [ansible/ansible-modules-core#3422]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

network/junos/junos_template
##### ANSIBLE VERSION

ansible 2.1.0
##### CONFIGURATION

No specific configuration in ansible.cfg and no ANSIBLE env variables.
##### OS / ENVIRONMENT

Ubuntu 14.04.3
##### SUMMARY

I can't get the junos_template module to work with juniper devices.  I guess there is specific requirements on the juniper devices (what devices/OS version is supported).  
Please provide specific requirements for Juniper devices (hardware, software, config?)

I tried this:

Connecting to Ex4300,QFX5100 and QFX10002 with a admin user (configured with super-user class):
fatal: [ex4300]: FAILED! => {"failed": true, "msg": "failed to transfer file to error: unknown command: /bin/sh/junos_template:\nsftp> put /tmp/tmp_QCbtq 'error: unknown command: /bin/sh/junos_template'\n\nremote open(\"/var/home/admin/error: unknown command: /bin/sh/junos_template\"): No such file or directory\r\n"}

Connecting to Ex4300 with root account:
fatal: [ex4300]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "/usr/bin/python: Operation not permitted\r\n", "msg": "MODULE FAILURE", "parsed": false}

Connecting to QFX5100 with user root:
fatal: [qfx5100]: FAILED! => {"changed": false, "failed": true, "msg": "paramiko is required but does not appear to be installed"}

Connecting to QFX10002  with user root:
fatal: [qfx10002]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
##### STEPS TO REPRODUCE

Use role which make reference to junos_template
- name: commonConfig | Configure commonConfig
  junos_template:
    src: commonConfig.j2
  tags: syslog

**commonConfig just include few lines of static syslog config
##### EXPECTED RESULTS

I'm expecting the devices to be configured with the provided configuration
##### ACTUAL RESULTS

Module is failing, nothing is getting configured

Error messages were provided in Summary section

**Comment by privateip** [comment]
this looks like a problem with not specifying the right connection type.  Did you specify connection: local in your playbooks (or elsewhere)?  Can you post a copy of your playbook that generate these messages?

**Comment by jf1cloutier** [comment]
You are right, I was initially missing the "connection: local".  After specifying to use local connection it started working as expected.

**Comment by privateip** [comment]
great, thanks for the update
