### ISSUE TITLE
service module fails to start service when both init.d and systemd scripts exist

### ISSUE THREAD

**Issue by claco** [ansible/ansible-modules-core#345]
This is originally reported in
- https://github.com/ansible/ansible-modules-core/pull/232#issuecomment-63016019
- https://github.com/ansible/ansible-modules-core/pull/232#issuecomment-63119092

In situations where there is both a systemd .service unit file and a init.d startup script, the service module will detect and run the init.d script instead of calling systemd. In this case, I'm on Fedora 20, but I suspect this is true on RHEL/Centos7 as well.

A quick synopsis of the comments above:

With both in place, `self.svc_cmd` returns `/usr/bin/service`
When I delete the script in init.d, `self.svc_cmd` returns `/usr/bin/systemctl`

I suspect line ~475: It's finding service, but prioritizes that over systemd:

```
        # Locate a tool for runtime service management (start, stop etc.)
        if location.get('service', None) and os.path.exists("/etc/init.d/%s" % self.name):
            # SysV init script
            self.svc_cmd = location['service']
        elif location.get('start', None) and os.path.exists("/etc/init/%s.conf" % self.name):

```

Final thought. There are other places, where it does a secondary `systemctl` type check:

```
        # Locate a tool for enable options
        if location.get('chkconfig', None) and os.path.exists("/etc/init.d/%s" % self.name):
            if check_systemd(self.name):
                # service is managed by systemd
                self.enable_cmd = location['systemctl']
            else:
                # we are using a standard SysV service
                self.enable_cmd = location['chkconfig']

```

**Comment by bcoca** [comment]
I was looking into similar issues, if you can, see if this branch fixes the issue for you:
https://github.com/bcoca/ansible-modules-core/tree/service_cleanup

**Comment by claco** [comment]
@bcoca That fixes this particular issue for me.

**Comment by Jmainguy** [comment]
@bcoca Was that merged in? Can this be closed?

**Comment by bcoca** [comment]
not yet
