### ISSUE TITLE
ansible-pull Failing to checkout non-HEAD commit hashes

### ISSUE THREAD

**Issue by srkiNZ84** [ansible/ansible-modules-core#3450]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Git module 
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When doing an "ansible-pull" command the git module fails to checkout if the commit hash specified is not the current "HEAD"
##### STEPS TO REPRODUCE

Create a repository with a simple playbook e.g.

```
- hosts: all
  tasks:
    - name: List files in directory
      connection: local
      command: ls -al
      register: filelisting

    - name: Print out listing
      connection: local
      debug: msg="{{ filelisting.stdout_lines }}"
```

After the initial commit, note the commit hash.

Then add another commit after the initial one (e.g. add a "dummy" file to the repo).

The repository should have two commits now, each with their own hash (lets refer to them as COMMIT1 and COMMIT2).

Run:

```
ansible-pull listfiles.yml -U git@bitbucket.org:username/ansible-pull-test.git -i hosts -C COMMIT1 -vvvvvv
```
##### EXPECTED RESULTS

Expected the command to clone the repository at that commit hash and execute the "listfiles.yml" playbook.
##### ACTUAL RESULTS

```
$ ansible-pull listfiles.yml -U git@bitbucket.org:username/ansible-pull-test.git -i hosts -C COMMIT1 -vvvvvv
No config file found; using defaults
Starting Ansible Pull at 2016-04-17 12:38:42
/usr/local/bin/ansible-pull listfiles.yml -U git@bitbucket.org:username/ansible-pull-test.git -i hosts -C COMMIT1 -vvvvvv
EXEC: /usr/local/bin/ansible -i "hosts" -c local  -vvvvvv -m git -a "name=git@bitbucket.org:username/ansible-pull-test.git dest=/Users/srdan/.ansible/pull/srdans-macbook-pro.local version=COMMIT1 depth=1" "localhost,MacBook-Pro.local,127.0.0.1"
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: username
localhost EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1460853522.66-246354459416972 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1460853522.66-246354459416972 )" )
localhost PUT /var/folders/01/fswx1t811p3_q5bj53yjfhnw0000gn/T/tmpKIrvZa TO /Users/username/.ansible/tmp/ansible-tmp-1460853522.66-246354459416972/git
localhost EXEC LANG=en_NZ.UTF-8 LC_ALL=en_NZ.UTF-8 LC_MESSAGES=en_NZ.UTF-8 /usr/bin/python /Users/username/.ansible/tmp/ansible-tmp-1460853522.66-246354459416972/git; rm -rf "/Users/username/.ansible/tmp/ansible-tmp-1460853522.66-246354459416972/" > /dev/null 2>&1
localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "accept_hostkey": false,
            "bare": false,
            "clone": true,
            "depth": 1,
            "dest": "/Users/username/.ansible/pull/macbook-pro.local",
            "executable": null,
            "force": false,
            "key_file": null,
            "name": "git@bitbucket.org:username/ansible-pull-test.git",
            "recursive": true,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "git@bitbucket.org:username/ansible-pull-test.git",
            "ssh_opts": null,
            "track_submodules": false,
            "update": true,
            "verify_commit": false,
            "version": "COMMIT1"
        },
        "module_name": "git"
    },
    "msg": "Failed to checkout COMMIT1"
}
```

**Comment by srkiNZ84** [comment]
Should comment that I'm not sure if this same issue happens when calling the module directly (could be an issue with the "ansible-pull"). Also, have not tried to reproduce this using any other Git repository than BitBucket.

**Comment by srkiNZ84** [comment]
We've been working around this by specifying both the "--full" and the "-C" flags with ansible-pull. However, this is much slower due to repo size.

**Comment by robinro** [comment]
According to http://stackoverflow.com/questions/7196682/is-it-possible-to-clone-only-certain-commit-from-a-git-repo-with-depth-1 there is no way to make git clone a repository and only get one specific commit by hash. So this is a git restriction we can not change.

Things that work
- do a full clone and checkout the commit (your current workaround)
- have a tag or branch associated with that commit and clone that

Shallow clones by default in pull are quite new: https://github.com/ansible/ansible/pull/13502
If many people use hash versions with ansible pull maybe one should reconsider this default. 
I would guess that the number of people affected is quite small and the workaround is easy/obvious and this combination is outweight by saving time/resources for everyone else.

**Comment by srkiNZ84** [comment]
Ok. That's fine. Will change to tagging the commit. 

I do think that ansible-pull should take a look at the -C argument and if it is a commit hash, do a "full" clone anyway. Otherwise, the documentation should specify that unless the "commit hash" you pass as an argument is the one currently pointed to by HEAD, it won't work.

Alternatively, just modify the documentation to make it clear that you can only put branch/tag names after "-C" unless you add the "--full" flag.

**Comment by robinro** [comment]
@srkiNZ84 you're right, it should fall back automatically to a full clone. I'll look into it.
