### ISSUE TITLE
Add support for installing apt build dependencies. 

### ISSUE THREAD

**Issue by graingert** [ansible/ansible-modules-core#349]
@nathanhruby created a PR to add support for installing apt build dependencies. 

Is it worth attempting to reintegrate this https://github.com/ansible/ansible/pull/8583 ?

**Comment by abadger** [comment]
Yes, if you're willing to take a look at doing it.  It was somewhat lower priority than other things we had to get merged in but it does seem like a useful feature to support.

**Comment by abadger** [comment]
I'll go ahead and close this issue but feel free to open a pull request if you get the code rebased.
