### ISSUE TITLE
ec2_eip module creates new ip on repeated run

### ISSUE THREAD

**Issue by arnuschky** [ansible/ansible-modules-core#35]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

Ubuntu 14.04.1
##### Summary:

If an EC2 instance already has an EIP associated to it, I would expect the ec2_eip module to do nothing/reuse the existing IP. Instead, it creates a new IP and associates this.

Note that I am not asking for the functionality provided by `reuse_existing_ip_allowed`.
##### Steps To Reproduce:
1. Associate an EIP to any instance using the ec2_eip module, for example `- ec2_eip: instance_id=i-1212f003`
2. repeat
##### Expected Results:

An instance without an EIP gets a new one allocated.
An instance with an EIP gets the same one allocated (idempotent),
##### Actual Results:

An instance with an EIP gets the another new EIP allocated (no idempotent, every new run creates and allocated a new EIP)

Here's the playbook that creates an instance and associates an EIP.
(vpc and security group exist already)

```
- name: EIP module bug
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - include_vars: "aws/eip-bug/vpc_info"
    - name: Creating instance
      local_action:
        module: ec2
        key_name: "keyname"
        region: us-east-1
        group_id:
          - "{{ sg_default.group_id }}"
        instance_type: t2.micro
        image: "ami-0619bf6e"
        wait: yes
        vpc_subnet_id: "{{ subnet_test_id }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Environment: "eip-bug"
          Class: eip-bug
        instance_tags:
          Environment: "eip-bug"
          Class: eip-bug
          Name: eip-bug
      register: instance
    - name: Allocating elastic IP to instance
      ec2_eip:
        in_vpc: yes
        reuse_existing_ip_allowed: yes
        state: present
        region: us-east-1
        instance_id: "{{ instance.tagged_instances[0].id }}"
      register: instance_eip
    - debug: var=instance_eip.public_ip
```

The instance task is idempotent thanks to exact_count/count_tag. The EIP task creates and associates a new EIP on every invocation. Accordingly, the number of EIPs increases; after 4 invocations the task fails due to Amazon's restriction to 3 unallocated EIPs.

EIP module output with -vvv:

```
TASK: [Allocating elastic IP to instance] ************************************* 
<127.0.0.1> REMOTE_MODULE ec2_eip region=us-east-1 state=present instance_id=i-xxx
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211 && echo $HOME/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211']
<127.0.0.1> PUT /tmp/tmpvxur9q TO /home/user/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211/ec2_eip
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /home/user/.pvenvs/ansible/bin/python /home/user/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211/ec2_eip; rm -rf /home/user/.ansible/tmp/ansible-tmp-1411248496.02-82225394781211/ >/dev/null 2>&1']
changed: [127.0.0.1] => {"changed": true, "public_ip": "xx.xx.xx.xx"}
```

**Comment by herbyg-axial** [comment]
Fixed by ansible/ansible-modules-core/issues/300

**Comment by bcoca** [comment]
closing this and keeping track in the PR
