### ISSUE TITLE
[Bug Report] cloudformation module not available for China (Beijing) Region.

### ISSUE THREAD

**Issue by yunlzheng** [ansible/ansible-modules-core#351]
#### Issue Type:

Bug Report
###### Ansible Version:

1.7.2
###### Environment:

Mac
###### Summary:

As the AWS doc show the Beijing region Cloudformation endpoint is 
[cloudformation.cn-north-1.amazonaws.com](cloudformation.cn-north-1.amazonaws.com)

How ever as we test, the really endpoint is [cloudformation.cn-north-1.amazonaws.com.cn](cloudformation.cn-north-1.amazonaws.com.cn). So when we i try use ansible for China Beijing Region, it fails.

I believe this is the issue about AWS China. but can we try use

```
boto.cloudformation.connect_to_region()
```

rather than

```
boto.cloudformation.connection.CloudFormationConnection()
```

in AWS cloudformation module?

ref: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-endpoints.html

**Comment by bcoca** [comment]
This seems like a AWS bug, either in docs or implementation. We should do 'what works' anyways so keeping this open as a bug.

**Comment by bcoca** [comment]
closing per fix merged
