### ISSUE TITLE
docker: parameter `user` is ignored

### ISSUE THREAD

**Issue by seschwar** [ansible/ansible-modules-core#352]
##### Issue Type:

Bug Report
##### Ansible Version:

```
% ansible --version
ansible 1.7.2
```
##### Environment:

Debian unstable

```
% cat /etc/debian_version
jessie/sid
% uname -v
#1 SMP Debian 3.16.7-2 (2014-11-06)
% docker --version
Docker version 1.3.1, build 4e9bbfa
% pip show docker-py

---
Name: docker-py
Version: 0.5.3
Location: /usr/lib/python2.7/dist-packages
Requires: requests, six, websocket-client
% python --version
Python 2.7.8
```
##### Summary:

The `docker` module does not handle the `user` parameter which
would correspond to `--user` option of `docker run` or `docker
create` correctly.  It isn't applied but no error is thrown.
The parameter `user` is simply ignored.

The parameter should be either supported (which is what i would
like to see) or it should raise an error.
##### Steps To Reproduce:

Launch a simple container and look at the `failed` and `User`
fields using the following command:

```
ansible -m docker -a 'image=busybox command=true user=nobody' localhost | sed '1c{' | jq -c '[.failed, .ansible_facts.docker_containers[0].Config.User]'
```
##### Expected Results:

There are two possible outcomes:
1. The `user` parameter is not supported.  The appropriate error
   message for that would be "unsupported parameter for module:
   user" and the output of the command above should therefore be
   the following:
   
   [true,null]
2. The `user` parameter supported.  Then the process in the
   container should be launched as the user `nobody` and therefore
   the output of the command above should be the following:
   
   [false,"nobody"]
##### Actual Results:

However neither is the case.  The unknown paramter `user` is simply
ingnored and the process of the container is simply launched as
`root`.  The output of the command above is actually the following

```
[false,""]
```

**Comment by simono** [comment]
@seschwar You can try my pull request, if you like #361 
I added the option `docker_user' which should do what you want.
