### ISSUE TITLE
dns parameter of module docker raise a type error 

### ISSUE THREAD

**Issue by picpicpic** [ansible/ansible-modules-core#3528]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

cloud/docker
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 0f373c1767) last updated 2016/04/23 22:41:07 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 1d25c41844) last updated 2016/04/23 22:55:03 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD de22b721db) last updated 2016/04/23 22:55:04 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Dns parameter raise the error : Docker API Error: json: cannot unmarshal string into Go value of type []string"
##### STEPS TO REPRODUCE

Create the following playbook

```

---
- hosts : XXX
  tasks : 
    - docker :
        name : container
        image : hello-world        
        dns : 
         - 8.8.4.4
```
##### EXPECTED RESULTS

container created
##### ACTUAL RESULTS

Error raised : Docker API Error: json: cannot unmarshal string into Go value of type []string

```
fatal: [XXX]: FAILED! => 
{   
 "changed": false,
 "failed": true,
 "invocation": 
     {
     "module_args": 
         {
         "cap_add": null,
         "cap_drop": null,
         "command": null,
         "count": 1,
         "cpu_set": null,
         "cpu_shares": 0,
         "debug": false,
         "detach": true,
         "devices": null,
         "dns": "['8.8.4.4']",
         "docker_api_version": "1.22",
         "docker_url": null,
         "docker_user": null,
         "domainname": null,
         "email": null,
         "entrypoint": null,
         "env": null,
         "env_file": null,
         "expose": null,
         "extra_hosts": null,
         "hostname": null,
         "image": "hello-world",
         "insecure_registry": false,
         "labels": {},
         "links": null,
         "log_driver": null,
         "log_opt": null,
         "lxc_conf": null,
         "memory_limit": 0,
         "memory_swap": 0,
         "name": "container",
         "net": null,
         "password": null,
         "pid": null,
         "ports": null,
         "privileged": false,
         "publish_all_ports": false,
         "pull": "missing",
         "read_only": null,
         "registry": null,
         "restart_policy": null,
         "restart_policy_retry": 0,
         "signal": null,
         "state": "started",
         "stdin_open": false,
         "stop_timeout": 10,
         "timeout": 60,
         "tls_ca_cert": null,
         "tls_client_cert": null,
         "tls_client_key": null,
         "tls_hostname": null,
         "tty": false,
         "ulimits": null,
         "use_tls": null,
         "username": null,
         "volumes": null,
         "volumes_from": null
         },
     "module_name": "docker"
     },
 "msg": "Docker API Error: json: cannot unmarshal string into Go value of type []string"
 }
```

**Comment by tillkuhn** [comment]
I temporarily applied https://github.com/ansible/ansible-modules-core/issues/3528 to fix this problem, but with the latest [v2.1.1.0-1](https://github.com/ansible/ansible/releases/tag/v2.1.1.0-1) Ansible Ubuntu package this issue was re-introduced. Does anybody know why this important fix did not make it into the recent release, and for which release it can be expected? Thanks!

**Comment by picpicpic** [comment]
Hi,
Hmm... good question !
The devel branch is even in version 2.0.0-0.5.beta3, I'm a bit lost... 
Does anybody know where to create the pull request in order to be included in the next release ?
Is the devel branch still to be used for bug fix ?
Thx in advance

**Comment by chouseknecht** [comment]
The fix is in the devel branch. The devel branch will be the basis for release 2.2. I cherry picked commit [fee0055](https://github.com/ansible/ansible-modules-core/commit/fee0055f9f02bf8ff8a3ebe7a9a7237e1703a548), which I believe fixes the issue, to the stable-2.1 brach. If we cut another point release of 2.1, it will be included.

**Comment by picpicpic** [comment]
Many thx !

**Comment by tillkuhn** [comment]
@chouseknecht yes https://github.com/ansible/ansible-modules-core/commit/fee0055f9f02bf8ff8a3ebe7a9a7237e1703a548 is the right one, thanks for including it!
