### ISSUE TITLE
Unarchive Module fails with Traceback

### ISSUE THREAD

**Issue by tkinz27** [ansible/ansible-modules-core#3597]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

```
[root@8a976966193f stuff]# ansible --version
ansible 2.2.0 (devel cf62a62b83) last updated 2016/05/03 23:19:15 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 9db1233521) last updated 2016/05/03 23:19:24 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 675d778b50) last updated 2016/05/03 23:19:29 (GMT +000)
  config file = /stuff/ansible.cfg
  configured module search path = ['./library']
```
##### OS / ENVIRONMENT

centos based Docker image
##### SUMMARY

While using the unarchive module to unzip consul from a /tmp directory on the remote machine to the destination /usr/local/bin the module throws an exception. In this case, consul had previously been installed, so /usr/local/bin/consul already existed.

```
fatal: [10.64.1.198]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_5Ccjgl/ansible_module_unarchive.py\", line 751, in <module>\r\n    main()\r\n  File \"/tmp/ansible_5Ccjgl/ansible_module_unarchive.py\", line 711, in main\r\n    check_results = handler.is_unarchived()\r\n  File \"/tmp/ansible_5Ccjgl/ansible_module_unarchive.py\", line 397, in is_unarchived\r\n    err += 'Path %s differs in permissions (%o vs %o)\\n' % (path, self.file_args['mode'], stat.S_IMODE(st.st_mode))\r\nTypeError: %o format: a number is required, not str\r\n", "msg": "MODULE FAILURE", "parsed": false}
```
##### STEPS TO REPRODUCE

The tasks I'm running are... (my role is not very different from https://github.com/savagegus/ansible-consul)

```
- name: downoad consul
  get_url: >
    url={{ consul_release_url }}
    checksum={{ consul_release_checksum }}
    dest={{ consul_download_folder }}/{{ consul_archive }}
  register: consul_downloaded
  become: yes

- name: install consul
  unarchive: >
    src={{ consul_download_folder }}/{{ consul_archive }}
    dest=/usr/local/bin
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=755
    copy=no
  become: yes
```

##### EXPECTED RESULTS

Previously with the current stable release of ansible (ansible 2.0.2) this task runs without any errors. 
##### ACTUAL RESULTS

I can run with higher verbosity if you think its helpful. 

```
fatal: [10.64.1.78]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_bGfFXq/ansible_module_unarchive.py\", line 751, in <module>\r\n    main()\r\n  File \"/tmp/ansible_bGfFXq/ansible_module_unarchive.py\", line 711, in main\r\n    check_results = handler.is_unarchived()\r\n  File \"/tmp/ansible_bGfFXq/ansible_module_unarchive.py\", line 397, in is_unarchived\r\n    err += 'Path %s differs in permissions (%o vs %o)\\n' % (path, self.file_args['mode'], stat.S_IMODE(st.st_mode))\r\nTypeError: %o format: a number is required, not str\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

I worked around this by changing the string formatting thats throwing the error to cast everything as a string. Probably not the correct way to do it which is why I'm not creating a pull request, but it gets me past the error for now. 

```
--- a/files/unarchive.py
+++ b/files/unarchive.py
@@ -394,7 +394,7 @@ class ZipArchive(object):
                     mode = self._permstr_to_octal(permstr, umask)
                 if self.file_args['mode'] and  self.file_args['mode'] != stat.S_IMODE(st.st_mode):
                     change = True
-                    err += 'Path %s differs in permissions (%o vs %o)\n' % (path, self.file_args['mode'], stat.S_IMODE(st.st_mode))
+                    err += 'Path %s differs in permissions (%s vs %s)\n' % (path, str(self.file_args['mode']), str(stat.S_IMODE(st.st_
                     itemized[5] = 'p'
                 elif mode != stat.S_IMODE(st.st_mode):
                     change = True
```

**Comment by alikins** [comment]
> centos based Docker image

which version?

**Comment by alikins** [comment]
> I can run with higher verbosity if you think its helpful. 

The output of the unzip command the module builds when doing the archive checkout would be useful, something like

```
unzip -ZT -s /path/to/the/consul_zip_archive.zip
```

**Comment by tkinz27** [comment]
@alikins the unarchive module is being run on Ubuntu based remote hosts

The output to that zip command is 

```
unzip -ZT -s /var/consul/consul_0.6.3_linux_amd64.zip
Archive:  /var/consul/consul_0.6.3_linux_amd64.zip
Zip file size: 5714093 bytes, number of entries: 1
-rwxr-xr-x  3.0 unx 20417720 bx defN 20160114.213313 consul
1 file, 20417720 bytes uncompressed, 5713931 bytes compressed:  72.0%
```

If you think it will help, here is my docker file as well...
The remote machine is ami-3b6a8050 which is just Ubuntu 14.

```
FROM centos

RUN yum install -y \
    @development \
    python-devel \
    libxml-devel \
    libxslt-devel \
    libffi-devel \
    openssl-devel \
    git vim \
    ca-certifactes

RUN curl -L https://bootstrap.pypa.io/get-pip.py | python -
RUN pip install -U six boto awscli cryptography shade requests 

RUN git clone --recurse https://github.com/ansible/ansible /ansible
RUN pip install -e /ansible
```

**Comment by dagwieers** [comment]
@alikins Can you please merge the fix and close this issue ? Thanks !

**Comment by dagwieers** [comment]
Nevermind.

**Comment by ghost** [comment]
I'm running in to the same issue.  Fresh install of latest ansible from source on centos7.  Unarchiving a zip file when the extracted files already exist results in the OPs error. Appears to only affect zip files, unarchiving a tar file where the extracted files already exist results in normal behavior.  

Ansible version with error:
ansible 2.2.0 (devel bef1971ffe) last updated 2016/06/17 10:34:08 (GMT -400)

Ansible version without error:
ansible 2.1.0 (devel e3a6accc1d) last updated 2016/01/20 11:18:11 (GMT -400)

**Comment by dagwieers** [comment]
The fix exists, you can backport it yourself if it is urgent.

**Comment by OldCrowEW** [comment]
I am running into this issue. Is there a fix? I am running from trunk. Current log shows me @ commit c5d4151234fd4dfc797bfdfe277f02eeddc34f6d

**Comment by dagwieers** [comment]
Yes, look at the reference above.

**Comment by OldCrowEW** [comment]
looks like the patch isnt passing travis tests. is it safe?
