### ISSUE TITLE
yum module does not install a package with a full URL when no repositories are configured

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#3606]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

yum
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

(but found since 1.8.x at least, and probably forever)
##### CONFIGURATION

```
[defaults]
host_key_checking = False
roles_path = roles
pipelining = True
timeout = 30
force_color = 1
```
##### OS / ENVIRONMENT

Running from: Fedora 23
Managing: Red Hat Enterprise Linux 7.2
##### SUMMARY

When no repositories are configured, yum modules fails to install the package when the argument is an URI (http://...) which points to an rpm package.
It _does_ work when the package is available on the remote system, so the path for name: is a local path, not an remote URI.

I understand this can be considered a corner case (for sure a minor problem): CentOS always have repositories,  the first step should be subscription-manager registration and/or a workaround with command module (which complains about not using yum...), but I think that a direct RPM should be always installed, overriding yum native behavior.
(I didn't check whether this works when dnf behaves in the same way).
##### STEPS TO REPRODUCE

```
- hosts: rhel1
  tasks:
      - yum:
            name: https://dl.fedoraproject.org/pub/epel/7/x86_64/h/htop-2.0.1-1.el7.x86_64.rpm
            state: latest
        become: yes
```
##### EXPECTED RESULTS

Package installed
##### ACTUAL RESULTS

```
fatal: [rhel1]: FAILED! => {"changed": true, "failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "i
nstall_repoquery": true, "list": null, "name": ["https://dl.fedoraproject.org/pub/epel/7/x86_64/h/htop-2.0.1-1.el7.x86_64.rpm"], "state": "installed", "update_cache": false}, "module_name": "yum"}, "msg": "There a
re no enabled repos.\n Run \"yum repolist all\" to see the repos you have.\n You can enable repos with yum-config-manager --enable <repo>\n", "rc": 1, "results": ["Loaded plugins: product-id, search-disabled-repos
, subscription-manager\nThis system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.\n"]}
```

**Comment by ghost** [comment]
Additional note: it works when the package is on the remote server, but only for state: present, not state: latest (where the plugin probably tries to access the repositories).

**Comment by jctanner** [comment]
We're limited by the fact that yum won't install a package from http this way ...

```
[root@localhost ~]# yum  update http://localhost/packages/foobar-2-1.x86_64.rpm --disablerepo=*
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>
[root@localhost ~]# echo $?
1
```

A filepath will work ...

```
[root@localhost ~]# yum  update /var/www/html/packages/foobar-2-1.x86_64.rpm --disablerepo=*
Loaded plugins: fastestmirror
Examining /var/www/html/packages/foobar-2-1.x86_64.rpm: foobar-2-1.x86_64
Marking /var/www/html/packages/foobar-2-1.x86_64.rpm as an update to foobar-1-1.x86_64
Resolving Dependencies
--> Running transaction check
---> Package foobar.x86_64 0:1-1 will be updated
---> Package foobar.x86_64 0:2-1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================================================================
 Package                                Arch                                   Version                              Repository                                          Size
=============================================================================================================================================================================
Updating:
 foobar                                 x86_64                                 2-1                                  /foobar-2-1.x86_64                                 0.0

Transaction Summary
=============================================================================================================================================================================
Upgrade  1 Package

Is this ok [y/d/N]:
```

The workaround is a combination of get_url and shell:rpm or get_url and yum: <filepath>.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:
- yum does not allow the requested behavior per the comment above.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!
- https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implenting a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!

**Comment by ghost** [comment]
I disagree with closing this. It should be possible to check if the file is an URL and in that case download the package first and then proceed with a local installation, which would override the issue with yum. The alternative leads to an annoying notice about "please use yum" and to less clear (and inconsistent) code IMHO. I'd ask to reconsider.

**Comment by bcoca** [comment]
I would just use get_url and not try to build in too much 'magic' into the yum module.
