### ISSUE TITLE
stderr of script module is always empty string

### ISSUE THREAD

**Issue by lost-in-revery** [ansible/ansible-modules-core#3610]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

module script
##### ANSIBLE VERSION

```
ansible 2.0.1.0
 config file = /usr/local/etc/ansible/ansible.cfg
 configured module search path = Default w/o overrides
```
##### CONFIGURATION

forks = 200
 ssh_args = -o ControlMaster=auto -o ControlPersist=60s
 pipelining = True
##### OS / ENVIRONMENT

FreeBSD 10.x
##### SUMMARY

"stderr" is always empty. Whole output goes to "stdout" and "stdout_lines". 
##### STEPS TO REPRODUCE

```
     - name: check script output
       script: check_output.sh
       become: yes

sample script:

#!/bin/sh
echo "This is STDERR string" 1>&2
echo "This is STDOUT string"


```
##### EXPECTED RESULTS

TASK [check script output] ***********************************************
changed: [some.host] => {"changed": true, "rc": 0, "stderr": "This is STDERR string\r\n", "stdout": "This is STDOUT string\r\n", "stdout_lines": ["This is STDOUT string"]}
##### ACTUAL RESULTS

```
TASK [check script output] ***********************************************
changed: [some.host] => {"changed": true, "rc": 0, "stderr": "", "stdout": "This is STDERR string\r\nThis is STDOUT string\r\n", "stdout_lines": ["This is STDERR string", "This is STDOUT string"]}
```

**Comment by alikins** [comment]
Would it be possible to get the output from running that with

`ANSIBLE_DEBUG=1 ansible-playbook -vvvvv` ?

And just to verify, the case where this happens is using the ssh connection (as opposed to local, etc)?

**Comment by alikins** [comment]
Oh, if possible, could you try to reproduce this with a newer verson (https://github.com/ansible/ansible/releases/tag/v2.1.0.0-0.1.rc1 for example)?

**Comment by lost-in-revery** [comment]
Hello.

Yes, we use the ssh connection. Unfortunately, I can't try a newer version right now. Sorry. May be a bit later.   

ANSIBLE_DEBUG=1 ansible-playbook:

[ansible-playbook.txt](https://github.com/ansible/ansible-modules-core/files/257822/ansible-playbook.txt)

**Comment by lost-in-revery** [comment]
The problem still exists in version 2.1.0.0

**Comment by sivel** [comment]
This is a result of using `-tt` (forcing pseudo-terminal) with ssh.  When running with `-tt`, effectively everything happens over stdin due to use of only using a single channel.

**Comment by jctanner** [comment]
Confirmed that this test patch creates the expected results ...

```
$ git diff
diff --git a/lib/ansible/plugins/connection/ssh.py b/lib/ansible/plugins/connection/ssh.py
index 16f086b..40fbf4b 100644
--- a/lib/ansible/plugins/connection/ssh.py
+++ b/lib/ansible/plugins/connection/ssh.py
@@ -567,6 +567,8 @@ class Connection(ConnectionBase):
             args = ('ssh', self.host, cmd)

         cmd = self._build_command(*args)
+        if '-tt' in cmd:
+            cmd.remove('-tt')
         (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)

         return (returncode, stdout, stderr)
```

We use -tt primarily for sudo purposes, but I'll have to dig further and determine if there's another workaround.

**Comment by jctanner** [comment]
A more targeted patch ...

```
$ git diff
diff --git a/lib/ansible/plugins/action/script.py b/lib/ansible/plugins/action/script.py
index 358775c..59c7c8a 100644
--- a/lib/ansible/plugins/action/script.py
+++ b/lib/ansible/plugins/action/script.py
@@ -20,6 +20,7 @@ __metaclass__ = type
 import os

 from ansible.plugins.action import ActionBase
+from ansible.plugins.connection import ssh


 class ActionModule(ActionBase):
@@ -85,7 +86,19 @@ class ActionModule(ActionBase):
         env_string = self._compute_environment_string()
         script_cmd = ' '.join([env_string, tmp_src, args])

-        result.update(self._low_level_execute_command(cmd=script_cmd, sudoable=True))
+        if isinstance(self._connection, ssh.Connection):
+            # -tt's pseudo terminal squashes stderr to stdout, so
+            # this block instead redirects stderr to a file for
+            # a second command to read
+            # sudoable=True == always adds -tt
+            stderr_file = os.path.join(tmp, 'stderr')
+            stderr_cmd = 'cat %s' % stderr_file
+            script_cmd += ' 2>%s' % stderr_file
+            result.update(self._low_level_execute_command(cmd=script_cmd, sudoable=True))
+            stderr_data = self._low_level_execute_command(cmd=stderr_cmd, sudoable=True)
+            result['stderr'] = stderr_data['stdout']
+        else:
+            result.update(self._low_level_execute_command(cmd=script_cmd, sudoable=True))

         # clean up after
         self._remove_tmp_path(tmp)
```

**Comment by jctanner** [comment]
Hi!

A change has been applied for this ticket, which should address this item for you. We have decided not to alter the script module functionality to compensate for pttys at this time, but may do so at some point. For now, we have noted this issue in the module documentation with a workaround.

If you believe this ticket is not addressed, or have further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments on closed tickets, though the mailing list is a great way to get involved or discuss this one further.

Thanks!
