### ISSUE TITLE
unarchive module fails with "No such file or directory" on OS X - El Capitan nodes

### ISSUE THREAD

**Issue by mtlynch** [ansible/ansible-modules-core#3631]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 56ba10365c) last updated 2016/05/04 16:27:09 (GMT -400)
  lib/ansible/modules/core: (detached HEAD b6ad3b6773) last updated 2016/05/02 11:06:58 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 1846de2809) last updated 2016/05/02 11:06:58 (GMT -400)
  config file = /home/mtlynch/e2e/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
hostfile = hosts
host_key_checking = False
```
##### OS / ENVIRONMENT

Control: Ubuntu 14.04
Node: Mac OS X El Capitan
##### SUMMARY

Unarchive fails with "No such file or directory" when the target node is an OS X - El Capitan machine. I can run the same command against an Ubuntu 14.04 node and it works fine. If I reimplement the module via shell commands, it works as expected, but the unarchive module does not seem to work.
##### STEPS TO REPRODUCE

``` bash
$ echo "foo" > test.txt && \
    zip test.zip test.txt && \
    ansible mac-capitan -m unarchive -a "src=test.zip dest=/tmp/"
```
##### EXPECTED RESULTS

`test.txt` gets unzipped to `/tmp` on `mac-capitan` node
##### ACTUAL RESULTS

```
mac-capitan | FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "copy": true, 
            "creates": null, 
            "delimiter": null, 
            "dest": ".", 
            "directory_mode": null, 
            "exclude": [], 
            "extra_opts": [], 
            "follow": false, 
            "force": null, 
            "group": null, 
            "keep_newer": false, 
            "list_files": false, 
            "mode": null, 
            "original_basename": "test.zip", 
            "owner": null, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/Users/user/.ansible/tmp/ansible-tmp-1462551399.13-228141622532747/source"
        }
    }, 
    "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: './test.txt'"
}
```

**Comment by dagwieers** [comment]
What is weird is that `dest` is set to `.` rather than `/tmp/` ?

I do not see this happening from the module's source code.
What version is this ? Can you try the latest unarchive module from the devel branch ?

**Comment by mtlynch** [comment]
Confirmed that this is now fixed (including `dest` showing the correct value). On Ansible version:

```
$ ansible --version
ansible 2.2.0 (devel ba63ccb880) last updated 2016/05/16 12:57:04 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 127d518011) last updated 2016/05/16 13:02:14 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD f953d5dc0c) last updated 2016/05/16 13:02:14 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```

**Comment by dagwieers** [comment]
Thanks for reporting back.

**Comment by mailtonskiran** [comment]
i am finding it difficult to execute unarchive in mac OS EI Captain version 10.11.6 (15G31). - unarchive: copy=no src=/home/ec2-user/ansible-test/xyz.zip dest=/home/ec2-user/ansible-test/ and also I tried unarchive: copy=no src="/home/ec2-user/ansible-test/xyz.zip dest="/home/ec2-user/ansible-test/" remote_src=yes. I have Python 2.7. This does not seem to work. Any clue would be much appreciated.﻿

**Comment by MikeSpreitzer** [comment]
Did you try `brew install gnu-tar` ?

**Comment by MikeSpreitzer** [comment]
I have experimentally verified on MacOS 10.10.5 and python 2.7.10 and Ansible 2.1.1.0 that `brew install gnu-tar` wards off this bug.

**Comment by dagwieers** [comment]
Alright, so it is notabug, BSD tar is not supported, only GNU tar.

**Comment by MikeSpreitzer** [comment]
Can somebody explain why tar is relevant to a bug wrt unzipping?

**Comment by dagwieers** [comment]
It shouldn't.

Have you been testing the same version. A lot of things have improved in unarchive over the last releases.

**Comment by MikeSpreitzer** [comment]
Using MacOS 10.10.5 and python 2.7.10 and Ansible 2.1.1.0, I find that I can make the bad symptom go away and come back by doing `brew install gnu-tar` and `brew uninstall gnu-tar` (respectively).

**Comment by MikeSpreitzer** [comment]
@dagwieers thanks for the reminder, I rediscovered the remark at https://docs.ansible.com/ansible/unarchive_module.html#notes saying that `gtar` is required.  I still do not understand why that is relevant when processing a ZIP archive, but it explains why uninstalling `gnu-tar` on my Mac breaks `unarchive`.
