### ISSUE TITLE
s3 fails when behind a proxy even though proxy environment variables set

### ISSUE THREAD

**Issue by dwcramer** [ansible/ansible-modules-core#3650]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

s3 module
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /Users/davcrame/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Nothing special:

```
[defaults]
host_key_checking = False
log_path=~/.ansible/ansible.log

[ssh_connection]
control_path = %(directory)s/%%h-%%r(v
```
##### OS / ENVIRONMENT

Control machine: Mac OS X 10.11.4
Target machines: Ubuntu 14.04
##### SUMMARY

When targeting machines in a lab that are behind a proxy, the s3 module fails. In the playbook I have set the proxy environment variables:

```
  environment:
    http_proxy: http://proxy.mydomain.com:80/
    https_proxy: http://proxy.esl.mydomain.com:80/
```

Other modules like apt and pip are able to download content via the proxy.

```
failed: [10.89.38.xxx] => (item={u'dest': u'truststore.jks', u'src': u'truststore.jks'}) => {"failed": true, "item": {"dest": "truststore.jks", "src": "truststore.jks"}, "msg": "Source bucket cannot be found"}
```
##### STEPS TO REPRODUCE

Use the s3 module on a target machine that is behind a proxy and does not have access to the aws endpoints directly.
##### EXPECTED RESULTS

I expect the s3 module to be able to download content from my s3 buckets.
##### ACTUAL RESULTS

The playbook fails with an error like: 

```
failed: [10.89.38.xxx] => (item={u'dest': u'truststore.jks', u'src': u'truststore.jks'}) => {"failed": true, "item": {"dest": "truststore.jks", "src": "truststore.jks"}, "msg": "Source bucket cannot be found"}
```

**Comment by dwcramer** [comment]
It occurs to me that this is probably a boto thing and the boto docs have details about proxy config (I'll try that). But it would be nice if s3 used the same config from the playbook.

**Comment by dwcramer** [comment]
Closing because the problem turns out to be that the time on the remote host was not accurate (because the server is behind a proxy and couldn't talk to its ntp servers). When the time is off, AWS returns a 403. Correcting the time on the server allows boto to talk to AWS.

**Comment by mmack** [comment]
@dwcramer thanks, your comment "When the time is off, AWS returns a 403. Correcting the time on the server allows boto to talk to AWS." Saved my day :)
