### ISSUE TITLE
Cron module fails to set env variable, instead raises unsupported parameter for module: value

### ISSUE THREAD

**Issue by dylanjbarth** [ansible/ansible-modules-core#3691]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

cron
##### ANSIBLE VERSION

2.0.2.0
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

Mac OSX Yosemite 10.10.2
##### SUMMARY

I am attempting to set environment variables using the cron module. I tried an example (and variations) from the docs (http://docs.ansible.com/ansible/cron_module.html) but I keep getting `unsupported parameter for module` errors. 
##### STEPS TO REPRODUCE

Try a simple play which is in the example docs: 
`- cron: name=PATH env=yes value=/opt/bin`

##### EXPECTED RESULTS

I expected that the play would add a line to the top of my crontab `PATH=/opt/bin`.
##### ACTUAL RESULTS

`TASK [common : cron] ***************************************************
fatal: [dev_box]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: value"}`
I tried again, substituting `value` with `job` with the same result, `unsupported parameter for module: value`

**Comment by sivel** [comment]
Per the documentation, env functionality is added for the upcoming Ansible 2.1 release.
