### ISSUE TITLE
subversion: export fails if dest directory exists

### ISSUE THREAD

**Issue by earchibald** [ansible/ansible-modules-core#370]
Using the following syntax, the task always fails if /tmp/foo already exists.

`- name: (testing) svn export of desired callflow.xml
      subversion: repo=http://repo.local/repos/target/ dest=/tmp/foo/ export=yes`

The error shown is:
`msg: ERROR: /tmp/foo/ folder already exists, but its not a subversion repository.`

This appears to be happening because the subversion module does not account for exporting if the target directory exists (but is not a working copy):

`if not os.path.exists(dest):`
...export and checkout both handled
`elif os.path.exists("%s/.svn" % (dest, )):`
...checkout handled. export presumably not handled because this is a working directory
`else:
        module.fail_json(msg="ERROR: %s folder already exists, but its not a subversion repository." % (dest, ))`

I think if we insert another case before the `else` of `elif os.path.exists(dest) and export:` and handle export to a preexisting directory there, it should work.

**Comment by phpcc** [comment]
Without export, it fails too if the directory already exists. So a checkout in an existing directory isn't possible.

**Comment by jimsmith** [comment]
This isn't work as expected I'm getting this same error with 1.8.4

I am using the export and force switches from the subversion module but as you will see below force is being outputted but still get the error message, so I'm having to use the shell module and revert back to the svn cli :(

TASK: [subversion] ************************************************************
<localhost> username=svnuser force=yes dest=~/checkout/ repo=https://my.svn.server/PROJECT/develop export=yes password=VALUE_HIDDEN revision=HEAD
<localhost>
<localhost>
<localhost> u'LANG=C LC_CTYPE=C /usr/bin/python /home/svnuser/.ansible/tmp/ansible-tmp-1426256869.1-122427451446849/subversion; rm -rf /home/svnuser/.ansible/tmp/ansible-tmp-1426256869.1-122427451446849/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true}
msg: ERROR: /home/svnuser/checkout/ folder already exists, but its not a subversion repository.

**Comment by abadger** [comment]
@jimsmith Could you open a new issue and include a sample playbook and the error message you're getting?  Thanks!

**Comment by abadger** [comment]
@jimsmith Actually one other thing you can test before opening a bug -- 1.8.4 doesn't have the fix.  The fix involved changing the behaviour of the force parameter so we decided it should wait until 1.9.  If you can test with 1.9 or devel then we'll know if there's still a bug lurking.  If not, 1.9 will be out shortly.  We tagged 1.9rc1 on Tuesday.  1.9rc2 will be out on this coming Tuesday.
