### ISSUE TITLE
eos_command does not work with --check ansible-playbook option

### ISSUE THREAD

**Issue by petereh** [ansible/ansible-modules-core#3727]
**Yes**
##### ISSUE TYPE

**Bug Report**
##### COMPONENT NAME

eos_command
##### ANSIBLE VERSION

2.1
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

when i use eos_command for configuring arista devices or running commands like " write mem"  with the --check option  , what ever list of commands specified under eos_command still gets applied to the devices .  whereas --check documentation indicates the following

  -C, --check           don't make any changes; instead, try to predict some
                        of the changes that may occur

```
##### STEPS TO REPRODUCE
Sample playbook:

- name: Play to configure Vlans on arista devices
  connection: local
  gather_facts: no
  hosts: "{{  arista }}"
  tags: 
    - arista

  tasks:
     - name: Prechecks to verify vlan does not exist
       eos_command:
         commands:
           - show vlan {{vlan}} | json
         provider: "{{ cli }}"
       failed_when: "'not found in current VLAN' not in output.msg"
       register: output
     - debug: var=output       


     - name: Configure Vlans
       eos_command:
         commands:
           - enable 
           - configure terminal
           - vlan {{ vlan }}
           - name {{ vlan_desc }}
           - exit
           - exit
           - write memory
         provider: "{{ cli }}"

     - name: Postchecks to verify vlan exists
       eos_command:
         commands:
           - show vlan  {{vlan}} | json
         provider: "{{ cli }}"
       register: output
     - debug: var=output 

```
##### EXPECTED RESULTS

See problem description
##### ACTUAL RESULTS

See problem description

**Comment by abadger** [comment]
Verified that module has `supports_check_mode=True` but does not appear to check `module.check_mode` so that it only makes changes when check_mode is False.  A quick grep of networking/_/_command\* shows that all the command modules have a similar pattern.   @Qalthos, @privateip This might need to be fixed in all of the networking command modules.

**Comment by privateip** [comment]
@petereh I would highly recommend that you use eos_config for performing configuration operations and not eos_command.

**Comment by privateip** [comment]
When running in check module, eos_command will only allow show commands now
