### ISSUE TITLE
File module: Allow 'compress' state

### ISSUE THREAD

**Issue by bendoh** [ansible/ansible-modules-core#3734]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

File
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

There is no obvious way to ensure a file is compressed. For my particular use case, I want to keep a sql dump file on hand, but make sure it's always compressed. 

The `file` module seems like a good place to add this, by adding a 'compress' state, which would be semantically equivalent to the 'file' state, except the file would be kept compressed using an additional `compression` argument, which would default to 'gzip'. The `compression` argument could be influenced by an environment variable or top-level variable, whatever is felt to be appropriate.
##### STEPS TO REPRODUCE

``` yaml
- name: Ensure file is compressed
  file: path=/the/target-file state=compress
```
##### EXPECTED RESULTS

The file at `/the/target-file` would be compressed and become `/the/target-file.{gz,zip}`, depending on the compression used.

**Comment by abadger** [comment]
No need to have both an issue and a PR so going to go ahead and close this in favor of #3735
