### ISSUE TITLE
"docker_container" misses env-file option that "docker" got in 2.1

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#3768]
##### ISSUE TYPE
- Bug Report
- Feature Idea
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### OS / ENVIRONMENT

Running: Fedora 23
Host: CentOS 7
##### SUMMARY

The module "docker_container" lacks the env_file option to set the --env-file parameter with docker. The now deprecated module "docker" got that thing in 2.1.

**Comment by chouseknecht** [comment]
Adding...
