### ISSUE TITLE
wait_for always timeouts in v2.1

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#3790]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

wait_for module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

None, using the default
##### OS / ENVIRONMENT

CentOS 6.7
##### SUMMARY

The wait_for module that was installed updating ansible to 2.1 through PIP is now always resulting in a timeout (300 sec default)
##### STEPS TO REPRODUCE

```
- hosts: pre-production
  become: yes
  serial: 1
  vars:
    pre_db_stop: False

  tasks:
    - name: Wait for tomcat to be started
    wait_for: port={{http_port}}
```

##### EXPECTED RESULTS

Status changed
##### ACTUAL RESULTS

status failed

```
EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/markh/.ansible/cp/ansible-ssh-%h-%p-%r -tt host-foo-bar '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=pknakwbfbajwekkvkbchpoczrkqqkzka] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-pknakwbfbajwekkvkbchpoczrkqqkzka; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/markh/.ansible/tmp/ansible-tmp-1464605660.2-153948321896324/wait_for; rm -rf "/home/markh/.ansible/tmp/ansible-tmp-1464605660.2-153948321896324/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [host-foo-bar]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "invocation": {"module_args": {"connect_timeout": 5, "delay": 0, "exclude_hosts": null, "host": "127.0.0.1", "path": null, "port": 8080, "search_regex": null, "state": "started", "timeout": 300}, "module_name": "wait_for"}, "msg": "Timeout when waiting for 127.0.0.1:8080"}
```

**Comment by Jacob-SAE** [comment]
I'm experiencing this same issue with Ubuntu 14.04 while attempting to connect to remote Ubuntu 14.04 instances. When I remove wait_for ; however, it works without issue.

This is the error message I see when I use wait_for:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'upper'
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by bitmensch** [comment]
Looks like I see the same issue `Timeout when waiting for 172.19.0.2:8090` on latest CentOS 5:

```
fatal: [default]: FAILED! => {"changed": false, "elapsed": 60, "failed": true, "invocation": {"module_args": {"connect_timeout": 5, "delay": 0, "exclude_hosts": null, "host": "172.19.0.2", "path": null, "port": 8090, "search_regex": null, "state": "started", "timeout": 60}, "module_name": "wait_for"}, "msg": "Timeout when waiting for 172.19.0.2:8090"}
```

This occurs although the service is definitely available on the specified IP address at that time.

**Comment by ghost** [comment]
You can bypass by copying the wait_for module from a previous version into the ansible module folder. However, this doesn't fix the current module ofcourse ;)

**Comment by XooR** [comment]
Problem appeared with commit 67de0675c39e6e505e02b145ee1456c284c45344

**Comment by jimi-c** [comment]
@XooR can you send your fix as a PR please?

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
