### ISSUE TITLE
Unarchive module fails with big archive

### ISSUE THREAD

**Issue by m-messiah** [ansible/ansible-modules-core#3810]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
- unarchive
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Host: MacOSX, ansible from pip
Destination: debian/jessie64
##### SUMMARY

Unarchive module fails when use big zip archive
##### STEPS TO REPRODUCE

Create zip file with, for example 47 000 files (at all, not in one dir). 

```
mkdir -p test/{1..47}
for i in {1..47}; do
    for j in {1..1000}; do
        echo $i$j > test/$i/$j.txt
    done
done
zip -r archive.zip test
```

```
- name: Deploy test archive
  hosts: all
  become: yes
  tasks:
    - name: Install unzip
      apt: name=unzip

    - name: Upload archive
      unarchive: src=archive.zip dest=/home/user/test/
```
##### EXPECTED RESULTS

Successful uploaded and unpacked test/{1..47}
##### ACTUAL RESULTS

Task Upload archive fails with unzip error and giant output

```
fatal: [192.168.0.1]: FAILED! => {  
  "changed":false,
  "cmd":"/usr/bin/unzip -o /home/vagrant/.ansible/tmp/ansible-tmp-1464769575.42-38201563551750/source ./  ./test/ ./test/1/  <AND_47K_OTHER_FILENAMES> -d /home/user/test/",
  "failed":true,
  "invocation":{  
    "module_args":{  
      "backup":null,
      "content":null,
      "copy":true,
      "creates":null,
      "delimiter":null,
      "dest":"/home/user/test/",
      "directory_mode":null,
      "exclude":[ ],
      "extra_opts":[ ],
      "follow":false,
      "force":null,
      "group":null,
      "keep_newer":false,
      "list_files":false,
      "mode":null,
      "original_basename":"archive.zip",
      "owner":null,
      "regexp":null,
      "remote_src":null,
      "selevel":null,
      "serole":null,
      "setype":null,
      "seuser":null,
      "src":"/home/vagrant/.ansible/tmp/ansible-tmp-1464769575.42-38201563551750/source"
    }
  },
  "msg":"[Errno 7] Argument list too long",
  "rc":7
}
```

**Comment by alikins** [comment]
Could you retest this a devel version from git? 

There have been a lot of changes to unarchive that should address this, including 983cdd00bc71571df74f5f5a8afbe20468c27bde

**Comment by m-messiah** [comment]
Confirm, devel version (I have used ansible https://github.com/ansible/ansible/commit/1b3d6df98514c56fb1a2d86ee3adaa20a1e15586, as last successful build on travis, with updated modules) resolved this bug. 
Thank you.

**Comment by maxramqvist** [comment]
I am hitting the same bug with the latest devel-branch. Am I using the wrong branch?

Or perhaps not the same bug but the same error message.
Large file: ~650mb zipped, 1,1gb unzipped. 130'000 files.

... "failed": true, "item": "hybrisServer-AllExtensions.zip", "msg": "[Errno 7] Argument list too long", "rc": 7}

**Comment by boufnichel** [comment]
Hi maxramqvist,

Have you solve your problem ? i've the same issue when i try to copy hybris all extensions with ansible

Thanks

**Comment by truptimali** [comment]
Hi,
I am also facing the same problem. It used to work before.

**Comment by tomaspinho** [comment]
This is still a bug, Ansible expands all files contained in the zip to the command line as to select them all for extraction. Can someone reopen this?

**Comment by dagwieers** [comment]
Well, this is required in the sense that in order to have an idempotent unarchive module, we need to make a list of files that have to be extracted. The old behaviour extracted everything always. The new behaviour will only extract modified files. Granted if that list is very long, you get this issue.

So I am willing to improve it as to not provide the complete list if no files have been explicitly excluded and no files already existed. But that may not fix it in all cases (e.g. a large archive was modified for most files).

There's no good solution here, except implementing a pure-python unarchive module. Which I would like to implement, rather than fixing silly bugs in a module that can never do the right thing.

**Comment by tomaspinho** [comment]
I've been researching possible solutions, but unfortunately unzip does not have a --files-from flag as tar does. Placing filenames in a temporary file could have been a possible hack.

In regards to the possibility of having unzip functionality ported directly to Python, https://docs.python.org/3/library/zipfile.html seems to cover most of the use cases for the Ansible module.

**Comment by dagwieers** [comment]
A pure-python module is the way to go, but is also limiting (e.g. xz support). I am already working on an `uncompress` module that is pure-python.

Problem is that it won't be a drop-in replacement due to `extra_opts`. But it will be idempotent, and support check-mode and diff-mode !

**Comment by simonpie** [comment]
So, how are we suppose to deploy product like wso2 that come in a large .zip archive ?  Using the command module ?

**Comment by boufnichel** [comment]
at the moment you can use the command module with "unzip" standard unix

**Comment by mailtonskiran** [comment]
That (command: unzip ) neither worked for WSO2 product which it used to work in earlier versions. 
i am finding it difficult to execute unarchive in mac OS EI Captain version 10.11.6 (15G31). 
- unarchive: copy=no src=/home/ec2-user/ansible-test/wso2am-1.10.0.zip dest=/home/ec2-user/ansible-test/ mode=0777
- unarchive: remote_src=yes src=/home/ec2-user/ansible-test/wso2am-1.10.0.zip dest=/home/ec2-user/ansible-test/ mode=0777

ansible --version
ansible 2.1.1.0
  config file = /usr/local/etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

I have tested it with small zip file, it works but for large files it doesn't. Any quick help, would be much appreciated

**Comment by mailtonskiran** [comment]
getting -> "failed": true, "msg": "[Errno 7] Argument list too long", "rc": 7} for a big zip file

**Comment by dagwieers** [comment]
If you want a quick fix, disable the following two lines: https://github.com/ansible/ansible-modules-core/blob/devel/files/unarchive.py#L542

``` python
#        if self.includes:
            # NOTE: Command unzip has this strange behaviour where it expects quoted filenames to also be escaped
#            cmd.extend(map(shell_escape, self.includes))
```

Beware though that this means the **complete** zip file will be unarchived everytime there is a change, any change.

**Comment by dagwieers** [comment]
Please test !

**Comment by mailtonskiran** [comment]
For a command - unarchive: src=/home/ec2-user/ansible-test/wso2am-1.10.0.zip dest=/home/ec2-user/ansible-test/ copy=no mode=0777 
I am getting 

XXXXXXXXXXXXX-d /home/ec2-user/ansible-test/", "failed": true, "msg": "[Errno 7] Argument list too long", "rc": 7}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'site.retry'.         [Errno 2] No such file or directory: ''

PLAY RECAP *********************************************************************
10.20.7.6               : ok=1    changed=0    unreachable=0    failed=1  

This is after commenting below two lines Line no. 542 and 546

# if self.includes:

```
          # NOTE: Command unzip has this strange behaviour where it expects quoted filenames to also be escaped
```

# cmd.extend(map(shell_escape, self.includes))

Note: I can still unzip a file if I use a small size zip

**Comment by mailtonskiran** [comment]
Sorry, I meant to say 542 and 544.
542: if self.includes:
544: cmd.extend(map(shell_escape, self.includes))

**Comment by mailtonskiran** [comment]
This is my ansible installation on mac
/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/modules/core/files
[unarchive.txt](https://github.com/ansible/ansible-modules-core/files/448765/unarchive.txt)

This is my original system Python installation on mac
/Users/sgj929/Library/Python/2.7/lib/python/site-packages/ansible/modules/core/files
[Lib_unarchive.txt](https://github.com/ansible/ansible-modules-core/files/448792/Lib_unarchive.txt)

**Comment by dagwieers** [comment]
@mailtonskiran That's impossible. If we are not adding anything to the argument-list, there's no possible way the argument-list would be too long. My guess is that you are not editing the file that is being actually used.

**Comment by mailtonskiran** [comment]
I just did added the comments, no effect. But, when I meddled with unarchive from the other location file, it started working. I also see the complete list of files unarchived :-)

**Comment by mailtonskiran** [comment]
Thanks @dagwieers

**Comment by dagwieers** [comment]
@mailtonskiran I have no clue what this _"other location file"_ is, but I am happy that it now works for you ! :-)
Thanks for testing !

**Comment by edgarsj** [comment]
Same happening for me with latest devel version (982db58). 

Checking with:
 `ANSIBLE_KEEP_REMOTE_FILES=1 ansible wc-linux64-3 -vvv -b -m unarchive -a "src=https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip dest=/opt creates=/opt/android-ndk-r12b copy=no"`

Output has: `"cmd": "/usr/bin/unzip -o /tmp/ansible_6jJQ3g/android-ndk-r12b-linux-x86_64.zip 'android\\-ndk\\-r12b\\/' 'android\\-ndk\\-r12b\\/toolchains\\/' ... lists all the filenames inside the archive` and obviously: `"msg": "[Errno 7] Argument list too long",`

**Comment by edgarsj** [comment]
Oh, I read the commit 078f2a mentioned above. 

> Unfortunately we cannot fix this for `unzip`

So should we rewrite our ansible playbooks to manually download and extract Android NDK zip instead of using unarchive module that actually worked ok in the past?

**Comment by dagwieers** [comment]
@edgarsj That note was related to the line directly above, which means we have to unzip the complete archive if one or more files have modifications. (Obviously we exclude files that are excluded on the command-line, or when keep_newer is used) That was the behaviour you deemed "worked ok in the past".

I don't think it is ok to extract the whole archive when a single file is modified, but I cannot fix it on the command-line.

**Comment by edgarsj** [comment]
Sorry @dagwieers, hopefully your fix will be merged soon.
