### ISSUE TITLE
docker_container - Registry Field Not Used

### ISSUE THREAD

**Issue by amcrn** [ansible/ansible-modules-core#3824]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.0.0 (detached HEAD b599477242) last updated 2016/05/31 22:32:16 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 04a871d007) last updated 2016/05/31 22:32:28 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD b5fa2b3416) last updated 2016/05/31 22:32:34 (GMT +000)
  config file = /ansible/ansible.cfg
  configured module search path = ['/opt/ansible/ansible/library']
```
##### CONFIGURATION

None.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The docker_container documentation suggests that a field called `registry` is supported: https://github.com/ansible/ansible-modules-core/blob/e8db7fd8cc96299b6758164c8e1f45ebef04e7fc/cloud/docker/docker_container.py#L321-L326 . 

However, this field is not registered anywhere, resulting in `FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: registry"}`
##### STEPS TO REPRODUCE

N/A
##### EXPECTED RESULTS

As far as I can tell, this field is no longer needed and therefore this documentation can be removed. However, the original `docker` module supported `registry` and therefore it's inconclusive from my end as to whether this is a documentation issue, or a code issue.
##### ACTUAL RESULTS

N/A

**Comment by chouseknecht** [comment]
Pretty sure we don't need registry. Should be able to pull from private registry by providing full path in image option. Will test to make sure that works and then remove _registry_ option.

**Comment by chouseknecht** [comment]
You can provide the full path e.g. `image: localhost:5000/chouseknecht/ubuntu:14.04`, and that will work, provided you previously logged into the registry with `docker_login` (or `docker login` from the command line).

**Comment by amcrn** [comment]
thanks @chouseknecht for the quick fix!
