### ISSUE TITLE
"file" cannot create a relative symlink in a particular directory

### ISSUE THREAD

**Issue by leonty** [ansible/ansible-modules-core#3825]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

Module "file" (as well as many others working with the file system)
##### ANSIBLE VERSION

```
ansible 2.0.0.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = /opt/ansible_modules/
```
## 
##### OS / ENVIRONMENT

Ubuntu Server 16.04
##### SUMMARY

The module "file" doesn't really provide all means to create relative symlinks. The current directory is important for this action and it cannot be specified. Neither there's a flag to tell the module to create relative symlink in a specific directory.
This is important for directories exported via NFS. Links that reside (both src and dest) in such a directory must be relative so that the remote can follow it.
##### STEPS TO REPRODUCE

Create a relative symlink from /bin/ls to /bin/myls using the module "file". There's no way to make the dest parameter relative because it won't get into the /bin then.
##### EXPECTED RESULTS

It could be an additional parameter like "chdir" for "command" module. 
Or there could be a flag like "relative=true" or "state=relative" so the the module compare the the "src" and "dest" paths, take the longest matching segment, change the current directory to this segment and create a link using the relative rest of paths.

It could be implemented as follows:
1) src=build-1234 dest=release chdir=/opt/myapp
the module changes the current directory to "/opt/myapp/" and performs "ln -s build-1234 release"

or

2) src=/opt/myapp/build-1234 dest=/opt/myapp/release state=relative (or relative=true)
the module finds the longest matching path prefix (that is "/opt/myapp/"), changes the current directory to this prefix (/opt/myapp/) and performs "ln -s build-1234 release"
##### ACTUAL RESULTS

If the "dest" parameter is not a full path, it will be in some temporary directory of the ansible script.

**Comment by bcoca** [comment]
you should be able to create a relative link regardless of the cwd, use the `force` option to ignore the source's existence relative to cwd.

**Comment by leonty** [comment]
@bcoca I don't really understand how you mean to use it...

```
localhost# ansible remotesrv -m file -a "src=ls dest=/bin/myls state=link force=true"

remotesrv# ls -l /bin/myls
ls: cannot access /bin/myls: No such file or directory

localhost# ansible remotesrv -m file -a "src=/bin/ls dest=myls state=link force=true"

remotesrv# ls -l /bin/myls
ls: cannot access /bin/myls: No such file or directory
```

and I expect:

```
remotesrv# ls -l /bin/myls
lrwxrwxrwx 1 root root 2 Jun  2 00:17 /bin/myls -> ls
```

**Comment by bcoca** [comment]
`ansible remotesrv -m file -a "src=./ls dest=/bin/myls state=link force=true"`

it has to be relative to the link not CWD

**Comment by leonty** [comment]
The command succeds but there's no link myls->ls in /bin

**Comment by leonty** [comment]
It's even stranger for long paths:

```
remotesrv# mkdir -p /tmp/a/b/c/d 
remotesrv# ls -l /tmp/a/b/c
total 0
drwxr-xr-x 2 root root 6 Jun  2 00:52 d

localhost# ansible remotesrv -m file -a "src=./d dest=/tmp/a/b/c/d2 state=link force=true"
remotesrv | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "Error while linking: [Errno 2] No such file or directory",
    "path": "/tmp/a/b/c/d2",
    "state": "absent"
}
```

**Comment by bcoca** [comment]
it does succeed and create a symlink in /bin for me

**Comment by leonty** [comment]
Yes, it works. It's worth to add such an example to the file module.
