### ISSUE TITLE
nxos_command ssh_keyfile not working

### ISSUE THREAD

**Issue by cjreyn** [ansible/ansible-modules-core#3862]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

networking/nxos_command
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/admin-0/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Scientific Linux 6.7
##### SUMMARY

I can successfully authenticate against the NX-OS device using a username/password with transport:cli. When using an ssh key it fails with a socket timeout. I have tested access to the NX-OS device using the same user and ssh key and it works fine in the shell.

The same user/key works fine with an IOS device using ios_command (actually IOS-XE).
##### STEPS TO REPRODUCE

Playbook:

```
[admin-0@control-0 ansible]$ cat test_nxos.yml 

---
- hosts: test_nxos
  remote_user: admin-0
  gather_facts: no
  connection: local
  roles:
   - test_nxos_cmd
```

Role:

```
[admin-0@control-0 ansible]$ cat roles/test_nxos_cmd/tasks/main.yml 

---
- name: test command
  nxos_command:
    host: 10.11.187.17
    username: admin-0
    transport: cli
    ssh_keyfile: "/home/admin-0/.ssh/id_rsa"
    commands: ["show version"]
```
##### EXPECTED RESULTS

Output of show version
##### ACTUAL RESULTS

[admin-0@control-0 ansible]$  ansible-playbook --diff --check test_nxos.yml  -vvv
Using /home/admin-0/ansible/ansible.cfg as config file

PLAYBOOK: test_nxos.yml ********************************************************
1 plays in test_nxos.yml

PLAY [test_nxos] ***************************************************************

TASK [test_nxos_cmd : test command] ********************************************
task path: /home/admin-0/ansible/roles/test_nxos_cmd/tasks/main.yml:2
<switch-0> ESTABLISH LOCAL CONNECTION FOR USER: admin-0
<switch-0> EXEC /bin/sh -c '( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1464966635.06-71959254296436`" && echo ansible-tmp-1464966635.06-71959254296436="`echo $HOME/.ansible/tmp/ansible-tmp-1464966635.06-71959254296436`" ) && sleep 0'
<switch-0> PUT /tmp/tmpz0wwh4 TO /home/admin-0/.ansible/tmp/ansible-tmp-1464966635.06-71959254296436/nxos_command
<switch-0> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /home/admin-0/.ansible/tmp/ansible-tmp-1464966635.06-71959254296436/nxos_command; rm -rf "/home/admin-0/.ansible/tmp/ansible-tmp-1464966635.06-71959254296436/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_eIL9y_/ansible_module_nxos_command.py", line 195, in <module>
    main()
  File "/tmp/ansible_eIL9y_/ansible_module_nxos_command.py", line 160, in main
    response = module.execute(commands, **kwargs)
  File "/tmp/ansible_eIL9y_/ansible_modlib.zip/ansible/module_utils/nxos.py", line 246, in execute
  File "/tmp/ansible_eIL9y_/ansible_modlib.zip/ansible/module_utils/nxos.py", line 223, in connect
  File "/tmp/ansible_eIL9y_/ansible_modlib.zip/ansible/module_utils/nxos.py", line 175, in connect
  File "/tmp/ansible_eIL9y_/ansible_modlib.zip/ansible/module_utils/shell.py", line 117, in open
  File "/tmp/ansible_eIL9y_/ansible_modlib.zip/ansible/module_utils/shell.py", line 126, in receive
  File "/usr/lib/python2.6/site-packages/paramiko/channel.py", line 586, in recv
    raise socket.timeout()
socket.timeout

fatal: [switch-0]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "nxos_command"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_eIL9y_/ansible_module_nxos_command.py\", line 195, in <module>\n    main()\n  File \"/tmp/ansible_eIL9y_/ansible_module_nxos_command.py\", line 160, in main\n    response = module.execute(commands, **kwargs)\n  File \"/tmp/ansible_eIL9y_/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 246, in execute\n  File \"/tmp/ansible_eIL9y_/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 223, in connect\n  File \"/tmp/ansible_eIL9y_/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 175, in connect\n  File \"/tmp/ansible_eIL9y_/ansible_modlib.zip/ansible/module_utils/shell.py\", line 117, in open\n  File \"/tmp/ansible_eIL9y_/ansible_modlib.zip/ansible/module_utils/shell.py\", line 126, in receive\n  File \"/usr/lib/python2.6/site-packages/paramiko/channel.py\", line 586, in recv\n    raise socket.timeout()\nsocket.timeout\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
switch-0               : ok=0    changed=0    unreachable=0    failed=1

**Comment by privateip** [comment]
merged 16181 which should address this problem
