### ISSUE TITLE
Subversion: Export fails because `svn info` is called after export

### ISSUE THREAD

**Issue by dailyherold** [ansible/ansible-modules-core#388]
I have a task that does the following:
- name: Export latest templates from SVN
  subversion: repo=https://repo/path/to/templates
              dest=/opt/templates
              export=True
              username=user
              password=pass

If the destination folder **does not** exist then the task fails as I get the following msg:
`svn: '/opt/templates' is not a working copy`
Looking at the failed command output by Ansible I see:
`"cmd": "/usr/bin/svn --non-interactive --trust-server-cert --no-auth-cache --username user --password ******** info /opt/templates"`
Confirming in the source code I find on [line 225](https://github.com/ansible/ansible-modules-core/blob/devel/source_control/subversion.py#L225) that `get_revision()` will be run no matter if export is true or false. [`get_revision()`](https://github.com/ansible/ansible-modules-core/blob/devel/source_control/subversion.py#L141) calls `svn info` which will fail if `export=True` since there is no `.svn` file. 

**Note:** The repo path _is_ in fact exported on the remote machine despite this message. So the export action itself works, it is just the call to `get_revision()` that fails.

Any further attempts to run fail as well, and I get the same `ERROR: /opt/templates folder already exists, but its not a subversion repository.` as the existing issue #370.

**Comment by abadger** [comment]
I just merged https://github.com/ansible/ansible-modules-core/pull/506 which should fix this issue as well.  Please open a new bug if the problem still occurs with the new version of the module.
