### ISSUE TITLE
impossible use of vsphere_guest for stand alone esxi hosts

### ISSUE THREAD

**Issue by mihai-satmarean** [ansible/ansible-modules-core#3915]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible-modules-core/cloud/vmware
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

when using vsphere_guest against an standalone esxi host the key pair datacenter and hostname are required thus failing

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case this works by using the ESXI machine as the hostname and ha-datacenter  as the datacenter, as documented in the module. http://docs.ansible.com/ansible/vsphere_guest_module.html#options

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
