### ISSUE TITLE
docker: check for container existence broken for swarm

### ISSUE THREAD

**Issue by awasilyev** [ansible/ansible-modules-core#3916]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

default
##### OS / ENVIRONMENT

docker-1.11.1, centos 7
##### SUMMARY

check for container existence broken for swarm
##### STEPS TO REPRODUCE

[root@ba0 ~]# ansible -c local localhost -m docker_container -a "image=rabbitmq name=mq1 docker_url=tcp://127.0.0.1:2376 "
localhost | SUCCESS => {
.....

[root@ba0 ~]# ansible -c local localhost -m docker_container -a "image=rabbitmq name=mq1 docker_url=tcp://127.0.0.1:2376 "
localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "Error creating container: 409 Client Error: Conflict (\"Conflict: The name mq1 is already assigned. You have to delete (or rename) that container to be able to assign mq1 to a container again.\")"
}
##### EXPECTED RESULTS

docker module find that container already running and does nothing on this step
##### ACTUAL RESULTS

docker module don't see existing container with this name and trying to launch it agait - which cause error

**Comment by chouseknecht** [comment]
@awasilyev If you're trying to launch containers on swarm, you should be doing it with docker_service. docker_container is not intended to support swarm.
