### ISSUE TITLE
postgres_user: assign privs to all tables

### ISSUE THREAD

**Issue by rgrinberg** [ansible/ansible-modules-core#3948]
How can I assign privileges to all tables in a database? This is straightforward in SQL:

``` sql
GRANT SELECT ON ALL TABLES IN SCHEMA Public TO readonly;
```

But it seems like `ALL TABLES IN SCHEMA Public` can't be specified as a table. But it seems like all the queries are hard coded to use tables. For example:

``` sql
    query = '''SELECT privilege_type FROM information_schema.role_table_grants
    WHERE grantee=%s AND table_name=%s AND table_schema=%s'''
```

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
