### ISSUE TITLE
mysql_user fails to create grant "GRANT" but works with "GRANT OPTION"

### ISSUE THREAD

**Issue by kowalskey** [ansible/ansible-modules-core#395]
Hello!

After upgrade to ansible 1.8 I noticed that I'm unable to create _mysql_user_ resource when
priv field contains "GRANT".

failing example:

``` yaml
mysql_user: >
    user=xxx
    password=yyy
    state=present
    priv=*.*:ALL,GRANT
```

working example:

``` yaml
  mysql_user: >
    user=xxx
    password=yyy
    state=present
    priv=*.*:ALL,"GRANT OPTION"
```

**Comment by MiLk** [comment]
You have to update to 1.8.1
See #391 and https://github.com/ansible/ansible/issues/9633

**Comment by kowalskey** [comment]
I confirm that after update to  1.8.1 I am able to correctly execute playbooks which add MySQL grants containing "WITH GRANT OPTION" clause.
