### ISSUE TITLE
docker_container - security_opts - unknown type <type 'list'> error

### ISSUE THREAD

**Issue by quater** [ansible/ansible-modules-core#3956]
##### ISSUE TYPE
- Bugfix Pull Request
##### COMPONENT NAME

docker_container.py
##### Feature Name

security_opts
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/modules/']
```
##### SUMMARY

I have been trying to use the "security_opts" option as outlined below.

```
    security_opts:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
```

This has been fixed with below pull request.

Fix has been proposed with #3959 docker_container - security_opts - unknown type <type 'list'> error

**Comment by nitzmahone** [comment]
Should be fixed by #3959 - closing
