### ISSUE TITLE
docker_service - NameError: global name 'compose_version' is not defined

### ISSUE THREAD

**Issue by quater** [ansible/ansible-modules-core#3978]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker_service
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/modules/']
```
##### OS / ENVIRONMENT

Ubuntu 16.04
Kernel: 4.4.0-21-generic x86_64
Docker-py: 1.8.0
Docker API: 1.23
##### SUMMARY

Trying to use the `docker_service` module but get error when running a very basic playbook. The error message is **NameError: global name 'compose_version' is not defined**:

```
fatal: []: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_PxFd_Y/ansible_module_docker_service.py\", line 807, in <module>\r\n    main()\r\n  File \"/tmp/ansible_PxFd_Y/ansible_module_docker_service.py\", line 802, in main\r\n    result = ContainerManager(client).exec_module()\r\n  File \"/tmp/ansible_PxFd_Y/ansible_module_docker_service.py\", line 487, in __init__\r\n    if LooseVersion(compose_version) < LooseVersion(MINIMUM_COMPOSE_VERSION):\r\nNameError: global name 'compose_version' is not defined\r\n", "msg": "MODULE FAILURE", "parsed": false}
```
##### STEPS TO REPRODUCE

I only need to include the `docker_service` directive and get the error.

```
- docker_service:
    project_src: blabla
    state: absent
```

##### EXPECTED RESULTS

Status OK:
##### ACTUAL RESULTS

fatal: []: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_PxFd_Y/ansible_module_docker_service.py\", line 807, in <module>\r\n    main()\r\n  File \"/tmp/ansible_PxFd_Y/ansible_module_docker_service.py\", line 802, in main\r\n    result = ContainerManager(client).exec_module()\r\n  File \"/tmp/ansible_PxFd_Y/ansible_module_docker_service.py\", line 487, in **init**\r\n    if LooseVersion(compose_version) < LooseVersion(MINIMUM_COMPOSE_VERSION):\r\nNameError: global name 'compose_version' is not defined\r\n", "msg": "MODULE FAILURE", "parsed": false}

**Comment by chouseknecht** [comment]
I believe this is happening because the compose library is not actually installed. The check for the correct version takes place before we check if the module actually imported.

This PR reverses the order so that we detect the missing compose module first and stop before attempting to check the version:  https://github.com/ansible/ansible-modules-core/pull/3995
