### ISSUE TITLE
netcfg.py using OrderDict from collections.py which isn't available under Python 2.6

### ISSUE THREAD

**Issue by dpcryer** [ansible/ansible-modules-core#3979]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

nxos_template and other Networking modules that use netcfg.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/xxxxx/.ansible.cfg
  configured module search path = Default w/o ocerrides
```
##### CONFIGURATION

No significant configuration changes from default ansible config.
##### OS / ENVIRONMENT

SLES 11
Python 2.6.8
##### SUMMARY

Attempting to use module nxos_template results in an error

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_epZvOE/ansible_module_nxos_template.py", line 164, in <module>
    main()
  File "/tmp/ansible_epZvOE/ansible_module_nxos_template.py", line 146, in main
    commands = str(candidate).split('\n')
  File "/usr/local/lib64/python2.6/site-packages/ansible-2.1.0.0-py2.6.egg/ansible/module_utils/netcfg.py", line 112, in **str**
    config = collections.OrderedDict()
AttributeError: 'module' object has no attribute 'OrderedDict'

Doing a bit of searching seem to indicate that OrderedDict isn't available in the collections.py module until Python 2.7. Documentation indicates that ansible control machine should be able to run on Python 2.6.
##### STEPS TO REPRODUCE

```
Playbook:

---
- hosts: xxxxxx
  gather_facts: false
  tasks:
     - nxos_template:
          src: yyyyyy.j2
          host: "{{ inventory_hostname }}"
          username: zzzzzz
          force: True
       connection: local
```

##### EXPECTED RESULTS

Expected result would be a change to the configuration of the host based on the template file.
##### ACTUAL RESULTS

Fatal error and play failed

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_epZvOE/ansible_module_nxos_template.py", line 164, in <module>
    main()
  File "/tmp/ansible_epZvOE/ansible_module_nxos_template.py", line 146, in main
    commands = str(candidate).split('\n')
  File "/usr/local/lib64/python2.6/site-packages/ansible-2.1.0.0-py2.6.egg/ansible/module_utils/netcfg.py", line 112, in __str__
    config = collections.OrderedDict()
AttributeError: 'module' object has no attribute 'OrderedDict'

fatal: [xxxxxx]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"force": true, "host": "xxxxxx", "src": "device-alias database\n device-alias name BLAH pwwn 01:02:03:04:05:06:07:08\ndevice-alias commit\n", "username": "zzzzzz"}, "module_name": "nxos_template"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_epZvOE/ansible_module_nxos_template.py\", line 164, in <module>\n    main()\n  File \"/tmp/ansible_epZvOE/ansible_module_nxos_template.py\", line 146, in main\n    commands = str(candidate).split('\\n')\n  File \"/usr/local/lib64/python2.6/site-packages/ansible-2.1.0.0-py2.6.egg/ansible/module_utils/netcfg.py\", line 112, in __str__\n    config = collections.OrderedDict()\nAttributeError: 'module' object has no attribute 'OrderedDict'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by dpcryer** [comment]
Complete novice with Git (and not much Python experience either!) so haven't worked out how to do the pull requests etc. and I don't know how bad a thing it is to add a dependancy on ordereddict (https://pypi.python.org/pypi/ordereddict?). If that's OK then I think the following diffs would pull in OrderedDict from either collections of it's there or ordereddict otherwise.

[netcfg.txt](https://github.com/ansible/ansible-modules-core/files/335886/netcfg.txt)

**Comment by privateip** [comment]
I think the right solution here is to refactor OrderedDict out of netcfg for the time being (which I'm working on now).  I hope to have a fix available very soon.

**Comment by dpcryer** [comment]
Great, thanks.
