### ISSUE TITLE
Unarchive module - Throws error when unzipping a folder containing spaces

### ISSUE THREAD

**Issue by avalara-chase-farrant** [ansible/ansible-modules-core#3980]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

unarchive.py
##### ANSIBLE VERSION

ansible 2.1.0.0 (also exists in 2.1.1 RC1. Was previously working in 2.0.0.0)
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Ubuntu
##### SUMMARY

When trying to extract a .zip file, an error is thrown if a folder contains a space within the folder name. (Haven't tried a filename with a space.)
##### STEPS TO REPRODUCE

Create a .zip file

Test.zip
--testfile1.txt
--\NestedFolderWithoutSpaces
----testfile2.txt
--\Nested Folder With Spaces
----testfile3.txt

If you try to extract this using unarchive, it throws an error.
##### EXPECTED RESULTS

Extracted zip file w/out errors. Was working in 2.0.0.0.
##### ACTUAL RESULTS

fatal: [KCISDKWRK-WV02.sanjuan.avalara.com -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/ansible/eztax/Java Interface/'"}

**Note, the output could be different for 2.1.1 RC

**Comment by abadger** [comment]
@avalara-chase-farrant I think I lead you astray.  I had an old checkout when i tried your test case.  I think that 2.1.1rc1 is fixed as it has this commit in it: 
- devel: https://github.com/ansible/ansible-modules-core/commit/3f7a935932c888d624cf8e6bb4a3ccf300b9345f
- stable-2.1: https://github.com/ansible/ansible-modules-core/commit/e50653bde479c7d3fc99946d801926c3ceedb59b

Give the rc a try and see if this is fixed for you.

**Comment by avalara-chase-farrant** [comment]
I believe you are correct. I updated to the latest version and the issue seems to have been resolved. Although now I am seeing new unrelated errors and will probably create another issue for them.

**Comment by avalara-chase-farrant** [comment]
This can be closed I believe.

**Comment by dagwieers** [comment]
This is indeed fixed. @abadger

**Comment by jmcollin78** [comment]
Hello, I just reproduce the problem with the 2.1.0.0 release on Debian 8 with a zip file containing a file with whitespace.

```
root$ ansible --version 
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

Should it be fixed in this release ? Should I open a new Issue ?

Jean-Marc

**Comment by dagwieers** [comment]
Please test with the devel branch instead. The nuarchive module in Ansible v2.1.0.0 has known issues.

**Comment by jmcollin78** [comment]
Sorry but I'm in production env and I cannot test with devel branch. I will wait for the next release instead. Thx for you reply.
