### ISSUE TITLE
Yum module's state=latest doesn't appear to work with direct URLs to RPMs

### ISSUE THREAD

**Issue by slmingol** [ansible/ansible-modules-core#3983]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

yum module
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0 (devel 1db02dfb71) last updated 2016/06/18 12:08:52 (GMT -400)
  lib/ansible/modules/core: (detached HEAD f0f5272f90) last updated 2016/06/18 12:09:05 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 6cb6829384) last updated 2016/06/18 12:09:05 (GMT -400)
  config file = /Users/sammingolelli/projects/git_repos/devops/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using the YUM module to install a RPM via a direct URL the state=latest doesn't work.
##### STEPS TO REPRODUCE

```
$ ansible -s -i host all -m yum -a 'name=http://www.server.com/apps/RPMS/tomcat8-8.0.24-1.noarch.rpm state=latest'
hostx | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "No Package matching 'http://www.server.com/apps/RPMS/tomcat8-8.0.24-1.noarch.rpm' found available, installed or updated",
    "rc": 0,
    "results": []
}
```
##### EXPECTED RESULTS

The newer version of the RPM should've been installed/upgraded.
##### ACTUAL RESULTS

Running from a playbook shows the error like so:

```
fatal: [hostx]: FAILED! => {"changed": false, "failed": true, "msg": "No Package matching 'http://www.server.com/apps/RPMS/tomcat8-8.0.24-1.noarch.rpm' found available, installed or updated", "rc": 0, "results": []}
```

**Comment by alikins** [comment]
Looking at the yum module docs, the docs only mention using a full url in combination with 'state=present'. 

To install a package from a full url, the state needs to be 'present'

From http://docs.ansible.com/ansible/yum_module.html:

> Package name, or package specifier with version, like name-1.0. When using state=latest, this can be '*' which means run: yum -y update. You can also pass a url or a local path to a rpm file (using state=present). To operate on several packages this can accept a comma separated list of packages or (as of 2.0) a list of packages.

Looking at the yum module code, the path for handing state=latest doesn't support full urls. The docs don't really mention it, but the expectation for 'state=latest' is that the pkg will be available in a yum repo.

The error message in that case is vague though, and there is a fixme in the code related to that.

``` python
pkglist = what_provides(module, repoq, spec, conf_file, en_repos=en_repos, dis_repos=dis_repos)
# FIXME..? may not be desirable to throw an exception here if a single package is missing
if not pkglist:
    res['msg'] += "No Package matching '%s' found available, installed or updated" % spec
    module.fail_json(**res)
```

I think the code is working correctly, at least according to the docs. But that error message could be improved and the docs blurb could be more explicit about the requirements for state=latest.

Using state=present should let you install via URL.

**Comment by slmingol** [comment]
Your description makes sense, especially given the examples where state=present is shown, while state=latest is omitted. 

It still feels like state=present is not working correctly though. If I were to change the name of the RPM, yum still returns the error, so I'm not sure what to make of that. Guessing that YUM is looking at the internals of the RPM, and determining that the package named inside of the RPM is installed, and not the file name per say.

I guess my gripe is that the state=present for a URL feels like a misplaced feature and should probably be removed if it's not going to behave in a consistent manner with the rest of the YUM module.

**Comment by jctanner** [comment]
Implemented in https://github.com/ansible/ansible-modules-core/pull/4003

**Comment by jctanner** [comment]
Hi!

A change has been applied for this ticket, which should resolve this item for you.

If you believe this ticket is not resolved, or have further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments on closed tickets, though the mailing list is a great way to get involved or discuss this one further.

Thanks!
