### ISSUE TITLE
apt_key fails to fetch GPG key sometimes

### ISSUE THREAD

**Issue by mattymo** [ansible/ansible-modules-core#3986]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

apt_key
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 16.04 (Xenial)
##### SUMMARY

ansible node1 -b --become-user=root apt_key -m apt_key -a "keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D"
sometimes has error:
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net\ngpg: no valid OpenPGP data found.\ngpg: Total number processed: 0\ngpg: keyserver communications error: keyserver helper general error\ngpg: keyserver communications error: unknown pubkey algorithm\ngpg: keyserver receive failed: unknown pubkey algorithm

Repeating would mitigate this problem.
##### STEPS TO REPRODUCE

```
ansible node1 -b --become-user=root apt_key -m apt_key -a "keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D"
```

##### ACTUAL RESULTS

```

```

**Comment by Xyrodileas** [comment]
I still get this issue from time to time with my plays.
