### ISSUE TITLE
tests: how do we submit these in concert with module code?

### ISSUE THREAD

**Issue by billwanjohi** [ansible/ansible-modules-core#40]
Like many others, I have a recently closed Ansible pull request that I'd like to resubmit here (https://github.com/ansible/ansible/pull/6303).

My original pull request has an integration test for the added functionality, and I'd like to submit that. Unfortunately, the module tests didn't come along with the module code in the repository split.

Given this, what's the best way to submit tests in one repository for functionality that's yet to be merged in another repository?

**Comment by mpdehaan** [comment]
Hi,

This looks like a ticket and not a pull request.  Can you please resubmit this as a pull request?

Thanks very much!

**Comment by billwanjohi** [comment]
Hi, sorry for not being clear. I submitted the user module patch as pull request #41. I intended for this issue to discuss the general confusion around module tests, since I figured many people would be confused about where to put them.
