### ISSUE TITLE
win_get_url: Error downloading when file exists 

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible-modules-core#4036]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_get_url
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0 (devel 9330edd6b9) last updated 2016/06/24 13:04:03 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 530ee87bd3) last updated 2016/06/24 13:04:03 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 1c36665545) last updated 2016/06/24 13:04:03 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

ANSIBLE_KEEP_REMOTE_FILES=1
##### OS / ENVIRONMENT

Ansible host OSX 10.11.5
Managed host Windows 7 64bit
##### SUMMARY

Error downloading https://www.cygwin.com/setup-x86.exe to C:\cygwin\setup-x86.exe Exception calling DownloadFile with 2 argument(s): An exception occurred during a WebClient request.
##### STEPS TO REPRODUCE

```
- name: create cygwin home directory
  win_file:
    path: 'C:\cygwin'
    state: 'directory'
  tags: cygwin

- name: get cygwin setup 
  win_get_url:
    url: 'https://www.cygwin.com/setup-x86.exe'
    dest: 'C:\cygwin\setup-x86.exe'
  tags: cygwin
```

##### EXPECTED RESULTS

The setup-x86.exe would be downloaded and saved to C:\cygwin\setup-x86.exe.
##### ACTUAL RESULTS

NOTE: if the C:\cygwin directory does not exist the play complete successfully
NOTE2: If C:\cygwin\setup-x86.exe does not exist the play complete successfully

Adding force: 'yes' to the win_get_url lets things complete successfully so the bug seems to be if the dest file exists the $webClient.DownloadFile() fails.

```
fatal: [win7-90day]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "win_get_url"}, "msg": "Error downloading https://www.cygwin.com/setup-x86.exe to C:\\cygwin\\setup-x86.exe Exception calling \"DownloadFile\" with \"2\" argument(s): \"An exception occurred during a WebClient request.\""}
```

Running the generated .ps1 through the debugger.

```
[DBG]: PS C:\Users\Administrator>> $url
https://www.cygwin.com/setup-x86.exe

[DBG]: PS C:\Users\Administrator>> $dest
C:\cygwin\setup-x86.exe

[DBG]: PS C:\Users\Administrator>> 
[DBG]: PS C:\Users\Administrator>> $_
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient 
request."
At C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1466790694.7-32383049506207\win_get_url.p
s1:306 char:9
+         $webClient.DownloadFile($url, $dest)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

**Comment by jhawkesworth** [comment]
So the failure occurs when the file already exists?
Just wondering if the user that you are running as has permissions to overwrite the existing file?

**Comment by basictheprogram** [comment]
Yes, when the file exists. Running as the same user every time.

IF the folder/file does not exist the task succeeds. Run it again as the same user fails.

> On Jun 24, 2016, at 3:51 PM, jhawkesworth notifications@github.com wrote:
> 
> So the failure occurs when the file already exists?
> Just wondering if the user that you are running as has permissions to overwrite the existing fi

## 

Bob Tanner tanner@real-time.com                                 | Phone : 952-943-8700
http://www.real-time.com, Linux, OSX, VMware, Windows | Fax      : 952-943-8500
Key fingerprint = 9906 320A 8BB6 64AD 96A7  7785 CBFB 10BF 568B F98C

**Comment by jhawkesworth** [comment]
Is it not acceptable to run with force: no?

Or if the exe keeps changing and your playbook's purpose is to always update to the latest version, then perhaps just and add a win_file with a sate: absent beforehand?

**Comment by basictheprogram** [comment]
Prefer not to download it if it hasn’t changed, but force: no is an acceptable work around.

> On Jun 24, 2016, at 4:32 PM, jhawkesworth notifications@github.com wrote:
> 
> Is it not acceptable to run with force: no?
> 
> Or if the exe keeps changing and your playbook's purpose is to always update to the latest version, then perhaps just and add a win_file with a sate: absent beforehand?

## 

Bob Tanner tanner@real-time.com                                 | Phone : 952-943-8700
http://www.real-time.com, Linux, OSX, VMware, Windows | Fax      : 952-943-8500
Key fingerprint = 9906 320A 8BB6 64AD 96A7  7785 CBFB 10BF 568B F98C

**Comment by jhawkesworth** [comment]
Can we close this then?

**Comment by basictheprogram** [comment]
> On Jun 25, 2016, at 11:39 AM, jhawkesworth notifications@github.com wrote:
> 
> Can we close this then?

Yes, close.

## 

Bob Tanner tanner@real-time.com                                 | Phone : 952-943-8700
http://www.real-time.com, Linux, OSX, VMware, Windows | Fax      : 952-943-8500
Key fingerprint = 9906 320A 8BB6 64AD 96A7  7785 CBFB 10BF 568B F98C

**Comment by basictheprogram** [comment]
Work-around is to use  force: no, closing ticket.
