### ISSUE TITLE
htpasswd logs users password in output log

### ISSUE THREAD

**Issue by jmcollin78** [ansible/ansible-modules-core#4058]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 1.7.2

```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

$ uname -a
Linux xxxxx 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
##### SUMMARY

When using the htpasswd feature, the password are displayed in output logs.
##### STEPS TO REPRODUCE

My configuration is the following:

```
- name: Install Basic Auth authentication file
  htpasswd: path=/etc/nginx/conf.d/htpasswd create=yes name={{item.login}} password={{item.password}} state=present
  with_items: pio_basic_auth.users
  when: pio_basic_auth is defined
  notify: reload nginx
```

I try to add `no_log: true` but without success.
The output is the following:

```
TASK: [etg-pio-deploy | Install Basic Auth authentication file] *************** 
ok: [etg-pio-tmp] => (item={'login': 'user1', 'password': 'user1Pwd'}) => {"changed": false, "item": {"login": "user1", "password": "user1Pwd"}, "msg": "user1 already present"}
idem for all users.
```
##### EXPECTED RESULTS

The password (ie. user1Pwd in example) is not displayed in output log

**Comment by bcoca** [comment]
fixed via 2f0f04437b605617e850954ad3f4607d39d41a97, it will be part of 2.2 release
