### ISSUE TITLE
DRS Cluster and multiple Folder not working in vsphere_guest module

### ISSUE THREAD

**Issue by hikaushik** [ansible/ansible-modules-core#4079]
1. Folder definition like folder: 'USA/Linux' in var.yaml doesn't work.
   error:-
   failed: [127.0.0.1] => {"failed": true}
   msg: Could not clone selected machine: [Object Not Found]: Couldn't find folder USA/Linux.
2. Don't have option to mention DRS Cluster instead of datastore:

**Comment by nitzmahone** [comment]
@hikaushik Please fill out the issue template you deleted when filing this issue, and give a more detailed explanation of what you're trying to do, as it's unclear from this.
