### ISSUE TITLE
docker_container: add 

### ISSUE THREAD

**Issue by srstsavage** [ansible/ansible-modules-core#4087]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

`docker_container` module
##### ANSIBLE VERSION

(Future version)

**Comment by nitzmahone** [comment]
You mean like this one? http://docs.ansible.com/ansible/docker_container_module.html ;)

**Comment by srstsavage** [comment]
@nitzmahone Weird, I must have accidentally created this while trying to create https://github.com/ansible/ansible-modules-core/issues/4088 but no idea how. Thanks for closing.
