### ISSUE TITLE
More solid language features

### ISSUE THREAD

**Issue by asmodehn** [ansible/ansible-modules-core#4114]
Sorry if this is useless as an issue, feel free to close.

I am pretty new to ansible, and getting used to it triggered a lot of confusion and frustration, because of the different scopes for variables, and how to pass parameters, and role dependencies, etc. all this doesnt seem consistent as a whole...
I feel like all this is a hadoc description yaml format, slowly evolving while needs arise.

But I wonder what really are the blockers to implement a consistent YAML-based functional language, that would allow ansible playbook to rely on time proven solid theory and establish language features ?

Ansible relies on "tasks" to be distributed to different machines, and also on "describing a desired infrastructure state", which is exactly what functional languages are good at implementing (functional languages can be easily paralleled and check https://www.gnu.org/software/guix/ for example on describing a state on one machine).

Is this something in the works ? is it something that was thought about ? Or is it not even worth thinking about it, and if so what would be the reason ?

Thanks for sharing some lights on this topic.

**Comment by jhawkesworth** [comment]
I am just a community volunteer so this is just my opinion but I think the idea with ansible was to make it less of a programming language and using human-readable yaml and keeping the programming constructs minimal was part of that.

I think it was likely that this was thought about as the project founder, Michael DeHaan, previously wrote func https://fedorahosted.org/func/ (and Cobbler).

If you want to go into some detail about what you feel is missing then by all means create a proposal https://github.com/ansible/proposals

**Comment by jctanner** [comment]
Please submit this as a proposal.

**Comment by asmodehn** [comment]
I don't have much time to dedicate to ansible at the moment sadly, so I cant really drive that proposal just yet...
