### ISSUE TITLE
Defining a static IP address with "ansible_host" for a remote hostname in inventory file is useless

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible-modules-core#4118]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Inventory file
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Same issue with 2.1.1.0
##### CONFIGURATION

inventory = ./hosts
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles
fact_caching = redis
fact_caching_timeout = 86400
##### OS / ENVIRONMENT

host: Ubuntu 16.04 4.4.0
##### SUMMARY

If I provide the DNS mapping of a remote hostname in the hosts file through the **ansible_host** variable, ansible is "unable to resolve host name". 
If I use the IP address of the remote host, ansible is able to connect to it of course. 
##### STEPS TO REPRODUCE

In ./hosts:

```
[iosv_l2]
IOSv_L2_1 ansible_host=192.168.137.242
```

**Running any playbook leads to the issue described below in "ACTUAL RESULTS"**.

However, replacing the hostname by:

```
[iosv_l2]
192.168.137.242
```

leads to no connection error obviously.
##### ACTUAL RESULTS

```
TASK [ios_pull_config : Fetching the startup-config from the remote node] ******
task path: /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles/ios_pull_config/tasks/main.yml:49
<192.168.137.242> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.137.242> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467827144.23-57529429825029 `" && echo ansible-tmp-1467827144.23-57529429825029="` echo $HOME/.ansible/tmp/ansible-tmp-1467827144.23-57529429825029 `" ) && sleep 0'
<192.168.137.242> PUT /tmp/tmpPXhiZu TO /root/.ansible/tmp/ansible-tmp-1467827144.23-57529429825029/ios_command
<192.168.137.242> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1467827144.23-57529429825029/ios_command; rm -rf "/root/.ansible/tmp/ansible-tmp-1467827144.23-57529429825029/" > /dev/null 2>&1 && sleep 0'
fatal: [IOSv_L2_1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "authorize": true, "commands": ["show startup-config"], "host": "IOSv_L2_1", "interval": 1, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "port": 22, "provider": "{'username': 'admin', 'authorize': True, 'ssh_keyfile': '~/.ssh/id_rsa', 'auth_pass': '********', 'host': 'IOSv_L2_1', 'version': 2, 'timeout': 10, 'password': '********', 'port': 22, 'transport': 'cli'}", "retries": 10, "ssh_keyfile": "/root/.ssh/id_rsa", "timeout": 10, "username": "admin", "waitfor": null}, "module_name": "ios_command"}, "msg": **failed to connect to IOSv_L2_1:22 - unable to resolve host name**}
```

**Comment by jctanner** [comment]
The first column in an ini style ansible inventory file is called an "alias". This alias must be a resolvable name or reachable adddress for ssh unless the connection is local where modules aren't running on a remote host. The alias is _not_ added into the underlying libsolv libraries or hosts file of the system to make it reachable for all contexts of the ansible run. The ios_command module is expecting a reachable address for the host= parameter, and is expected to fail like in your example if not True.

There are many ways to resolve this:
1. Use your second inventory example
2. Add ios_l2 into /etc/hosts
3. Use a templated variable such as host="{{ ansible_host }}"

**Comment by jean-christophe-manciot** [comment]
I don't get your point at all: from [Ansible inventory documentation](http://docs.ansible.com/ansible/intro_inventory.html): 

> Suppose you have just static IPs and want to set up some aliases that live in your host file, or you are connecting through tunnels. You can also describe hosts like this:
> 
> jumper ansible_port=5555 ansible_host=192.168.1.50

So, my inventory entry seems legitimate and should work; why have you closed this bug report?
Also, it's complicated to use /etc/hosts in my situation because I run Ansible on local labs where the same remote hostname may be used in different labs with different IP addresses. Hence one inventory per lab which is appropriate here.
At last, I need Ansible to run each lab playbook on each aliased remote device, and I use the hostname (not the IP address) as a parameter within the playbook and roles (see example below). So, none of your proposals are applicable here.
For instance in a role:

```
- name: Saving fetched config into local file
  local_action:
        copy content="{{ result.stdout }}" dest=files/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_{{ config }}_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}_{{ ansible_date_time.tz }}.txt
```

**Comment by Niceplace** [comment]
Boy am I glad to read this !

I run ansible (2.1.0) in a docker container and I just spend 5 hours wondering why the heck it refused to connect via SSH to another machine which I could SSH into (by hand) just fine. I read the documentation and used the same variables in my inventory file because I understood the same thing from the documentation as you did. I kept getting a "ssh failed" error with not much to help even at maximum verbosity.

hosts file that generated the error (ip adresses are fictive)

[centos_potato]
ansible_host=166.66.66.66 ansible_port=5555

hosts file without errors

[centos_potato]
172.19.47.85 ansible_port=5555

With some help, I finally found out that ansible adds literally "ansible_host=$THEIP" at the end of the ssh command that it generates. Removing the parameter ansible_host and putting directly the IP adress instead solved the issue.

Why is this ? Maybe I misunderstood the documentation ?

**Comment by jean-christophe-manciot** [comment]
My understanding is that this behaviour is a regression they chose to ignore.
Have you tried the following entry in the inventory file:

```
[centos_potato]
some_hostname ansible_host=172.19.47.85 ansible_port=5555
```

**Comment by Niceplace** [comment]
Hi Jean-Christophe, I just tested your suggestion and it seems to work as well !
Maybe the documentation is not wrong after all, it won't work if a custom hostname is not specified.

To summarize, if the hosts file is structured this way : 

```
[centos_potato]
some_hostname ansible_host=172.19.47.85 ansible_port=5555
```

Or this way

```
[centos_potato]
172.19.47.85 ansible_port=5555
```

It will work, and the following ssh command will be generated by Ansible (I am specifying **-u centos** in my ansible command):

> ssh -C -vvv -o StrictHostKeyChecking=no -o Port=5555 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 -tt 172.19.47.85

However, if the hosts file is structured this way :

```
[centos_potato]
ansible_host=172.19.47.85 ansible_port=5555
```

It will fail to connect and will generate this ssh command (notice the ansible_host at the end)

> ssh -C -vvv -o StrictHostKeyChecking=no -o Port=5555 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 ansible_host=172.19.47.85

Bear in mind that I have nothing in my actual hosts file (/etc/hosts) that defines 172.19.47.85

**Comment by jean-christophe-manciot** [comment]
I have found the trick to workaround the issue in my situation: **no need to use /etc/hosts**, instead in each lab inventory file:
```
[iosv_l2]
192.168.137.242 ansible_host=IOSv_L2_1
```
In the playbooks, inventory_hostname will be the IP address 192.168.137.242.

**Comment by jean-christophe-manciot** [comment]
I have found the trick to workaround the issue in my situation: no need to use /etc/hosts, instead in each lab inventory file, something like this is enough for each remote node:

```
[iosv_l2]
192.168.137.242 ansible_host=IOSv_L2_1
```

In the playbooks, inventory_hostname will only be the IP address of the current remote node.

**Comment by xijq227** [comment]
Is there a way to define host={{ansible_host}} at global level instead of at each individual play?
`---
- name: Junos OS Module Test
  hosts: junos
  roles:
    - Juniper.junos
  connection: local
  remote_user: ansible
  gather_facts: no
  vars:
    #wait_time: 3600
    #pkg_dir: /var/tmp/junos-install
    #OS_version: 14.1R1.10
    #OS_package: jinstall-14.1R1.10-domestic-signed.tgz
    #log_dir: /var/log/ansible

  tasks:
    - name: Checking NETCONF connectivity
      wait_for:
        **host={{ansible_host}}**
        port=830
        timeout=5
    - name: show version
      juniper_junos_command:
        **host={{ansible_host}}**
        commands: "show version"
      register: version
    - name: print version
      debug:
        var: version.stdout`

**Comment by mftovey** [comment]
I solved it in my inventory file this way:

[R1]
10.48.94.50

[S1]
10.48.94.34

[S2]
10.48.150.11

[Routers:children]
R1

[Switches:children]
S1
S2

Now I can specify 'R1' or 'S1' or 'S2' in the playbooks and the IP addresses will be used for the connections.  It is quite kludgy, but what ever works, I guess.
