### ISSUE TITLE
systemd: Shouldn't specify version when it's unreleased

### ISSUE THREAD

**Issue by hagbarddenstore** [ansible/ansible-modules-core#4134]
The systemd module shouldn't specify a version if that version isn't released. Especially when that release doesn't exist yet. It'd be much nicer if it was explicit about not being released yet.

**Comment by bcoca** [comment]
All new modules MUST specify the version in which they are released.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
