### ISSUE TITLE
Windows: raw module does not show change in logs

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible-modules-core#4185]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

[raw](http://docs.ansible.com/ansible/raw_module.html) module
##### ANSIBLE VERSION

```
# ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
#
```
##### SUMMARY

Ansible run should show the number of tasks **changed** when a file or directory is created
##### STEPS TO REPRODUCE

Create a playbook with below tasks

```
- raw: New-Item -Path C:\Users\vikas027\Desktop\testfile.txt -ItemType file
- raw: New-Item -Path C:\Users\vikas027\Desktop\testdir -ItemType Directory
```
##### EXPECTED RESULTS

`changed=2` in ansible-playbook in logs
##### ACTUAL RESULTS

`changed=0` in ansible-playbook in logs

**Comment by nitzmahone** [comment]
Not a bug: raw has no way of knowing what you did (we're not parsing the command or its result in any way). That's what modules are for (eg, see win_file for the case you gave). However, this behavior _is_ inconsistent with the *nix shell/command modules (which aren't currently available for Windows) in that those modules err on the side of always returning `changed: true`. We're discussing changing raw's behavior for 2.2 to be in line with those modules.

**Comment by vikas027** [comment]
@nitzmahone thanks for the explanation
