### ISSUE TITLE
Files are copied in check mode when remote_src is true

### ISSUE THREAD

**Issue by onitake** [ansible/ansible-modules-core#4195]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

copy
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/rieplgr/Code/ansible-swisstxt/ansible.cfg
  configured module search path = ['/usr/share/ansible', 'library']
```
##### OS / ENVIRONMENT

Host: Debian stretch
Target: CentOS 7
##### SUMMARY

When using the remote_src=True parameter in a copy task (or handler), the file(s) are always copied, even in check (-C) mode.
##### STEPS TO REPRODUCE

Create a test file:

```
echo "test" > /tmp/testfile
```

Run the following playbook in **check mode** (ansible-playbook -i localhost -C test.yml):

```

---
- name: copy test file
  copy: remote_src=True src=/tmp/testfile dest=/tmp/targetfile mode=0644
```

##### EXPECTED RESULTS

Only the file /tmp/testfile is created.
##### ACTUAL RESULTS

Both /tmp/testfile and /tmp/targetfile exist.

**Comment by resmo** [comment]
backported fix to stable-2.1 /cc @bcoca
