### ISSUE TITLE
docker_container module state stopped should stop container when match only container name

### ISSUE THREAD

**Issue by winggundamth** [ansible/ansible-modules-core#4199]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

N/A
##### SUMMARY

From https://github.com/ansible/ansible-modules-core/issues/3822. My understanding the container will stop when it presented. To match with present it needs to match all the docker run configuration.

My problem is I already have my production container run by hand right now and I need to control it with docker_container module but I can't stop it right now with state stopped.

Please correct me if I'm wrong but state stopped should stop container when match only name or whatever parameters we put in docker_container action.

**Comment by chouseknecht** [comment]
It will match on name. Something like the following should work:

```
docker_container:
   name: my_container_1
   state: stopped
```

Do you have a test case where that does not work?

EDIT: needs_info
