### ISSUE TITLE
unarchive failed to transfer on devel

### ISSUE THREAD

**Issue by linusgg** [ansible/ansible-modules-core#4202]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

ansible 2.2.0 (devel 134d70e7b9) last updated 2016/07/18 12:43:12 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD 7de287237f) last updated 2016/07/18 12:43:16 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 68ca157f3b) last updated 2016/07/18 12:43:16 (GMT +1000)
  config file = /home/linus/Documents/ansible-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
hostfile = ./inventory
remote_user = centos
host_key_checking = False
log_path = /var/log/ansible.log
##### OS / ENVIRONMENT

management node: ubuntu 14.04
remote node: centos 7
##### SUMMARY

unarchive module shows error when src is an url using latest Ansible devel but works fine using the same playbook using Ansible stable 2.1.0.0 version.
##### STEPS TO REPRODUCE

```
unarchive:
    copy: no
    src: https://someurl.tar.gz
    dest: /tmp/somefolder
    owner: user
    group: user

```

##### EXPECTED RESULTS

changed
##### ACTUAL RESULTS

fatal: [xx.xx.xx.xx]: FAILED! => {"changed": false, "failed": true, "msg": "Source 'https://someurl.tar.gz' failed to transfer"}

**Comment by lucascbeyeler** [comment]
Found where the problem is: files/unarchive.py (Line 736):

> ```
>  if not os.path.exists(src):
>     if not remote_src or copy:
>         module.fail_json(msg="Source '%s' failed to transfer" % src)
> ```

Copy is set as always True. When you reach this condition, as copy will be always True, the module will fail everytime.  I think the correct is this:

> ```
> if not os.path.exists(src):
>     if not remote_src and copy:
>         module.fail_json(msg="Source '%s' failed to transfer" % src)
> ```

Can't push the correction now...maybe later. Sorry =/

**Comment by eb4x** [comment]
Ran into this bug today, thanks for providing a fix!

**Comment by jctanner** [comment]
ping @dagwieers, @pileofrogs

**Comment by dagwieers** [comment]
resolved_by_pr #4244
