### ISSUE TITLE
redhat_subscription errors with "RhsmPool' object has no attribute 'PoolId'"

### ISSUE THREAD

**Issue by rothgar** [ansible/ansible-modules-core#421]
##### Issue Type:

Bug Report
##### Ansible Version:

1.7
##### Environment:

RHEL 6
##### Summary:

An unregistered system cannot attach a subscription upon registration with redhat_subscription
##### Steps To Reproduce:

Unsubscribe a system
Run `ansible localhost -m redhat_subscription -a 'username=disneyfa password=donald pool="Red Hat Enterprise Linux Server"'`
##### Expected Results:

System would be registered and attach to a pool.
##### Actual Results:

I verified the pool exists with `subscription-manager list --available` on the host. Output is

```
rh-host | FAILED >> {
    "failed": true, 
    "msg": "Failed to register with 'subscription.rhn.redhat.com': 'RhsmPool' object has no attribute 'PoolId'"
}
```

I checked that the system is registered with `subscription-manager identity` but `subscription-manager list --consumed` returns "No consumed subscription pools to list"

Because the system registers but fails to attach subscriptions it also causes a problem when trying to attach pools again with ansible because the system needs to be unregistered first. I will open a separate issue for that problem.

**Comment by gregdek** [comment]
Looks like fix for this was merged. Closing.
