### ISSUE TITLE
remove dependency to extra python library for digital_ocean* modules 

### ISSUE THREAD

**Issue by kontrafiktion** [ansible/ansible-modules-core#4221]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

digital_ocean
digital_ocean_sshkey
digital_ocean_domain
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Currently the digital_ocean\* modules have a dependency to an extra Python library: "dopy" (https://github.com/Wiredcraft/dopy). 
1. The library is not very well maintained. Especially: Publishing new releases can currently only be done by a single person
2. The library could be replaced by using ansible.module_utils.urls without too much effort and code duplication 

see also: #4219

**Comment by harneksidhu** [comment]
Close this issue and refer to #4219 as there is strong overlap?

**Comment by alukovenko** [comment]
#4219 is the main issue
wontfix here

**Comment by bcoca** [comment]
closing in favor of #4219
