### ISSUE TITLE
document module_utils.*

### ISSUE THREAD

**Issue by kontrafiktion** [ansible/ansible-modules-core#4222]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

internal: module_utils.*
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

Module developers/maintainers have a hard time using module_utils.\* because there is nearly no documentation. At least I couldn't find any.

Proposal:
1. Create documentation for module_utils.*
2. Publish it on the Ansible web site
###### Details

For example, the fetch_url method does not document its return values. You have to debug and know the internally used urllib2 to understand what the "info" return value contains. 

When creating a new module, using the "requests" library, the build says: 

```
8.60s$ ansible-validate-modules --exclude 'utilities/' .
============================================================================
./cloud/digital_ocean/digital_ocean_tag.py
============================================================================
ERROR: requests import found, should use ansible.module_utils.urls instead
```

**Comment by jctanner** [comment]
@kontrafiktion please file this in https://github.com/ansible/ansible/issues
