### ISSUE TITLE
wait_for fails on apt / aptitude lock-file in /var/lib/dpkg/lock

### ISSUE THREAD

**Issue by jhit** [ansible/ansible-modules-core#4241]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

wait_for
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

bento/ubuntu16.04 Virtualbox
##### SUMMARY

My rule:

```
- name: Wait for automatic system updates
  become: yes
  wait_for: path=/var/lib/dpkg/lock state=absent
```

will wait until ist timeouts with a error. This lockfile is never removed by the system but only emptied.
on shell this works for me:

```
while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
    sleep 1;
done
```
##### STEPS TO REPRODUCE

boot up a bento/ubuntu16.04 virtualbox image and insert as first task/rule the code below.
ubuntu 1604 runs a system update in background on (first) boot, that will lock /var/lib/dpkg/lock for some seconds up to a minute.  

```
- name: Wait for automatic system updates
  become: yes
  wait_for: path=/var/lib/dpkg/lock state=absent
```

##### EXPECTED RESULTS

I would expect wait_for can handle the lock file of apt.
##### ACTUAL RESULTS

```
TASK [common : Wait for automatic system updates] ******************************
==> default: fatal: [33.33.33.20]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for /var/lib/dpkg/lock to be absent."}
==> default:
```

**Comment by alikins** [comment]
```
TASK [common : Wait for automatic system updates] ******************************
==> default: fatal: [33.33.33.20]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for /var/lib/dpkg/lock to be absent."}
==> default:
```

http://docs.ansible.com/ansible/wait_for_module.html

The default timeout is 300 seconds, which that wait_for exceeded. Try bumping the timeout.

**Comment by jhit** [comment]
Hello.

Please review this again. The timeout is not the problem. The lock state on the lockfile is removed after about 60 seconds. The problem is ansible waits for the removal of the file. But this lockfile is never removed but only emptied. So I can set whatever timeout value I want. It will always timeout and never recognise the lockfile is clean.

**Comment by bcoca** [comment]
@jhit, but that is what you are asking wait_for to do, it does not know about locks, it knows if a file exists or not. In any case this is not a bug, just a misunderstanding of what the feature actually does.

**Comment by jhit** [comment]
I see. So my report is more a feature request than a bug report. will see if i can emulate what I need with the search_regex parameter.

**Comment by Hashfyre** [comment]
@jhit Currently facing this issue, were you successful with `search_regex` param?

**Comment by jhit** [comment]
@Hashfyre Please see my comment here: https://github.com/ansible/ansible/issues/16593#issuecomment-253026793
I linked to a workaround in one of my repositories on github.
