### ISSUE TITLE
Script module, Powershell 4.0, Wusa.exe,  Error 2147942405 "Access is denied" 

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible-modules-core#4242]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

script module
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0 (devel 93c5ec42cf) last updated 2016/07/22 15:00:30 (GMT -500)
  lib/ansible/modules/core: (detached HEAD b3c606047d) last updated 2016/07/22 00:12:41 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD d9b4613941) last updated 2016/07/22 00:12:41 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ansible control host OS X 10.11.6
Managed host Windows 7 64-bit
##### SUMMARY

Powershell script (v4.0) gives "Access is denied" when executed via Ansible script task but works properly from the powershell command line
##### STEPS TO REPRODUCE

Powershell info

```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.18444
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

Ansible task

```
- name: install powershell v5 software
  script: "InstallWNF-5.0.ps1"
```

InstallWNF-5.0.ps1

```
$MSU = "C:\Users\Administrator\Downloads\Win7AndW2K8R2-KB3134760-x64.msu"
$Command = "wusa.exe $MSU /quiet /log /forcerestart"; 

# Invoke the command we built above 
Invoke-Expression -Command $Command; 

# Wait for wusa.exe to finish and exit (wusa.exe actually leverages 
# TrustedInstaller.exe, so you won't see much activity within the wusa process) 
while (@(Get-Process wusa -ErrorAction SilentlyContinue).Count -ne 0) { 
    Start-Sleep 1 
    Write-Host "Waiting for update to finish ..." 
} 
```

##### EXPECTED RESULTS

WNF 5.0 and Powershell 5.0 will be installed and the computer will reboot
##### ACTUAL RESULTS

```
TASK [test-workstation : install powershell v5 software] *******************
task path: /Users/tanner/projects/ansible.git/playbooks.git/roles/test-workstation/tasks/main.yml:65
<172.X.X.X> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 172.X.X.X
<172.X.X.X> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1469259240.3-240073857756770").FullName | Write-Host -Separator '';
<172.X.X.X> PUT "/Users/tanner/projects/ansible.git/playbooks.git/roles/test-workstation/files/InstallWNF-5.0.ps1" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1469259240.3-240073857756770\InstallWNF-5.0.ps1"
<172.X.X.X> EXEC &  'C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1469259240.3-240073857756770\InstallWNF-5.0.ps1'
changed: [TEST1457] => {"changed": true, "invocation": {"module_args": {"_raw_params": "InstallWNF-5.0.ps1"}, "module_name": "script"}, "rc": 0, "stderr": "", "stdout": "Waiting for update to finish ...\n", "stdout_lines": ["Waiting for update to finish ..."]}
```

And the Eventviewer shows me

```
Windows update  could not be installed because of error 2147942405 "Access is denied." (Command line: ""C:\Windows\system32\wusa.exe"  C:\Users\Administrator\Downloads\Win7AndW2K8R2-KB3134760-x64.msu /quiet /log /forcerestart") 
```

Executing this script by hand as local Administrator works as expected.

**Comment by jhawkesworth** [comment]
Hi wusa.exe isn't supported via winrm https://support.microsoft.com/en-us/kb/2773898

However there is a workaround described in the link above, though.

Since it's a limitation in windows, rather than anything that can be changed in Ansible, I am going to close this issue. I can vouch for the workaround as I have used it in one of my roles.

**Comment by jensni-ch** [comment]
But then, how can the following examle of the win_package module (http://docs.ansible.com/ansible/win_package_module.html) even work?

>-name: 'Microsoft .NET Framework 4.5.1'
  win_package:
    path: https://download.microsoft.com/download/1/6/7/167F0D79-9317-48AE-AEDB-17120579F8E2/NDP451-KB2858728-x86-x64-AllOS-ENU.exe
    productid: '{7DEBE4EB-6B40-3766-BB35-5CBBC385DA37}'
    arguments: '/q /norestart'
    ensure: present
    expected_return_code: 3010

The .NET Framework 4.5.1 contains .msu files too, so the same problem should occur in the mentioned example.
 (I do get the error if I try to install .NET 4.5.2.)

Thanks for advice
