### ISSUE TITLE
ec2_eip not idempotent

### ISSUE THREAD

**Issue by dkaufman-irise** [ansible/ansible-modules-core#430]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9 (devel 2bf269568b) last updated 2014/12/03 07:59:53 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 3a80b734e6) last updated 2014/12/03 07:59:53 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 317654dba5) last updated 2014/12/03 07:59:54 (GMT +000)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/28 01:26:59 (GMT +000)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/28 01:27:04 (GMT +000)
  configured module search path = /usr/share/ansible
##### Environment:

Amazon Linux AMI 2014.09
##### Summary:

using ec2_eip to allocate/assoiciate an elastic IP with an instance is not idempotent - subsequent runs of a play error out because an elastic IP is already allocated.
##### Steps To Reproduce:

include this task in a role or playbook:

```
- name: allocate and associate EIP with instance_id
  ec2_eip: instance_id={{ instance_id}} region={{ region }} in_vpc=yes  aws_access_key={{ aws_access_key}} aws_secret_key={{ aws_secret_key }} state=present
```

run given play more than once.
##### Expected Results:

task is skipped if elastic IP is associated with instance.
##### Actual Results:

```
failed: [HOSTNAME] => {"failed": true, "parsed": false}

SUDO-SUCCESS-xxuqhjqkaxicupomjpkkerurdieofrec
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1417594450.45-30576064061425/ec2_eip", line 2063, in <module>
    main()
  File "/tmp/ansible-tmp-1417594450.45-30576064061425/ec2_eip", line 282, in main
    address = allocate_address(ec2, domain, module, reuse_existing_ip_allowed)
  File "/tmp/ansible-tmp-1417594450.45-30576064061425/ec2_eip", line 199, in allocate_address
    address = ec2.allocate_address(domain=domain)
  File "/usr/lib/python2.6/site-packages/boto/ec2/connection.py", line 1828, in allocate_address
    return self.get_object('AllocateAddress', params, Address, verb='POST')
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1204, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AddressLimitExceeded</Code><Message>The maximum number of addresses has been reached.</Message></Error></Errors><RequestID>ac7f5ad1-d9ba-43db-b14a-61719770ffaa</RequestID></Response>


FATAL: all hosts have already failed -- aborting
```

**Comment by lamielle** [comment]
Looks like PR #300 will fix this issue.  I'm running into this problem as well.

**Comment by bennojoy** [comment]
@dkaufman-irise #1015 seems to fix it.. can you give the latest devel a try

**Comment by dkaufman-irise** [comment]
ec2_eip.py from latest devel is now idempotent.  reports

```
ok: [HOSTNAME -> 127.0.0.1] => {"changed": false, "public_ip": "ip.add.re.ss"}
```

when host already has an assigned eip
