### ISSUE TITLE
hostnamectl Not Used When Setting Hostname Using hostname Module On CentOS 7

### ISSUE THREAD

**Issue by jwbrown77** [ansible/ansible-modules-core#438]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.1
##### Environment:

Running from: Ubuntu 14.04.1.  Destination host: CentOS 7.0.1406
##### Summary:

CentOS 7 uses systemd and should use the "hostnamectl" utility to set the hostname rather than adding it to /etc/sysconfig/network
##### Steps To Reproduce:

```
- name: Set the hostname
  hostname: name={{ hostname }}
```
##### Expected Results:

For the hostname to be permanently set to what the playbook defines.
##### Actual Results:

It appears that it's using behavior from previous non-systemd versions of CentOS: Using the "hostname" binary to set the current hostname, then adding "HOSTNAME=xxx" to /etc/sysconfig/network in an attempt to set it permanently.  The temporary change works, but the changes are lost on reboot, as CentOS 7 doesn't seem to respect the "HOSTNAME" value in /etc/sysconfig/network.  The correct way is to use "hostnamectl set-hostname xxx"
##### My Debugging Effort:

It appears that there is a "Redhat Strategy" and a "Fedora Strategy" in the source code.  The Fedora Strategy does what's required; calling hostnamectl.  But it never gets triggered, because in lines 52-53 of hostname.py, the version is set to "0" if a string is returned from Python's platform module:

```
 if type(distribution_version) is str:
    distribution_version = 0
```

Running this:

```
import platform; type(platform.linux_distribution()[1])
```

On Ubuntu 14.04, CentOS 6, and CentOS 7 always returns a "str" type, but lines 52-53 check for "str" type and set the version to 0.  I don't know why it would set to 0 instead of attempting to cast to an integer/float where line 384-385 could use it in its comparison:

```
if distribution_version and LooseVersion(distribution_version) >= LooseVersion("7"):
    strategy_class = FedoraStrategy
```

Apologies if I'm misunderstanding the problem; I'm not a highly skilled Python programmer.

Thanks

**Comment by jwbrown77** [comment]
I forked the repo to attempt a fix, but found that casting to an int doesn't work, because the "LooseVersion" class _expects_ a string, and fails if fed an int.

Actually, I wound up simply commenting out all the logic in _get_distribution_version in hostname.py and simply return the raw result of:

```
distribution_version = get_distribution_version()
```

After doing that, all the logic of checking for CentOS >= 7 works fine, and hostnamectl is used as desired.

So in the end... I guess I don't understand why str returns from get_distribution_version calls are being converted to 0.  Everything in that script that calls _get_distribution_version is using the LooseVersion class for version comparison, which seems to only work with a string input.

I'm sure there was a reason for the _get_distribution_version to have been added, so perhaps there's another way to make it work other than basically ignoring _get_distribution_version and calling get_distribution_version directly.

Thanks

**Comment by mscherer** [comment]
Well I do not think there is a reason, so I think we should indeed revert cbc417ca

**Comment by abadger** [comment]
Thanks @mscherer and @jwbrown77 Revert has been merged so this should be fixed.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by magnars** [comment]
I'm using `ansible 1.9.3` and the hostname set by ansible is lost when rebooting. Looks like this issue. Anything I can do to help get it fixed?

**Comment by magnars** [comment]
Turns out that this change does work, but that `cloud-init` in the AWS CentOS build is resetting it.

**Comment by ScubaDrew** [comment]
@magnars did you find a way to prevent cloud-init from resetting the updated hostname?
