### ISSUE TITLE
ec2_elb_lb to allow for setting policies

### ISSUE THREAD

**Issue by thomascramer** [ansible/ansible-modules-core#447]
Issue Type:

Feature Idea

Ansible Version:

1.8.1

Environment:

Managing EC2 from generic.

Summary:

Boto allows for setting of ELB policies (i.e. create_lb_policy/delete_lb_policy, set_lb_policies_of_backend_server, set_lb_policies_of_listener).  This is in a similar vein of #386, but stickiness is set with a different api calls.  I would like the ability to define/set a policy with my ELB definition.  For example to be able to assign the proxypass to an ELB (http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html); if you use ELB in a HIPAA compliant setup you must use TCP pass through with https connection but to get the forwarded originating client IP you have to use proxypass.  

Steps To Reproduce:

I would expect it would be an option like:
- local_action:
  module: ec2_elb_lb
  name: "test-please-delete"
  state: present
  zones:
  - us-east-1d
    listeners:
  - protocol: http
    load_balancer_port: 80
    instance_port: 80
    policies:
  - name: EnableProxyProtocol
    type: ProxyProtocolPolicyType
    attributes:
    - ProxyProtocol: true
      port: 443 
      policy_type: backend # or listener if it was a listener policy

This should map to the API requirements.  The policy_port would be the backend policy this would be the instance_port and lb_port for the listener policy.

Expected Results:

Have backend policy added to my load balancer?

Actual Results:

Just the default policies are set...

**Comment by mitsuhiko** [comment]
Something like this would be really useful.  Especially the mentioned proxy flag is a very important feature for many environments and the workarounds are really ugly currently (shelling out to aws tools).

**Comment by Javlopez** [comment]
Hi everyone
Someone knows what happend with this feature?

**Comment by ertanden** [comment]
+1 for this feature. Need to enable ProxyProtocol on ELB. Currently the only way is to call aws CLI tools.
