### ISSUE TITLE
Docker / Debug output verbosity 

### ISSUE THREAD

**Issue by tfhartmann** [ansible/ansible-modules-core#448]
Sorry if this is a duplicate, it looked like there are some similar issues open, but my question was related to the examples in the docs. 

This example _looks_ like it should print the hostname and port binding, but instead prints that, as well as the verbose output from debug.  
https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker.py#L230-L232

From googling around it looks like this is because the default behavior in the debug module is to always be verbose, and print everything when it loops through a list/hash.  

My question is this, is there anyway to get just the msg output? Is there a knob that can be twiddled in the debug module?  Is there a better way to do this? 

Overall what I'm trying to do is something similar to this example from the aws_ec2_eip module : 

``` Yaml
- name: output the IP
  debug: msg="Allocated IP inside a VPC is {{ eip.public_ip }}"
```

But output info about the docker containers I just spun up.

**Comment by mpdehaan** [comment]
Since this is a question, can you please ask on ansible-project list?   Thanks!
