### ISSUE TITLE
Systemd module missing in Ubuntu Xenial PPA

### ISSUE THREAD

**Issue by will-janz** [ansible/ansible-modules-core#4502]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

systemd
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No config changes
##### OS / ENVIRONMENT

Linux Mint 18 (Sarah) / Ubuntu 16.04 Xenial
##### SUMMARY

Attempting to use the systemd module in my playbook resulted in the "no action detected in task" error. After running `ansible localhost -m systemd` I was given 

```
localhost | FAILED! => {
    "failed": true, 
    "msg": "The module systemd was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem."
}
```

however I did not install this through git, I used the PPA. After searching for documentation and poking through the [xenial packages diff](https://launchpadlibrarian.net/275533180/ansible_2.1.0.0-1ppa~xenial_2.1.1.0-1ppa~xenial.diff.gz), I found no reference to the systemd module. I did find a comment about systemd in the service module, however the service module does not support the "daemon_reload" parameter. 

Since Ubuntu 16, systemd has been used in place of initd. Please include the systemd module with the Ubuntu package. Additionally, if it is reasonable, documentation on how to add additional modules to a package managed Ansible installation would be fantastic.

Thank you!
##### STEPS TO REPRODUCE
- Install according to [given instructions](http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-ubuntu)
- Attempt to use systemd module
- Run `ansible localhost -m systemd`

Relevant playbook tasks entry

```
- name: Confirm nginx works
  systemd:
    name: nginx
    state: restarted
    enabled: true
```
##### EXPECTED RESULTS

The playbook to run through and be told by a cow that everything went ok.
##### ACTUAL RESULTS

Ran with -vvv

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/will/git/ansible/tasks/config.yml': line 51, column 3, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Confirm nginx works
  ^ here


The error appears to have been in '/home/will/git/ansible/tasks/config.yml': line 51, column 3, but may be elsewhere on the file depending on the exact syntax problem.

The offending line appears to be:


- name: Confirm nginx works
  ^ here
```

**Comment by sivel** [comment]
The `systemd` module is listed as being added in Ansible 2.2 which has not been released yet.  Per your version output, you are still running version 2.1.1.0.

**Comment by sivel** [comment]
You however can utilize the `service` module which can interact with systemd
