### ISSUE TITLE
Windows Setup.ps1 fails(Get-PendingRebootStatus)

### ISSUE THREAD

**Issue by domcar** [ansible/ansible-modules-core#4762]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

- ansible/modules/core/windows/setup.ps1
##### ANSIBLE VERSION

```
ansible 2.1.2.0 (stable-2.1 2587d2aaf9) last updated 2016/09/09 14:54:57 (GMT +200)
  lib/ansible/modules/core: (detached HEAD bf5b3de83e) last updated 2016/09/09 14:54:35 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD f83aa9fff3) last updated 2016/09/09 14:54:38 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Control Machine: Ubuntu 16.04
Target: Windows 2012 R2
##### SUMMARY

The setup module fails
##### STEPS TO REPRODUCE

```
ansible windows -i inventory -m setup
```

##### EXPECTED RESULTS

I expected all facts like:

```
x.x.x.x | SUCCESS => {
    "ansible_facts": {
        "ansible_architecture": "64-bit", 
        "ansible_bios_date": "11.26.2012", 
        "ansible_bios_version": "Hyper-V UEFI Release v1.0", 
        "ansible_date_time": {
            "date": "2016-09-09", 

```
##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
At C:\Users\domenico\AppData\Local\Temp\ansible-tmp-1473427086.65-56661362870983\setup.ps1:445 char:18
+ $PendingReboot = Get-PendingRebootStatus
+                  ~~~~~~~~~~~~~~~~~~~~~~~
x.x.x.x| FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "setup"
    }, 
    "msg": "The term 'Get-PendingRebootStatus' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
}
```
##### Work Around

Comment out the Get-PendingRebootStatus from: lib/ansible/modules/core/windows/setup.ps1

```
#$PendingReboot = Get-PendingRebootStatus
#Set-Attr $result.ansible_facts "ansible_reboot_pending" $PendingReboot
```

**Comment by jhawkesworth** [comment]
@domcar Are you running from source?
If so please check you have run 
`source hacking/env-setup`
just to make sure you are picking up the correct version of the powershell.ps1 file?

**Comment by domcar** [comment]
@jhawkesworth, yes I am running from source and I had done  `<source hacking/env-setup>`. I repeated the command again just to be sure but the result is the same

**Comment by jhawkesworth** [comment]
Its not clear what version you are trying to run.  If you want to try 2.1.2 release candidate 2 then please checkout like this
git fetch origin
git checkout v2.1.2.0-0.2.rc2
git submodule update --init

then ansible --version will report something like this

ansible 2.1.2.0 (detached HEAD e83840c3fd) last updated 2016/09/12 14:00:23 (GMT +100)
  lib/ansible/modules/core: (detached HEAD c4791e39cf) last updated 2016/09/12 14:00:28 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD af1718b0f2) last updated 2016/09/12 14:00:28 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

@domcar Please can you try the above and report back as I am able to run setup module just fine having done the above?

**Comment by domcar** [comment]
@jhawkesworth I hadn't run git submodule update --init, now it works well, thanks for the help.

**Comment by jhawkesworth** [comment]
Great, glad you are up and running again.
