### ISSUE TITLE
script module: more interpreter than sh

### ISSUE THREAD

**Issue by cherusk** [ansible/ansible-modules-core#4884]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

script module
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```

```
```

**Comment by cherusk** [comment]
I'd be prepared to do that. Expect an OK from maintainer.

**Comment by bcoca** [comment]
script module already supports this, just set the shebang on your script
