### ISSUE TITLE
ios_config -- unsupported parameter for module: backup -- both yes/no don't work?

### ISSUE THREAD

**Issue by salman1485** [ansible/ansible-modules-core#4959]
Searched around but does not look like anyone has u
##### ISSUE TYPE

- Bug Report
- Documentation Report

`I'm hoping this is a documentation issue and not a bug but it does look like a bug to me.`
##### COMPONENT NAME

ios_config with option backup
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 1db02dfb71) last updated 2016/06/20 13:52:27 (GMT +000)
  lib/ansible/modules/core: (detached HEAD f0f5272f90) last updated 2016/06/20 13:52:45 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 6cb6829384) last updated 2016/06/20 13:53:03 (GMT +000)
  config file =
  configured module search path = ['{root-path-removed}ansible/library']
```
##### OS / ENVIRONMENT

RHEL 6.8
##### SUMMARY

With "backup: yes" under ios_config module a backup of running-config should be created in backup directory which is created in the path from where ansible pb is being run. But instead, I get below error:

{"changed": false, "failed": true, "msg": "unsupported parameter for module: backup"}

I've tried yes,no,true,false (see below) as input for backup but all give the above error only.
backup: yes
backup: no
backup: true
backup: false
##### STEPS TO REPRODUCE

```
  - name: Perform v3670 QOS changes
    ignore_errors: yes
    ios_config:
      backup: yes
      authorize: yes
      provider: "{{ cli }}"

```

##### EXPECTED RESULTS

As already mentioned, backup should be taken in backup directory.
##### ACTUAL RESULTS

TASK [Perform v3670 QOS changes] ***********************************************
task path: {actual-path-edited}/cisco/v3650_Global_Entries.yml:10
Using module file {actual-path-edited}/ansible/lib/ansible/modules/core/network/ios/ios_config.py
fatal: [{host-name-edited}]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "authorize": true, "backup": true, "host": "{host-name-edited}", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "provider": {"auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "authorize": true, "host": "{host-name-edited}", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "transport": "cli", "username": "{user-name-edited}"}, "username": "{user-name-edited}"}, "module_name": "ios_config"}, "msg": "unsupported parameter for module: backup"}
...ignoring

```

```

**Comment by salman1485** [comment]
@privateip @gundalow Tagging you guys as you usually reply for ios modules.

**Comment by gundalow** [comment]
@AnsiNoob Thanks for the detailed bug report

From

```
ansible 2.2.0 (devel 1db02dfb71) last updated 2016/06/20 13:52:27 (GMT +000)
  lib/ansible/modules/core: (detached HEAD f0f5272f90) last updated 2016/06/20 13:52:45 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 6cb6829384) last updated 2016/06/20 13:53:03 (GMT +000)
```

It looks like your Ansible 2.2.0 checkout is very old.

Have a look at this page for how to get the latest version.

http://docs.ansible.com/ansible/intro_installation.html#running-from-source

You will want to install from source.

**Comment by salman1485** [comment]
I'm working on pulling the latest version. Will get to you guys ASAP ..

**Comment by salman1485** [comment]
We went to https://releases.ansible.com/ansible/ and pulled the latest. After this the available version is below:

ansible 2.1.2.0

You still want me to pull frm git? I see that git version file has below info:

2.2.0 0.0.devel

And this does not seem much different from what I have ..

**Comment by gundalow** [comment]
Hi,
I should have been clear, apologies.

You need to be running the latest `devel`, installed from git.

Ansible 2.2.0 hasn't been released yet, so all of `devel` will identify as `2.2.0` until the point that we create the RC (release candidate) branch
If you look at the following, it's the highlighted dates that need updating:

ansible 2.2.0 (devel 1db02dfb71) last updated **2016/06/20** 13:52:27 (GMT +000)
  lib/ansible/modules/core: (detached HEAD f0f5272f90) last updated **2016/06/20** 13:52:45 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 6cb6829384) last updated **2016/06/20** 13:53:03 (GMT +000)

**Comment by salman1485** [comment]
Thank You! backup option of ios_config works after updating to latest devel release. I'll make sure that I do git pull going forward before opening any thread. 

```
ansible 2.2.0 (devel cf4d436e07) last updated 2016/09/23 13:50:43 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 0f505378c3) last updated 2016/09/23 13:51:09 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 1ade801f65) last updated 2016/09/23 13:51:25 (GMT +000)

```
