### ISSUE TITLE
Docs for http(s) enable issue eos_eapi, nxos_nxapi, etc

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#4970]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

eos_eapi
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 547cea556f) last updated 2016/09/20 12:12:18 (GMT +100)
  lib/ansible/modules/core: (devel 12a7027c49) last updated 2016/09/20 15:11:43 (GMT +100)
  lib/ansible/modules/extras: (devel db7a3f48e1) last updated 2016/09/20 11:53:00 (GMT +100
```
##### SUMMARY

Docs for eos_eapi, nxos_nxapi list http(s) as being enabled by default when they are not.
Also the docs need improving to make it clear that if you set the port you also need to enable the service

**Comment by gundalow** [comment]
I'll fix this

**Comment by gundalow** [comment]
Should we also change the default to arguments to `enable_http` (rather than `http`) to make it clearer in docs & examples?

**Comment by privateip** [comment]
leaving the current arguments as is (eg `http`) and keeping aliases (eg `enable_http`)

**Comment by gundalow** [comment]
Agreed, no work to be done here.
