### ISSUE TITLE
[CRON module] Add Support for Env Variables, eg MailTo, as in Bash Cron.

### ISSUE THREAD

**Issue by AnneTheAgile** [ansible/ansible-modules-core#50]
The old repo had a PR that was upvoted quote a bit but not merged yet. It was referenced in two tickets; 
1.[]This one has the code ; X.Adding env to allow cron jobs with environment variables by djatlantic · Pull Request #4584 · ansible/ansible ;; https://github.com/ansible/ansible/pull/4584

2.[]This one is a subset of [1] and was not accepted. ; X.cron module: Add mailto parameter by RSpiertz · Pull Request #5466 · ansible/ansible ;; https://github.com/ansible/ansible/pull/5466

**Comment by mpdehaan** [comment]
Hi,

Thanks for filing this ticket, though this is an issue, but not a pull request.  Can you make it as a pull request?

Thanks!

**Comment by infinityandbian** [comment]
+1 on addressing this in the cron module, setting env through the module would be very useful

**Comment by m00dawg** [comment]
:+1: This would be a highly useful feature.

**Comment by infinityandbian** [comment]
workaround so far is to place env vars inline into crontab file, then use command module to register that cron job. 

If your variables are static this should be easy-peasy, and if you need to set them based on other values such as staging/production, use the jinja2 template module combined with vars_files and define the corresponding env from the command line when running the playbook.

**Comment by JocelynDelalande** [comment]
FYI, this issue is addressable via [cronvar module](http://docs.ansible.com/ansible/cronvar_module.html)

**Comment by jeffwidman** [comment]
A pull request incorporating this into Ansible's core `cron` module was accepted just last week:
https://github.com/ansible/ansible-modules-core/pull/2010

Once that's released, I don't see a need for the `cronvar` module, and filed an issue suggesting it be deprecated: https://github.com/ansible/ansible-modules-extras/issues/1779 

If you have a use case supported by `cronvar` that's not supported by `cron` (once this PR makes it into a public release) then probably a good idea to comment on the issue above.
