### ISSUE TITLE
Error Parsing `name` when using the systemd module

### ISSUE THREAD

**Issue by drusellers** [ansible/ansible-modules-core#5020]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

systemd
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

Host: OS X El Capitan
Guest: ubuntu/xenial64
##### SUMMARY

When setting up an ansible playbook, I ran into a strange YAML parsing error that I could not explain and only seems to apply to `systemd`
##### STEPS TO REPRODUCE

As I installed Elastic Search using the play book below I ran into the above error.

The gist below contains the Vagrant file and the playbooks.

https://gist.github.com/drusellers/f120b5b26fa2ed3591ae0dd9024a72c1
##### EXPECTED RESULTS

I expected systemd to start my service
##### ACTUAL RESULTS

```
    default: Running ansible-playbook...
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/drusellers/dev/beta/beta-server/provisioning/roles/elasticsearch/tasks/main.yml': line 16, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: start es
  ^ here


The error appears to have been in '/Users/drusellers/dev/beta/beta-server/provisioning/roles/elasticsearch/tasks/main.yml': line 16, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: start es
  ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by sivel** [comment]
The problem here is that the `systemd` module will not be introduced until the 2.2 release of ansible.

You are currently running version 2.1.

See http://docs.ansible.com/ansible/systemd_module.html for more information on the systemd module.

In the mean time you can just use the `service` module instead.

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by drusellers** [comment]
:facepalm:

**Comment by joaodlf** [comment]
Am I right in assuming this isn't live at all? I get the same errors on 2.2.2.0.
