### ISSUE TITLE
S3 - Source bucket cannot be found

### ISSUE THREAD

**Issue by lmilbaum** [ansible/ansible-modules-core#5186]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

s3
##### ANSIBLE VERSION

ansible 2.2.0
##### OS / ENVIRONMENT

OSX 10.12
##### SUMMARY

Getting an object from s3 bucket. The bucket exists. Works for two other buckets.
##### STEPS TO REPRODUCE
- name: download sb packages from <bucket name>
  s3:  
    bucket: <bucket name>
    object: /{{ item }}
    dest: /var/tmp/{{ item }}
    mode: get
  with_items:
  - file1
  - file2
##### EXPECTED RESULTS

file1 and file2 downloaded from s3 bucket to /var/tmp on the target machine
##### ACTUAL RESULTS

TASK [sb.docker-build : download sb packages from sb-devops-devel] *************
task path: /Users/liora/git/DevOps/docker/roles/sb.docker-build/tasks/main.yml:48
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/liora/.ssh/sb-internal.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/liora/.ansible/cp/%h-%p-%r ec2-52-212-104-59.eu-west-1.compute.amazonaws.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1475835107.53-237296860801321`" && echo ansible-tmp-1475835107.53-237296860801321="`echo $HOME/.ansible/tmp/ansible-tmp-1475835107.53-237296860801321`" ) && sleep 0'"'"''
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> PUT /var/folders/jg/pqnkkqx55n36p_czgwb08b2w0000gn/T/tmpihwAMp TO /home/ubuntu/.ansible/tmp/ansible-tmp-1475835107.53-237296860801321/s3
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/liora/.ssh/sb-internal.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/liora/.ansible/cp/%h-%p-%r '[ec2-52-212-104-59.eu-west-1.compute.amazonaws.com]'
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/liora/.ssh/sb-internal.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/liora/.ansible/cp/%h-%p-%r -tt ec2-52-212-104-59.eu-west-1.compute.amazonaws.com '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-rrodlfcofqyzpstjhaqbymxgdilqkhyb; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1475835107.53-237296860801321/s3; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1475835107.53-237296860801321/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
failed: [ec2-52-212-104-59.eu-west-1.compute.amazonaws.com](item=wekaWrapper-0.3.0.tar.gz) => {"failed": true, "invocation": {"module_args": {"aws_access_key": null, "aws_secret_key": null, "bucket": "sb-devops-devel", "dest": "/var/tmp/.sparkbeyond/wekaWrapper-0.3.0.tar.gz", "ec2_url": null, "encrypt": true, "expiry": "600", "headers": null, "marker": null, "max_keys": "1000", "metadata": null, "mode": "get", "object": "/wekaWrapper-0.3.0.tar.gz", "overwrite": "always", "permission": ["private"], "prefix": null, "profile": null, "region": null, "retries": 0, "s3_url": null, "security_token": null, "src": null, "validate_certs": true, "version": null}, "module_name": "s3"}, "item": "wekaWrapper-0.3.0.tar.gz", "msg": "Source bucket cannot be found"}
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/liora/.ssh/sb-internal.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/liora/.ansible/cp/%h-%p-%r ec2-52-212-104-59.eu-west-1.compute.amazonaws.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1475835109.39-67000962379013`" && echo ansible-tmp-1475835109.39-67000962379013="`echo $HOME/.ansible/tmp/ansible-tmp-1475835109.39-67000962379013`" ) && sleep 0'"'"''
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> PUT /var/folders/jg/pqnkkqx55n36p_czgwb08b2w0000gn/T/tmp8ee0YO TO /home/ubuntu/.ansible/tmp/ansible-tmp-1475835109.39-67000962379013/s3
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/liora/.ssh/sb-internal.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/liora/.ansible/cp/%h-%p-%r '[ec2-52-212-104-59.eu-west-1.compute.amazonaws.com]'
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<ec2-52-212-104-59.eu-west-1.compute.amazonaws.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/Users/liora/.ssh/sb-internal.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/liora/.ansible/cp/%h-%p-%r -tt ec2-52-212-104-59.eu-west-1.compute.amazonaws.com '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-zscdcyglbkwrqvwkqeadklctchuxsnyp; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1475835109.39-67000962379013/s3; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1475835109.39-67000962379013/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
failed: [ec2-52-212-104-59.eu-west-1.compute.amazonaws.com](item=mllib-driver_2.10-2.0.jar.tar.gz) => {"failed": true, "invocation": {"module_args": {"aws_access_key": null, "aws_secret_key": null, "bucket": "sb-devops-devel", "dest": "/var/tmp/.sparkbeyond/mllib-driver_2.10-2.0.jar.tar.gz", "ec2_url": null, "encrypt": true, "expiry": "600", "headers": null, "marker": null, "max_keys": "1000", "metadata": null, "mode": "get", "object": "/mllib-driver_2.10-2.0.jar.tar.gz", "overwrite": "always", "permission": ["private"], "prefix": null, "profile": null, "region": null, "retries": 0, "s3_url": null, "security_token": null, "src": null, "validate_certs": true, "version": null}, "module_name": "s3"}, "item": "mllib-driver_2.10-2.0.jar.tar.gz", "msg": "Source bucket cannot be found"}

**Comment by lmilbaum** [comment]
OK. Found the root cause. The instance role didn't include permissions to download from this bucket. A more accurate error could be helpful.

**Comment by VinayakKorape** [comment]
@lioramilbaum - Can you please provide more details about the resolution? I am facing the same issue.

**Comment by lmilbaum** [comment]
The instance where this module was running has an IAM role attached. The IAM role should include a policy which allows downloading files from the bucket.

**Comment by VinayakKorape** [comment]
Thank you so much. 
My issue was something different, though the error I was getting was exactly same.
I was using http_proxy in the environment for the play and the proxy server was not working.
After commenting out that part it worked fine for me.
