### ISSUE TITLE
tmp files still being 

### ISSUE THREAD

**Issue by haroldTlan** [ansible/ansible-modules-core#5198]
ISSUE TYPE
 •BUG

ANSIBLE VERSION
 version: 2.3.0

CONFIGURATION
 python2.7

OS / ENVIRONMENT
 Linux Ubuntu 

SUMMARY

I post my questions in groups and it is still no solutions to fix it.
https://groups.google.com/forum/#!topic/ansible-project/PzmELqzydbY
https://groups.google.com/forum/#!topic/ansible-devel/TW4GsR-hTtQ

I did not know what should I do

install Ubuntu 13.1

then

`apt-get install git python-pip setuptools`

```
$ git clone git://github.com/ansible/ansible.git --recursive
$ cd ./ansible

$ source ./hacking/env-setup
$ source ./hacking/env-setup -q
```

prevent "Python.h" error

```
$ apt-get install python-dev libffi-dev libssl-dev

$ pip install setuptools pip --upgrade
```

```
$ pip install cffi
$ pip install paramiko PyYAML Jinja2 httplib2 six
```

now I finish my installation.

First,use `$ ansible 192.168.2.85 -m ping`

it let me install sshpass

`$ apt-get install sshpass`

then `$ ansible 192.168.2.85 -m ping`

```
192.168.2.85 | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

it's ok, tmp file gone;

Second,!!!!!!!!!!!!!!!!
I am using the official example(http://docs.ansible.com/ansible/developing_api.html) :

`$ python official.py`
https://github.com/haroldTlan/ansible/blob/master/official.py

but tmp file still there

```
$ cd /.ansible/tmp
$ ls
ansible-local-65005zhPKlI  ansible-local-70192KRXI4M
```

Is there any installation step wrong?
or official code wrong?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible-devel on irc.freenode.net  
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-devel
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by haroldTlan** [comment]
I post my questions in there ,but no one help me!!!!
https://groups.google.com/forum/#!topic/ansible-project/PzmELqzydbY
https://groups.google.com/forum/#!topic/ansible-devel/TW4GsR-hTtQ

https://groups.google.com/forum/#!topic/ansible-project/e1m7hP2INuI
@bcoca
