### ISSUE TITLE
ec2_group module failures with ICMP protocol

### ISSUE THREAD

**Issue by kalefranz** [ansible/ansible-modules-core#529]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

localhost / OSX / *
##### Summary:

The `ec2_group` module fails on ICMP protocol operations that should normally be unchanged. That is, the first time the module is called to create and/or change a group, the operation succeeds.  The second and subsequent times the module is called, where the operation should normally be idempotent, the module instead fails.
##### Steps To Reproduce:

Call the `ec2_group` module twice in a row where one of the `rules` **or** `egress_rules` has `proto=ICMP`.
##### Expected Results:

According to the [boto documentation](http://boto.readthedocs.org/en/latest/security_groups.html), the correct way to allow all ICMP types is to use the range -1:-1.  I would expect the following task to idempotently allow the instance to respond to all ICMP types

```
- ec2_group:
    name: IcmpAllInboundSG
    description: respond to all inbound ICMP traffic
    region: us-west-2
    rules:
      - proto: ICMP
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0
```

Likewise, I would expect the following task to idempotently allow the instance to respond only to traceroute requests

```
- ec2_group:
    name: EX2
    description: respond to all inbound traceroute requests
    region: us-west-2
    rules:
      - proto: ICMP
        from_port: 30
        to_port: 30
        cidr_ip: 0.0.0.0/0
```

And likewise again, only to ping requests

```
- ec2_group:
    name: EX3
    description: respond to all inbound ping requests
    region: us-west-2
    rules:
      - proto: ICMP
        from_port: 0
        to_port: 0
        cidr_ip: 0.0.0.0/0
```
##### Actual Results:

In the above three examples, the first time the operation is ran (and thus the results "changed"), the operation succeeds.  In subsequent playbook runs, the operation fails with the following output.

```
TASK: [security group to allow ping] ******************************************
failed: [127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/kfranz/.ansible/tmp/ansible-tmp-1418809244.68-137009819118878/ec2_group", line 2145, in <module>
    main()
  File "/Users/kfranz/.ansible/tmp/ansible-tmp-1418809244.68-137009819118878/ec2_group", line 293, in main
    group.authorize(rule['proto'], rule['from_port'], rule['to_port'], ip, grantGroup)
  File "/Library/Python/2.7/site-packages/boto-2.34.0-py2.7.egg/boto/ec2/securitygroup.py", line 203, in authorize
    dry_run=dry_run)
  File "/Library/Python/2.7/site-packages/boto-2.34.0-py2.7.egg/boto/ec2/connection.py", line 3192, in authorize_security_group
    params, verb='POST')
  File "/Library/Python/2.7/site-packages/boto-2.34.0-py2.7.egg/boto/connection.py", line 1223, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidPermission.Duplicate</Code><Message>the specified rule "peer: 0.0.0.0/0, ICMP, type: 30, code: 30, ALLOW" already exists</Message></Error></Errors><RequestID>0e8274ad-7884-4050-adca-5c742fe0c697</RequestID></Response>


FATAL: all hosts have already failed -- aborting
```

**Comment by viatcheslavmogilevsky** [comment]
Is it released on 1.8.4?
