### ISSUE TITLE
Comma as a value in a dict type parameter fails

### ISSUE THREAD

**Issue by jcpowermac** [ansible/ansible-modules-core#543]
##### Issue Type:

Bug Report
##### Ansible Version:

jcallen@helix ~/Development/ansible/hanlon ->
 12:49 PM Thu Dec 18$ ansible --version
ansible 1.8.1
  configured module search path = /usr/share/ansible
##### Environment:

Fedora 20 (ansible) managing Fedora 21 (docker host)
##### Summary:

Trying to start a docker container and I receive an exception `"ValueError: dictionary update sequence element #2 has length 1; 2 is required"`
##### Steps To Reproduce:

The offending task is:

```
- name: ensure_hanlon_container_run
     docker: image=jcpowermac/hanlon ports=8026:8026 links=mongodb:mongo name=hanlon env=DOCKER_HOST="{{ ansible_eth0.ipv4.address }}, HANLON_SUBNETS=10.53.252.0/24,172.17.0.0/16" privileged=true volumes=/opt/hanlon/image:/home/hanlon/image
```

Or like this:

```
- name: ensure_hanlon_container_run
     docker: 
       image: jcpowermac/hanlon 
       ports: 8026:8026 
       links: mongodb:mongo 
       name: hanlon
       env: DOCKER_HOST={{ ansible_eth0.ipv4.address }}, HANLON_SUBNETS="10.53.252.0/24,172.17.0.0/16"
       privileged: true
       volumes: /opt/hanlon/image:/home/hanlon/image
```
##### Expected Results:

Container to start normally.
##### Actual Results:

```
TASK: [ensure_hanlon_container_run] ******************************************* 
<10.53.252.245> ESTABLISH CONNECTION FOR USER: root
<10.53.252.245> REMOTE_MODULE docker name=hanlon ports=8026:8026 net=bridge volumes=/opt/hanlon/image:/home/hanlon/image image=jcpowermac/hanlon links=mongodb:mongo env='DOCKER_HOST=10.53.252.245, HANLON_SUBNETS="10.53.252.0/24,172.17.0.0/16"'
<10.53.252.245> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jcallen/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 10.53.252.245 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1418924984.89-228593922622016 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1418924984.89-228593922622016 && echo $HOME/.ansible/tmp/ansible-tmp-1418924984.89-228593922622016'
<10.53.252.245> PUT /tmp/tmpqB542R TO /root/.ansible/tmp/ansible-tmp-1418924984.89-228593922622016/docker
<10.53.252.245> EXEC ssh -C -tt -q -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jcallen/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 10.53.252.245 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1418924984.89-228593922622016/docker; rm -rf /root/.ansible/tmp/ansible-tmp-1418924984.89-228593922622016/ >/dev/null 2>&1'
failed: [10.53.252.245] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1418924984.89-228593922622016/docker", line 2422, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1418924984.89-228593922622016/docker", line 745, in main
    net             = dict(default=None)
  File "/root/.ansible/tmp/ansible-tmp-1418924984.89-228593922622016/docker", line 1157, in __init__
    self._check_argument_types()
  File "/root/.ansible/tmp/ansible-tmp-1418924984.89-228593922622016/docker", line 1799, in _check_argument_types
    self.params[k] = dict([x.strip().split("=", 1) for x in value.split(",")])
ValueError: dictionary update sequence element #2 has length 1; 2 is required


FATAL: all hosts have already failed -- aborting
```

**Comment by abadger** [comment]
Okay, I see the problem.  The current code is splitting on all of the commas in the env parameter.  This includes the , inside of the double quotes.  Then it tries to construct a dict out of that and fails because the last field does not have both a key and value:

``` python
 ['DOCKER_HOST=10.53.252.245', ' HANLON_SUBNETS="10.53.252.0/24', '172.17.0.0/16"']
```

Looking for the best way to protect that comma now.

**Comment by jcpowermac** [comment]
A co-worked found me a workaround so this is certainly not as a priority as the volume issue #522 that I am currently also working around (installing older version of docker).

```
- name: ensure_hanlon_container_run
     docker:
       image: cscdock/hanlon
       ports: 8026:8026
       links: mongodb:mongo
       name: hanlon
       privileged: true
       volumes: /opt/hanlon/image:/home/hanlon/image
       env:
         DOCKER_HOST: "{{ ansible_eth0.ipv4.address }}"
         HANLON_SUBNETS: "{{ hanlon_subnets }}"
```

Thanks!

**Comment by abadger** [comment]
Note: You should be able to work around this by using dict syntax instead.  I haven't tried this out specifically so you may have to tweak a little but something similar to this:

```
env:
    DOCKER_HOST:  "10.53.252.245"
    HANLON_SUBNETS: "10.53.252.0/24,172.17.0.0/16"
```

**Comment by abadger** [comment]
Heh, sorry, I should refresh the page before posting :-)

Yep, that's the workaround (and probably an overall better syntax anyway.)

Created a PR here to address the bug here: https://github.com/ansible/ansible/pull/9878

**Comment by abadger** [comment]
yay, PR merged.  So this can be closed.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
