### ISSUE TITLE
Spurious warning when running win_file to create directory since 2.2 

### ISSUE THREAD

**Issue by Chris-YBS** [ansible/ansible-modules-core#5644]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_file

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Logfile location changed only
##### OS / ENVIRONMENT
N/A

##### SUMMARY
When an directory is created with win_file a spurious warning is produced:

---
TASK [win_file] ****************************************************************
 **[WARNING]: Module invocation had junk after the JSON data:**

changed: [YBSXW265.ybs.com]

TASK [debug] *******************************************************************
ok: [YBSXW265.ybs.com] => {
    "status": {
        "changed": true
    }
}
---

##### STEPS TO REPRODUCE
Use win_file to create a directory. Does not occur when directory is already present or when creating a file

```
           - win_file: path=C:/Temp/TestFolder state=directory
```
minimal example playbook
-------
     - name: test 
       hosts: YBSTEST.ybs.com

       pre_tasks:
             - win_file: path=C:/Temp/TestFolder state=directory
               register: status
             - debug: var=status
      
       # Remove so I can run again!
       post_tasks:
             - win_file: path=C:/Temp/TestFolder state=absent
-------

##### EXPECTED RESULTS
Prior to Ansible 2.2 this completed without warning. Expected it to complete without warning still

##### ACTUAL RESULTS

Warning produced: 

```
TASK [win_file] ****************************************************************
task path: /vagrant/Ansible/TestCreateFolder.yaml:5
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/windows/win_file.ps1
<YBSXW265.ybs.com> ESTABLISH WINRM CONNECTION FOR USER: actian on PORT 5986 TO YBSXW265.ybs.com
<YBSXW265.ybs.com> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1479373470.54-55872217189586").FullName | Write-Host -Separator '';
<YBSXW265.ybs.com> PUT "/tmp/tmpimMNu1" TO "C:\Users\actian\AppData\Local\Temp\ansible-tmp-1479373470.54-55872217189586\win_file.ps1"
<YBSXW265.ybs.com> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\actian\AppData\Local\Temp\ansible-tmp-1479373470.54-55872217189586\win_file.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\actian\AppData\Local\Temp\ansible-tmp-1479373470.54-55872217189586" -Force -Recurse -ErrorAction SilentlyContinue }
 [WARNING]: Module invocation had junk after the JSON data:

changed: [YBSTEST.ybs.com] => {
    "changed": true,
    "invocation": {
        "module_name": "win_file"
    }
}

```

**Comment by jhawkesworth** [comment]
Hi @Chris-YBS , this was discovered very late on in 2.2 - after the final release candidate.  You can blame me for not testing sooner.
However, @nitzmahone has already merged a fix for it in commit de7ec946e9d1cdb636f172b4ec9aeff7e07191d4 so will be fixed in next ansible release.

For this reason I'm closing this issue.
Jon
