### ISSUE TITLE
assemble module does not make use of 'remote_src' module parameter

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-modules-core#660]
**Issue Type:** Bug Report
**Ansible Version:** Current
**Steps to reproduce:**
Search for _remote_src_ in the assemble module source code
**Expected result:**
Find a condition verifying the state of _remote_src_ and corresponding logic for the both True/False outcomes.
**Actual result:**
No code references found

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ghost** [comment]
Hi Brian,

I am afraid you got me wrong.

Here is what I see in the documentation for this module (http://docs.ansible.com/assemble_module.html):

_remote_src_ If False, it will search for src at originating/master machine, if True it will go to the remote/target machine for the src. Default is True. (added in Ansible 1.4).

However if I try using this parameter, it won't work. By checking the code you can see that there is no logic around this parameter.

So I'd say, either logic should be implemented, or _remote_src_ should be removed from the documentation. Either way it is a bug, so please reopen this issue.

**Comment by bcoca** [comment]
the code is implemented in the action_plugin, not the module https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/assemble.py#L88

**Comment by ghost** [comment]
Got it. Sorry, will re-test.
