### ISSUE TITLE
Ansible requires the virtualenv command even when it doesn't use it

### ISSUE THREAD

**Issue by brainsik** [ansible/ansible-modules-core#688]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.8.2
  configured module search path = None
```
##### Environment:

Running from OS X 10.10.1
Managing Ubuntu 14.04.1
##### Summary:

When installing a package to an existing virtualenv directory, Ansible requires the virtualenv command even though it doesn't use it. 

When virtualenv isn't available on the standard PATH you must include the `virtualenv_command` argument for no reason. As a workaround, one can use `virtualenv_command=/bin/true` to avoid adding additional host specific details (which may change). Instead, Ansible shouldn't look for a command it won't use (i.e., when the virtualenv already exists).
##### Steps To Reproduce:

```
$ ansible all -m pip -a "name=pep8 virtualenv=~/.virtualenvs/pizza"
```
##### Expected Results:

```
trusty.local | success >> {
    "changed": true,
    "cmd": "/home/brainsik/.virtualenvs/pizza/bin/pip install pep8",
    "name": "pep8",
    "requirements": null,
    "state": "present",
    "stderr": "",
    "stdout": "Downloading/unpacking pep8\n  Downloading pep8-1.5.7-py2.py3-none-any.whl\nInstalling collected packages: pep8\nSuccessfully installed pep8\nCleaning up...\n",
    "version": null,
    "virtualenv": "/home/brainsik/.virtualenvs/pizza"
}
```
##### Actual Results:

```
trusty.local | FAILED >> {
    "failed": true,
    "msg": "Failed to find required executable virtualenv"
}
```

**Comment by abadger** [comment]
Hey, @brainsik Could you give that PR a test run to make sure I didn't mess somehting up?

**Comment by brainsik** [comment]
@abadger First of all, I've met you a bunch of times through @glyphobet. :-)  Pretty weird to see you as the author of this PR. Hope you are doing well!

More relevant, it worked!

```
$ ansible -v all -m pip -a "name=pep8 virtualenv=~/.virtualenvs/pizza"
trusty.local | success >> {
    "changed": true,
    "cmd": "/home/brainsik/.virtualenvs/pizza/bin/pip install pep8",
    "name": "pep8",
    "requirements": null,
    "state": "present",
    "stderr": "",
    "stdout": "Downloading/unpacking pep8\n  Downloading pep8-1.5.7-py2.py3-none-any.whl\nInstalling collected packages: pep8\nSuccessfully installed pep8\nCleaning up...\n",
    "version": null,
    "virtualenv": "/home/brainsik/.virtualenvs/pizza"
}
```

**Comment by abadger** [comment]
@brainsik Eggsellent!  Yep, I get around the open source world.  If you make it to pycon this year we should all hang out :-)

**Comment by glyphobet** [comment]
@abadger @brainsik worlds collide, everyone is using ansible now! I'll be at PyCon.
