### ISSUE TITLE
git: get_head_branch incorrect when branch name contains a slash

### ISSUE THREAD

**Issue by thpani** [ansible/ansible-modules-core#70]
[re-posting module issue from ansible/ansible#6672]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.3
##### Environment:

OS X 10.9.2
##### Summary:

`get_head_branch()` fails to correctly compute the HEAD branch if the branch name contains a slash. This is caused by splitting on '/' and indexing [-1] [here](https://github.com/ansible/ansible-modules-core/blob/c8e1a2077ed356fb893cd9886f758ac3d284e6b9/source_control/git.py#L398).
##### Steps To Reproduce:

Run this playbook:

```
- name: checkout llvm
  git: repo=https://github.com/thpani/llvm.git
       dest=/home/vagrant/llvm/
```

Checkout fails because branch is computed as
`release_33_nullsucc`
instead of
`patches/release_33_nullsucc`.
##### Expected Results:

`get_head_branch()` computes the correct branch name.

I.e. behave as if the above example were

```
- name: checkout llvm
  git: repo=https://github.com/thpani/llvm.git
       dest=/home/vagrant/llvm/
       version=patches/release_33_nullsucc
```
##### Actual Results:

```
TASK: [checkout llvm] *********************************************************
failed: [default] => {"failed": true}
msg: Failed to checkout branch release_33_nullsucc
```

**Comment by robynbergeron** [comment]
Hi @thpani -- Thanks for submitting this bug report. Apologies for taking so long to triage it.

Going to close this issue -- It looks like #441 fixed this last year -- so hopefully that resolved the problem for you. If not, let us know!

**Comment by pierrre** [comment]
It looks like #441 wasn't merged.
Is it really fixed?
