### ISSUE TITLE
Solaris prtdiag hangs during gather facts

### ISSUE THREAD

**Issue by zystem** [ansible/ansible-modules-core#701]
https://github.com/ansible/ansible/issues/4583
Bug still not resolved.

jlstanton commented on 18 Oct 2013

This seems to be a known issue with solaris 10. way to fix is to restart picl before running prtdiag.

Could add something like the below to setup:
def get_virtual_facts(self):
module.run_command("svcadm restart svc:/system/picl:default")
rc, out, err = module.run_command("/usr/sbin/prtdiag")

python debug output:

-bash-3.00# python -m pdb setup

```
/tmp/.ansible/tmp/ansible-1382106487.8-10732644317884/setup(21)()
-> import os
(Pdb) continue
```

^C{"msg": "Traceback (most recent call last):\n File \"setup\", line 3089, in run_command\n out, err = cmd.communicate(input=data)\n File \"/opt/csw/lib/python2.6/subprocess.py\", line 691, in communicate\n return self._communicate(inpu
t)\n File \"/opt/csw/lib/python2.6/subprocess.py\", line 1211, in _communicate\n rlist, wlist, xlist = select.select(read_set, write_set, [])\nKeyboardInterrupt\n", "failed": true, "cmd": "/usr/sbin/prtdiag", "rc": 257}
The program exited via sys.exit(). Exit status: 1

**Comment by bcoca** [comment]
closing in favor of existing #4583
