### ISSUE TITLE
Ref before assignment in apt module

### ISSUE THREAD

**Issue by hughsaunders** [ansible/ansible-modules-core#710]
##### Steps To Reproduce:

root@node05:~/rpc_repo/rpc_deployment# ansible localhost -m apt -a upgrade=yes
localhost | FAILED >> {
    "failed": true,
    "msg": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1422366728.69-223823867696576/apt\", line 2203, in <module>\n    main()\n  File \"/root/.ansible/tmp/ansible-tmp-1422366728.69-223823867696576/apt\", line 591, in main\n    upgrade(module, p['upgrade'], force_yes,\nUnboundLocalError: local variable 'upgrade' referenced before assignment\n",
    "parsed": false
}
##### Expected Results:

apt upgrades
##### Actual Results:

Ref before assignment error
##### Notes:

In the generated apt module, main() calls upgrade(), but further down in the main function, a variable called upgrade is defined:

```
def upgrade()
  ...

main()
  upgrade()
  ...
  upgrade = 'something'
```

My understanding is this: upgrade cannot be global (required to call upgrade()) and local in the same scope. As there is no global keyword, the assignment forces upgrade to be local, so upgrade() from the parent scope is not found.

**Comment by hughsaunders** [comment]
@conrado maybe you could look at this?

**Comment by conrado** [comment]
heh, how do I go about testing if it worked?

**Comment by abadger** [comment]
@conrado, yep -- your fix looks correct.  If you want to submit a pull request I'll merge it right away.

**Comment by abadger** [comment]
Ah, I see the PR now: https://github.com/ansible/ansible-modules-core/pull/711
