### ISSUE TITLE
Digital Ocean module incorrectly thinks size_id and ssh_pub_key are mutually exclusive

### ISSUE THREAD

**Issue by science** [ansible/ansible-modules-core#734]
### Issue Type:

Bug Report
### Ansible Version:

1.8.2
### Environment:

Ubuntu x64 14.04 LTS (likely irrelevant to bug)
### Summary:

When invoking the Digital Ocean module and specifying both ssh_pub_key and size_id, an error is incorrectly raised (see below for exact message).

This exception is incorrect behavior as ssh_pub_key is unrelated in functionality to the size_id parameter.
### Steps To Reproduce:

The following command reproduces the error when loaded into a task. The following variables have to be setup:

```
do_client_id=[digital ocean client id]
do_api_key=[digital ocean api key]
name=[any hostname string]
admin_ssh_pub=[string containing a valid ssh public key]
```

The command is:

```
...
  - name: Create Digital Ocean server
    digital_ocean: >
        state=present
        command=droplet
        unique_name=yes
        wait_timeout=500
        backups_enabled=no
        private_networking=yes
        client_id="{{do_client_id}}"
        api_key="{{do_api_key}}"
        name="{{inventory_hostname}}"
        ssh_pub_key="{{admin_ssh_pub}}"
        size_id=63
        region_id=4
        image_id=9801950
    register: new_server
```
### Expected Results:

The digital ocean server should be created with the specified size_id and with the public ssh key specified.
### Actual Results:

```
TASK: [Create Digital Ocean server] *************** 
failed: [web01-staging] => {"failed": true}
msg: parameters are mutually exclusive: ['size_id', 'ssh_pub_key']

FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment]
Not sure why, but this has been part of the module since it was created:

```
        mutually_exclusive = (
            ['size_id', 'ssh_pub_key'],
            ['image_id', 'ssh_pub_key'],
            ['region_id', 'ssh_pub_key'],
        ),
```

@zbal can you explain the reason for this?

**Comment by zbal** [comment]
I believe the reason is that `ssh_pub_key` only applies to the `ssh` command, hence creating / adding an SSH key to the account vs. `size_id`, `image_id`, `region_id` applies to the `droplet` command of the module. The `droplet` command expect a ssh key id (int) to apply to the `ssh_key_ids` (that id is given by the Digital Ocean API)

The module does not support auto creation of the SSH key, and the current workflow should currently be:

```
do_client_id=[digital ocean client id]
do_api_key=[digital ocean api key]
name=[any hostname string]
admin_ssh_pub=[string containing a valid ssh public key]
admin_ssh_name=[string containing the name of the ssh pub key]
```

```
#  it will either create new, or return ID of existing key matching name
- name: Create Digital Ocean SSH key
  local_action:
    module: digital_ocean
    client_id: "{{ do_client_id }}"
    api_key: "{{ do_api_key }}"
    command: ssh
    state: present
    name: "{{ admin_ssh_name }}"
    ssh_pub_key: "{{ admin_ssh_pub }}"
  register: do_key

  - name: Create Digital Ocean server
    digital_ocean: >
        state=present
        command=droplet
        unique_name=yes
        wait_timeout=500
        backups_enabled=no
        private_networking=yes
        client_id="{{do_client_id}}"
        api_key="{{do_api_key}}"
        name="{{inventory_hostname}}"
        ssh_key_ids: "{{ do_key.ssh_key.id }}"       <--- use ssh_key_ids
        size_id=63
        region_id=4
        image_id=9801950
    register: new_server
```

The documentation might be a bit unclear; the code as well should be updated to reflect this info...

**Comment by science** [comment]
Ok - thanks. That's helpful. I'm closing this b/c it's an invalid report (file under product of wishful thinking).

**Comment by murugan-pandian** [comment]
Can i have a solution for the above issue. Because this issue is still coming for me.
whether private_networking=yes is working ?
I think this is not working?
