### ISSUE TITLE
lineinfile function appends to last line if there is no trailing LF character

### ISSUE THREAD

**Issue by miguelgrinberg** [ansible/ansible-modules-core#736]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary:

The problem occurs when the `dest` argument given to the `lineinfile` function points to a file that does not have a LF character at the end of the last line. With these conditions, if the function needs to insert a line at the end of the file it will instead append it to the existing last line (i.e. it does not add a LF to the last line in the original file).
##### Steps To Reproduce:

Create a text file that does not have a LF character after the last line. For example:

```
# echo first line >/etc/test.txt
# echo second line >>/etc/test.txt
# echo -n third line >>/etc/test.txt
```

Then write a task as follows:

```
- name: 
  lineinfile:
    dest: /etc/test.txt
    regexp: 'fourth'
    line: "fourth line"
```
##### Expected Results:

After the above test, the contents of /etc/test.txt should be:

```
first line
second line
third line
fourth line
```
##### Actual Results:

The contents of /etc/test.txt are:

```
first line
second line
third linefourth line
```

**Comment by sysadmin75** [comment]
I wasn't able to reproduce this. I'm using the latest devel version. Both ansible and target servers are latest Centos 6.6.

**Comment by miguelgrinberg** [comment]
Looking at the code in `files/lineinfile.py` it does not like this has been fixed.

The lines of the source file are read with `readlines()`, which does not add line separators. If you have a file where the last line does not have a LF then that last element will stay w/o LF once loaded.

Supposed the function ends up adding one line at the very end, right after this line that does not have a LF. Then the function writes the file back using `writelines()`, which again does not insert or remove line separators. This causes the last two lines to be written as a single line.

It seems to me you need to ensure all lines have a LF terminator. You can do that after they are imported with `readlines()`, or right before they are written with `writelines()`.

**Comment by sysadmin75** [comment]
@miguelgrinberg You are using version 1.6.10. You really need to test with the latest devel version.

**Comment by miguelgrinberg** [comment]
Sorry, right, somehow I missed it, but yes, this is fixed in the development version. Closing.
