### ISSUE TITLE
Digital Ocean module no longer honors private_networking=yes

### ISSUE THREAD

**Issue by science** [ansible/ansible-modules-core#740]
### Issue Type:

Bug Report
### Ansible Version:

1.8.2
### Environment:

Ubuntu x64 14.04 LTS (likely irrelevant to bug)
### Summary:

When invoking the Digital Ocean module and specifying "private_networking=yes" option, the Digital Ocean droplet is created without private networking enabled.
### Steps To Reproduce:

The following command reproduces the error when loaded into a task. The following variables have to be setup:

```
do_client_id=[digital ocean client id]
do_api_key=[digital ocean api key]
name=[any hostname string]
ssh_key_id=[id to an ssh key associated with your DO account]
```

The command is:

```
...
  - name: Create Digital Ocean server
    digital_ocean: >
        state=present
        command=droplet
        unique_name=yes
        wait_timeout=500
        backups_enabled=no
        private_networking=yes
        client_id="{{do_client_id}}"
        api_key="{{do_api_key}}"
        name="{{inventory_hostname}}"
        ssh_pub_ids="{{ssh_pub_key}}"
        size_id=63
        region_id=4
        image_id=9801950
    register: new_server
```
### Expected Results:

The digital ocean server should be created with private networking enabled.
### Actual Results:

The digital ocean server is created, but private networking is not enabled.

Note that when using the direct v1 API against Digital Ocean, passing in the same parameters as provided to the Ansible module, the droplet is created with private networking enabled. Here is an API call sample that you can use to verify that the DO API is working, but the Ansible module is not:

```
wget "https://api.digitalocean.com/v1/droplets/new?client_id=[client_id]&api_key=[api_key]&name=[droplet-name]&size_id=63&image_id=9801950&region_id=4&ssh_key_ids=[ssh_key_id]&private_networking=true"
```

**Comment by abadger** [comment]
I believe this was fixed in devel via this Pull Request: https://github.com/ansible/ansible-modules-core/pull/677

If you're interested in verifying the fix, it's a very small change (or you could pull the latest from the repository.)  I'll close this in a few days unless it turns out that did not fix things.

**Comment by science** [comment]
Looks exactly like my issue - sorry for not spotting it before filing. I'll close this and re-open if it doesn't resolve the issue. I'd love to know if #734 has any pending resolution. I couldn't find anything in the pipeline for that either (but now am wondering if I'm not looking correctly for pending fixes). Thanks for the reference and attention on this one.
