### ISSUE TITLE
service: integrate daemontools

### ISSUE THREAD

**Issue by SkaveRat** [ansible/ansible-modules-core#774]
It would be awesome to control daemontools services with the ansible service module

Documetation for daemontools:
http://cr.yp.to/daemontools.html

**Comment by bcoca** [comment]
I need to resubmit this but here is a module dedicated to daemontools:
https://github.com/bcoca/ansible/blob/daemontools/library/system/svc

**Comment by SkaveRat** [comment]
integration with `service` would be cooler, but this will work for my case. thanks a lot!

**Comment by bcoca** [comment]
the reason i kept as separate module is that daemontools can have many
options that don't mesh well with service, also wanted to expand it to
handle variants (encore, s6, runit, monit, etc)

## 

Brian Coca

**Comment by SkaveRat** [comment]
The now new location of
https://github.com/ansible/ansible-modules-extras/blob/devel/system/svc.py

suggests to me, that this will now officially move into the modules-extras? ;)

**Comment by bcoca** [comment]
yep, this ticket reminded me to resubmit it and it got accepted, so closing it.
