### ISSUE TITLE
Documentation issue in File Module

### ISSUE THREAD

**Issue by TBSliver** [ansible/ansible-modules-core#787]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Running on Debian Jessie, managing Debian Wheezy
##### Summary:

Ran into an issue with the File Module documentation - when using the 'mode' argument with a numerical file mode, this needs to be in an octal form. The example only showing a 4 digit version is misleading, and can cause confusion when this does something different when using a mode such as '2710'. The documentation should probably include a note saying something like 

```
this must be an octal number, which means it MUST have a leading 0, otherwise silly things can happen
```
##### Steps To Reproduce:

try setting a role with:

```
- name: broken file thing
  file: ~/test
  state: directory
  mode: 2710
```
##### Expected Results:

the directory should have come out similar to this ( from an `ls -la`):

```
drwx--s---  2 username group  4096 Feb 13 19:16 test
```

This will happen if the mode line above is:

```
mode: 02710
```
##### Actual Results:

the directory will come out with something similar to this (from an `ls -la`):

```
d-wS-w-rwT  2 username group  4096 Feb 13 19:16 test
```

**Comment by rahulmehrotra1** [comment]
The issue will be resolved with the https://github.com/ansible/ansible-modules-core/pull/790 pull request

**Comment by bcoca** [comment]
closing this in favor of #790
