### ISSUE TITLE
apt: update ignores specified repository from dpkg_options

### ISSUE THREAD

**Issue by SkaveRat** [ansible/ansible-modules-core#803]
Running the `apt` module with `update_cache=yes` takes quite some time.

ideally, you should be able to supply `dpkg_options` with `sourcelist="/etc/apt/sources.list.d/foobar.list"` and use this option on line [583](/ansible/ansible-modules-core/blob/devel/packaging/os/apt.py#L583) to just update a single source.

is there a reason this is currently not supported or is it just overlooked?

**Comment by SkaveRat** [comment]
PR #807 is an attempt to fix this

**Comment by bcoca** [comment]
closing this in favor of the PR
