### ISSUE TITLE
Deprecated Openstack modules need a drepecated: documentation field

### ISSUE THREAD

**Issue by abadger** [ansible/ansible-modules-core#858]
@emonty Looks like we just merged the deprecation of old openstack modules: https://github.com/ansible/ansible-modules-core/pull/244  When we did this the documentation build job noticed that we did not add a deprecation field to the module's documentation at the same time.  Each of the deprecated modules need something like:

```
 module: glance_image
 version_added: "1.2"
 deprecated: Deprecated in 1.9.  Use os_image instead
 short_description: Add/Delete images from glance
```

I could just add deprecated in 1.9 to all those modules but that's not very friendly to users.  Better if you do it so that you can mention the replacement module to use.  Would that be okay?

**Comment by emonty** [comment]
@abadger absolutely - on it

**Comment by abadger** [comment]
@emonty Cool, thanks!  There's one module that was missed in the pull request: _quantum_router.py
