### ISSUE TITLE
script module crashes with "Exception while splitting arguments"

### ISSUE THREAD

**Issue by bitmax1** [ansible/ansible-modules-core#864]
When calling a windows powershell script, that sends backslashes to std_err script module crashes with exception, caused by the call of vvvv because split_args can't handle the input.

Sample windows output:
Der Pfad 
"HKLM:\SOFTWARE\Policies\Microsoft\Windows\RemovableStorageDevices" kann nicht 
gefunden werden, da er nicht vorhanden ist.
In C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1425043462.98-71560949
861849\enableRDPcdromAccess.ps1:7 Zeichen:1
- set-ItemProperty -Path 
  'HKLM:\SOFTWARE\Policies\Microsoft\Windows\RemovableStora ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...eStorageDevic 
   es:String) [Set-ItemProperty], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetIt 
   emPropertyCommand

```

**Comment by cchurch** [comment]
Could you provide an example playbook and PowerShell script to help us reproduce?

**Comment by bitmax1** [comment]
Sorry, can't reproduce it anymore by myself either.
Having changed line 153 of ansible/lib/ansible/runner/connection_plugins/winrm.py to 
<code>return (result.status_code, '', result.std_out.decode('cp437').encode('utf-8'), result.std_err.decode('cp437').encode('utf-8'))</code>
to come around the problems with the german umlauts, the problem with the output above mentioned seems to vanished again.
Next time something like this happens, i'll freeze my machine (i promise)

**Comment by bitmax1** [comment]
Got the error again, this time reproducable.

In conjunction with a windows machine:

On the windows machine place file test.txt in c:\
Content:

<pre>
C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1426092743.23-120099741664982
C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1426092743.23-120099741664982
 "choco.exe install stunnel -source https://chocolatey.org/api/v2/",
 Install error: !!ATTENTION!! The next version of Chocolatey (v0.9.9) will require -y to perform   behaviors that change state without prompting for confirmation. Start   using it now in your automated scripts.    For details on the all new Chocolatey, visit http://bit.ly/new_choco Chocolatey (v0.9.8.33) is installing \u0027stunnel\u0027 and dependencies. By installing you accept the license for \u0027stunnel\u0027 and each dependency you are installing.   stunnel v5.10 Attempt to get headers for https://www.stunnel.org/downloads/stunnel-5.10-installer.exe failed.   Exception calling \"GetResponse\" with \"0\" argument(s): \"The remote server returned an error:   (404) Not Found.\" Downloading stunnel 32 bit   from \u0027https://www.stunnel.org/downloads/stunnel-5.10-installer.exe\u0027 Finished installing \u0027stunnel\u0027 and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
Write-Error : stunnel did not finish successfully. Boo to the chocolatey gods!
-----------------------
[ERROR] Exception calling "GetResponse" with "0" argument(s): "The remote serve
r returned an error: (404) Not Found."
-----------------------
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-Chocolat
eyFailure.ps1:30 char:3
+   Write-Error $errorMessage
+   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,Write-Error
 
Write-Error : Package 'stunnel v5.10' did not install successfully: Exception c
alling "GetResponse" with "0" argument(s): "The remote server returned an error
: (404) Not Found."
At C:\ProgramData\chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:9
0 char:17
+                 Write-Error "Package `'$installedPackageName v$installedPacka
geV ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,Write-Error
</pre>

in the files folder place a script: killer.ps1 with content:

<pre>
#!powershell
# <license>
# WANT_JSON
# POWERSHELL_COMMON
type c:\test.txt
</pre>

this file simply puts the content of the file to stdout

call that script with:
-name: killer
  script: killer.ps1

and then you get:
TASK: [windows-zone/provision-zone | killer] *********************************\* 
Traceback (most recent call last):
  File "/tank/home/max/bitagentur/ansible/kmu-server/plugins/connection_plugins/winrm.py", line 149, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
  File "/tank/home/max/bitagentur/ansible/kmu-server/plugins/connection_plugins/winrm.py", line 123, in _winrm_exec
    vvvvv('WINRM STDOUT %s' % response.std_out, host=self.host)
  File "/tank/home/max/bitagentur/ansible/kmu-server/plugins/connection_plugins/winrm.py", line 45, in vvvvv
    verbose(msg, host=host, caplevel=4)
  File "/usr/lib/pymodules/python2.7/ansible/callbacks.py", line 190, in verbose
    msg = utils.sanitize_output(msg)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 1002, in sanitize_output
    parts = parse_kv(str)
  File "/usr/lib/pymodules/python2.7/ansible/utils/**init**.py", line 793, in parse_kv
    vargs = split_args(args)
  File "/usr/lib/pymodules/python2.7/ansible/module_utils/splitter.py", line 185, in split_args
    raise Exception("error while splitting arguments, either an unbalanced jinja2 block or quotes")
Exception: error while splitting arguments, either an unbalanced jinja2 block or quotes
fatal: [10.43.0.90] => failed to exec cmd  C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1426093233.73-219021277552968\debug.ps1 

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\*

**Comment by bitmax1** [comment]
was closed by error

**Comment by cchurch** [comment]
This issue has been fixed in devel via https://github.com/ansible/ansible/pull/11719 (by specifying the UTF-8 codepage for the remote shell and treating all commands/responses as UTF-8).
