### ISSUE TITLE
Hidden files (dotfiles) are not excluded in 'assembly' module

### ISSUE THREAD

**Issue by m-emelchenkov** [ansible/ansible-modules-core#876]
**Issue Type:**
Bug report for 'assembly' module

**Ansible Version:**
1.8.4

**Environment:**
Mac OS 10.10.2 / Ansible from Homebrew

**Summary:**

There is error produced by runner/**init**.py module which is called from runner/action_plugins/assemble.py module: 
`fatal: [1.2.3.4] => failure encoding into utf-8`

The problem: 'assemble' module counts hidden files (dot files) as regular files, but they are binary (i.e. .DS_Store) so it just hangs. It will hang:
`assemble: src=../../files/ssl/crt dest=/etc/ssl/certs/my_website.crt remote_src=False owner=root group=root mode=0640`

I think the default behaviour without any additional options should be ignoring dotfiles in src directory.

**Steps to Reproduce:**
1. Create `src` directory with binary dotfile (i.e. .DS_Store)
2. Use this `src` directory as source for assemble task.
3. Run playbook and notice error "fatal: [1.2.3.4] => failure encoding into utf-8"

**Expected Results:**
Ignoring dotfiles.

**Actual Results:**
The error message, also it is not obvious (I must add debug output to sources in order to found what happening).

**Comment by thegalexc** [comment]
+1 For this as a bug. Running OS X 10.10.3, Ansible 1.9.2. I had to manually remove .DS_Store from assemble source directory.

**Comment by bcoca** [comment]
fixed via e33f0930753876be85f8f851e3cfdc81e219a73c
