### ISSUE TITLE
apt_repository: utilise /etc/apt/sources.list.d

### ISSUE THREAD

**Issue by sammcj** [ansible/ansible-modules-core#894]
[apt_repository](https://github.com/ansible/ansible-modules-core/blob/devel/packaging/os/apt_repository.py) is currently hard coded to edit /etc/apt/sources.list

It is recommended to instead use /etc/apt/sources.list.d/reponame.list

This also allows one to ensure that only the repositories managed by Ansible are being deployed and the default, bundled repositories that come with Debian / Ubuntu in /etc/apt/sources.list are not used (if you choose to purge them)

Example use:

```
# Add specified repository into archive apt list.
apt_repository: repo='deb http://archive.canonical.com/ubuntu hardy partner' state=present list=archive
```

I would expect this to create `/etc/apt/sources.list.d/archive.list'

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- apt_repository is currently hard coded to edit /etc/apt/sources.list

However, however what is happening is that:
- it does create a file in /etc/apt/sources.list.d/, it is just not named archive.list, it uses a longer name to make sure there are no collisions: archive_cannonical_ubuntu.list.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by sammcj** [comment]
Hi @bcoca thanks for your detailed response,
That makes sense to me and sounds good.

The only thing I think it probably should also provide is the ability to ensure that the sources.list / sources.list.d only contains repos managed by Ansible (aka, blow away anything that does).

I saw the user list - but to be honest I tend to avoid posting on Google Groups (it's a dog right!)
