### ISSUE TITLE
win_feature breaking with windows 2008 r2

### ISSUE THREAD

**Issue by DanielFurze** [ansible/ansible-modules-core#898]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.4
##### Environment:

Host: os x 10.10.2, python 2.7.8
Target: windows 2008 r2 (aws ami-01b83376) with either powershell 3 or 4
##### Summary:

Trying to use win_feature against windows 2008 R2 causes issues. The aws ami comes with powershell 3 already installed, I've tried upgrading this to powershell 4 with no success. 

The other windows modules are working for me against this server. Also trying win_feature against a windows 2012 R2 (aws ami-e7ac2790) instance works as expected.
##### Steps To Reproduce:

Try to use the win_feature module against a fresh AWS windows 2008 R2 instance. Any of the examples from here break for me 

http://docs.ansible.com/win_feature_module.html
##### Expected Results:

```
PLAY [configure iis server] ***************************************************

TASK: [win_feature] ***********************************************************
changed: [10.x.x.x]

PLAY RECAP ********************************************************************
10.x.x.x              : ok=1    changed=1    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [configure iis server] ***************************************************

TASK: [win_feature] ***********************************************************
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 149, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 120, in _winrm_exec
    vvvv('WINRM RESULT %r' % response, host=self.host)
  File "/usr/local/lib/python2.7/site-packages/ansible/callbacks.py", line 187, in vvvv
    return verbose(msg, host=host, caplevel=3)
  File "/usr/local/lib/python2.7/site-packages/ansible/callbacks.py", line 190, in verbose
    msg = utils.sanitize_output(msg)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 1002, in sanitize_output
    parts = parse_kv(str)
  File "/usr/local/lib/python2.7/site-packages/ansible/utils/__init__.py", line 793, in parse_kv
    vargs = split_args(args)
  File "/usr/local/lib/python2.7/site-packages/ansible/module_utils/splitter.py", line 185, in split_args
    raise Exception("error while splitting arguments, either an unbalanced jinja2 block or quotes")
Exception: error while splitting arguments, either an unbalanced jinja2 block or quotes
fatal: [10.x.x.x] => failed to exec cmd PowerShell -NoProfile -NonInteractive -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARgBpAGwAZQAgACIAQwA6AFwAVQBzAGUAcgBzAFwAQQBkAG0AaQBuAGkAcwB0AHIAYQB0AG8AcgBcAEEAcABwAEQAYQB0AGEAXABMAG8AYwBhAGwAXABUAGUAbQBwAFwAYQBuAHMAaQBiAGwAZQAtAHQAbQBwAC0AMQA0ADIANQA1ADcANAAwADcAMAAuADIAOAAtADIANQA5ADUAOAAxADgANwA5ADcAOQAwADQANQAwAFwAXAB3AGkAbgBfAGYAZQBhAHQAdQByAGUALgBwAHMAMQAiACAAIgBDADoAXABVAHMAZQByAHMAXABBAGQAbQBpAG4AaQBzAHQAcgBhAHQAbwByAFwAQQBwAHAARABhAHQAYQBcAEwAbwBjAGEAbABcAFQAZQBtAHAAXABhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADQAMgA1ADUANwA0ADAANwAwAC4AMgA4AC0AMgA1ADkANQA4ADEAOAA3ADkANwA5ADAANAA1ADAAXABcAGEAcgBnAHUAbQBlAG4AdABzACIAOwAgAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgACIAQwA6AFwAVQBzAGUAcgBzAFwAQQBkAG0AaQBuAGkAcwB0AHIAYQB0AG8AcgBcAEEAcABwAEQAYQB0AGEAXABMAG8AYwBhAGwAXABUAGUAbQBwAFwAYQBuAHMAaQBiAGwAZQAtAHQAbQBwAC0AMQA0ADIANQA1ADcANAAwADcAMAAuADIAOAAtADIANQA5ADUAOAAxADgANwA5ADcAOQAwADQANQAwAFwAIgAgAC0ARgBvAHIAYwBlACAALQBSAGUAYwB1AHIAcwBlADsA

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/dan/setupinstances.retry

10.x.x.x              : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by jhawkesworth** [comment]
Not sure if this is relevant but I had trouble with a fresh Windows Server 2008 install which were fixed by http://support.microsoft.com/kb/2842230.

**Comment by DanielFurze** [comment]
I've tried the patch but it didn't seem to help for this issue. Watching system performance when trying to run the command shows no change to cpu or memory so I'm guessing it's being blocked before windows starts to do any work.

**Comment by jhawkesworth** [comment]
Can you run with -vvvvv and see what it is attempting to do?
The iis example there is a bit a strange as it specifies 'state=absent', which is going to want to remove IIS if it is present.  Have you tried with state=present?

**Comment by DanielFurze** [comment]
I'm using the following in my tasks file

```
- name: Install iis
  win_feature:
    name: "Web-Server"
    state: present
    restart: yes
    include_sub_features: yes
    include_management_tools: yes
```

the output
https://gist.github.com/BushiDan/075ee2d7c50d16764bce

**Comment by jhawkesworth** [comment]
Only difference I can see from the playbook I've run is 1/ I used server 2012 and 2/ no double quotes around "Web-Server".  I would have been using an older ansible version actually.

**Comment by DanielFurze** [comment]
Yeah it seems to work fine with windows 2012 r2, I've just been using it for now as all the work I'm doing is compatible with both 2008 & 2012.

**Comment by jhawkesworth** [comment]
Just a thought, if I recall there were 32 bit and 64 bit editions of 2008. Which are you using?  Jon

**Comment by jhawkesworth** [comment]
This is still bugging me.  I think the win_feature powershell module is throwing an exception and there's something about the exception message which is creating unexpected json, which I think is then confusing the controller logic.

I'm thinking this line of code could do with some sanitizing:

```
Fail-Json $result $_.Exception.Message
```

As I imagine there's no guarantee that the contents of the exception message can be reliably converted to Json.

Anyone got a 2008 box who could try this out?

**Comment by DanielFurze** [comment]
I'll try and do some more testing next week with the updated ansible 1.9.1. The 2008 svr was 64bit.

**Comment by DanielFurze** [comment]
It's working correctly now using ansible 1.9.1 with the latest windows 2008 r2 ami: ami-c1d1b0b6. 

I downgraded to 1.8.4 and experienced the same issue again so I guess we can mark this as fixed now?

**Comment by jhawkesworth** [comment]
Great, thanks for retesting.

Jon

**Comment by kchrzanowski** [comment]
I have the same issue as BushiDan, but with win_chocolatey module: http://stackoverflow.com/questions/30869780/error-installing-chocolatey-via-ansible-on-windows
But I have installed everything required and have ansible v1.9.1. Could anyone help me?

**Comment by cchurch** [comment]
@tasarius Since `win_chocolately` is an extras module, could you submit a bug report at https://github.com/ansible/ansible-modules-extras/issues/new?

Closing since it has been tested and is working on 1.9.1.
