### ISSUE TITLE
{ failed: "true" } error when running basic rax module from samples

### ISSUE THREAD

**Issue by kenperkins** [ansible/ansible-modules-core#919]
I'm using a slightly modified playbook from the [examples](http://docs.ansible.com/rax_module.html#examples). I'm expliciting adding my username and api_key, as well as region.

Ansible Version 1.8.4
Pyrax version 1.9.3

```
- name: Build a Cloud Server
  hosts: all
  gather_facts: False
  tasks:
    - name: Server build request
      failed_when: false
      ignore_errors: true
      local_action:
        module: rax
        username: myusername
        api_key: xxxxx
        name: rax-test1
        region: IAD
        flavor: general1-1
        image: fed66ee7-fb4b-4464-b8c6-609c1fde218f
        key_name: ken-mbp
        wait: yes
        state: present
        networks:
          - private
          - public
      register: rax
```

```
$ ansible-playbook -i localhost, playbook.yml

PLAY [Build a Cloud Server] ***************************************************

TASK: [Server build request] **************************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/ken/playbook.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by sivel** [comment]
You should have gotten additional information below the 'failed'.  

Something to the effect of:

```
TASK: [Server build request] **************************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: iad is not a valid region, must be one of: SYD,IAD,DFW,ORD,HKG
```

To note, that is indeed 1 of your errors, 'iad' is not a valid region, it should be 'IAD'.  I'll also assume it is a typo that you have no 'hosts' listed in your play.

On another note, I am unable to confirm whether that image exists, but that should also lead to `msg: Can not find requested image`.

It may also help to run with extra verbosity such as using `-vv` in your ansible-playbook run.  If you can provide the output from that run, it may be useful in determining what your issue is.

**Comment by kenperkins** [comment]
@sivel you're correct about the missing hosts; I updated my example above to be accurate with what I ran.

Regarding the error you listed above, that does not appear. I see nothing beyond the `{"failed": true}` output.

I'll re-run with `-vv`.

**Comment by kenperkins** [comment]
Ok with `-vv` it doesn't materially change the output, just adds a log line above:

```
<127.0.0.1> username=redacted name=rax-test1 key_name=ken_mbp region=iad state=present api_key=redacted image=b11d9567-e412-4255-96b9-bd63ab23bcfe
```

**Comment by kenperkins** [comment]
I've confirmed that switching to `IAD` and a valid image id doesn't change the output.

**Comment by sivel** [comment]
Ok, I was hoping it would reply with the full response of the module.  There are a few additional options:
1. add `failed_when: false` to the task, in addition to `-vv`
2. add `ignore_errors: true` to the task, and create another task similar to `- debug: var=rax`

Hopefully that can get us to the 'msg'.  Why you aren't seeing the 'msg' I have no idea.

**Comment by kenperkins** [comment]
I'm not sure what you mean by:

> create another task similar to `- debug: var=rax`

That said, I added `failed_when: false` and `ignore_errors: true` under `tasks`. New output:

```
ok: [localhost -> 127.0.0.1] => {"failed": false, "failed_when_result": false, "msg": ""}
```

**Comment by sivel** [comment]
@kenperkins thanks for talking with me outside of the issue.  From what we found, an exception was being raised, `fail_json` was being called with `e.message` however `e.message` was empty.

I'll work on a fix and in the shared module utils to handle such a situation, and still provide some error message.

**Comment by sivel** [comment]
This should now be "resolved" by the above merged PRs.  I say "resolved" as it doesn't fix the underlying issue, but exposes the exception via `msg` in the failure when an exception doesn't provide a nice message.

In this case, the issue was a result of a dependency version mismatch:

```
TASK: [Server build request] **************************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: VersionConflict(six 1.8.0 (/Users/matt/python_venvs/ansibledev/lib/python2.7/site-packages), Requirement.parse('six>=1.9.0'))
```

Such an issue would be exposed to the user now.

The resolution to the above message was upgrading six to an appropriate version: `pip install -U six>=1.9.0`

**Comment by kenperkins** [comment]
Thanks for the quick turn-around @sivel; I cleaned my machine and did a fresh install of both pyrax and ansible and confirmed the issue does not manifest. It must have only been from installing pyrax back when six 1.5.x was the most recent version.

**Comment by kenperkins** [comment]
Would `pip install -U pyrax` also have fixed my issue?

**Comment by sivel** [comment]
> Would pip install -U pyrax also have fixed my issue?

Yes, that would have also fixed it.
