### ISSUE TITLE
Feature idea: django_manage to accept arguments

### ISSUE THREAD

**Issue by oppianmatt** [ansible/ansible-modules-core#930]
The django_manage command should be able to take arguments for commands run. I.e. I want to run manage.py jenkins with --noinput or anything else I should be able to give extra args.

**Comment by cchurch** [comment]
It can already take arguments to run any manage.py command, e.g.:

```
django_manage: command="jenkins --noinput"
```

I've submitted a PR to give a better example of this usage in the docs: https://github.com/ansible/ansible-modules-core/pull/574

**Comment by bcoca** [comment]
closing as this feature is already provided
