### ISSUE TITLE
docker: support setting entrypoint

### ISSUE THREAD

**Issue by bobrik** [ansible/ansible-modules-core#938]
For some images it is useful to overwrite `ENTRYPOINT`. Use case: redirecting logs to bind-mounted syslog socket.

```
docker run -v /syslog.sock:syslog.sock --entrypoint /bin/sh myimage \
    -c 'myprogram | logger -u /syslog.sock -t myimage'
```

I can come up with PR.

**Comment by monokal** [comment]
Any progress on this? Using "command" isn't possible for some.
