### ISSUE TITLE
rax_clb: Support `http_redirect` and `ssl_termination` 

### ISSUE THREAD

**Issue by jumoel** [ansible/ansible-modules-core#939]
Pyrax supports it, so it'd be great if Ansible did as well.

It's already implemented in a [local `rax_clb` module in the developer.rackspace.com repository](https://github.com/rackerlabs/developer.rackspace.com/blob/master/script/modules/rax_clb), specifically in [this commit](https://github.com/rackerlabs/developer.rackspace.com/commit/9301388c8305a0636d2bb5c487c4b62705962962).

**Comment by ckrough** [comment]
This is in-progress in https://github.com/ansible/ansible-modules-extras/pull/268

**Comment by jumoel** [comment]
Ah, cool!
