### ISSUE TITLE
apt module doesn't install module with a 'when' condition

### ISSUE THREAD

**Issue by johan-chassaing** [ansible/ansible-modules-core#94]
Issue Type:
Bug Report

Ansible Version:
ansible 1.7.2

Environment:
Ubuntu 14.04 amd64

Summary:

I made a list of package that I would like to be upgraded if needed.
So, I retrieve the list of every packages needed to be upgraded on my server,
and it install the package when the result is matched
The problem appears only when I add the when condition.

Steps To Reproduce:

Generate a list of file to be upgraded
 vars:
- to_upgrade: [ 'apache2-mpm-worker', 'apache2.2-bin', 'apache2.2-common' ]
  Create a tasks which will get the full package list of the server and run apt module to install each module included in the first generated list
  tasks:
- name: List packages to upgrade
  shell: aptitude -q -F%p --disable-columns search "~U"
  register: updates
- name: Upgrade
  apt: name={{ item }} state=latest
  # debug: msg="Package to update:{{item}}"
  with_items: updates.stdout_lines
  when: item in to_upgrade

Expected Results:
  Packages must be installed.
 TASK: [Upgrade] **************************************************************\*  
 <127.0.0.1> REMOTE_MODULE apt name=apache2-mpm-worker,apache2.2-bin,apache2.2-common state=latest
 changed: [127.0.0.1] => (item=apache2-mpm-worker,apache2.2-bin,apache2.2-common,bash) => {"changed": true, 
 [...]
 PLAY RECAP *******************************************************************\* 
 127.0.0.1                  : ok=4    changed=2    unreachable=0    failed=0

Actual Results:
 TASK: [Upgrade] **************************************************************\* 
 skipping: [127.0.0.1] => (item=apache2-mpm-worker,apache2.2-bin,apache2.2-common)
 [...]
 PLAY RECAP
 127.0.0.1                  : ok=3    changed=1    unreachable=0    failed=0

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question than a bug report, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
