### ISSUE TITLE
No error reported when service state=reloaded fails

### ISSUE THREAD

**Issue by mhogerheijde** [ansible/ansible-modules-core#952]
Re-report of https://github.com/ansible/ansible/issues/9108 
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.8.4
  configured module search path = /usr/share/ansible:library
```
##### Environment:

Controlling machine is Ubuntu 14.10, 

```
$ lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:
                core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:
                core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:
                core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:
                cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:
                cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:
                cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:
                cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:
                desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:
                desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:
                graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:
                graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:
                graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:
                graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:
                languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:
                languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:
                multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:
                multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:
                printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:
                printing-4.0-noarch:printing-4.1-amd64:printing-4.1-noarch:
                qt4-3.1-amd64:qt4-3.1-noarch:security-4.0-amd64:
                security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:        14.10
Codename:       utopic
```

controlled is Ubuntu 14.04.1

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
```
##### Summary:

Errors produced by syntactically invalid modifications to nginx.conf are not reported in playbook output on service start/restart/reload, the task is instead marked as changed. Probably this is not specific to Nginx.
##### Steps To Reproduce

```
tasks:
- name:   nginx is installed
  action: apt name=nginx

- name:   nginx.conf is in place
  action: copy content='?.=x)@+!+!%+' dest=/etc/nginx/nginx.conf
  notify: restart nginx

handlers:

- name:   restart nginx
  action: service name=nginx state=reloaded
```
##### Expected Results:

The handler reports an error.
##### Actual Results:

The handler reports a change.
##### Additional:

That was the initial report, updated with currently used version by myself.

The problem actually exist due to both `serivce nginx reload` and `service nginx configtest` exit with `0` in stead of a non-zero value.

I _know_ that Ansible is not responsible for that, but for things as specific as the `service` module, I expect it to see the "fail!" in stdout and pick that up and report an error.

This behaviour is similar with `haproxy`.

**Comment by bcoca** [comment]
So is it reloaded or restarted? they are not the same. 

If the init system is having errors and returning rc=0, this is really an upstream bug. 

We can try a workaround but looking at stdout is very unreliable (it should at least output to stderr!) as the standards rely on return codes not on terminal messages.

**Comment by mhogerheijde** [comment]
Sorry, I meant `reloaded` indeed. (Fixed it above). 

I know that this is actually a bug with NginX, but since haproxy has similar behaviour it almost feels like "this is the way it works". 

Unfortunately, the script does output to `stdout` and not `stderr`, which is also strange.

I'll report this bug to NginX as well

**Comment by bcoca** [comment]
report to ubuntu, if this is the standard package, it is their job to make sure the init scripts/upstart/systemd behave correctly.

**Comment by mhogerheijde** [comment]
Ack!

**Comment by jooadam** [comment]
This is not specific to Nginx, Postfix behaves similarly (as of 14.04).

@mhogerheijde Have you reported this?

**Comment by bcoca** [comment]
so closing this as the error was specific to the system's init script and it was not reporting back correctly to ansible.

**Comment by jooadam** [comment]
Here’s the bug report, please vote: https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1413555

**Comment by alexfd** [comment]
`service nginx configtest` now exits with **1**

```
# service nginx configtest
nginx: [emerg] unknown directive "asfafsa" in /etc/nginx/nginx.conf:3
nginx: configuration file /etc/nginx/nginx.conf test failed
# echo $?
1
```

yet ansible still reports _changed_:  

```
GATHERING FACTS *************************************************************** 
ok: [ubuntu@x.x.x.x]
TASK: [nginx | install nginx.conf] ******************************************** 
changed: [ubuntu@x.x.x.x]
NOTIFIED: [nginx | reload nginx] ********************************************** 
changed: [ubuntu@x.x.x.x]
PLAY RECAP ******************************************************************** 
ubuntu@x.x.x.x       : ok=3    changed=2    unreachable=0    failed=0`
```
