### ISSUE TITLE
UndefinedError: 'dict object' has no attribute 'stdout'

### ISSUE THREAD

**Issue by xied75** [ansible/ansible-modules-core#960]
Dear all,

I have a task defined like this:

```
  - name: wait template ready
    shell: /usr/local/bin/cs listTemplates templatefilter=self name=dong-test-ansible | /usr/bin/jq '.template[0].isready'
    register: template_status
    until: "'{{template_status.stdout}}' == 'true'"
    retries: 240
    delay: 5
```

If I run this with --check, it gives me error msg:

```
TASK: [wait template ready] *************************************************** 
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1034, in _executor_internal_inner
    if not utils.check_conditional(cond,  self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 275, in check_conditional
    conditional = template.template(basedir, conditional, inject, fail_on_undefined=fail_on_undefined)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 119, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 365, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 9, in root
  File "/usr/local/lib/python2.7/dist-packages/jinja2/runtime.py", line 485, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
UndefinedError: 'dict object' has no attribute 'stdout'


FATAL: all hosts have already failed -- aborting
```

But if I remove --check then it runs without problem, the waiting actually works!

Not really sure if this a bug or belongs to jinja2 or Ansible, but I guess this has nothing to do with Cloudstack, the output from cs is json, then parsed by jq, the final output is just a simple string.

ansible --version
ansible 1.8.4

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

In any case, this is expected, --check will skip a shell action and the registered var will not have a stdout, you can use either 'is defined' or '|default' to avoid the error.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
