### ISSUE TITLE
error when trying to use with_items with apt module

### ISSUE THREAD

**Issue by gergelyimre** [ansible/ansible-modules-core#99]
Originally opened as ansible/ansible#8314

**Issue Type:**

Bug Report

**Ansible Version:**

ansible 1.7 (devel 226dacc) last updated 2014/07/28 21:56:28 (GMT +300)

**Environment:**

managing host: Ubuntu 14.04 64bit
managed host: Ubuntu 10.04 32bit (python 2.6.5 + python-apt 0.7.94)

**Summary:**

Getting an error message while using with_items with the apt module.

**Steps To Reproduce:**

According to feature request #7863 and fix #8292, with_items should be used like this:

```
- name: install debs
  apt: deb=/tmp/{{ item }} state=installed
  with_items:
    - linux-headers-3.11.6-031106_3.11.6-031106.201310181453_all.deb
    - linux-headers-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb
    - linux-image-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb
```

**Expected Results:**

deb packages getting installed

**Actual Results:**

error message:

```
TASK: [install debs] ********************************************************** 
failed: [host1] => (item=linux-headers-3.11.6-031106_3.11.6-031106.201310181453_all.deb,linux-headers-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb,linux-image-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb) => {"failed": true, "item": "linux-headers-3.11.6-031106_3.11.6-031106.201310181453_all.deb,linux-headers-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb,linux-image-3.11.6-031106-generic_3.11.6-031106.201310181453_i386.deb", "parsed": false}
invalid output was: SUDO-SUCCESS-mwctpznrbdkgnukozzhwfjskdskanudn
Traceback (most recent call last):
  File "<stdin>", line 1865, in <module>
  File "<stdin>", line 523, in main
  File "<stdin>", line 302, in install_deb
  File "/usr/lib/python2.6/dist-packages/apt/debfile.py", line 285, in compare_to_version_in_cache
    if pkgname in self._cache:
TypeError: argument of type 'NoneType' is not iterable


FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
Hi, 

This is because of the usage with deb paths.  We need to make this recognize that some of the paths are debs and not join them in Ansible into a big list, basically.

As such, can you open this ticket in https://github.com/ansible/ansible ?

Sorry for the confusion here.  We may have asked to move this incorrectly.

Thanks!
